force-app/main/default/objects/ICEProperty__c/ICEProperty__c.object-meta.xml
<CustomObject>
    <description>ICE PROPERTY OBJECT
NICC-009421: The ICE Project - (TrackIt 108757)</description>
    <label>ICE Property</label>
    <nameField>
        <displayFormat>ICEPRP{000000}</displayFormat>
        <label>ICEPropertyId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ICE Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ICEProperty__c/fields/DelphiNetIsActive__c.field-meta.xml
<CustomField>
    <fullName>DelphiNetIsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Delphi.Net IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ICEProperty__c/fields/HideOnICEForms__c.field-meta.xml
<CustomField>
    <fullName>HideOnICEForms__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hide On ICE Forms</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ICEProperty__c/fields/ICESubscriptionId__c.field-meta.xml
<CustomField>
    <fullName>ICESubscriptionId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ICE Subscription</label>
    <referenceTo>ICESubscription__c</referenceTo>
    <relationshipLabel>ICE Properties</relationshipLabel>
    <relationshipName>ICE_Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ICEProperty__c/fields/PropertyName__c.field-meta.xml
<CustomField>
    <fullName>PropertyName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Delphi.Net Property Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ICEProperty__c/fields/SelectedForMigration__c.field-meta.xml
<CustomField>
    <fullName>SelectedForMigration__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Selected For Migration</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ICEProperty__c/fields/StreetAddress__c.field-meta.xml
<CustomField>
    <fullName>StreetAddress__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Street Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ICEProperty__c/fields/TimeZone__c.field-meta.xml
<CustomField>
    <fullName>TimeZone__c</fullName>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>(GMT+14:00) Line Islands Time (Pacific/Kiritimati)</fullName>
            </value>
            <value>
                <fullName>(GMT+13:45) Chatham Daylight Time (Pacific/Chatham)</fullName>
            </value>
            <value>
                <fullName>(GMT+13:00) New Zealand Daylight Time (Pacific/Auckland)</fullName>
            </value>
            <value>
                <fullName>(GMT+13:00) Phoenix Islands Time (Pacific/Enderbury)</fullName>
            </value>
            <value>
                <fullName>(GMT+13:00) Fiji Summer Time (Pacific/Fiji)</fullName>
            </value>
            <value>
                <fullName>(GMT+13:00) Tonga Time (Pacific/Tongatapu)</fullName>
            </value>
            <value>
                <fullName>(GMT+12:00) Magadan Time (Asia/Kamchatka)</fullName>
            </value>
            <value>
                <fullName>(GMT+11:30) Norfolk Islands Time (Pacific/Norfolk)</fullName>
            </value>
            <value>
                <fullName>(GMT+11:00) Lord Howe Daylight Time (Australia/Lord_Howe)</fullName>
            </value>
            <value>
                <fullName>(GMT+11:00) Australian Eastern Daylight Time (Australia/Sydney)</fullName>
            </value>
            <value>
                <fullName>(GMT+11:00) Solomon Islands Time (Pacific/Guadalcanal)</fullName>
            </value>
            <value>
                <fullName>(GMT+10:30) Australian Central Daylight Time (Australia/Adelaide)</fullName>
            </value>
            <value>
                <fullName>(GMT+10:00) Australian Eastern Standard Time (Australia/Brisbane)</fullName>
            </value>
            <value>
                <fullName>(GMT+09:30) Australian Central Standard Time (Australia/Darwin)</fullName>
            </value>
            <value>
                <fullName>(GMT+09:00) Korean Standard Time (Asia/Seoul)</fullName>
            </value>
            <value>
                <fullName>(GMT+09:00) Japan Standard Time (Asia/Tokyo)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Hong Kong Time (Asia/Hong_Kong)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Malaysia Time (Asia/Kuala_Lumpur)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Philippine Time (Asia/Manila)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) China Standard Time (Asia/Shanghai)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Singapore Standard Time (Asia/Singapore)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Taipei Standard Time (Asia/Taipei)</fullName>
            </value>
            <value>
                <fullName>(GMT+08:00) Australian Western Standard Time (Australia/Perth)</fullName>
            </value>
            <value>
                <fullName>(GMT+07:00) Indochina Time (Asia/Bangkok)</fullName>
            </value>
            <value>
                <fullName>(GMT+07:00) Indochina Time (Asia/Ho_Chi_Minh)</fullName>
            </value>
            <value>
                <fullName>(GMT+07:00) Western Indonesia Time (Asia/Jakarta)</fullName>
            </value>
            <value>
                <fullName>(GMT+06:30) Myanmar Time (Asia/Rangoon)</fullName>
            </value>
            <value>
                <fullName>(GMT+06:00) Bangladesh Time (Asia/Dhaka)</fullName>
            </value>
            <value>
                <fullName>(GMT+06:00) Yekaterinburg Time (Asia/Yekaterinburg)</fullName>
            </value>
            <value>
                <fullName>(GMT+05:45) Nepal Time (Asia/Kathmandu)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ICESubscription__c/ICESubscription__c.object-meta.xml
<CustomObject>
    <description>ICE SUBSCRIPTION OBJECT
NICC-009421: The ICE Project - (TrackIt 108757)</description>
    <label>ICE Subscription</label>
    <nameField>
        <displayFormat>ICESUB{000000}</displayFormat>
        <label>ICESubscription</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ICE Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ICESubscription__c/fields/AcceptOnlineTermsCompleted__c.field-meta.xml
<CustomField>
    <fullName>AcceptOnlineTermsCompleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Accept Online Terms Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ICESubscription__c/fields/AgreementAcceptedIP__c.field-meta.xml
<CustomField>
    <fullName>AgreementAcceptedIP__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Agreement Accepted IP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ICESubscription__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>ICE Subscriptions</relationshipLabel>
    <relationshipName>ICE_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ICESubscription__c/fields/ContactCityStateZip__c.field-meta.xml
<CustomField>
    <fullName>ContactCityStateZip__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact City, State, Zip</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ICESubscription__c/fields/ContactEmail__c.field-meta.xml
<CustomField>
    <fullName>ContactEmail__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ICESubscription__c/fields/ContactName__c.field-meta.xml
<CustomField>
    <fullName>ContactName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ICESubscription__c/fields/ContactStreetAddress__c.field-meta.xml
<CustomField>
    <fullName>ContactStreetAddress__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact Street Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ICESubscription__c/fields/ContactTitle__c.field-meta.xml
<CustomField>
    <fullName>ContactTitle__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ICESubscription__c/fields/ContactVenue__c.field-meta.xml
<CustomField>
    <fullName>ContactVenue__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contact Venue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ICESubscription__c/fields/IAcknowledgeandHavetheAuthority__c.field-meta.xml
<CustomField>
    <fullName>IAcknowledgeandHavetheAuthority__c</fullName>
    <defaultValue>false</defaultValue>
    <label>I Acknowledge and Have the Authority</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ICESubscription__c/fields/ICE_Link__c.field-meta.xml
<CustomField>
    <fullName>ICE_Link__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>ICE Homepage Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/ICESubscription__c/fields/MigrationPortalKey__c.field-meta.xml
<CustomField>
    <fullName>MigrationPortalKey__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Migration Portal Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ICESubscription__c/fields/PropertySettingsCompleted__c.field-meta.xml
<CustomField>
    <fullName>PropertySettingsCompleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Property Settings Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ICESubscription__c/fields/ReviewPropertiesAndUsersCompleted__c.field-meta.xml
<CustomField>
    <fullName>ReviewPropertiesAndUsersCompleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Review Properties And Users Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ICESubscription__c/fields/ScheduledMigrationDate__c.field-meta.xml
<CustomField>
    <fullName>ScheduledMigrationDate__c</fullName>
    <description>This field determines when the ICE Portal forms get locked for editing.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Scheduled Migration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ICESubscription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Postponed</fullName>
            </value>
            <value>
                <fullName>Org Split</fullName>
            </value>
            <value>
                <fullName>Researching</fullName>
            </value>
            <value>
                <fullName>Info Sent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ICESubscription__c/fields/StatusReason__c.field-meta.xml
<CustomField>
    <fullName>StatusReason__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Status Reason</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ICESubscription__c/fields/SubscriptionID__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionID__c</fullName>
    <externalId>true</externalId>
    <label>Subscription ID</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ICESubscription__c/fields/SubscriptionName__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Subscription Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ICESubscription__c/fields/UploadMergeDocumentsCompleted__c.field-meta.xml
<CustomField>
    <fullName>UploadMergeDocumentsCompleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Upload Merge Documents Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ICESubscription__c/fields/UserSettingsCompleted__c.field-meta.xml
<CustomField>
    <fullName>UserSettingsCompleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>User Settings Completed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ICEUser__c/ICEUser__c.object-meta.xml
<CustomObject>
    <description>ICE USER OBJECT
NICC-009421: The ICE Project - (TrackIt 108757)</description>
    <label>ICE User</label>
    <nameField>
        <displayFormat>ICEUSR{000000}</displayFormat>
        <label>ICEUserId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ICE Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ICEUser__c/fields/ICESubscriptionId__c.field-meta.xml
<CustomField>
    <fullName>ICESubscriptionId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ICE Subscription</label>
    <referenceTo>ICESubscription__c</referenceTo>
    <relationshipLabel>ICE Users</relationshipLabel>
    <relationshipName>ICE_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ICEUser__c/fields/LoginName__c.field-meta.xml
<CustomField>
    <fullName>LoginName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Login Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ICEUser__c/fields/SubscriptionID__c.field-meta.xml
<CustomField>
    <fullName>SubscriptionID__c</fullName>
    <label>Subscription ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/NI_ICEController.cls
/****************************************************************************************
Name            : NI_ICEController Class
Author          : Sean Harris
Created Date    : 02/26/2014 
Last Mod Date   : 
Last Mod By     : 
NICC Reference  : 
Description     : 
                : 
                : 
******************************************************************************************/
public class NI_ICEController 
{

    // THE OFFSET DAYS USED FOR LOCKING DOWN FORM PRIOR TO MIGRATION DATE
    public integer iDaysGrace {get; set;}

    public List<ICEProperty__c> lstMigrationProperty {get; set;} 
    public List<ICEUser__c> lstMigrationEndUser {get; set;} 
    public List<Attachment> lstAttachments {get; set;} 

    // TRUE IF AUTHKEY URL PARAMETER IS CORRECT
    public Boolean authenticated {get; set;}

    // TRUE IF USERS AND PROPERTIES SELECTION SHOULD BE LOCKED - FOR REVIEW PROPERTIES AND USERS PAGE
    public Boolean usersselectionlocked {get; set;}
                    
    // Migration Customer Record
    public ICESubscription__c iceSub {get; set;}
    
    // the contact found by authkey URL parameter
    public Contact loggedincontact {get; set;}
    // the value of authkey parameter
    public String authkey {get; set;}
    // the upgrade date
    public Date migrationdate {get; set;}
    // the list of files already uploaded - for merge documents upload page
    
    public String[] uploadeddocs {get; set;}
    // the number of files already uploaded - for merge documents upload page
    public Integer uploadeddocssize {get; set;}
    // for file upload form - file contents - for merge documents upload page
    public Blob uploadeddocbody {get; set;}
    // for file upload form - file name - for merge documents upload page
    public String uploadeddocname {get; set;}    

    // "I have read and acknowledge..." checkbox state - for Accept On-line Terms
    public Boolean agreementread {get; set;}
    // to display the message "check I have read... checkbox" - for Accept On-line Terms
    public Boolean agreementnotread {get; set;}
    // use logged in contact as authorization contact - for Accept On-line Terms
    
    public Boolean usecontactdata {get; set;}
    // true if merge documents upload should be locked - for Upload Merge Documents Templates and Logos page
    public Boolean fileuploadlocked {get; set;}
    // holds info on a page to be displayed - for MigrationPortalPage
//    public MigrationPortalPage__c page {get; set;}    
    // for home page to return there from some step - to display a message next to that step
    public Integer stepsaved {get; set;}
    // the name of the file to delete - for upload merge documents page
    public String filetodelete {get; set;}

 
    // CONSTRUCTOR, HANDLES AUTHENTICATION AND ICE SUBSCRIPTION RECORD RETRIEVAL
    public NI_ICEController() 
    {
        // INITIALIZE VARIABLES
        iDaysGrace = 10;
        authenticated = false;
        authkey = null;
        uploadeddocs = new String[0];
        usersselectionlocked = false;
        fileuploadlocked = false;
        agreementnotread = false;
        stepsaved = 0;
        
        // GET AUTH KEY FROM REQUEST PARAMETERS
        if (ApexPages.currentPage().getParameters().containsKey('authkey')) 
        {
            if (Test.isRunningTest())
            {
                authkey = ApexPages.currentPage().getParameters().get('authkey');
            }
            else
            {
                authkey = EncodingUtil.urlEncode(ApexPages.currentPage().getParameters().get('authkey').replace(' ', '+'), 'UTF-8');
            }
        }
       
        if (ApexPages.currentPage().getParameters().containsKey('stepsaved')) 
        {
            stepsaved = Integer.valueOf(ApexPages.currentPage().getParameters().get('stepsaved'));
        }

        // IF NO AUTHKEY FOUND IN URL THEN EXIT
        if (authkey == null)
        {
            return;
        }
        
        uploadeddocname = ApexPages.currentPage().getParameters().get('authkey');
          
        List<ICESubscription__c> lstICE = new List<ICESubscription__c>([
            SELECT Id, AcceptOnlineTermsCompleted__c, AgreementAcceptedIP__c, Contact__c, ContactCityStateZip__c, ContactEmail__c, 
            ContactName__c, ContactStreetAddress__c, ContactTitle__c, ContactVenue__c, DelphiNetIsActive__c, IAcknowledgeandHavetheAuthority__c, 
            ICE_Link__c, MigrationPortalKey__c, PropertySettingsCompleted__c, ReviewPropertiesAndUsersCompleted__c, ScheduledMigrationDate__c, 
            Status__c, StatusReason__c, SubscriptionID__c, SubscriptionName__c, UploadMergeDocumentsCompleted__c, UserSettingsCompleted__c, ContactFirstName__c       
            FROM ICESubscription__c
            WHERE MigrationPortalKey__c = : authkey LIMIT 1
        ]);         

        if (lstICE.Size() == 1)
        {

            if (lstICE[0].Contact__c == null)
            {
                return;
            } 

            loggedincontact = [SELECT Id, Name, Email, Account.Name, Title, MailingStreet, MailingCity, MailingState, MailingPostalCode FROM Contact WHERE Id = : lstICE[0].Contact__c LIMIT 1];
            migrationdate = lstICE[0].ScheduledMigrationDate__c;
            iceSub = lstICE[0];
            authenticated = true;
                    
            // IF ScheduledMigrationDate__c IS NULL THEN LOCK DOWN THE FORM 
            if (migrationdate == null)
            {
                usersselectionlocked = true;
                fileuploadlocked = true;
            }
            else
            {  
                if (migrationdate.addDays(-iDaysGrace) <= Date.today())
                {
                    usersselectionlocked = true;
                    fileuploadlocked = true;
                }
                else
                {
                    usersselectionlocked = false;
                    fileuploadlocked = false;
                }
            }

        }

    }

    // redirect to the home page
    public PageReference backtohome() 
    {
        PageReference pg = new PageReference('http://newmarketinc.force.com/migrationportal/NI_ICE_Home?authkey=' + authkey);
        pg.setRedirect(true);
        return pg;
    }

// ===================================================================    
// NIMigrationPortalReviewPropertiesUsers PAGE FUNCTIONS (STEP 1)
// ===================================================================    
    
    // LIST OF PROPERTIES RELATED TO VISITOR'S CONTACT RECORD
    public List<ICEProperty__c> getICEProperties()  
    {   
    
        List<ICEProperty__c> lstMP = new List<ICEProperty__c>(); 

        for (ICEProperty__c mp : [SELECT Id, PropertyName__c, StreetAddress__c, DelphiNetIsActive__c, City__c, Zip__c, State__c, SelectedForMigration__c, TimeZone__c
                                  FROM ICEProperty__c
                                  WHERE ICESubscriptionId__c = : iceSub.Id 
                                  AND HideOnICEForms__c = false 
                                  ORDER BY SelectedForMigration__c DESC, Name ASC]) 
        {
            lstMP.add(mp); 
           
        }
        
        lstMigrationProperty = lstMP;
                
        return lstMP; 
        
    }   
    
    
    // DISTINCT LIST OF USERS RELATED TO VISITOR'S CONTACT RECORD
    public List<ICEUser__c> getICEUsers()  
    {   
    
        List<ICEUser__c> lstMEU = new List<ICEUser__c>(); 
        Boolean bFound = false;

        for (ICEUser__c meu : [SELECT Id, DelphiNetIsActive__c, Email__c, LoginName__c, UserName__c, SelectedForMigration__c  
                               FROM ICEUser__c 
                               WHERE ICESubscriptionId__c = : iceSub.Id 
                               AND HideOnICEForms__c = false 
                               ORDER BY SelectedForMigration__c DESC, UserName__c ASC]) 
        {
        
            bFound = false;
            // DUPE FINDER
            for (ICEUser__c usr : lstMEU) 
            {
                if (meu.Email__c == usr.Email__c)
                {
                    bFound = true;
                }
            }
            // ADD NON-DUPES TO DISTINCT USER LIST
            if (!bFound)
            {
                lstMEU.add(meu); 
            }
            
        }
        
        lstMigrationEndUser = lstMEU; 
        
        return lstMEU; 
        
    }
    
    // SAVE BUTTON 
    public void submitReviewPropertiesUsers() 
    {

        if (lstMigrationProperty.Size() > 0)
        {
            Database.Update(lstMigrationProperty);
        }
        if (lstMigrationEndUser.Size() > 0)
        {
            Database.Update(lstMigrationEndUser);
        }
        
        String ip = ApexPages.currentPage().getHeaders().get('X-Salesforce-SIP');
//        update new ICESubscription__c(Id = iceSub.Id, PropertiesUsersReviewedIP__c = ip);        
        
    }    
    
    // MARK REVIEW PROPERTIES AND USERS STEP COMPLETE AND RETURN TO THE HOME PAGE
    public PageReference completeReviewPropertiesUsers() 
    {
        if (!iceSub.ReviewPropertiesAndUsersCompleted__c)
        {
            update new ICESubscription__c(Id = iceSub.Id, ReviewPropertiesAndUsersCompleted__c = true);
        }
        submitReviewPropertiesUsers();        
        PageReference pg = new PageReference('http://newmarketinc.force.com/migrationportal/NI_ICE_Home?authkey=' + authkey + '&stepsaved=1');
        pg.setRedirect(true);
        return pg;
    }   
  
        

// ===================================================================    
// NIMigrationPortalPropertySettings PAGE FUNCTIONS (STEP 2)   
// ===================================================================    

    public List<ICEProperty__c> getSelectedProperties()  
    {   
    
        List<ICEProperty__c> lstMP = new List<ICEProperty__c>(); 

        for (ICEProperty__c mp : [SELECT Id, PropertyName__c, StreetAddress__c, DelphiNetIsActive__c, City__c, Zip__c, State__c, SelectedForMigration__c, TimeZone__c, EventOnly__c 
                                        FROM ICEProperty__c
                                        WHERE ICESubscriptionId__c = : iceSub.Id 
                                        AND SelectedForMigration__c = true 
                                        ORDER BY SelectedForMigration__c DESC, Name ASC]) 
        {
            lstMP.add(mp);            
        }
        
        lstMigrationProperty = lstMP;
//System.Debug('iceSub.Id = ' + iceSub.Id + ',    lstMigrationProperty.size() = ' + lstMigrationProperty.size());      
        return lstMP; 
        
    }   

    // SAVE BUTTON
    public void submitPropertySettings() 
    {

        if (lstMigrationProperty.Size() > 0)
        {
            Database.Update(lstMigrationProperty);
        }

        String ip = ApexPages.currentPage().getHeaders().get('X-Salesforce-SIP');
//        update new ICESubscription__c(Id = iceSub.Id, PropertiesUsersReviewedIP__c = ip);        
        
    }    
    
    // MARK REVIEW PROPERTIES AND USERS STEP COMPLETE AND RETURN TO THE HOME PAGE
    public PageReference completePropertySettings() 
    {
        if (!iceSub.PropertySettingsCompleted__c)
        {
            update new ICESubscription__c(Id = iceSub.Id, PropertySettingsCompleted__c = true);
        }
        submitPropertySettings();        
        PageReference pg = new PageReference('http://newmarketinc.force.com/migrationportal/NI_ICE_Home?authkey=' + authkey + '&stepsaved=2');
        pg.setRedirect(true);
        return pg;
    }   


// ===================================================================    
// NIMigrationPortalUserSettings PAGE FUNCTIONS (STEP 3)   
// ===================================================================    

    public List<ICEUser__c> getSelectedUsers()  
    {   
    
        List<ICEUser__c> lstMEU = new List<ICEUser__c>(); 
        Boolean bFound = false;

        for (ICEUser__c meu : [SELECT Id, DelphiNetIsActive__c, Email__c, LoginName__c, UserName__c, SelectedForMigration__c, isCorporateAdmin__c, isPropertyAdmin__c, TimeZone__c  
                                FROM ICEUser__c 
                                WHERE ICESubscriptionId__c = : iceSub.Id 
                                AND SelectedForMigration__c = true 
                                ORDER BY SelectedForMigration__c DESC, UserName__c ASC]) 
        {
        
            bFound = false;
            // DUPE FINDER
            for (ICEUser__c usr : lstMEU) 
            {
                if (meu.Email__c == usr.Email__c)
                {
                    bFound = true;
                }
            }
            // ADD NON-DUPES TO DISTINCT USER LIST
            if (!bFound)
            {
                lstMEU.add(meu); 
            }
            
        }
        
        lstMigrationEndUser = lstMEU; 
        
        return lstMEU;         

    }   
    
    // SAVE BUTTON
    public void submitUsersSettings() 
    {

        if (lstMigrationEndUser.Size() > 0)
        {
            Database.Update(lstMigrationEndUser);
        }

        String ip = ApexPages.currentPage().getHeaders().get('X-Salesforce-SIP');
//        update new ICESubscription__c(Id = iceSub.Id, PropertiesUsersReviewedIP__c = ip);        
        
    }    
    
    // MARK REVIEW PROPERTIES AND USERS STEP COMPLETE AND RETURN TO THE HOME PAGE
    public PageReference completeUsersSettings() 
    {
        if (!iceSub.UserSettingsCompleted__c)
        {
            update new ICESubscription__c(Id = iceSub.Id, UserSettingsCompleted__c = true);
        }
        submitUsersSettings();        
        PageReference pg = new PageReference('http://newmarketinc.force.com/migrationportal/NI_ICE_Home?authkey=' + authkey + '&stepsaved=3');
        pg.setRedirect(true);
        return pg;
    }   





// ===================================================================    
// NIMigrationPortal PAGE FUNCTIONS (STEP 4)   
// ===================================================================      
    // prepare the data for Accept On-line Terms step
    public void prepareacceptterms() 
    {
        if (iceSub.ContactCityStateZip__c == null)
        {
            iceSub.ContactCityStateZip__c = loggedincontact.MailingCity + ', ' + loggedincontact.MailingState + '. ' + loggedincontact.MailingPostalCode;
        }
        
        if (iceSub.ContactEmail__c == null)
        {
            iceSub.ContactEmail__c = loggedincontact.Email;
        }
        
        if (iceSub.ContactName__c == null)
        {
            iceSub.ContactName__c = loggedincontact.Name;
        }
        
        if (iceSub.ContactStreetAddress__c == null)
        {
            iceSub.ContactStreetAddress__c = loggedincontact.MailingStreet;
        }
        
        if (iceSub.ContactTitle__c == null)
        {
            iceSub.ContactTitle__c = loggedincontact.Title;
        }
        
        if (iceSub.ContactVenue__c == null)
        {
            iceSub.ContactVenue__c = loggedincontact.Account.Name;
        }
                
        agreementread = false;
        
//        if (iceSub.AuthorizationContact__c != null)
//        {
//            usecontactdata = true;
//        }
//        else
//        {
//            usecontactdata = false;
//        }

    }
    
    public PageReference acceptTerms() 
    {
    
        PageReference pg = null; 

        // VISITOR DETAILS =========================================================
//        iceSub.AuthorizationContact__c = loggedincontact.Id; 
//        iceSub.AgreementAcceptedBy__c = loggedincontact.Id; 
        iceSub.AcceptOnlineTermsCompleted__c = true; 
        iceSub.IAcknowledgeandHavetheAuthority__c = true; 

        String ip = ApexPages.currentPage().getHeaders().get('X-Salesforce-SIP'); 
        iceSub.AgreementAcceptedIP__c = ip; 
        
        update iceSub; 
        
        pg = new PageReference('http://newmarketinc.force.com/migrationportal/NI_ICE_Home?authkey=' + authkey + '&stepsaved=4');         
        pg.setRedirect(true);
        return pg;
        
    }


// ===================================================================    
// NIMigrationPortal PAGE FUNCTIONS (STEP 5)   
// ===================================================================  

    public string strProp {get; set;} 
    public string strType {get; set;}    
    
    public List<SelectOption> getItems() 
    {
        
        List<SelectOption> options = new List<SelectOption>();

        for (ICEProperty__c mp : [SELECT Id, PropertyName__c 
                                    FROM ICEProperty__c
                                    WHERE ICESubscriptionId__c = : iceSub.Id 
                                    AND SelectedForMigration__c = true 
                                    ORDER BY Name ASC]) 
        {            
            options.add(new SelectOption(mp.PropertyName__c, mp.PropertyName__c));           
        }
        
        return options;
        
    }
    
    public List<SelectOption> getTypes() 
    {
        
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('ACCT', 'Account')); 
        options.add(new SelectOption('CNCT', 'Contact')); 
        options.add(new SelectOption('BOOK', 'Booking')); 
        options.add(new SelectOption('NRATE', 'Negotiated Rate'));
        options.add(new SelectOption('BEO', 'BEO'));
        options.add(new SelectOption('SAMP_BEO', 'Sample Merged BEO'));        
        options.add(new SelectOption('BQT', 'Banquet Check'));    
        options.add(new SelectOption('SAMP_BQT', 'Sample Merged Banquet Check'));

        return options;
        
    }    
        
    // prepares data for Upload Merge Documents page and handles file upload
    public void uploaddocs() 
    {
        if (authenticated) 
        {
            // save uploaded file, clear doc body and name variables
            if ((uploadeddocname != null) && (uploadeddocbody != null) && (uploadeddocbody.size() > 0))
            {
                
                string strFinalFileName = strProp + '_-_' + strType + '_-_' + uploadeddocname;

                Attachment doc = new Attachment();
                doc.OwnerId = UserInfo.getUserId();
                doc.IsPrivate = false;
                doc.ParentId = iceSub.Id;
//                doc.Name = uploadeddocname;
                doc.Name = strFinalFileName;
                doc.Body = uploadeddocbody;
                insert doc;
                uploadeddocbody = null;
                uploadeddocname = null;
            }
            
        }
        
        // fetch the names of files already uploaded
        uploadeddocs = new String[0];
        lstAttachments = new List<Attachment>();
        
        for (Attachment att : [SELECT Id, Name, Description FROM Attachment WHERE ParentId = : iceSub.Id ORDER BY Name]) 
        {
            uploadeddocs.add(att.Name);
            lstAttachments.add(att);
        }
        
        uploadeddocssize = uploadeddocs.size();
        
    }

/*
    // delete an uploaded document SMH NEW for prompt.
    public void deleteAttachment(string strAttachId) 
    {
        if (strAttachId != null) 
        {
            for (Attachment att : [SELECT Id FROM Attachment WHERE ParentId = : iceSub.Id AND Id = : strAttachId]) 
            {
                delete att;
            }
        }
        uploaddocs();
    }
*/

    public void deletedoc() 
    {
system.debug('========================= ' + filetodelete);    
        if (filetodelete != null) 
        {
            for (Attachment att : [SELECT Id FROM Attachment WHERE ParentId = : iceSub.Id AND Id = : filetodelete]) 
            delete att;
        }
        uploaddocs();
    }   

    // mark Upload Merge Documents... step complete and return to the home page
    public PageReference completeuploaddocsstep() 
    {
        
        uploaddocs();
        
        if (!iceSub.UploadMergeDocumentsCompleted__c)
        {
            update new ICESubscription__c(Id = iceSub.Id, UploadMergeDocumentsCompleted__c = true);
        }
        
        PageReference pg = new PageReference('http://newmarketinc.force.com/migrationportal/NI_ICE_Home?authkey=' + authkey + '&stepsaved=5');
        pg.setRedirect(true);
        return pg;
        
    }

}