force-app/main/default/objects/AH_UDC_ConfigurationSetting__c/AH_UDC_ConfigurationSetting__c.object-meta.xml
<CustomObject>
    <description>This is a common object to store settings used by the application, allowing storage of both managed package and custom settings.</description>
    <label>UDC Configuration Setting</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UDC Configuration Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_UDC_Form__c/AH_UDC_Form__c.object-meta.xml
<CustomObject>
    <description>This object contains details of Forms that are available as Workbook Steps.</description>
    <label>UDC Form</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UDC Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_UDC_Form__c/fields/FormAssemblyId__c.field-meta.xml
<CustomField>
    <fullName>FormAssemblyId__c</fullName>
    <description>This is the numeric ID for the form in Form Assembly.
Example URL: https://amadeushospitality.tfaforms.net/4853168
Form Assembly Id would be: 4853168</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>This is the numeric ID for the form in Form Assembly.
Example URL: https://amadeushospitality.tfaforms.net/4853168
Form Assembly Id would be: 4853168</inlineHelpText>
    <label>Form Assembly Id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AH_UDC_Form__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>Click this link to preview your form.</description>
    <formula>IF( RecordType.DeveloperName !=&apos;FormAssembly&apos;,&apos;&apos;,
&apos;https://amadeushospitalitysb.tfaforms.net/&apos; +
IF(ISBLANK(CustomUrlId__c), FormAssemblyId__c, &apos;f/&apos; + CustomUrlId__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Click this link to preview your form.</inlineHelpText>
    <label>Preview Form</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AH_UDC_Workbook__c/AH_UDC_Workbook__c.object-meta.xml
<CustomObject>
    <description>This object contains details of workbooks and sent workbooks</description>
    <label>UDC Workbook</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Workbook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UDC Workbooks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_UDC_Workbook__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This determines if the Workbook is available to be sent</description>
    <inlineHelpText>This determines if the Workbook is available to be sent</inlineHelpText>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AH_UDC_Workbook__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Denotes which product for which the Workbook is used</description>
    <inlineHelpText>Denotes which product for which the Workbook is used</inlineHelpText>
    <label>Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ACRS</fullName>
                <color>#0B6FCE</color>
                <label>ACRS</label>
            </value>
            <value>
                <fullName>All Products</fullName>
                <color>#DDDDDD</color>
                <label>All Products</label>
            </value>
            <value>
                <fullName>APMA</fullName>
                <color>#A845DC</color>
                <label>APMA</label>
            </value>
            <value>
                <fullName>APMS</fullName>
                <color>#F3D904</color>
                <label>APMS</label>
            </value>
            <value>
                <fullName>ASEM Standard</fullName>
                <isActive>false</isActive>
                <label>ASEM Standard</label>
            </value>
            <value>
                <fullName>BI</fullName>
                <color>#419249</color>
                <label>BI</label>
            </value>
            <value>
                <fullName>BI - Agency360</fullName>
                <color>#B6E32E</color>
                <label>BI - Agency360</label>
            </value>
            <value>
                <fullName>BI - Demand360</fullName>
                <color>#641CCF</color>
                <label>BI - Demand360</label>
            </value>
            <value>
                <fullName>BI - RevenueStrategy360</fullName>
                <color>#F96FB7</color>
                <label>BI - RevenueStrategy360</label>
            </value>
            <value>
                <fullName>Central Sales</fullName>
                <color>#2F5D85</color>
                <label>Central Sales</label>
            </value>
            <value>
                <fullName>Consortia</fullName>
                <color>#AFCADF</color>
                <label>Consortia</label>
            </value>
            <value>
                <fullName>Delphi</fullName>
                <color>#A53711</color>
                <label>Delphi</label>
            </value>
            <value>
                <fullName>Delphi Diagramming</fullName>
                <color>#78C953</color>
                <label>Delphi Diagramming</label>
            </value>
            <value>
                <fullName>Delphi Select</fullName>
                <color>#66E9BD</color>
                <label>Delphi Select</label>
            </value>
            <value>
                <fullName>Digital Media</fullName>
                <color>#EFAE73</color>
                <label>Digital Media</label>
            </value>
            <value>
                <fullName>DirectBook</fullName>
                <color>#57F17C</color>
                <label>DirectBook</label>
            </value>
            <value>
                <fullName>GDS Media</fullName>
                <color>#0B6FCE</color>
                <label>GDS Media</label>
            </value>
            <value>
                <fullName>GMS</fullName>
                <color>#78C953</color>
                <label>GMS</label>
            </value>
            <value>
                <fullName>iHotelier</fullName>
                <color>#E27001</color>
                <label>iHotelier</label>
            </value>
            <value>
                <fullName>Integrations</fullName>
                <color>#A845DC</color>
                <label>Integrations</label>
            </value>
            <value>
                <fullName>IoT</fullName>
                <color>#FF6600</color>
                <label>IoT</label>
            </value>
            <value>
                <fullName>LinkHotel</fullName>
                <color>#F3D904</color>
                <label>LinkHotel</label>
            </value>
            <value>
                <fullName>MeetingBroker</fullName>
                <color>#A53711</color>
                <label>MeetingBroker</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <color>#66E9BD</color>
                <label>Other</label>
            </value>
            <value>
                <fullName>RezExchange</fullName>
                <color>#0B24BE</color>
                <label>RezExchange</label>
            </value>
            <value>
                <fullName>RFP Toolkit</fullName>
                <color>#419249</color>
                <label>RFP Toolkit</label>
            </value>
            <value>
                <fullName>SEO Digital Marketing</fullName>
                <color>#8F6429</color>
                <label>SEO Digital Marketing</label>
            </value>
            <value>
                <fullName>SO</fullName>
                <color>#B6E32E</color>
                <label>SO</label>
            </value>
            <value>
                <fullName>Travel Audience</fullName>
                <color>#641CCF</color>
                <label>Travel Audience</label>
            </value>
            <value>
                <fullName>Web</fullName>
                <color>#F96FB7</color>
                <label>Web</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AH_UDC_Workbook__c/fields/SecurityCode__c.field-meta.xml
<CustomField>
    <fullName>SecurityCode__c</fullName>
    <description>This is the security code specific and unique to this Workbook Sent. This will allow the form to retrieve data from Salesforce.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>This is the security code specific and unique to this Workbook Sent. This will allow the form to retrieve data from Salesforce.</inlineHelpText>
    <label>Security Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AH_UDC_Workbook__c/recordTypes/AH_UDC_Workbook.recordType-meta.xml
<RecordType>
    <fullName>AH_UDC_Workbook</fullName>
    <active>true</active>
    <description>Record type for creating Workbooks</description>
    <label>Workbook</label>
</RecordType>

force-app/main/default/objects/AH_UDC_WorkbookStep__c/AH_UDC_WorkbookStep__c.object-meta.xml
<CustomObject>
    <description>This object contains details of Workbook steps and sent Workbook steps.</description>
    <label>UDC Workbook Step</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Workbook Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UDC Workbook Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_UDC_WorkbookStep__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This determines if this step is enabled</description>
    <inlineHelpText>This determines if this step is enabled</inlineHelpText>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AH_UDC_WorkbookStep__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The form which this step uses</description>
    <inlineHelpText>The form which this step uses</inlineHelpText>
    <label>Form</label>
    <referenceTo>AH_UDC_Form__c</referenceTo>
    <relationshipLabel>UDC Workbook Steps</relationshipLabel>
    <relationshipName>Workbook_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AH_UDC_WorkbookStep__c/fields/Prerequisite_Step__c.field-meta.xml
<CustomField>
    <fullName>Prerequisite_Step__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If this step requires another step to be completed before, select that step here.</description>
    <inlineHelpText>If this step requires another step to be completed before, select that step here.</inlineHelpText>
    <label>Prerequisite Step</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2 AND 3</booleanFilter>
        <errorMessage>The Prerequisite Step must be enabled and part of your current workbook.</errorMessage>
        <filterItems>
            <field>AH_UDC_WorkbookStep__c.Workbook__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Workbook__c</valueField>
        </filterItems>
        <filterItems>
            <field>AH_UDC_WorkbookStep__c.Enabled__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>AH_UDC_WorkbookStep__c.Id</field>
            <operation>notEqual</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <infoMessage>Chose another step on the same workbook.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AH_UDC_WorkbookStep__c</referenceTo>
    <relationshipLabel>UDC Workbook Steps</relationshipLabel>
    <relationshipName>UDC_Workbook_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AH_UDC_WorkbookStep__c/fields/SortOrder__c.field-meta.xml
<CustomField>
    <fullName>SortOrder__c</fullName>
    <description>The order of the steps</description>
    <inlineHelpText>The order of the steps</inlineHelpText>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AH_UDC_WorkbookStep__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>The External URL that will be shown for the step.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The External URL that will be shown for the step.</inlineHelpText>
    <label>External URL</label>
    <length>2048</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AH_UDC_WorkbookStep__c/fields/Workbook__c.field-meta.xml
<CustomField>
    <fullName>Workbook__c</fullName>
    <description>This is the Workbook record to which the step is attached</description>
    <inlineHelpText>This is the Workbook record to which the step is attached</inlineHelpText>
    <label>Workbook</label>
    <referenceTo>AH_UDC_Workbook__c</referenceTo>
    <relationshipLabel>UDC Workbook Steps</relationshipLabel>
    <relationshipName>Workbook_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AH_UDC_WorkbookStep__c/recordTypes/AH_UDC_WorkbookStep.recordType-meta.xml
<RecordType>
    <fullName>AH_UDC_WorkbookStep</fullName>
    <active>true</active>
    <description>Created to capture the steps in a Workbook</description>
    <label>Workbook Step</label>
</RecordType>

force-app/main/default/objects/AH_UDC_WorkbookStep__c/recordTypes/AH_UDC_WorkbookStepSent.recordType-meta.xml
<RecordType>
    <fullName>AH_UDC_WorkbookStepSent</fullName>
    <active>true</active>
    <description>Created to capture the steps in a Workbook sent.</description>
    <label>Workbook Step Sent</label>
</RecordType>

force-app/main/default/objects/NI_Documentation__c/NI_Documentation__c.object-meta.xml
<CustomObject>
    <label>NI Documentation</label>
    <nameField>
        <displayFormat>DOC-{00000}</displayFormat>
        <label>Doc #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NI Documentation</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_Documentation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Salesforce.com Change Request: NICC-007494</description>
    <inlineHelpText>Related Account record</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>NI Documentation</relationshipLabel>
    <relationshipName>NI_Documentation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Documentation__c/recordTypes/AH_UDC_Workbook.recordType-meta.xml
<RecordType>
    <fullName>AH_UDC_Workbook</fullName>
    <active>true</active>
    <description>Used by Unified Data Collection to manage Workbooks</description>
    <label>Unified Data Collection - Workbook</label>
</RecordType>

force-app/main/default/classes/AH_UDC_WorkbookStepTriggerHelper_Test.cls
/**
 * Name          : AH_UDC_WorkbookStepTriggerHelper_Test
 * Created By    : Amadeus Hospitality Services (Rob.Stevens@Amadeus.com)
 * Created Date  : 2021-04-20
 * Description   : This class is a test class for AH_UDC_WorkbookStepTriggerHelper
 * Dependencies  : AH_UDC_WorkbookStepTriggerHelper
 **/

@isTest
private class AH_UDC_WorkbookStepTriggerHelper_Test {
   @testSetup
   private static void setupTestData() {
      AH_UDC_InitializationHelper.Initialize('TestClass');
      //Prevent error : System.LimitException: Too many SOQL queries: 101
      AH_UDC_InitializationHelper.Initialize('ConfigurationSettings');
      List<Profile> lstProfiles = new List<Profile> ([SELECT Id FROM Profile WHERE Name = :AH_UDC_Constants.PROFILE_DEFAULT_NAME_PSA_SF_LIGHTNING]);
      System.assertEquals(true, lstProfiles != null && lstProfiles.size() > 0, 'Could not get profile Id of \'' + AH_UDC_Constants.PROFILE_DEFAULT_NAME_PSA_SF_LIGHTNING + '\'');

      User objWorkbookAdminUser = null;
      AH_UDC_WorkbookStep__c objWorkbookStep = null;
      User objUDCSystemAdminUser = null;
      Account objAccount = null;
      NI_Documentation__c objNIDoc = null;
      AH_UDC_Workbook__c objWorkbook = null;
      Schema.DescribeFieldResult fieldResult = null;
      List<Schema.PicklistEntry> pickListEntry = null;

      //Get Product Picklist
      fieldResult = AH_UDC_Workbook__c.Product__c.getDescribe();
      if (fieldResult != null) {
         pickListEntry = fieldResult.getPicklistValues();
      }

      //Insert Workbook Admin user
      objWorkbookAdminUser = AH_UDC_TestData.GetUserObject(null, lstProfiles[0].Id, 'Workbook', 'Admin', 'Mr.', 'admin@workbook.com', 'admin@workbook.com.ahcc');
      objWorkbookAdminUser.No_AD_Account_Standard_User__c = true;
      insert objWorkbookAdminUser;

      //Insert UDC System Admin user
      objUDCSystemAdminUser = AH_UDC_TestData.GetUserObject(null, lstProfiles[0].Id, 'UDC', 'SystemAdmin', 'Mr.', 'systemadmin@udc.com', 'systemadmin@udc.com.ahcc');
      objUDCSystemAdminUser.No_AD_Account_Standard_User__c = true;
      insert objUDCSystemAdminUser;

      //Insert new Account data 		
      objAccount = AH_UDC_TestData.GetAccountObject('UDC Test Account 2', 'Hospitality Companies', 'Portsmouth', 'US', '03801', 'NH', '75 New Hampshire Ave');
      insert objAccount;

      objNIDoc = AH_UDC_TestData.GetNIDocObject('Test NI Document 1', Date.newInstance(2021, 8, 30));
      objNIDoc.Account__c = objAccount.Id;
      insert objNIDoc;

      //Insert Workbook Record
      objWorkbook = AH_UDC_TestData.GetWorkbookObject(objNIDoc.Id, 'Test Workbook 1', 'Test Workbook 1 Description', 'Central Sales');
      //Set OwnerId to provide Workbook Step delete rights to Workbook Admin User
      objWorkbook.OwnerId = objWorkbookAdminUser.Id;
      insert objWorkbook;

      //Insert Workbook Step Record for Delete
      objWorkbookStep = AH_UDC_TestData.GetWorkbookStepObject(objWorkbook.Id, 'Test Workbook Step');
      objWorkbookStep.URL__c = 'https://www.google.com/';
      insert objWorkbookStep;

      //Create Form
      AH_UDC_Form__c form = new AH_UDC_Form__c(Name = 'TestForm1', FormAssemblyId__c = '123');
      insert form;

      Id wbRTId = Schema.SObjectType.AH_UDC_Workbook__c.getRecordTypeInfosByDeveloperName().get('AH_UDC_Workbook').getRecordTypeId();
      Id wbsRTId = Schema.SObjectType.AH_UDC_WorkbookStep__c.getRecordTypeInfosByDeveloperName().get('AH_UDC_WorkbookStep').getRecordTypeId();

      //Test Update Data Setup
      //Insert Workbook 
      AH_UDC_Workbook__c wb1 = new AH_UDC_Workbook__c(Name = 'Test11', RecordtypeId = wbRTId, SecurityCode__c = '4a1d7cd6-e80a-4561-975e-7229655ed41f3758b38b-75f0-416d-872e-1205b8cbaaa7');
      wb1.Product__c = pickListEntry[0].getLabel();
      insert wb1;

      AH_UDC_WorkbookStep__c wbs21 = new AH_UDC_WorkbookStep__c(Name = 'WBS21', RecordtypeId = wbsRTId, Workbook__c = wb1.id, URL__c = 'www.googlese1.com');
      insert wbs21;

      AH_UDC_WorkbookStep__c wbs31 = new AH_UDC_WorkbookStep__c(Name = 'WBS31', RecordtypeId = wbsRTId, Workbook__c = wb1.id, URL__c = 'www.googlese.com');
      insert wbs31;

      AH_UDC_WorkbookStep__c wbs41 = new AH_UDC_WorkbookStep__c(Name = 'WBS41', RecordtypeId = wbsRTId, Workbook__c = wb1.id, form__c = form.id);
      wbs41.Prerequisite_Step__c = wbs21.Id;
      insert wbs41;
      //END Test Update

      //Test Delete Setup Data
      //Insert Workbook
      AH_UDC_Workbook__c wbDelete = new AH_UDC_Workbook__c(Name = 'TestDelete', RecordtypeId = wbRTId, SecurityCode__c = '4a1d7cd6-e80a-4561-975e-7229655ed41f3758b38b-75f0-416d-872e-1205b8cbaaa1');
      wbDelete.Product__c = pickListEntry[0].getLabel();
      insert wbDelete;

      AH_UDC_WorkbookStep__c wbs2 = new AH_UDC_WorkbookStep__c(Name = 'WBS2', RecordtypeId = wbsRTId, Workbook__c = wbDelete.id, URL__c = 'www.test1.com');
      insert wbs2;

      AH_UDC_WorkbookStep__c wbs3 = new AH_UDC_WorkbookStep__c(Name = 'WBS3', RecordtypeId = wbsRTId, Workbook__c = wbDelete.id, form__c = form.id);
      insert wbs3;

      AH_UDC_WorkbookStep__c wbs4 = new AH_UDC_WorkbookStep__c(Name = 'WBS4', RecordtypeId = wbsRTId, Workbook__c = wbDelete.id, URL__c = 'www.test.com');
      wbs4.Prerequisite_Step__c = wbs2.Id;
      insert wbs4;
      //END Test Delete

      //Test UnDelete Setup Data
      AH_UDC_Workbook__c wbUndelete = new AH_UDC_Workbook__c(Name = 'TestUnDelete', RecordtypeId = wbRTId, SecurityCode__c = '4a1d7cd6-e80a-4561-975e-7229655ed41f3758b38b-75f0-416d-872e-1205b8cbaaa5');
      wbUndelete.Product__c = pickListEntry[0].getLabel();
      insert wbUndelete;

      AH_UDC_WorkbookStep__c wbs10 = new AH_UDC_WorkbookStep__c(Name = 'WBS10', RecordtypeId = wbsRTId, Workbook__c = wbUndelete.id, URL__c = 'www.test.com');
      insert wbs10;

      AH_UDC_WorkbookStep__c wbs11 = new AH_UDC_WorkbookStep__c(Name = 'WBS11', RecordtypeId = wbsRTId, Workbook__c = wbUndelete.id, form__c = form.id);
      wbs11.Prerequisite_Step__c = wbs10.Id;
      insert wbs11;
      //END Test UnDelete Setup Data

      //Test Exception Setup Data
      AH_UDC_Workbook__c wbException = new AH_UDC_Workbook__c(Name = 'TestExc', RecordtypeId = wbRTId, SecurityCode__c = '4a1d7cd6-e80a-4561-975e-7229655ed41f3758b38b-75f0-416d-872e-1205b8cbaaa2');
      wbException.Product__c = pickListEntry[0].getLabel();
      insert wbException;
      //END Test Exception Setup Data
   }

   @isTest
   private static void testUpdate() {
      Test.startTest();

      List<AH_UDC_Workbook__c> workbookDetail = [select id, name from AH_UDC_Workbook__c WHERE Name = 'Test11'];
      System.assertEquals(1, workbookDetail.size(), 'Expected 1 Workbook.');

      List<AH_UDC_WorkbookStep__c> workbookSteps = [select id, name, sortorder__c from AH_UDC_WorkbookStep__c WHERE Workbook__c = :workbookDetail[0].id order by SortOrder__c];
      System.assertEquals(3, workbookSteps.size(), 'Expected 3 Workbook Steps');

      List<AH_UDC_WorkbookStep__c> workbookStep21 = [select id, name, sortorder__c, Prerequisite_Step__c from AH_UDC_WorkbookStep__c WHERE Workbook__c = :workbookDetail[0].id AND Name = 'WBS21'];
      System.assertEquals(1, workbookStep21.size(), 'Expected 1 Workbook Steps');

      List<AH_UDC_WorkbookStep__c> workbookStep31 = [select id, name, sortorder__c, Prerequisite_Step__c from AH_UDC_WorkbookStep__c WHERE Workbook__c = :workbookDetail[0].id AND Name = 'WBS31'];
      System.assertEquals(1, workbookStep31.size(), 'Expected 1 Workbook Steps');

      List<AH_UDC_WorkbookStep__c> workbookStep41 = [select id, name, sortorder__c, Prerequisite_Step__c from AH_UDC_WorkbookStep__c WHERE Workbook__c = :workbookDetail[0].id AND Name = 'WBS41'];
      System.assertEquals(1, workbookStep41.size(), 'Expected 1 Workbook Steps');

      AH_UDC_WorkbookStep__c[] workstep1 = [select id, Enabled__c, SortOrder__c, Prerequisite_Step__c from AH_UDC_WorkbookStep__c WHERE Workbook__c = :workbookDetail[0].id AND Id = :workbookStep31[0].id];
      workstep1[0].Enabled__c = false;
      workstep1[0].SortOrder__c = 1;
      workstep1[0].Prerequisite_Step__c = workbookStep21[0].Id;
      update workstep1;
      System.assertEquals(true, workstep1[0].Prerequisite_Step__c != null, 'updated Sucessfully');
      System.assertEquals(false, workstep1[0].Enabled__c, 'updated Sucessfully');

      AH_UDC_WorkbookStep__c[] workstep2 = [select id, Enabled__c, SortOrder__c, Prerequisite_Step__c from AH_UDC_WorkbookStep__c WHERE Workbook__c = :workbookDetail[0].id AND Id = :workbookStep41[0].id];
      workstep2[0].Enabled__c = true;
      workstep2[0].SortOrder__c = 1;
      update workstep2;

      AH_UDC_WorkbookStep__c[] workstep = [select id from AH_UDC_WorkbookStep__c WHERE Workbook__c = :workbookDetail[0].id AND Id = :workbookStep31[0].id];
      Test.stopTest();

   }

   @isTest
   private static void testDelete() {
      Test.startTest();
      List<AH_UDC_Workbook__c> workbookDetail = [select id, name from AH_UDC_Workbook__c WHERE Name = 'TestDelete'];
      System.assertEquals(1, workbookDetail.size(), 'Expected 1 Workbook.');

      List<AH_UDC_WorkbookStep__c> workbookSteps = [select id, name, sortorder__c from AH_UDC_WorkbookStep__c WHERE Workbook__c = :workbookDetail[0].id order by SortOrder__c];
      System.assertEquals(3, workbookSteps.size(), 'Expected 3 Workbook Steps');

      List<AH_UDC_WorkbookStep__c> workbookStep3 = [select id, name, sortorder__c, Prerequisite_Step__c from AH_UDC_WorkbookStep__c WHERE Workbook__c = :workbookDetail[0].id AND Name = 'WBS3'];
      System.assertEquals(1, workbookStep3.size(), 'Expected 1 Workbook Steps');

      List<AH_UDC_WorkbookStep__c> workbookSteps3 = [select id, name, sortorder__c from AH_UDC_WorkbookStep__c WHERE Workbook__c = :workbookDetail[0].id AND Id = :workbookStep3[0].Id];
      delete workbookSteps3;

      List<AH_UDC_WorkbookStep__c> workbookSteps1 = [select id, name, sortorder__c from AH_UDC_WorkbookStep__c WHERE Workbook__c = :workbookDetail[0].id order by SortOrder__c];
      System.assertEquals(2, workbookSteps1.size(), 'Expected 2 Workbook Steps after deleting 1');

      Test.stopTest();
   }

   @isTest
   private static void testUndelete() {
      Test.startTest();

      List<AH_UDC_Workbook__c> workbookDetail = [select id, name from AH_UDC_Workbook__c WHERE Name = 'TestUnDelete'];
      System.assertEquals(1, workbookDetail.size(), 'Expected 1 Workbook.');

      List<AH_UDC_WorkbookStep__c> workbookStep11 = [select id, name, sortorder__c from AH_UDC_WorkbookStep__c WHERE Workbook__c = :workbookDetail[0].id AND Name = 'WBS11'];
      System.assertEquals(1, workbookStep11.size(), 'Expected 1 Workbook Steps');

      id workbookStep11iD = workbookStep11[0].Id;
      delete workbookStep11;

      List<AH_UDC_WorkbookStep__c> workbookSteps12 = [select id, name, sortorder__c from AH_UDC_WorkbookStep__c WHERE Workbook__c = :workbookDetail[0].id order by SortOrder__c];
      System.assertEquals(1, workbookSteps12.size(), 'Expected 1 Workbook Steps after deleting 1');

      AH_UDC_WorkbookStep__c[] workstep = [select id from AH_UDC_WorkbookStep__c WHERE Workbook__c = :workbookDetail[0].id AND Id = :workbookStep11iD ALL ROWS];

      undelete workbookStep11;

      List<AH_UDC_WorkbookStep__c> workbookSteps2 = [select id, name, sortorder__c from AH_UDC_WorkbookStep__c WHERE Workbook__c = :workbookDetail[0].id order by SortOrder__c];
      System.assertEquals(2, workbookSteps2.size(), 'Expected 2 Workbook Steps after undelete 1');

      Test.stopTest();
   }

   @isTest
   private static void testException() {

      List<AH_UDC_Workbook__c> workbookDetail = [select id, name from AH_UDC_Workbook__c WHERE Name = 'TestExc'];
      System.assertEquals(1, workbookDetail.size(), 'Expected 1 Workbook.');

      List<AH_UDC_Form__c> formDetail = [select id, name from AH_UDC_Form__c WHERE Name = 'TestForm1' AND FormAssemblyId__c = '123'];
      System.assertEquals(1, formDetail.size(), 'Expected 1 form.');

      Id wbsRTId = Schema.SObjectType.AH_UDC_WorkbookStep__c.getRecordTypeInfosByDeveloperName().get('AH_UDC_WorkbookStep').getRecordTypeId();

      Test.startTest();

      Boolean InsertException = false;
      try
      {
         AH_UDC_WorkbookStep__c wbs1 = new AH_UDC_WorkbookStep__c(Name = 'TestException',
                                                                  RecordtypeId = wbsRTId,
                                                                  Workbook__c = workbookDetail[0].id,
                                                                  form__c = formDetail[0].id);
         insert wbs1;
      }
      catch(exception exc)
      {
         InsertException = true;
      }

      Test.stopTest();
      System.assertEquals(true, InsertException, 'Expected Exception');
   }

   @isTest
   private static void testDeleteWithWorkbookAdminUser() {

      Test.startTest();
      testDeleteFuture();
      Test.stopTest();
   }

   //Created future method to prevent erro: MIXED_DML_OPERATION
   //Error Description: DML operation on setup object is not permitted after you have updated a non-setup object (or vice versa): PermissionSetAssignment, original object: AH_UDC_ConfigurationSetting__c:
   @Future
   private static void testDeleteFuture() {
      User objWorkbookAdminUser = [SELECT Id FROM User WHERE Username = 'admin@workbook.com.ahcc'];
      System.assertEquals(true, objWorkbookAdminUser != null, 'Workbook Admin User Record Not Found');

      List<PermissionSet> lstPermissionSets = new List<PermissionSet> ([SELECT Id FROM PermissionSet WHERE Name = 'AH_UDC_WorkbookAdministrator']);
      System.assertEquals(true, lstPermissionSets != null && lstPermissionSets.size() > 0, 'Could not get Permission Set Id of AH_UDC_WorkbookAdministrator');

      PermissionSetAssignment objPermissionSetAssignment = null;
      //Assign Workbook Admin permission set to the user
      objPermissionSetAssignment = new PermissionSetAssignment(PermissionSetId = lstPermissionSets[0].Id, AssigneeId = objWorkbookAdminUser.Id);
      insert objPermissionSetAssignment;

      String WorkbookStepSentRecordTypeId = Schema.SObjectType.AH_UDC_WorkbookStep__c.getRecordTypeInfosByDeveloperName().get('AH_UDC_WorkbookStepSent').getRecordTypeId();
      System.assertEquals(true, WorkbookStepSentRecordTypeId != null && WorkbookStepSentRecordTypeId != '', 'Record type AH_UDC_WorkbookStepSent not found');

      AH_UDC_WorkbookStep__c objWorkbookStep = [SELECT Id FROM AH_UDC_WorkbookStep__c WHERE RecordTypeId = :WorkbookStepSentRecordTypeId LIMIT 1];
      System.assertEquals(true, objWorkbookStep != null, 'Workbook Step Sent Record Not Found');

      System.runAs(objWorkbookAdminUser) {
         Id deletedId = null;
         try {
            deletedId = objWorkbookStep.Id;
            delete objWorkbookStep;
         }
         catch(Exception ex) {
            System.assertEquals(true, ex.getMessage().indexOf(Label.AH_UDC_NoAccessRightsDelete) > - 1, 'Error occured in deleting workbook step : ' + ex.getMessage());
         }

         //Check if workbook step record is deleted or not
         List<AH_UDC_WorkbookStep__c> lstWorkbookSteps = new List<AH_UDC_WorkbookStep__c> ([SELECT Id FROM AH_UDC_WorkbookStep__c WHERE Id = :deletedId]);
         System.assertEquals(true, lstWorkbookSteps != null && lstWorkbookSteps.size() > 0, 'Workbook Step has been deleted by using the user who don\'t have any permission set assigned');
      }

      User objUDCSystemAdminUser = [SELECT Id FROM User WHERE Username = 'systemadmin@udc.com.ahcc'];
      System.assertEquals(true, objUDCSystemAdminUser != null, 'UDC System Admin User Record Not Found');

      lstPermissionSets = new List<PermissionSet> ([SELECT Id FROM PermissionSet WHERE Name = 'AH_UDC_SystemAdministrator']);
      System.assertEquals(true, lstPermissionSets != null && lstPermissionSets.size() > 0, 'Could not get Permission Set Id of AH_UDC_SystemAdministrator');

      objPermissionSetAssignment = null;

      //Assign UDC System Admin permission set to the user
      objPermissionSetAssignment = new PermissionSetAssignment(PermissionSetId = lstPermissionSets[0].Id, AssigneeId = objUDCSystemAdminUser.Id);
      insert objPermissionSetAssignment;

      System.runAs(objUDCSystemAdminUser) {
         Id deletedId = objWorkbookStep.Id;
         delete objWorkbookStep;

         //Check if workbook step record is deleted or not
         List<AH_UDC_WorkbookStep__c> lstDeletedWorkbookSteps = new List<AH_UDC_WorkbookStep__c> ([SELECT Id FROM AH_UDC_WorkbookStep__c WHERE Id = :deletedId]);
         System.assertEquals(true, lstDeletedWorkbookSteps == null || lstDeletedWorkbookSteps.size() == 0, 'Workbook Step not deleted by using UDC System Admin User');
      }
   }
}