force-app/main/default/objects/AH_UDC_ConfigurationSetting__c/AH_UDC_ConfigurationSetting__c.object-meta.xml
<CustomObject>
    <description>This is a common object to store settings used by the application, allowing storage of both managed package and custom settings.</description>
    <label>UDC Configuration Setting</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UDC Configuration Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_UDC_ConfigurationSetting__c/fields/AH_UDC__c.field-meta.xml
<CustomField>
    <fullName>AH_UDC__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if this setting required by any AH_UDC custom code in this Org</description>
    <inlineHelpText>Indicates if this setting required by any AH_UDC custom code in this Org</inlineHelpText>
    <label>AH_UDC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AH_UDC_ConfigurationSetting__c/fields/DisplayOrder__c.field-meta.xml
<CustomField>
    <fullName>DisplayOrder__c</fullName>
    <description>This is the order in which the setting will be displayed; entries with the same value will be sorted by name.</description>
    <inlineHelpText>This is the order in which the setting will be displayed; entries with the same value will be sorted by name.</inlineHelpText>
    <label>Display Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AH_UDC_ConfigurationSetting__c/fields/OrgName__c.field-meta.xml
<CustomField>
    <fullName>OrgName__c</fullName>
    <description>This is the Name of the org for which these settings should be used; alternatively if no Org Name is specified it applies to all orgs.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This is the Name of the org for which these settings should be used; alternatively if no Org Name is specified it applies to all orgs.</inlineHelpText>
    <label>Org Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AH_UDC_ConfigurationSetting__c/fields/PageGroupName__c.field-meta.xml
<CustomField>
    <fullName>PageGroupName__c</fullName>
    <description>This is the grouping at the page level of display.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This is the grouping at the page level of display.</inlineHelpText>
    <label>Page Group Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AH_UDC_ConfigurationSetting__c/fields/PageName__c.field-meta.xml
<CustomField>
    <fullName>PageName__c</fullName>
    <description>This is the page onto which the settings should be grouped.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This is the page onto which the settings should be grouped.</inlineHelpText>
    <label>Page Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AH_UDC_ConfigurationSetting__c/fields/PageSectionName__c.field-meta.xml
<CustomField>
    <fullName>PageSectionName__c</fullName>
    <description>This is the section header name on the page.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This is the section header name on the page.</inlineHelpText>
    <label>Page Section Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AH_UDC_ConfigurationSetting__c/fields/SettingDisplayName__c.field-meta.xml
<CustomField>
    <fullName>SettingDisplayName__c</fullName>
    <description>This is the display name for the setting.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This is the display name for the setting.</inlineHelpText>
    <label>Setting Display Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AH_UDC_ConfigurationSetting__c/fields/SettingHelpText__c.field-meta.xml
<CustomField>
    <fullName>SettingHelpText__c</fullName>
    <description>This is the help text that should be displayed to the user.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This is the help text that should be displayed to the user.</inlineHelpText>
    <label>Setting Help Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AH_UDC_ConfigurationSetting__c/fields/SettingType__c.field-meta.xml
<CustomField>
    <fullName>SettingType__c</fullName>
    <description>Controls the data format, and the way the setting will appear in the editor.  All types except TextArea store values in the SettingValue__c field.  Settings of type TextArea store data in the SettingTextAreaValue__c field</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Controls the data format, and control used to display/edit the setting&apos;s value.  Valid Setting Types are:

String - Single line
TextArea - Multiline
Integer
Checkbox - Boolean
Picklist
URL

Page
Method</inlineHelpText>
    <label>Setting Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AH_UDC_ConfigurationSetting__c/fields/SettingValue__c.field-meta.xml
<CustomField>
    <fullName>SettingValue__c</fullName>
    <description>This is the value for the setting.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This is the value for the setting.</inlineHelpText>
    <label>Setting Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AH_UDC_ConfigurationSetting__c/fields/SettingValueDefault__c.field-meta.xml
<CustomField>
    <fullName>SettingValueDefault__c</fullName>
    <description>This is the default value for the setting.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This is the default value for the setting.</inlineHelpText>
    <label>Setting Value Default</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AH_UDC_ConfigurationSetting__c/fields/SettingValueDomain__c.field-meta.xml
<CustomField>
    <fullName>SettingValueDomain__c</fullName>
    <description>For the setting value, this will constrain entries the valid values that can be entered. Picklist values, min/max for an integer, valid values for a string.  Values in this field must be separated by a \r\n</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Specify the limits/ranges/values allowed in SettingValue__c.

Values are entered one per line with \r\n between them

Integer (Min/Max) [1\r\n10 limits value to a number from 1 to 10 inclusive]

Picklists (dropdown values) [red\r\n\blue\r\nblue]</inlineHelpText>
    <label>Setting Value Domain</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/AH_UDC_ConfigurationSetting__c/fields/UsedBy__c.field-meta.xml
<CustomField>
    <fullName>UsedBy__c</fullName>
    <description>This is the system which uses the setting. (ex. WorkOrchestrator)</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This is the system which uses the setting. (ex. WorkOrchestrator)</inlineHelpText>
    <label>Used By</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/AH_UDC_extConfigurationSettings_TEST.cls
/*
 * File            : AH_UDC_extConfigurationSettings_TEST.cls
 * Created Date    : 2019-08-29
 * Created By      : Rob.Stevens@Amadeus.com
 * Description     : Test Extension class for Configuration Settings Page
 */
@isTest
public with sharing class AH_UDC_extConfigurationSettings_TEST {

   public static final String TEST_CLASS_FORCED_EXCEPTION = 'TEST CLASS: Throwing an intentional exception for testing/code coverage from Test Class';

   @TestSetup private static void setup() {
      AH_UDC_InitializationHelper.Initialize('ConfigurationSettings');

      List<User> listUsers = new List<User> ();

      listUsers.add(AH_UDC_TestData.BuildUser(AH_UDC_Constants.PROFILE_DEFAULT_NAME_PSA_SF_LIGHTNING,
                                    AH_UDC_Constants.PERMISSIONSET_DEFAULT_NAME_UDC_SYSTEM_ADMIN,
                                    'ConfigSetUDCSysAdmin', null, false));

      User oCurrentUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
      oCurrentUser.ContactId = null;

      System.runAs(oCurrentUser) {
         AH_UDC_TestData.InsertWithRetries(listUsers);

         AH_UDC_TestData.AddPermissionSetToUser(AH_UDC_Constants.PERMISSIONSET_DEFAULT_NAME_UDC_SYSTEM_ADMIN, listUsers[0].Id);
      }
   }

   @isTest static void testLaunchPage() {
      //Get Org Info
      Organization orgInfo = [SELECT name FROM Organization];

      Test.startTest();

      AH_UDC_extConfigurationSettings ecs = new AH_UDC_extConfigurationSettings();
      String launchUrl = '/apex/GeneralSettingsViewEdit';
      ecs.actionParameter1 = launchUrl;
      PageReference pr = ecs.launchPage();
      System.assertEquals(launchUrl, pr.getUrl(), 'Page is not redirecting to expected Url');

      Test.stopTest();
   }

   @isTest static void testShowSettingPage() {
      //Get Org Info
      Organization orgInfo = [SELECT name FROM Organization];

      Test.startTest();

      AH_UDC_extConfigurationSettings ecs = new AH_UDC_extConfigurationSettings();
      ecs.actionParameter1 = 'Test';
      ecs.showSettingPage();
      System.assertEquals(ecs.actionParameter1, ecs.getpageName(), 'Did not find the expected PageName');
      
      Test.stopTest();
   }
   
   @isTest static void testUpdateSetting() {
      //Get Org Info
      Organization orgInfo = [select name from Organization];

      //Add a setting
      AH_UDC_ConfigurationSetting__c cs1 = new AH_UDC_ConfigurationSetting__c(
                                                                              DisplayOrder__c = 1,
                                                                              AH_UDC__c = true,
                                                                              Name = 'Test1',
                                                                              OrgName__c = orgInfo.Name,
                                                                              PageGroupName__c = 'TestPageGroupName',
                                                                              PageName__c = 'TestPageName',
                                                                              PageSectionName__c = 'TestPageSectionName',
                                                                              SettingDisplayName__c = 'TestDisplayName',
                                                                              SettingHelpText__c = 'TestHelpText',
                                                                              SettingType__c = 'String',
                                                                              SettingValue__c = 'TestOriginalValue',
                                                                              SettingValueDefault__c = 'Test',
                                                                              SettingValueDomain__c = 'Test',
                                                                              UsedBy__c = 'Test'
      );
      insert cs1;

      AH_UDC_ConfigurationSetting__c cs2 = new AH_UDC_ConfigurationSetting__c(
                                                                              DisplayOrder__c = 6,
                                                                              AH_UDC__c = true,
                                                                              Name = 'Test6',
                                                                              OrgName__c = orgInfo.Name,
                                                                              PageGroupName__c = 'TestPageGroupName',
                                                                              PageName__c = 'TestPageName',
                                                                              PageSectionName__c = 'TestPageSectionName',
                                                                              SettingDisplayName__c = 'TestDisplayName',
                                                                              SettingHelpText__c = null,
                                                                              SettingType__c = 'Time_24h',
                                                                              SettingValue__c = '',
                                                                              SettingValueDefault__c = '09:42',
                                                                              SettingValueDomain__c = '',
                                                                              UsedBy__c = 'Test'
      );
      insert cs2;

      List<User> lstUser = [Select Id From User Where Email like '%ConfigSetUDCSysAdmin%'];
      System.assert(lstUser.size() > 0, 'UDC System Admin user was not created');

      System.runAs(lstUser[0]) {
         Test.startTest();

         AH_UDC_extConfigurationSettings ecs = new AH_UDC_extConfigurationSettings();
         ecs.setupdateSettingName('Test1');
         System.assertEquals('Test1', ecs.getupdateSettingName(), 'Failed to set updateSettingName');

         ecs.setupdateSettingValue('TestValueUpdated');
         ecs.updateSetting();
         System.assertEquals('Setting updated', ecs.getupdateSettingStatus(), 'Failed to save STRING Setting Value');

         AH_UDC_ConfigurationSetting__c[] csUpdated = [SELECT name, SettingValue__c from AH_UDC_ConfigurationSetting__c where Name = 'Test1'];

         System.assertEquals('TestValueUpdated', ecs.getupdateSettingValue(), 'Setting Value Not Updated');
         System.assertEquals('TestValueUpdated', csUpdated[0].SettingValue__c, 'Saved Setting Value Not Updated');

         // Good value
         ecs.setupdateSettingName('Test6');
         ecs.setupdateSettingValue('12:34');
         ecs.updateSetting();
         System.assertEquals('Setting updated', ecs.getupdateSettingStatus(), 'Failed to save 24H Setting Value');

         // Bad value
         ecs.setupdateSettingName('Test6');
         ecs.setupdateSettingValue('12:60');
         ecs.updateSetting();
         System.assert(ecs.getupdateSettingStatus().startsWith('Unrecognized time format'), 'Should have failed to save 24H Setting Value with invalid number');

         // Bad value
         ecs.setupdateSettingName('Test6');
         ecs.setupdateSettingValue('ab:de');
         ecs.updateSetting();
         System.assert(ecs.getupdateSettingStatus().startsWith('Unrecognized time format'), 'Should have failed to save 24H Setting Value with letters and a colon entered');

         // Bad value
         ecs.setupdateSettingName('Test6');
         ecs.setupdateSettingValue('abcde');
         ecs.updateSetting();
         System.assert(ecs.getupdateSettingStatus().startsWith('Unrecognized time format'), 'Should have failed to save 24H Setting Value with letters entered');

         Test.stopTest();
      }
   }

   @isTest static void testUpdateSettingOutOfRange() {
      //Get Org Info
      Organization orgInfo = [SELECT name FROM Organization];

      //Add a setting
      AH_UDC_ConfigurationSetting__c cs1 = new AH_UDC_ConfigurationSetting__c(
                                                                              DisplayOrder__c = 1,
                                                                              AH_UDC__c = true,
                                                                              Name = 'Test1',
                                                                              OrgName__c = orgInfo.Name,
                                                                              PageGroupName__c = 'TestPageGroupName',
                                                                              PageName__c = 'TestPageName',
                                                                              PageSectionName__c = 'TestPageSectionName',
                                                                              SettingDisplayName__c = 'TestDisplayName',
                                                                              SettingHelpText__c = 'TestHelpText',
                                                                              SettingType__c = 'Integer',
                                                                              SettingValue__c = '100',
                                                                              SettingValueDefault__c = 'Test',
                                                                              SettingValueDomain__c = '0\r\n120',
                                                                              UsedBy__c = 'Test'
      );
      insert cs1;
      Test.startTest();

      AH_UDC_extConfigurationSettings ecs = new AH_UDC_extConfigurationSettings();
      ecs.setupdateSettingName('Test1');
      ecs.setupdateSettingValue('200');
      ecs.updateSetting();

      System.assert(ecs.getupdateSettingStatus().startsWith('Update failed'), 'Update should have failed as the new integer value was outside the valid range');

      Test.stopTest();
   }

   @isTest static void testUpdateMissingSetting() {
      //Get Org Info
      Organization orgInfo = [SELECT name FROM Organization];

      Test.startTest();

      AH_UDC_extConfigurationSettings ecs = new AH_UDC_extConfigurationSettings();
      ecs.setupdateSettingName('Test');
      ecs.setupdateSettingValue('TestValueUpdated');
      ecs.updateSetting();

      System.assert(ecs.getupdateSettingStatus().startsWith('Update failed:'), 'Missing Setting error not correct');

      Test.stopTest();
   }

   @isTest static void testRequestMethod() {
      //Get Org Info
      Organization orgInfo = [SELECT name FROM Organization];

      Test.startTest();

      AH_UDC_extConfigurationSettings ecs = new AH_UDC_extConfigurationSettings();
      ecs.setupdateSettingValue('Exception');
      ecs.requestMethod();

      System.assert(ecs.getupdateSettingStatus().startsWith('Request failed;'), 'Testing an exception while calling requestMethod should have failed');

      Test.stopTest();
   }

   @isTest static void testUpdateException() {
      //Get Org Info
      Organization orgInfo = [SELECT name FROM Organization];

      Test.startTest();

      AH_UDC_extConfigurationSettings ecs = new AH_UDC_extConfigurationSettings();
      ecs.setupdateSettingName('Exception');
      ecs.setupdateSettingValue('TestException');
      boolean isException = false;
      ecs.updateSetting();

      System.assert(ecs.getupdateSettingStatus().startsWith('Update failed:'), 'Exception Setting error not correct');

      Test.stopTest();
   }

   @isTest static void testPage() {
      //Get Org Info
      Organization orgInfo = [SELECT name FROM Organization];

      List<AH_UDC_ConfigurationSetting__c> cs = new List<AH_UDC_ConfigurationSetting__c> ();

      //Add a setting
      AH_UDC_ConfigurationSetting__c cs1 = new AH_UDC_ConfigurationSetting__c(
                                                                              DisplayOrder__c = 1,
                                                                              AH_UDC__c = true,
                                                                              Name = 'Test1',
                                                                              OrgName__c = orgInfo.Name,
                                                                              PageGroupName__c = 'TestPageGroupName',
                                                                              PageName__c = 'TestPageName',
                                                                              PageSectionName__c = 'TestPageSectionName',
                                                                              SettingDisplayName__c = 'TestDisplayName',
                                                                              SettingHelpText__c = 'TestHelpText',
                                                                              SettingType__c = 'String',
                                                                              SettingValue__c = 'TestOriginalValue',
                                                                              SettingValueDefault__c = 'Test',
                                                                              SettingValueDomain__c = 'Test',
                                                                              UsedBy__c = 'Test'
      );
      cs.add(cs1);

      //Add a setting
      AH_UDC_ConfigurationSetting__c cs2 = new AH_UDC_ConfigurationSetting__c(
                                                                              DisplayOrder__c = 2,
                                                                              AH_UDC__c = true,
                                                                              Name = 'Test2',
                                                                              OrgName__c = orgInfo.Name,
                                                                              PageGroupName__c = 'TestPageGroupName',
                                                                              PageName__c = 'TestPageName',
                                                                              PageSectionName__c = 'TestPageSectionName',
                                                                              SettingDisplayName__c = 'TestDisplayName',
                                                                              SettingHelpText__c = 'TestHelpText',
                                                                              SettingType__c = 'Integer',
                                                                              SettingValue__c = '1',
                                                                              SettingValueDefault__c = '1',
                                                                              SettingValueDomain__c = '1\r\n2',
                                                                              UsedBy__c = 'Test'
      );
      cs.add(cs2);

      //Add a setting
      AH_UDC_ConfigurationSetting__c cs3 = new AH_UDC_ConfigurationSetting__c(
                                                                              DisplayOrder__c = 3,
                                                                              AH_UDC__c = true,
                                                                              Name = 'Test3',
                                                                              OrgName__c = orgInfo.Name,
                                                                              PageGroupName__c = 'TestPageGroupName',
                                                                              PageName__c = 'TestPageName',
                                                                              PageSectionName__c = 'TestPageSectionName',
                                                                              SettingDisplayName__c = 'TestDisplayName',
                                                                              SettingHelpText__c = 'TestHelpText',
                                                                              SettingType__c = 'Picklist',
                                                                              SettingValue__c = 'Test',
                                                                              SettingValueDefault__c = 'Test',
                                                                              SettingValueDomain__c = 'Test',
                                                                              UsedBy__c = 'Test'
      );
      cs.add(cs3);

      //Add a setting
      AH_UDC_ConfigurationSetting__c cs4 = new AH_UDC_ConfigurationSetting__c(
                                                                              DisplayOrder__c = 4,
                                                                              AH_UDC__c = true,
                                                                              Name = 'Test4',
                                                                              OrgName__c = orgInfo.Name,
                                                                              PageGroupName__c = 'TestPageGroupName',
                                                                              PageName__c = 'TestPageName',
                                                                              PageSectionName__c = 'TestPageSectionName',
                                                                              SettingDisplayName__c = 'TestDisplayName',
                                                                              SettingHelpText__c = 'TestHelpText',
                                                                              SettingType__c = 'Checkbox',
                                                                              SettingValue__c = 'True',
                                                                              SettingValueDefault__c = 'True',
                                                                              SettingValueDomain__c = '',
                                                                              UsedBy__c = 'Test'
      );
      cs.add(cs4);

      //Add a Dynamic Picklist setting
      AH_UDC_ConfigurationSetting__c cs5 = new AH_UDC_ConfigurationSetting__c(
                                                                              DisplayOrder__c = 5,
                                                                              AH_UDC__c = true,
                                                                              Name = 'Test5',
                                                                              OrgName__c = orgInfo.Name,
                                                                              PageGroupName__c = 'TestPageGroupName',
                                                                              PageName__c = 'TestPageName',
                                                                              PageSectionName__c = 'TestPageSectionName',
                                                                              SettingDisplayName__c = 'TestDisplayName',
                                                                              SettingHelpText__c = null,
                                                                              SettingType__c = 'Picklist',
                                                                              SettingValue__c = '',
                                                                              SettingValueDefault__c = '',
                                                                              SettingValueDomain__c = '{!Opportunity.LeadSource}',
                                                                              UsedBy__c = 'Test'
      );
      cs.add(cs5);

      //Add a Time_24H setting
      AH_UDC_ConfigurationSetting__c cs6 = new AH_UDC_ConfigurationSetting__c(
                                                                              DisplayOrder__c = 6,
                                                                              AH_UDC__c = true,
                                                                              Name = 'Test6',
                                                                              OrgName__c = orgInfo.Name,
                                                                              PageGroupName__c = 'TestPageGroupName',
                                                                              PageName__c = 'TestPageName',
                                                                              PageSectionName__c = 'TestPageSectionName',
                                                                              SettingDisplayName__c = 'TestDisplayName',
                                                                              SettingHelpText__c = null,
                                                                              SettingType__c = 'Time_24h',
                                                                              SettingValue__c = '',
                                                                              SettingValueDefault__c = '09:42',
                                                                              SettingValueDomain__c = '',
                                                                              UsedBy__c = 'Test'
      );
      cs.add(cs6);

      //Add a object setting
      AH_UDC_ConfigurationSetting__c cs7 = new AH_UDC_ConfigurationSetting__c(
                                                                              DisplayOrder__c = 7,
                                                                              AH_UDC__c = true,
                                                                              Name = 'Test7',
                                                                              OrgName__c = orgInfo.Name,
                                                                              PageGroupName__c = 'TestPageGroupName',
                                                                              PageName__c = null,
                                                                              PageSectionName__c = 'TestPageSectionName',
                                                                              SettingDisplayName__c = 'TestDisplayName',
                                                                              SettingHelpText__c = null,
                                                                              SettingType__c = 'Object',
                                                                              SettingValue__c = '',
                                                                              SettingValueDefault__c = 'TestDefaultValue',
                                                                              SettingValueDomain__c = '',
                                                                              UsedBy__c = 'Test'
      );
      cs.add(cs7);
      insert cs;

      Test.startTest();

      String tpn = 'TestPageName';
      String tpgn = 'TestPageGroupName';
      PageReference pageRef = new PageReference('/apex/AH_UDC_ConfigurationSettings?pn=' + tpn);
      System.assertNotEquals(null, pageRef, 'Failed to render the extConfigurationSettings page reference');
      pageRef.getParameters().put('pn', tpn);
      Test.setCurrentPage(pageRef);

      AH_UDC_extConfigurationSettings extCS = new AH_UDC_extConfigurationSettings();

      System.assertEquals('/apex/AH_UDC_ConfigurationSettings?pn=' + tpn, ApexPages.currentPage().GetUrl(), 'PageReference is not pointing at the expected page');

      extCS.setpageName(tpn);
      System.assertEquals(tpn, extCS.getpageName(), 'Did not find the expected PageName');

      extCS.GetSettings(); //added to cover else condition where it sets pagegroupname, if it is null 
      System.assertEquals(tpgn, extCS.getPageGroupName(), 'Did not find the expected PageGroupName');

      extCS.setpageGroupName('TestPageGroupName1');
      System.assertEquals('TestPageGroupName1', extCS.getPageGroupName(), 'Did not find the expected PageGroupName');

      extCS.actionParameter1 = 'History';
      extCS.showSettingPage();
      extCS.showNextHistoryPage();
      System.assertEquals(extCS.actionParameter1, extCS.getpageName(), 'Did not find the expected PageName');
      
      extCS.setpageGroupName(tpgn);
      System.assertEquals(tpgn, extCS.getPageGroupName(), 'Did not find the expected PageGroupName');


      Test.stopTest();
   }
}