force-app/main/default/objects/Medallia_Adoption_Survey__c/Medallia_Adoption_Survey__c.object-meta.xml
<CustomObject>
    <description>NICC-059442</description>
    <label>Medallia_Adoption_Survey</label>
    <nameField>
        <displayFormat>MAS-{0000}</displayFormat>
        <label>Medallia_Adoption_Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medallia_Adoption_Survey</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Medallia_Adoption_Survey__c/fields/AppointmentBookedEmailReceived__c.field-meta.xml
<CustomField>
    <fullName>AppointmentBookedEmailReceived__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Used by Solution Adoption team to indicate if an initial contact has been made with a customer and if a customer has responded prior to follow-ups</inlineHelpText>
    <label>AppointmentBookedEmailReceived</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Medallia_Adoption_Survey__c/fields/Process_Status__c.field-meta.xml
<CustomField>
    <fullName>Process_Status__c</fullName>
    <label>Process Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Processed Yet</fullName>
                <default>true</default>
                <label>Not Processed Yet</label>
            </value>
            <value>
                <fullName>Invitation Created</fullName>
            </value>
            <value>
                <fullName>Invitation Update Received</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>API Error</fullName>
            </value>
            <value>
                <fullName>Not Sampled</fullName>
            </value>
            <value>
                <fullName>Bounced</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Invited</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Medallia_Service_Survey__c/Medallia_Service_Survey__c.object-meta.xml
<CustomObject>
    <description>NICC-060033</description>
    <label>Medallia_Service_Survey</label>
    <nameField>
        <displayFormat>MSS-{0000}</displayFormat>
        <label>Medallia Service Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medallia_Service_Survey</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Medallia_Service_Survey__c/fields/Process_Status__c.field-meta.xml
<CustomField>
    <fullName>Process_Status__c</fullName>
    <label>Process Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Processed Yet</fullName>
                <default>true</default>
                <label>Not Processed Yet</label>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Not Sampled</fullName>
            </value>
            <value>
                <fullName>Bounced</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>API Error</fullName>
            </value>
            <value>
                <fullName>Invitation Created</fullName>
            </value>
            <value>
                <fullName>Invitation Update Received</fullName>
            </value>
            <value>
                <fullName>Invited</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Medallia_Service_Survey__c/fields/Retry__c.field-meta.xml
<CustomField>
    <fullName>Retry__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Retry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Medallia_Support_Survey__c/Medallia_Support_Survey__c.object-meta.xml
<CustomObject>
    <description>NICC-060033</description>
    <label>Medallia_Support_Survey</label>
    <nameField>
        <displayFormat>CSS-{0000}</displayFormat>
        <label>Support Survey Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medallia_Support_Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Medallia_Support_Survey__c/fields/Process_Status__c.field-meta.xml
<CustomField>
    <fullName>Process_Status__c</fullName>
    <label>Process Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Processed Yet</fullName>
                <default>true</default>
                <label>Not Processed Yet</label>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Invitation Created</fullName>
            </value>
            <value>
                <fullName>Invitation Update Received</fullName>
            </value>
            <value>
                <fullName>Not Sampled</fullName>
            </value>
            <value>
                <fullName>Bounced</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>API Error</fullName>
            </value>
            <value>
                <fullName>Invited</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Medallia_Support_Survey__c/fields/Retry__c.field-meta.xml
<CustomField>
    <fullName>Retry__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check this box if the process status is still Not Processed Yet after the last run of surveys. This will queue the survey to  try again in the next run.</inlineHelpText>
    <label>Retry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AH_MedalliaInvitationsBatch_Schedule.cls
/***********************************************************************************************
Name            : AH_MedalliaInvitationsBatch_Schedule
Author          : Bhagwat Garkal
Created Date    : 07/08/2022
Last Mod Date   : 07/08/2022
Last Mod By     : Bhagwat Garkal
NICC Reference  : 
Description     : Schedulable class for AH_MedalliaInvitations_Schedule Class.   
                :
                :
************************************************************************************************/
global class AH_MedalliaInvitationsBatch_Schedule implements Schedulable
{
    
    global void execute(SchedulableContext sc) 
    {
        
        try
        {
            Date surveycreatedDate = System.today();
            //  Medallia_Support_Survey__c records
            String supportSurveySOQL = 'SELECT Id from Medallia_Support_Survey__c ';
            String supportSOQLWhere = 'WHERE Process_Status__c = \'Not Processed Yet\' AND (Retry__c = true OR CreatedDate = TODAY)';
            
            AH_MedalliaInvitations_Batch supportbatch = new AH_MedalliaInvitations_Batch(supportSurveySOQL + supportSOQLWhere, 'Support_FieldSet', 'sfdc_create_survey_hos_support', 'Customer Support');
            Id supportbatchId = Database.executeBatch(supportbatch, 10); 
            
            //  Medallia_Service_Survey__c records
            String serviceSurveySOQL = 'SELECT Id from Medallia_Service_Survey__c ';
            String serviceSOQLWhere = 'WHERE Process_Status__c = \'Not Processed Yet\' AND (Retry__c = true OR CreatedDate = TODAY)';
            
            AH_MedalliaInvitations_Batch servicebatch = new AH_MedalliaInvitations_Batch(serviceSurveySOQL + serviceSOQLWhere, 'Service_FieldSet', 'sfdc_create_survey_hos_implementations', 'Services - Installer Survey');
            Id servicebatchId = Database.executeBatch(servicebatch, 10); 
            
            //  Medallia_Adoption_Survey__c records
            String adoptionSurveySOQL = 'SELECT Id from Medallia_Adoption_Survey__c ';
            String adoptionSOQLWhere = 'WHERE Process_Status__c = \'Not Processed Yet\' AND AppointmentBookedEmailReceived__c = true AND (Retry__c = true OR CreatedDate = TODAY)';
           
            AH_MedalliaInvitations_Batch adoptionbatch = new AH_MedalliaInvitations_Batch(adoptionSurveySOQL + adoptionSOQLWhere, 'Adoption_FieldSet', 'sfdc_create_survey_hos_adoption', 'Adoption Survey');
            Id adoptionbatchId = Database.executeBatch(adoptionbatch, 10); 
            
        }
        catch (Exception e)
        {
            // CREATE DTS LOGS
            // AH_DTS_Integration_Logger.writeToDTSLog(system.now(), 'Medallia - Apex Job', 'Active', 'Error', 'Error Scheduling Apex Job', e.getMessage(), '3 - Medium', UserInfo.getUserName(), 'AH_MedalliaInvitationsBatch_Schedule', 'Apex Job Scheduling', 'Salesforce', true, false);
            // WRITE DTS INTGRATION LOG ERROR 
            AH_DTS_Integration_Logger.writeToDTSLog(system.now(), 'Medallia - Apex Job', 'Active', 'Error', 'Error Scheduling Apex Job', e.getMessage(), '3 - Medium', UserInfo.getUserName(), 'AH_MedalliaInvitationsBatch_Schedule','Apex Job Scheduling', 'Salesforce', true, false); 							// bWillSelfResolve        
        }
        
    }
    
}