force-app/main/default/objects/SFDC_CSP_Flash_Message__c/SFDC_CSP_Flash_Message__c.object-meta.xml
<CustomObject>
    <description>SFDC Customer Service Project</description>
    <label>Flash Message</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Flash Message</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flash Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SFDC_CSP_Flash_Message__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Flash Messages</relationshipLabel>
    <relationshipName>Flash_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SFDC_CSP_Flash_Message__c/fields/HideFlashFromChildren__c.field-meta.xml
<CustomField>
    <fullName>HideFlashFromChildren__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hide Flash From Children</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SFDC_CSP_Flash_Message__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Message</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SFDC_CSP_Flash_Message__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SFDC_CSP_Flash_Message__c/fields/Solution__c.field-meta.xml
<CustomField>
    <fullName>Solution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Solution</label>
    <referenceTo>Solution</referenceTo>
    <relationshipLabel>Flash Messages</relationshipLabel>
    <relationshipName>Flash_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SFDC_CSP_Flash_Message__c/fields/Viewable_to_All_Children__c.field-meta.xml
<CustomField>
    <fullName>Viewable_to_All_Children__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Viewable to All Children</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AccountFlashAlertListExtension.cls
/****************************************************************************************
Name            : AccountFlashAlertListExtension 
Author          : Black Iron Group
Created Date    : 07/18/2010 
Last Mod Date   : 04/25/2017 
Last Mod By     : Sean Harris
NICC Reference  : 
Description     : This class is an extention controller for a VF Page called AccountFlashAlerts
                :
****************************************************************************************/
public with sharing class AccountFlashAlertListExtension 
{

    Account a;
    public SFDC_CSP_Flash_Message__c[] messages {get; set;}

    public AccountFlashAlertListExtension(ApexPages.StandardController stdController)
    {
        
        this.a = (Account)stdController.getRecord();
        messages = new SFDC_CSP_Flash_Message__c[0];
        String accountId;
        
        // GET THE FLASHMESSAGES FOR THE ACCOUNT
        if (this.a != null) 
        {
            
            accountId = this.a.Id;
            
            for (SFDC_CSP_Flash_Message__c[] mess : [SELECT Id, Account__c, Name, Message__c, Priority__c, Solution__c, Viewable_to_All_Children__c, CreatedDate 
                                                     FROM SFDC_CSP_Flash_Message__c 
                                                     WHERE Account__c =: accountId]) 
            {
                messages.addAll(mess);
            }
            
            // GET THE PARENTS
            Boolean done = false;
            while (!done) 
            {
                
                accountId = [SELECT ParentId FROM Account WHERE Id =: accountId].ParentId;
                
                // IF THE ACCOUNT HAS A PARENT ADD THE MESSAGES THE CHILDREN CAN SEE
                if (accountId != null && accountId != '') 
                {
                    for (SFDC_CSP_Flash_Message__c[] mess : [SELECT Id, Account__c, Name, Message__c, Priority__c, Solution__c, Viewable_to_All_Children__c, CreatedDate 
                                                             FROM SFDC_CSP_Flash_Message__c 
                                                             WHERE Account__c =: accountId 
                                                             AND HideFlashFromChildren__c = false]) 
                    {
                        messages.addAll(mess);
                    }
                }
                // OTHERWISE WE'RE DONE
                else 
                {
                    done = true;
                }
            }
            
        }

    }
        
}