force-app/main/default/objects/AH_Salesforce_Instance__c/AH_Salesforce_Instance__c.object-meta.xml
<CustomObject>
    <description>NICC-031037 - Stores information about Salesforce instances retrieved via API from the Salesforce Trust website.</description>
    <label>AH Salesforce Instance</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Instance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AH Salesforce Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_Salesforce_Instance__c/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <description>NICC-031037</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Indicates whether the instance hosts either sandbox or production orgs.</inlineHelpText>
    <label>Environment</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AH_Salesforce_Instance__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NICC-031037</description>
    <inlineHelpText>Indicates whether or not the instance is active.</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AH_Salesforce_Instance__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Salesforce Key</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AH_Salesforce_Instance__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>NICC-031037</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Region where instance is located (NA, EU, APAC).</inlineHelpText>
    <label>Location</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AH_Salesforce_Instance__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <description>NICC-031037</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>List of Salesforce products available on the instance.</inlineHelpText>
    <label>Products</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/AH_Salesforce_Instance__c/fields/Release_Number__c.field-meta.xml
<CustomField>
    <fullName>Release_Number__c</fullName>
    <description>NICC-031037</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Current release number of the instance.</inlineHelpText>
    <label>Release Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AH_Salesforce_Instance__c/fields/Release_Version__c.field-meta.xml
<CustomField>
    <fullName>Release_Version__c</fullName>
    <description>NICC-031037</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Current release version of the instance.</inlineHelpText>
    <label>Release Version</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AH_Salesforce_Instance__c/fields/Services__c.field-meta.xml
<CustomField>
    <fullName>Services__c</fullName>
    <description>NICC-031037</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>List of Salesforce services available on the instance.</inlineHelpText>
    <label>Services</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/AH_Salesforce_Instance__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>NICC-031037</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The status of the instance - default is &apos;OK&apos;.</inlineHelpText>
    <label>Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AH_Salesforce_Instance_to_Notification__c/AH_Salesforce_Instance_to_Notification__c.object-meta.xml
<CustomObject>
    <description>NICC-031037 - Junction object used to link Salesforce Instances to Salesforce Trust Notifications.</description>
    <label>AH Salesforce Instance to Notification</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AH Salesforce Instance to Notifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_Salesforce_Instance_to_Notification__c/fields/AH_Salesforce_Instance__c.field-meta.xml
<CustomField>
    <fullName>AH_Salesforce_Instance__c</fullName>
    <description>NICC-031037</description>
    <label>AH Salesforce Instance</label>
    <referenceTo>AH_Salesforce_Instance__c</referenceTo>
    <relationshipLabel>AH Salesforce Notifications</relationshipLabel>
    <relationshipName>AH_Salesforce_Instance_to_Notification</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AH_Salesforce_Instance_to_Notification__c/fields/AH_Salesforce_Notification__c.field-meta.xml
<CustomField>
    <fullName>AH_Salesforce_Notification__c</fullName>
    <description>NICC-031037</description>
    <label>AH Salesforce Notification</label>
    <referenceTo>AH_Salesforce_Trust_Notification__c</referenceTo>
    <relationshipLabel>AH Salesforce Instances</relationshipLabel>
    <relationshipName>AH_Salesforce_Instance_to_Notification</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AH_Salesforce_Instance_to_Notification__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <caseSensitive>true</caseSensitive>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Key</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AH_Salesforce_Trust_Impact_Event__c/AH_Salesforce_Trust_Impact_Event__c.object-meta.xml
<CustomObject>
    <description>NICC-031037 - Detail object of the Salesforce Trust Notification object; used to store Impacts and Events that are child records of an Incident, Maintenance or General Message notification.</description>
    <label>AH Salesforce Trust Impact/Event</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Impact/Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AH Salesforce Trust Impacts/Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_Salesforce_Trust_Impact_Event__c/fields/AH_Salesforce_Trust_Notification__c.field-meta.xml
<CustomField>
    <fullName>AH_Salesforce_Trust_Notification__c</fullName>
    <description>NICC-031037</description>
    <inlineHelpText>Lookup to the master notification record.</inlineHelpText>
    <label>AH Salesforce Trust Notification</label>
    <referenceTo>AH_Salesforce_Trust_Notification__c</referenceTo>
    <relationshipLabel>AH Salesforce Trust Impacts/Events</relationshipLabel>
    <relationshipName>AH_Salesforce_Trust_Impact_Event</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AH_Salesforce_Trust_Impact_Event__c/fields/SF_Trust_ID__c.field-meta.xml
<CustomField>
    <fullName>SF_Trust_ID__c</fullName>
    <description>NICC-031037</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>The ID of the Impact or Event record on the Salesforce Trust website.</inlineHelpText>
    <label>SF Trust ID</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AH_Salesforce_Trust_Notification__c/AH_Salesforce_Trust_Notification__c.object-meta.xml
<CustomObject>
    <description>NICC-031037 - Used to store Incident, Maintenance and General Message notifications retrieved via API from the Salesforce Trust website.</description>
    <label>AH Salesforce Trust Notification</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Notification Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AH Salesforce Trust Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_Salesforce_Trust_Notification__c/fields/Services__c.field-meta.xml
<CustomField>
    <fullName>Services__c</fullName>
    <description>NICC-031037</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Services affected by the incident or maintenance event.</inlineHelpText>
    <label>Services</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/AH_Salesforce_Trust_Notification__c/fields/SF_Trust_ID__c.field-meta.xml
<CustomField>
    <fullName>SF_Trust_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <label>Salesforce Trust ID</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AH_Salesforce_Trust_Notification__c/recordTypes/Incident.recordType-meta.xml
<RecordType>
    <fullName>Incident</fullName>
    <active>true</active>
    <description>Used for Salesforce Trust Incidents</description>
    <label>Incident</label>
</RecordType>

force-app/main/default/objects/AH_Salesforce_Trust_Notification__c/recordTypes/Maintenance.recordType-meta.xml
<RecordType>
    <fullName>Maintenance</fullName>
    <active>true</active>
    <description>Used for Salesforce Trust Maintenances</description>
    <label>Maintenance</label>
</RecordType>

force-app/main/default/classes/AH_SalesforceTrustRefresh_Schedule_Test.cls
/****************************************************************************************
Name            : AH_SalesforceTrustRefresh_Schedule_Test Class 
Author          : Shashikant Nikam
Created Date    : 10/23/2018
Last Mod Date   : 10/24/2018
Last Mod By     : Shashikant Nikam
NICC Reference  : 
Description     : Test class for AH_Schedule_BatchSalesforceTrustRefresh class
:  
: 
******************************************************************************************/
@isTest
public class AH_SalesforceTrustRefresh_Schedule_Test 
{

    // ======================================================================================================================================= 
    // = CREATE TEST DATA
    // ======================================================================================================================================= 
    @testSetup static void createTestData() 
    {
        
        system.runAs([SELECT Id FROM User WHERE Id =: UserInfo.getUserId()][0]) 
        {
            
            // CREATE TEST INSTANCE RECORD
            List<AH_Salesforce_Instance__c> lstInstances = new List<AH_Salesforce_Instance__c>();
            
            AH_Salesforce_Instance__c a1 = new AH_Salesforce_Instance__c();
            a1.Name = 'NA67';
            a1.Key__c = 'na67';
            a1.Location__c = 'MAPC';
            a1.Environment__c = 'production';
            a1.Release_Version__c = 'Winter \'19 Patch 9.7';
            a1.Release_Number__c = '216.9.7';
            a1.Status__c = 'OK';
            a1.Is_Active__c = TRUE;
            a1.Services__c = '(CPQandBilling, analytics, search, liveAgent, coreService)';
            a1.Products__c = '(Community_Cloud, Einstein_Analytics)';
            
            lstInstances.add(a1);
            
            insert lstInstances;
            
            // ASSERT INSERT SUCCESSFUL
            List<AH_Salesforce_Instance__c> instanceList = new List <AH_Salesforce_Instance__c>([SELECT Id FROM AH_Salesforce_Instance__c]);
            system.assertEquals(1, instanceList.size(), 'Record count mismatch in Instance record in test Data..');
            
			// CREATE TEST NOTIFICATION RECORDS
            List<AH_Salesforce_Trust_Notification__c> IncidentsList1 = new List<AH_Salesforce_Trust_Notification__c>();
            
            AH_Salesforce_Trust_Notification__c notify1 = new AH_Salesforce_Trust_Notification__c();
            notify1.SF_Trust_ID__c = 'INCDNT-2992';
            notify1.RecordTypeId = Schema.SObjectType.AH_Salesforce_Trust_Notification__c.getRecordTypeInfosByName().get('Incident').getRecordTypeId();
            IncidentsList1.add(notify1);
            
            AH_Salesforce_Trust_Notification__c notify2 = new AH_Salesforce_Trust_Notification__c();
            notify2.SF_Trust_ID__c = 'INCDNT-2698';
            notify2.RecordTypeId = Schema.SObjectType.AH_Salesforce_Trust_Notification__c.getRecordTypeInfosByName().get('Incident').getRecordTypeId();
            IncidentsList1.add(notify2);
                        
            AH_Salesforce_Trust_Notification__c notify3 = new AH_Salesforce_Trust_Notification__c();
            notify3.SF_Trust_ID__c = 'MNTNCE-3299';
            notify3.RecordTypeId = Schema.SObjectType.AH_Salesforce_Trust_Notification__c.getRecordTypeInfosByName().get('Maintenance').getRecordTypeId();
            IncidentsList1.add(notify3);

            AH_Salesforce_Trust_Notification__c notify4 = new AH_Salesforce_Trust_Notification__c();
            notify4.SF_Trust_ID__c = 'GENMSG-2687';
            notify4.RecordTypeId = Schema.SObjectType.AH_Salesforce_Trust_Notification__c.getRecordTypeInfosByName().get('General Message').getRecordTypeId();
            IncidentsList1.add(notify4);

            insert IncidentsList1;
            
			// ASSERT INSERT SUCCESSFUL
            List<AH_Salesforce_Trust_Notification__c> LstNotificationAssert = new List<AH_Salesforce_Trust_Notification__c>([SELECT Id FROM AH_Salesforce_Trust_Notification__c]);
            system.assertEquals(4, LstNotificationAssert.size(), 'Record count mismatch in Trust notification record in test Data..');
            
            // CREATE TEST JUNCTION RECORD
            AH_Salesforce_Instance_to_Notification__c i2n = new AH_Salesforce_Instance_to_Notification__c();
            i2n.AH_Salesforce_Instance__c = a1.Id;
            i2n.AH_Salesforce_Notification__c = notify2.Id; 
            i2n.Key__c = (i2n.AH_Salesforce_Instance__c + '-' + i2n.AH_Salesforce_Notification__c);
            insert i2n;
            
            // ASSERT INSERT SUCCESSFUL
            List<AH_Salesforce_Instance_to_Notification__c> lstJuncAssert = new List<AH_Salesforce_Instance_to_Notification__c>([SELECT Id FROM AH_Salesforce_Instance_to_Notification__c]);
            system.assertEquals(1, lstJuncAssert.size(), 'Record count mismatch in AH_Salesforce_Instance_to_Notification__c record in test Data..');
            
        }
        
    } 
    
    // ======================================================================================================================================= 
    // = TEST METHOD 1: 
    // ======================================================================================================================================= 
    @isTest static void test1() 
    {
        
        List<AH_Salesforce_Instance__c> lstInstance = new List <AH_Salesforce_Instance__c>([SELECT Id FROM AH_Salesforce_Instance__c]);
        system.debug(' **** lstInstance.size() = ' + lstInstance.size());
        
        List<AH_Salesforce_Trust_Notification__c> lstNotification = new List<AH_Salesforce_Trust_Notification__c>([SELECT Id FROM AH_Salesforce_Trust_Notification__c]);
        system.debug(' **** lstNotification.size() = ' + lstNotification.size());
        
        List<AH_Salesforce_Trust_Impact_Event__c> lstImpactEvent = new List<AH_Salesforce_Trust_Impact_Event__c>([SELECT Id FROM AH_Salesforce_Trust_Impact_Event__c]);
        system.debug(' **** lstImpactEventsize() = ' + lstImpactEvent.size());
        
        List<AH_Salesforce_Instance_to_Notification__c> lstJunc = new List<AH_Salesforce_Instance_to_Notification__c>([SELECT Id FROM AH_Salesforce_Instance_to_Notification__c]);
        system.debug(' **** lstJunc.size() = ' + lstJunc.size());       
        
        Test.setMock(HttpCalloutMock.class, new AH_SalesforceTrustRefresh_Mock());
        
        Test.StartTest();
        
        AH_SalesforceTrustRefresh_Schedule s = new AH_SalesforceTrustRefresh_Schedule();
        String sch = '0 0 0 * * ?';
        String jobId = system.schedule('Schedule Trust Refresh Test', sch, s);
        
        Test.StopTest();
        
        List<AH_Salesforce_Instance__c> lstInstanceAssert = new List <AH_Salesforce_Instance__c>([SELECT Id FROM AH_Salesforce_Instance__c]);
        system.debug(' **** lstInstanceAssert.size() = ' + lstInstanceAssert.size());
        
        List<AH_Salesforce_Trust_Notification__c> lstNotificationAssert = new List<AH_Salesforce_Trust_Notification__c>([SELECT Id FROM AH_Salesforce_Trust_Notification__c]);
        system.debug(' **** lstNotificationAssert.size() = ' + lstNotificationAssert.size());
        
        List<AH_Salesforce_Trust_Impact_Event__c> lstImpactEventAssert = new List<AH_Salesforce_Trust_Impact_Event__c>([SELECT Id FROM AH_Salesforce_Trust_Impact_Event__c]);
        system.debug(' **** lstImpactEventAssert.size() = ' + lstImpactEventAssert.size());
        
        List<AH_Salesforce_Instance_to_Notification__c> lstJuncAssert = new List<AH_Salesforce_Instance_to_Notification__c>([SELECT Id FROM AH_Salesforce_Instance_to_Notification__c]);
        system.debug(' **** lstJuncAssert.size() = ' + lstJuncAssert.size());
        
    }
    
}