force-app/main/default/objects/AH_Internal_IT_Request__c/AH_Internal_IT_Request__c.object-meta.xml
<CustomObject>
    <description>Used for Amadeus Hospitality Employees to submit requests from the IT Department</description>
    <label>Internal IT Request</label>
    <nameField>
        <displayFormat>ITREQ-{00000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Internal IT Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_IT_Survey__c/AH_IT_Survey__c.object-meta.xml
<CustomObject>
    <description>Surveys for IT Requests</description>
    <label>IT_Survey</label>
    <nameField>
        <displayFormat>ITSURV-{00000}</displayFormat>
        <label>Survey Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IT Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_IT_Survey__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Comments</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AH_IT_Survey__c/fields/Did_technician_provide_status_updates__c.field-meta.xml
<CustomField>
    <fullName>Did_technician_provide_status_updates__c</fullName>
    <description>5. Did the technician provide you with periodic updates about your work order&apos;s status?</description>
    <inlineHelpText>5. Did the technician provide you with periodic updates about your work order&apos;s status?</inlineHelpText>
    <label>Did technician provide status updates</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AH_IT_Survey__c/fields/Internal_IT_Request__c.field-meta.xml
<CustomField>
    <fullName>Internal_IT_Request__c</fullName>
    <label>Internal IT Request</label>
    <referenceTo>AH_Internal_IT_Request__c</referenceTo>
    <relationshipLabel>IT Surveys</relationshipLabel>
    <relationshipName>IT_Surveys</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AH_IT_Survey__c/fields/IT_Request_system_acceptable_speed__c.field-meta.xml
<CustomField>
    <fullName>IT_Request_system_acceptable_speed__c</fullName>
    <description>8. Did you feel the Track-It application performed with acceptable speed?</description>
    <inlineHelpText>8. Did you feel the Track-It application performed with acceptable speed?</inlineHelpText>
    <label>IT Request system acceptable speed</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AH_IT_Survey__c/fields/IT_Request_system_user_experience__c.field-meta.xml
<CustomField>
    <fullName>IT_Request_system_user_experience__c</fullName>
    <description>7. Was the Track-It Help Desk system for submitting work orders easy to use?</description>
    <inlineHelpText>7. Was the Track-It Help Desk system for submitting work orders easy to use?</inlineHelpText>
    <label>IT Request system user experience</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AH_IT_Survey__c/fields/Professionalism_of_technician__c.field-meta.xml
<CustomField>
    <fullName>Professionalism_of_technician__c</fullName>
    <description>2. How would you rate the professionalism of the technician assigned to your work order?</description>
    <inlineHelpText>2. How would you rate the professionalism of the technician assigned to your work order?</inlineHelpText>
    <label>Professionalism of technician</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AH_IT_Survey__c/fields/Rate_your_overall_experience__c.field-meta.xml
<CustomField>
    <fullName>Rate_your_overall_experience__c</fullName>
    <description>6. How would you rate your overall experience for this work order?</description>
    <inlineHelpText>6. How would you rate your overall experience for this work order?</inlineHelpText>
    <label>Rate your overall experience</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AH_IT_Survey__c/fields/Resolved_in_timely_manner__c.field-meta.xml
<CustomField>
    <fullName>Resolved_in_timely_manner__c</fullName>
    <description>1. Did the technician meet your expectations for resolving this work order in a timely manner?</description>
    <inlineHelpText>1. Did the technician meet your expectations for resolving this work order in a timely manner?</inlineHelpText>
    <label>Resolved in timely manner</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AH_IT_Survey__c/fields/Was_the_issue_completely_resolved__c.field-meta.xml
<CustomField>
    <fullName>Was_the_issue_completely_resolved__c</fullName>
    <description>3. Did the technician resolve your issue completely? (If not, please add comments below)</description>
    <inlineHelpText>3. Did the technician resolve your issue completely? (If not, please add comments below)</inlineHelpText>
    <label>Was the issue completely resolved</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AH_IT_Survey__c/fields/Was_the_technician_knowledgeable__c.field-meta.xml
<CustomField>
    <fullName>Was_the_technician_knowledgeable__c</fullName>
    <description>4. Was the technician knowledgeable about your issue and how to resolve it?</description>
    <inlineHelpText>4. Was the technician knowledgeable about your issue and how to resolve it?</inlineHelpText>
    <label>Was the technician knowledgeable</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AH_IT_Survey__c/fields/Were_the_fields_clear_and_understandable__c.field-meta.xml
<CustomField>
    <fullName>Were_the_fields_clear_and_understandable__c</fullName>
    <description>9. Were the fields on the form clear and understandable?</description>
    <inlineHelpText>9. Were the fields on the form clear and understandable?</inlineHelpText>
    <label>Were the fields clear and understandable</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AH_ITREQ_Survey_Detail.cls
public class AH_ITREQ_Survey_Detail { 
	public String Internal_IT_Req_Name {get;set;}
	public String Internal_IT_Req_Title {get;set;}
	public String Internal_IT_Req_Technician {get;set;}
	public AH_IT_Survey__c survey{get;set;}     
    //public List<SelectOption> ROptions {get;set;}
    public AH_ITREQ_Survey_Detail(){
       // one =1;
	   survey = new AH_IT_Survey__c();
	   if(ApexPages.currentPage().getParameters().get('Id') == null){
			ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Kindly provide Id of IT Request for Survey'));			
	   } else {
		   String Internal_IT_Request = Id.valueOf(ApexPages.currentPage().getParameters().get('Id'));
		   survey.Id = Internal_IT_Request;
		   getDetailsOfITrequest(Internal_IT_Request);
	   }
    }
    public void getDetailsOfITrequest(String itreq){
		AH_IT_Survey__c objItReq = [Select id,Name, Resolved_in_timely_manner__c,Professionalism_of_technician__c , 
												Was_the_issue_completely_resolved__c,Was_the_technician_knowledgeable__c,
												Did_technician_provide_status_updates__c, Rate_your_overall_experience__c,
												IT_Request_system_user_experience__c, IT_Request_system_acceptable_speed__c,
												Were_the_fields_clear_and_understandable__c, Comments__c,Internal_IT_Request__c,Internal_IT_Request__r.Name,
												Internal_IT_Request__r.Subject__c,Internal_IT_Request__r.Owner.Name 
												 From  AH_IT_Survey__c Where id = :itreq];
		Internal_IT_Req_Title = objItReq.Internal_IT_Request__r.Subject__c;
		Internal_IT_Req_Technician = objItReq.Internal_IT_Request__r.Owner.Name;
		Internal_IT_Req_Name = objItReq.Internal_IT_Request__r.Name;
		if(objItReq.Resolved_in_timely_manner__c ==null) objItReq.Resolved_in_timely_manner__c= 0;
		if(objItReq.Professionalism_of_technician__c ==null) objItReq.Professionalism_of_technician__c= 0;
		if(objItReq.Was_the_issue_completely_resolved__c ==null) objItReq.Was_the_issue_completely_resolved__c= 0;
		if(objItReq.Was_the_technician_knowledgeable__c ==null) objItReq.Was_the_technician_knowledgeable__c= 0;
		if(objItReq.Did_technician_provide_status_updates__c ==null) objItReq.Did_technician_provide_status_updates__c= 0;
		if(objItReq.Rate_your_overall_experience__c ==null) objItReq.Rate_your_overall_experience__c= 0;
		if(objItReq.IT_Request_system_user_experience__c ==null) objItReq.IT_Request_system_user_experience__c= 0;
		if(objItReq.IT_Request_system_acceptable_speed__c ==null) objItReq.IT_Request_system_acceptable_speed__c= 0;
		if(objItReq.Were_the_fields_clear_and_understandable__c ==null) objItReq.Were_the_fields_clear_and_understandable__c= 0;
		


		survey = objItReq;
	}
    public List<SelectOption> getROptions() {
        List<SelectOption> options = new List<SelectOption>(); 
        options.add(new SelectOption('1','1',true)); 
        options.add(new SelectOption('2','2',true)); 
        options.add(new SelectOption('3','3',true)); 
         options.add(new SelectOption('4','4',true)); 
         options.add(new SelectOption('5','5',true)); 
         options.add(new SelectOption('0','N/A',true)); 
        return options; 
    }
	
    public List<SelectOption> getROptionslabels() {
        List<SelectOption> options = new List<SelectOption>(); 
        options.add(new SelectOption('1','1',true)); 
        options.add(new SelectOption('2','2',true)); 
        options.add(new SelectOption('3','3',true)); 
         options.add(new SelectOption('4','4',true)); 
         options.add(new SelectOption('5','5',true)); 
         options.add(new SelectOption('0','N/A',true)); 
        return options; 
    }
	
}