force-app/main/default/objects/AH_CaseFlagPreferences__c/AH_CaseFlagPreferences__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>NICC-026092</description>
    <label>AH Case Flag Preferences</label>
</CustomObject>

force-app/main/default/objects/INTGR_Account__c/INTGR_Account__c.object-meta.xml
<CustomObject>
    <description>!!! INTEGRATION OBJECT- DO NOT ALTER !!!
NICC-032393</description>
    <label>Integration Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Integration Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/INTGR_Account__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NICC-030216 - Provides the means to Enable/Disable a customer&apos;s integration</description>
    <inlineHelpText>When this checkbox is checked the integration is live for this specific customer. Uncheck to disable the integration.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/INTGR_Account__c/fields/Assignment_Group__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Group__c</fullName>
    <description>NICC-030216 - Default value to be assigned to any case inbound or outbound from service now</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Default value to be assigned to any case inbound or outbound from service now</inlineHelpText>
    <label>Assignment Group</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/INTGR_Account__c/fields/Case_Origin__c.field-meta.xml
<CustomField>
    <fullName>Case_Origin__c</fullName>
    <description>NICC-030216 - Value used by integration to set default case origin on standard Case it creates.</description>
    <inlineHelpText>Value used by integration to set default case origin on standard Case it creates.</inlineHelpText>
    <label>Case Origin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ServiceNow Integration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/INTGR_Account__c/fields/Default_New_Case_Status__c.field-meta.xml
<CustomField>
    <fullName>Default_New_Case_Status__c</fullName>
    <description>NICC-030216 - Value used by integration to set default status on standard Case it creates.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Value used by integration to set default status on standard Case it creates.</inlineHelpText>
    <label>Default New Case Status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/INTGR_Account__c/fields/Logger_Desk_Agent_Name__c.field-meta.xml
<CustomField>
    <fullName>Logger_Desk_Agent_Name__c</fullName>
    <description>NICC-030216 - Value used by integration to set default logger agent name on standard Case it creates.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Value used by integration to set default logger agent name on standard Case it creates.</inlineHelpText>
    <label>Logger/Desk Agent Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/INTGR_Account__c/fields/Logger_Desk_Agent_Phone__c.field-meta.xml
<CustomField>
    <fullName>Logger_Desk_Agent_Phone__c</fullName>
    <description>NICC-030216 - Value used by integration to set default logger desk agent phone on standard Case it creates.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Value used by integration to set default logger desk agent phone on standard Case it creates.</inlineHelpText>
    <label>Logger /Desk Agent Phone</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/INTGR_Account__c/fields/Logger_Group__c.field-meta.xml
<CustomField>
    <fullName>Logger_Group__c</fullName>
    <description>NICC-030216 - Value used by integration to set default logger group on standard Case it creates.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Value used by integration to set default logger group on standard Case it creates.</inlineHelpText>
    <label>Logger / Group</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/INTGR_Case__c/INTGR_Case__c.object-meta.xml
<CustomObject>
    <description>!!! INTEGRATION OBJECT- DO NOT ALTER !!!
NICC-032393</description>
    <label>Integration Case</label>
    <nameField>
        <displayFormat>INTGR-{0000000}</displayFormat>
        <label>Integration Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/INTGR_Case__c/fields/Assignment_Group__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Group__c</fullName>
    <description>NICC-030216 - The group to be set by winaproach</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The group to be set by winaproach</inlineHelpText>
    <label>Assignment Group</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/INTGR_Case__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>NICC-030216 - Lookup to case created by integration. This field is set by a Process Builder after Standard case is created via the Integration.</description>
    <inlineHelpText>Lookup to case created by integration. This field is set by a Process Builder after Standard case is created via the Integration.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Integration Cases</relationshipLabel>
    <relationshipName>Integration_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/INTGR_Case__c/fields/Customer_Ticket_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Ticket_Number__c</fullName>
    <description>NICC-030216 - User-friendly case/incident number of record in customer ITSM.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>User-friendly case/incident number of record in customer ITSM.</inlineHelpText>
    <label>Customer Ticket Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/INTGR_Case__c/fields/Customer_Ticket_System_Id__c.field-meta.xml
<CustomField>
    <fullName>Customer_Ticket_System_Id__c</fullName>
    <description>NICC-030216 - Primary key (system id) of case/incident record in customer ITSM.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Primary key (system id) of case/incident record in customer ITSM.</inlineHelpText>
    <label>Customer Ticket System Id</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/INTGR_Case__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>NICC-030216 - Explanation that describes the issue in more detail.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Explanation that describes the issue in more detail.</inlineHelpText>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/INTGR_Case__c/fields/INTGR_Account__c.field-meta.xml
<CustomField>
    <fullName>INTGR_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>NICC-030216 - Lookup populated by integration code for ease in referencing field values and to create a relationship for a related list on the INTGR_Account__c Object</description>
    <inlineHelpText>Lookup to integration account record details</inlineHelpText>
    <label>Integration Account</label>
    <referenceTo>INTGR_Account__c</referenceTo>
    <relationshipLabel>Integration Cases</relationshipLabel>
    <relationshipName>Integration_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/INTGR_Case__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <description>NICC-030216 - Value set by integration user and integration code for two-way (inbound/outbound) updating of Case severity.</description>
    <inlineHelpText>Value set by integration user and integration code for two-way (inbound/outbound) updating of Case severity.</inlineHelpText>
    <label>Severity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/INTGR_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>NICC-030216 - Value set by integration user and integration code for two-way (inbound/outbound) updating of Case status. Special rules apply (see documentation)</description>
    <inlineHelpText>Value set by integration user and integration code for two-way (inbound/outbound) updating of Case status. Special rules apply (see documentation)</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Acknowledged</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recovered</fullName>
            </value>
            <value>
                <fullName>Verified as Recovered</fullName>
            </value>
            <value>
                <fullName>Pending Master Recovery</fullName>
            </value>
            <value>
                <fullName>Pending Problem Resolution</fullName>
            </value>
            <value>
                <fullName>Pending Vendor</fullName>
            </value>
            <value>
                <fullName>Closed as recovered</fullName>
            </value>
            <value>
                <fullName>Closed as rejected</fullName>
            </value>
            <value>
                <fullName>Closed as withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/INTGR_Case__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>NICC-030216 - Value set by integration user and integration code for two-way (inbound/outbound) updating of Case subject.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Value set by integration user and integration code for two-way (inbound/outbound) updating of Case subject.</inlineHelpText>
    <label>Subject</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/INTGR_Status_Mapping__c/INTGR_Status_Mapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>NICC-032393 - Status mapping between Sales force and Service Now.</description>
    <label>INTGR Status Mapping</label>
</CustomObject>

force-app/main/default/objects/INTGR_Status_Mapping__c/fields/INTGR_Current_Status__c.field-meta.xml
<CustomField>
    <fullName>INTGR_Current_Status__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>INTGR Current Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/INTGR_Status_Mapping__c/fields/INTGR_Inbound_Status__c.field-meta.xml
<CustomField>
    <fullName>INTGR_Inbound_Status__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>INTGR Inbound Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/INTGR_Status_Mapping__c/fields/INTGR_Status_Updated__c.field-meta.xml
<CustomField>
    <fullName>INTGR_Status_Updated__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>INTGR Status Updated</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WinaproachIncidentSettings__c/WinaproachIncidentSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This settings used to manage end points and credentials for Win@proach integration. Create record name as &quot;Default&quot; and enter the required values for it.</description>
    <label>Win@proach Incident Settings</label>
</CustomObject>

force-app/main/default/objects/WinaproachIncidentSettings__c/fields/Integration_Username__c.field-meta.xml
<CustomField>
    <fullName>Integration_Username__c</fullName>
    <description>Salesforce username of the winaproach integration user, we do not need to send the information back to Win@proach because the insert or update came from Win@proach</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Salesforce username of the integration user i.e. winaproach user.  We do not need to send the information back to Win@proach because the insert or update came from Win@proach</inlineHelpText>
    <label>Integration Username</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/INTGR_Case_TriggerHandler_Test.cls
/****************************************************************************************
Name            : INTGR_Case_TriggerHandler_Test
Author          : Princy Jain
Created Date    : 06/06/2018
Last Mod Date   : 01/14/2019
Last Mod By     : Sean Harris
NICC Reference  : 
Description     : 
                :
****************************************************************************************/
@isTest
public class INTGR_Case_TriggerHandler_Test
{
    
    // ======================================================================================================================================= 
    // = CREATE TEST DATA
    // =======================================================================================================================================     
    @testSetup static void setupData() 
    {
        
        // CREATE WIN@PROACH & SERVICE NOW CUSTOM SETTINGS
        NI_TestClassData.createTestWinaproachServiceNowSettings();
        
        WinaproachIncidentSettings__c ws = WinaproachIncidentSettings__c.getInstance('Default');
        ws.Integration_Username__c = UserInfo.getUserName();
        update ws;
        
        // POPULATE INTEGRATION CUSTOM SETTING FOR STATUS
        Set<String> statusSet = new Set<String> {'Acknowledged-Open~Open',
            'Acknowledged-Recovered~Rejected',
            'New-New~New',
            'Open-Acknowledged~Acknowledged',
            'Open-Closed~Closed as Withdrawn',
            'Open-Closed as withdrawn~Closed as Withdrawn',
            'Recovered-Acknowledged~Acknowledged',
            'Recovered-Closed~Closed as Recovered',
            'Rejected-Acknowledged~Acknowledged',
            'Rejected-Closed~Closed as Rejected'};
        List<INTGR_Status_Mapping__c> isMappingList = new List<INTGR_Status_Mapping__c> ();
        
        for (String status : statusSet)
        {
            INTGR_Status_Mapping__c obj = new INTGR_Status_Mapping__c();
            obj.Name = status.split('~')[0];
            obj.INTGR_Inbound_Status__c = status.split('-')[1].split('~')[0];
            obj.INTGR_Status_Updated__c = status.split('~')[1];
            obj.INTGR_Current_Status__c = status.split('-')[0];
            
            isMappingList.add(obj);
        }
        
        insert isMappingList;
        
        // CREATE CASE FLAGS CUSTOM SETTINGS
        AH_CaseFlagPreferences__c caseFlagSetting = NI_TestClassData.createCaseFlagPreferences();
        upsert caseFlagSetting;
        
        Test.startTest();
        
        // CREATE TEST ACCOUNT
        Account a = NI_TestClassData.createTestAccount(1);
        a.Name = 'APEX TEST INTGR_Case_TriggerHandler_Test';
        insert a;
        
        // CREATE TEST CUSTOMER USER ACCOUNT
        User u = NI_TestClassData.createTestUser(111, 'Case Integration Customers');
        u.Email = 'apexTester111@amadeuscustomer.com';
        u.Alias = '111user';
        insert u;         
        
        // CREATE TEST INTEGRATION ACCOUNT RECORD
        INTGR_Account__c acc = NI_TestClassData.createTestINTGR_Account(1, a.id, u.id);
        acc.Active__c = true;
        acc.Assignment_Group__c = 'Test Group' ;
        acc.Case_Origin__c = 'ServiceNow';
        acc.Logger_Desk_Agent_Name__c = 'ServiceNow';
        acc.Default_New_Case_Status__c = 'New';
        acc.Logger_Desk_Agent_Phone__c = '123456789';
        acc.Logger_Group__c = 'ServiceNow';
        insert acc;
        
        system.runAs(u)
        {
            // CREATE INBOUND INTEGRATION CASE
            INTGR_Case__c caseObj2 = NI_TestClassData.createTestINTGR_Case(1, acc.Id, null);
            caseObj2.Customer_Ticket_System_Id__c = 'INC000001';
            caseObj2.Customer_Ticket_Number__c = 'INC000001';
            caseObj2.Status__c = 'Acknowledged';
            caseObj2.Subject__c = 'PROSPECT - ' + caseObj2.Subject__c;
            insert caseObj2;
            
            INTGR_Case__c caseObj = NI_TestClassData.createTestINTGR_Case(1, acc.Id, null);
            caseObj.Customer_Ticket_System_Id__c = 'INC000002';
            caseObj.Customer_Ticket_Number__c = 'INC000002';
            caseObj.Status__c = 'Acknowledged';
            caseObj.Subject__c = 'PROSPECT - ' + caseObj.Subject__c;
            insert caseObj;
            
            
            INTGR_Case__c caseObj3 = NI_TestClassData.createTestINTGR_Case(1, acc.Id, null);
            caseObj3.Customer_Ticket_System_Id__c = 'INC000003';
            caseObj3.Customer_Ticket_Number__c = 'INC000003';
            caseObj3.Status__c = 'Pending Problem Resolution';
            caseObj3.Subject__c = 'PROSPECT - ' + caseObj3.Subject__c;
            insert caseObj3;
            
            INTGR_Case__c caseObj4 = NI_TestClassData.createTestINTGR_Case(1, acc.Id, null);
            caseObj4.Customer_Ticket_System_Id__c = 'INC000004';
            caseObj4.Customer_Ticket_Number__c = 'INC000004';
            caseObj4.Subject__c = 'PROSPECT - ' + caseObj4.Subject__c;
            caseObj4.Status__c = 'Pending Master Recovery';
            insert caseObj4;
        }
        
        // Case cs = NI_TestClassData.createTestCaseIntegration(1, a.Id);
        //  cs.Integration_Account__c = acc.Id;
        // cs.Acknowledged__c = system.now();
        // cs.Rejected_Case__c = true;
        //insert cs;
        
    }
    
    // ======================================================================================================================================= 
    // = TEST METHOD 1:
    // ======================================================================================================================================= 
    static testmethod void initiateInBoundTestAPI() 
    {
        
        Test.setMock(HttpCalloutMock.class, new INTGR_REST_MockResponseGenerator());
        User u = [SELECT Id FROM User WHERE Alias = '111user'][0];    
        Id accId = [SELECT Id FROM INTGR_Account__c LIMIT 1][0].id;
        Test.startTest();       
        
        // CREATE INBOUND DATA FOR Internal Cases
        system.runAs(u)
        {
            
            List<INTGR_Case__c> caseAsserts1 = [SELECT Id, Assignment_Group__c, INTGR_Account__c, Status__c, Severity__c, Subject__c, Description__c, Case__c FROM INTGR_Case__c WHERE createdById =: u.id];
            caseAsserts1[0].Status__c = 'Open';
            caseAsserts1[0].Severity__c = '3';
            caseAsserts1[0].Subject__c = 'Update Subject';
            caseAsserts1[0].Assignment_Group__c = 'Update AG';
            
            caseAsserts1[1].Status__c = 'Recovered';
            
            caseAsserts1[2].Severity__c = '4';
            caseAsserts1[2].Status__c = 'Acknowledged';
            
            caseAsserts1[3].Assignment_Group__c = 'New AG';
            caseAsserts1[3].Status__c = 'Test Pending Master Recovery';
            
            try
            {
                update caseAsserts1;
            }
            catch(Exception e)
            {
                
            }
            
            system.assertEquals('Update Subject', caseAsserts1[0].Subject__c);
            //system.assertEquals('4', caseAsserts1[0].Severity__c);
            system.assertEquals('Open', caseAsserts1[0].Status__c);
            
        }
        
        Test.stopTest();
        
    }
    
    // ======================================================================================================================================= 
    // = TEST METHOD 2:
    // =======================================================================================================================================     
    static testmethod void createOutboundAPICall() 
    {
        
        Test.setMock(HttpCalloutMock.class, new INTGR_REST_MockResponseGenerator());
        User u = [SELECT Id FROM User WHERE Alias = '111user'][0];    
        Id accId = [SELECT Id FROM Account LIMIT 1][0].id;
        
        Test.startTest();       
        
        Case cs = NI_TestClassData.createTestCaseIntegration(1, accId);
        insert cs;
        
        Map<Id, Case> idVsCaseObjMap = INTGR_Case_SOQLDataProvider.getSCdetailsToInsertIC(cs.Id);
        INTGR_IntegrationHelper.upsertIntegrationCase(idVsCaseObjMap,true, false, null);
        
        Test.stopTest();
        
    }
    
    // ======================================================================================================================================= 
    // = TEST METHOD 3:
    // ======================================================================================================================================= 
    static testmethod void initiateInBoundTestSA() 
    {
        
        Test.setMock(HttpCalloutMock.class, new INTGR_REST_MockResponseGenerator());
        User u = [SELECT Id FROM User WHERE Alias = '111user'];    
        
        Test.startTest();
        
        //Id caseId = [Select Id, Case__c FROM INTGR_Case__c WHERE createdById =: u.id];
        Id caseId = [SELECT Case__c FROM INTGR_Case__c WHERE createdById =: u.id LIMIT 1][0].Case__c;
        
        try 
        {
            
            Case c = [Select id, Description,Rejected_Case__c,Customer_Ticket_Number__c,INTGR_Customer_Ticket_System_Id__c, Status FROM Case WHERE Id =:caseId];
            c.Status = 'Open';
            c.INTGR_Customer_Ticket_System_Id__c = null;
            c.Customer_Ticket_Number__c = null;
            c.Description = 'Update SF Case';
            c.Rejected_Case__c = true;
            update c;
            
            c.Status = 'Recovered';
            update c;
        }
        catch (Exception e)
        {
            system.debug('Error Occured' + e.getMessage());
        }
        
        List<INTGR_Case__c> caseAsserts1 = [SELECT Id, Assignment_Group__c, INTGR_Account__c, Status__c, Severity__c,Subject__c,Description__c, Case__c FROM INTGR_Case__c WHERE createdById =: u.id];
        
        caseAsserts1[0].Status__c = 'Open';
        caseAsserts1[0].Severity__c = '3';
        caseAsserts1[0].Subject__c = 'Update Subject';
        caseAsserts1[0].Assignment_Group__c = 'Update AG';
        
        caseAsserts1[1].Status__c = 'Recovered';
        
        caseAsserts1[2].Severity__c = '4';
        caseAsserts1[2].Status__c = 'Acknowledged';
        
        caseAsserts1[3].Assignment_Group__c = 'New AG';
        caseAsserts1[3].Status__c = 'Test Pending Master Recovery';
        
        try
        {
            update caseAsserts1;
        }
        catch(Exception e)
        {
            
        }

        Test.stopTest();
        
    }





    
    
/*
// ======================================================================================================================================= 
// = TEST METHOD 4:
// ======================================================================================================================================= 

static testmethod void initiateInBoundTestAPI1() 
{

    Test.setMock(HttpCalloutMock.class, new INTGR_REST_MockResponseGenerator());
    User u = [SELECT Id FROM User WHERE Alias = '111user'][0];    
    Id accId = [Select Id FROM  INTGR_Account__c limit 1][0].id;
    Test.startTest();       
    
    // CREATE INBOUND DATA FOR Internal Cases
    system.runAs(u)
    {
        List<INTGR_Case__c> caseAsserts1 = [SELECT Id, Assignment_Group__c, INTGR_Account__c, Status__c, Severity__c,Subject__c,Description__c, Case__c FROM INTGR_Case__c WHERE createdById =: u.id];
        caseAsserts1[0].Status__c = 'Open';
        update caseAsserts1[0];
        
        caseAsserts1[0].Status__c = 'Closed';
        update caseAsserts1[0];
        
        caseAsserts1[1].Status__c = 'Rejected';
        update caseAsserts1[1];
        
        caseAsserts1[1].Status__c = 'Closed';
        update caseAsserts1[1];
        
        caseAsserts1[2].Status__c = 'Recovered';
        update caseAsserts1[2];
        
        caseAsserts1[2].Status__c = 'Closed';
        update caseAsserts1[2];
    
    }
    Test.stopTest();
}
*/
        
}