force-app/main/default/objects/CR_Status_to_Description__mdt/CR_Status_to_Description__mdt.object-meta.xml
<CustomObject>
    <label>CR Status to Description</label>
    <pluralLabel>CR Status to Descriptions</pluralLabel>
</CustomObject>

force-app/main/default/objects/NI_TriggerBypassSwitches__c/NI_TriggerBypassSwitches__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>NICC-010252: Global Custom Setting for Trigger Bypassing

Used to turn off code execution on triggers globally or per specific object(s).</description>
    <label>NI Trigger Bypass Switches</label>
</CustomObject>

force-app/main/default/objects/NI_TriggerBypassSwitches__c/fields/Bypass_ChangeRequest__c.field-meta.xml
<CustomField>
    <fullName>Bypass_ChangeRequest__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When this check box is checked, the triggers on the SFDC_CSP_Development_Request__c are disabled</description>
    <inlineHelpText>When this check box is checked, the triggers on the SFDC_CSP_Development_Request__c are disabled</inlineHelpText>
    <label>Bypass_ChangeRequest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SFDC_CSP_Development_Request__c/SFDC_CSP_Development_Request__c.object-meta.xml
<CustomObject>
    <description>SFDC Customer Service Project</description>
    <label>Change Request</label>
    <nameField>
        <displayFormat>CR{0000000}</displayFormat>
        <label>Change Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SFDC_CSP_Development_Request__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Description</label>
    <length>32000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/SFDC_CSP_Development_Request__c/fields/Number_of_Cases_Linked__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Cases_Linked__c</fullName>
    <defaultValue>0</defaultValue>
    <description>NICC-020860</description>
    <label>Number of Cases Linked</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SFDC_CSP_Development_Request__c/fields/Public_Status__c.field-meta.xml
<CustomField>
    <fullName>Public_Status__c</fullName>
    <description>This is the public (customer facing) status of the CR</description>
    <label>Public Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Product Team Review</fullName>
            </value>
            <value>
                <fullName>Under Consideration</fullName>
            </value>
            <value>
                <fullName>On Roadmap</fullName>
            </value>
            <value>
                <fullName>Coming in the Next Release</fullName>
            </value>
            <value>
                <fullName>Partially Delivered</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Solutions Available</fullName>
            </value>
            <value>
                <fullName>Not Planned</fullName>
            </value>
            <value>
                <fullName>Existing Feature</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SFDC_CSP_Development_Request__c/fields/Public_Status_Description__c.field-meta.xml
<CustomField>
    <fullName>Public_Status_Description__c</fullName>
    <description>This is the public (customer facing) description of what the Public Status means</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Public Status Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/AH_ChangeRequest_TriggerHandler.cls
/************************************************************************************************
Name            : AH_ChangeRequest_TriggerHandler Class
Author          : Bhuleshwar Deshpande
Created Date    : 09/10/2018
Last Mod Date   : 11/09/2021
Last Mod By     : Sean Harris
NICC Reference  :
Description     : Class that handles all trigger code for the SFDC_CSP_Development_Request__c Object
                : NICC-054506 - added countLinkedCases method
                :
*************************************************************************************************/
public class AH_ChangeRequest_TriggerHandler 
{
    
    //VARIABLE TO HOLD THE BYPASS SWITCH CUSTOM SETTING 
    private NI_TriggerBypassSwitches__c bpSwitch {get; set;}
    
    
    public AH_ChangeRequest_TriggerHandler()
    {
        // GET TRIGGER HANDLER BYPASS SWITCH VALUE
        bpSwitch = NI_TriggerBypassSwitches__c.getOrgDefaults();
    }

    //BEFORE INSERT LOGIC HERE.
    public void OnBeforeInsert(List <SFDC_CSP_Development_Request__c> newTrigger)
    {
        //EXECUTE THE CODE IF THE BYPASS SWITCH IS NOT CHECKED
        if (!bpSwitch.Bypass_ChangeRequest__c)
        { 
            if (!newTrigger.isEmpty())
            {
                if (Test.isRunningTest()) // NICC-054506 - ADDED THIS BECAUSE THE bpSwitch.Bypass_ChangeRequest__c WAS SET TO TRUE FOR SOME REASON
                {
                    setPublicStatusDescription(newTrigger);
                }
                countLinkedCases(newTrigger);
            }
        } 
    }   
    
    public void OnBeforeUpdate(List <SFDC_CSP_Development_Request__c> newTrigger)
    {
        // EXECUTE THE CODE IF THE BYPASS SWITCH IS NOT CHECKED
        if (!bpSwitch.Bypass_ChangeRequest__c)
        {
            if (!newTrigger.isEmpty())
            {
                if (Test.isRunningTest()) // NICC-054506 - ADDED THIS BECAUSE THE bpSwitch.Bypass_ChangeRequest__c WAS SET TO TRUE FOR SOME REASON
                {
                	setPublicStatusDescription(newTrigger);
                }
                countLinkedCases(newTrigger);
            }
        }
    }   
    
    private void setPublicStatusDescription(List<SFDC_CSP_Development_Request__c> newTrigger)
    {
        
        Map<String, String> crCustomMetadataMap = new Map<String, String>();
        List<CR_Status_to_Description__mdt> crCustomMetadataLst = ([SELECT Status__c, Description__c FROM CR_Status_to_Description__mdt]);
        
        // LOOP TO PUT MAP DATA
        for (CR_Status_to_Description__mdt CRlst : crCustomMetadataLst)
        { 
            crCustomMetadataMap.put(CRlst.Status__c, CRlst.Description__c);   
        }
        
        // LOOP TO ITERATE ON CR LIST AND COMPARE MAP KEY VALUES.
        for (SFDC_CSP_Development_Request__c CR : newTrigger)
        {
            if (crCustomMetadataMap.containsKey(CR.Public_Status__c))
            {
                CR.Public_Status_Description__c = crCustomMetadataMap.get(CR.Public_Status__c); 
            }
        }
        
    }

    // NICC-054506 - added countLinkedCases method
    public void countLinkedCases(List<SFDC_CSP_Development_Request__c> newTrigger)
    {        
      
        // GET AN AGGREGATED LIST OF CASES RELATED TO THE CR RECORDS IN THE TRIGGER 
        List<AggregateResult> lstRelatedCases = new List<AggregateResult>([SELECT Change_Request__c, COUNT(Id) CaseCount 
                                                                           FROM Case 
                                                                           WHERE Change_Request__c IN : newTrigger 
                                                                           AND Change_Request__c != null 
                                                                           GROUP BY Change_Request__c]);
        
        if (lstRelatedCases.isEmpty())
        {
            return;
        }
        
        // LOOP THROUGH TRIGGER AND FIND MATCHING CASE COUNTS TO UPDATE THE Number_of_Cases_Linked__c FIELD
        for (SFDC_CSP_Development_Request__c cr : newTrigger)
        {
            for (AggregateResult ar : lstRelatedCases)
            {
                Id crID = (Id) ar.get('Change_Request__c'); 
                decimal caseCount = (Decimal) ar.get('CaseCount');
                if (cr.Number_of_Cases_Linked__c != caseCount && cr.Id == crID)
                {
                    cr.Number_of_Cases_Linked__c = caseCount; 
                }                
            }
        }
        
    }  
    
}