force-app/main/default/objects/Activity_Line_Item__c/Activity_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Activity Line Item</label>
    <nameField>
        <displayFormat>ACT-{00000}</displayFormat>
        <label>Activity Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Line Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity_Line_Item__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Activity Line Item</relationshipLabel>
    <relationshipName>Activity_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Billing_Contract__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contract__c</fullName>
    <description>Revenue Recognition line detail on Billing Contract Object</description>
    <label>Billing Contract</label>
    <referenceTo>Billing_Contract__c</referenceTo>
    <relationshipLabel>Activity Line Items</relationshipLabel>
    <relationshipName>Rev_Rec_BC_Line_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Cancel_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Cancel_Line_Item__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to indicate that an Activity Line Item record should be cancelled.  This field was originally created for the Contracts Team to indicate which Activity Line Items should be cancelled when processing Opportunities.</description>
    <inlineHelpText>This field is used to indicate that an Activity Line Item record should be cancelled.  This field was originally created for the Contracts Team to indicate which Activity Line Items should be cancelled when processing Opportunities.</inlineHelpText>
    <label>Flagged For Cancellation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Activity End / Delivered Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Activity Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Contract_Total_Amount_Currency__c.field-meta.xml
<CustomField>
    <fullName>Contract_Total_Amount_Currency__c</fullName>
    <formula>Contract_Total_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Flagged_For_Cancellation_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Flagged_For_Cancellation_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The opportunity from which this activity line was flagged for cancellation</description>
    <inlineHelpText>The opportunity from which this activity line was flagged for cancellation</inlineHelpText>
    <label>Flagged For Cancellation Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Activity Line Item (Flagged For Cancellation Opportunity)</relationshipLabel>
    <relationshipName>Activity_Line_Item_Flagged_Cancellation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Flagged_For_Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Flagged_For_Cancellation_Reason__c</fullName>
    <description>The reason that the &quot;Flagged for Cancellation&quot; check box has been checked.  This field is required if the &quot;Flagged for Cancellation&quot; check box is checked.</description>
    <inlineHelpText>The reason that the &quot;Flagged for Cancellation&quot; check box has been checked.  This field is required if the &quot;Flagged for Cancellation&quot; check box is checked.</inlineHelpText>
    <label>Flagged For Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cancellation_Reason</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Rev_Rec_BC_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Product_Package__c.field-meta.xml
<CustomField>
    <fullName>Product_Package__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>A lookup to the product package that relates to this product</inlineHelpText>
    <label>Product Package</label>
    <referenceTo>PSA_Product_Package__c</referenceTo>
    <relationshipLabel>Activity Line Item</relationshipLabel>
    <relationshipName>Activity_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/SKU__c.field-meta.xml
<CustomField>
    <fullName>SKU__c</fullName>
    <formula>Product__r.ProductCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Product Code</inlineHelpText>
    <label>SKU</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Units__c.field-meta.xml
<CustomField>
    <fullName>Units__c</fullName>
    <description>NICC-035500 - Changed Decimal Places</description>
    <label>Units</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billing_Contract__c/Billing_Contract__c.object-meta.xml
<CustomObject>
    <label>Billing Contract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Billing Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Contract</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Contract__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billing Contract</relationshipLabel>
    <relationshipName>Billing_Contract</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing_Contract__c/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contract End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billing_Contract__c/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PSA_Product_Package__c/PSA_Product_Package__c.object-meta.xml
<CustomObject>
    <description>Header record for the listings of PSA Milestone parameters for generation of Milestones based on Opportunity Products</description>
    <label>Product Package</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Cancellation_Reason.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Billing Contract Re-Negotiated / Moved to Bundle Pricing</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Exit (Leaving all together)</fullName>
    </customValue>
    <customValue>
        <fullName>Extract / Append</fullName>
    </customValue>
    <customValue>
        <fullName>Product Replacement/Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Upgrade /Migration</fullName>
    </customValue>
    <customValue>
        <fullName>User Reduction</fullName>
    </customValue>
    <description>Used for pick lists that contain the reasons that customers are cancelling</description>
    <masterLabel>Cancellation Reason</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AH_ActivityLineItemOpptyExt.cls
/****************************************************************************************
Name            : AH_ActivityLineItemOpptyExt Class
Author          : Stuart Emery
Created Date    : 10/06/2013
Last Mod Date   : 08/15/2019
Last Mod By     : Stuart Emery
NICC Reference  : 
Description     : Controller for the AH_ActivityLineItemOpptyExt Visualforce page 
                : The AH_ActivityLineItemOpptyExt page is used by the Contracts Team 
                : to identify Activity Line Items that need to be cancelled as part of the 
                : related Opportunity.
                : Updated 08/15/2019 Per NICC-036683
******************************************************************************************/
public with sharing class AH_ActivityLineItemOpptyExt 
{
    
    private Opportunity o;
    
    // USED TO ENABLE OR DISABLE THE CANCEL CHECKBOX ON THE VF PAGE  
    public Boolean bDisabled {get; set;}
       
    // WRAPPER CLASS LIST TO HOLD THE ACTIVITY LINE ITEMS
    public List<actLineItemWrapper> lstActLineItems {get; set;}
    
    
    public AH_ActivityLineItemOpptyExt(ApexPages.StandardController stdController)
    {        
        this.o = (Opportunity)stdController.getRecord();        
        // CALL THE METHODS TO POPULATE THE LISTS
        disableListEdit();        
    } 
    
    //METHOD TO POPULATE A PICKLIST WITH THE VALUES FROM THE FLAGGED FOR CANCELLATION REASON FIELD.  ADDED BY STUART EMERY ON 5/17/2017
    public List<SelectOption> getFlaggForCancellationReasonOptionList(){
        List<SelectOption> selOptionLst = new List<SelectOption>();
        Schema.DescribeFieldResult al = Activity_Line_Item__c.Flagged_For_Cancellation_Reason__c.getDescribe();
        List<Schema.PickListEntry> reasonList = al.getPickListValues();
        selOptionLst.add(new SelectOption('','--None--'));
        for(Schema.PickListEntry obj:reasonList){
            selOptionLst.add(new SelectOption(obj.getLabel(),obj.getValue()));
        }
        return selOptionLst;
    }
    
    public void disableListEdit()
    {
        bDisabled = true;
        getActivityLineItems(); 
    }
    
    public void EnableListEdit()
    {
        bDisabled = false;
        getActivityLineItems();
    }
    
    // QUERY TO RETURN A LIST OF ACTIVITY LINE ITEMS
    public List<actLineItemWrapper> getActivityLineItems() 
    {
        
        lstActLineItems = new List<actLineItemWrapper>();
        
        //Updated 08/15/2019 Per NICC-036683
        for (Activity_Line_Item__c ali : 
             [SELECT Id, Name, Cancel_Line_Item__c, SKU__c, Product__r.Name, Contract_Start_Date__c, Contract_End_Date__c, Units__c, Status__c, 
              Contract_Total_Amount_Currency__c, Flagged_For_Cancellation_Reason__c, Product_Package__c, Product_Package__r.Name  
              FROM Activity_Line_Item__c 
              WHERE Billing_Contract__r.Account__c =: o.AccountId 
              AND Status__c = 'Active' 
              ORDER BY Product_Description__c]) 
        {
            lstActLineItems.add(new actLineItemWrapper(ali));
        }   
        
        return lstActLineItems;
        
    } 
    
    public PageReference saveSelected() 
    {        
        
        // LIST OF ACTIVITY LINE ITEMS THAT WILL BE POPULATED WITH ONLY THE SELECTED ACTIVITY LINE ITEMS
        List<Activity_Line_Item__c> lstSelectedLineItems = new List<Activity_Line_Item__c>();
        
        // LIST OF ACTIVITY LINE ITEMS THAT WILL BE POPULATED WITH ONLY THE NON-SELECTED ACTIVITY LINE ITEMS
        List<Activity_Line_Item__c> lstNonSelectedLineItems = new List<Activity_Line_Item__c>();  
        
        // LIST OF SELECTED ACTIVITY LINE ITEMS TO UPDATE  
        List<Activity_Line_Item__c> lstActLineItemsToUpdate = new List<Activity_Line_Item__c>();
        
        // LOOP THROUGH OUR lstActLineItems LIST TO SEE IF THE SELECTED PROPERTY IS SET TO TRUE AND ADD THE RECORD TO THE lstSelectedAssets LIST OR THE lstNonSelectedLineItems LIST
        for (actLineItemWrapper li : lstActLineItems) 
        {   
            if (li.isSelected == true) 
            {
                lstSelectedLineItems.add(li.ali);
            }
            else
            {
                lstNonSelectedLineItems.add(li.ali);
            }  
        } 
        
        // LOOP THROUGH THE lstSelectedLineItems LIST AND SET THE Cancel__c FIELD TO 'TRUE' FOR THE SELECTED RECORDS AND ADD THEM TO THE lstActLineItemsToUpdate LIST 
        for (Activity_Line_Item__c s : lstSelectedLineItems)
        {
            if(s.Flagged_For_Cancellation_Reason__c == null)
            { 
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,System.Label.AH_ActivityLineItemOpptyView_Save_Error));
            }
            else
            {
                    s.Cancel_Line_Item__c = true;
                    s.Flagged_For_Cancellation_Opportunity__c = o.Id;
                    lstActLineItemsToUpdate.add(s);
            }     
                }
        
        // LOOP THROUGH THE lstNonSelectedLineItems LIST AND SET THE Cancel__c FIELD TO 'FALSE' FOR THE SELECTED RECORDS AND ADD THEM TO THE lstActLineItemsToUpdate LIST   
        for (Activity_Line_Item__c n : lstNonSelectedLineItems)
        {
            n.Cancel_Line_Item__c = false;
            n.Flagged_For_Cancellation_Opportunity__c = null;
            n.Flagged_For_Cancellation_Reason__c = null;
            lstActLineItemsToUpdate.add(n);
        }   
        
        // USE DATABASE DML METHOD TO UPDATE ALL OF THE SELECTED AND NON-SELECTED RECORDS
        if (lstActLineItemsToUpdate.size() > 0)
        {
            database.update(lstActLineItemsToUpdate);
        }                     
        
        // SET THE LIST TO NULL SO A NEW LIST IS CREATED
        lstActLineItems.Clear(); 
        disableListEdit(); 
        
        return null;
        
    }
    
    public pageReference changeSelected()
    {
        //if (li.isSelected == true)
        //{
        
        // }
        return null;
    }
    
    // WRAPPER CLASS TO BUILD THE SOFTRAX ASSETS LIST  
    public class actLineItemWrapper 
    {
        public Activity_Line_Item__c ali {get; set;}
        public Boolean isSelected {get; set;}
        public Id idActLineItem {get; set;}
        public Id idProductPackage {get; set;} //ADDED 08/15/2019 Per NICC-036683
        
        public actLineItemWrapper(Activity_Line_Item__c a) 
        {
            ali = a;
            idActLineItem = ali.Id;
            idProductPackage = ali.Product_Package__c; //ADDED 08/15/2019 Per NICC-036683
            if (ali.Cancel_Line_Item__c) 
            {
                isSelected = true;
            }
            else
            {
                isSelected = false; 
            }
        }
    }
    
}