force-app/main/default/objects/Activity_Line_Item__c/Activity_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Activity Line Item</label>
    <nameField>
        <displayFormat>ACT-{00000}</displayFormat>
        <label>Activity Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Line Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity_Line_Item__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Activity Line Item</relationshipLabel>
    <relationshipName>Activity_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Activation_Date__c.field-meta.xml
<CustomField>
    <fullName>Activation_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Activation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Activation_Required__c.field-meta.xml
<CustomField>
    <fullName>Activation_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activation Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Billing_Contract__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contract__c</fullName>
    <description>Revenue Recognition line detail on Billing Contract Object</description>
    <label>Billing Contract</label>
    <referenceTo>Billing_Contract__c</referenceTo>
    <relationshipLabel>Activity Line Items</relationshipLabel>
    <relationshipName>Rev_Rec_BC_Line_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Activity End / Delivered Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Activity Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Opp_Product_ID__c.field-meta.xml
<CustomField>
    <fullName>Opp_Product_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Opp Product ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Activity Line Item</relationshipLabel>
    <relationshipName>Activity_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Terms</label>
    <referenceTo>Payment_Terms__c</referenceTo>
    <relationshipLabel>Activity Line Item</relationshipLabel>
    <relationshipName>Activity_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Rev_Rec_BC_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Revenue_Category__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Category__c</fullName>
    <label>Revenue Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hosting and Support</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Subscription</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Units__c.field-meta.xml
<CustomField>
    <fullName>Units__c</fullName>
    <description>NICC-035500 - Changed Decimal Places</description>
    <label>Units</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billing_Contract__c/Billing_Contract__c.object-meta.xml
<CustomObject>
    <label>Billing Contract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Billing Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Contract</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Contract__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billing Contract</relationshipLabel>
    <relationshipName>Billing_Contract</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing_Contract__c/fields/Activation_Date__c.field-meta.xml
<CustomField>
    <fullName>Activation_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Activation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billing_Contract__c/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contract End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billing_Contract__c/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billing_Contract__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Billing Contract</relationshipLabel>
    <relationshipName>Billing_Contract</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/Billing_Contract_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Billing Contract Line Item</label>
    <nameField>
        <displayFormat>BL-{00000}</displayFormat>
        <label>Billing Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Activation_Required__c.field-meta.xml
<CustomField>
    <fullName>Activation_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Determined by the related Payment Terms</inlineHelpText>
    <label>Activation Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Activity_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Activity_Line_Item__c</fullName>
    <label>Activity Line Item</label>
    <referenceTo>Activity_Line_Item__c</referenceTo>
    <relationshipLabel>Billing Contract Line Items</relationshipLabel>
    <relationshipName>Billing_Contract_Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Billing_Contract__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contract__c</fullName>
    <description>Billing Contract line item detail for Billing Contract object</description>
    <label>Billing Contract</label>
    <referenceTo>Billing_Contract__c</referenceTo>
    <relationshipLabel>Billing Contract Line Items</relationshipLabel>
    <relationshipName>Billing_Contract_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Billing Contract Line Items</relationshipLabel>
    <relationshipName>Billing_Contract_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Payment_Term_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Term Line Item</label>
    <referenceTo>Payment_Term_Line_Item__c</referenceTo>
    <relationshipLabel>Billing Contract Line Items</relationshipLabel>
    <relationshipName>Billing_Contract_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Terms</label>
    <referenceTo>Payment_Terms__c</referenceTo>
    <relationshipLabel>Billing Contract Line Items</relationshipLabel>
    <relationshipName>Billing_Contract_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Billing Contract Line Items</relationshipLabel>
    <relationshipName>Billing_Contract_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Revenue_Category__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Category__c</fullName>
    <label>Revenue Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hosting and Support</fullName>
            </value>
            <value>
                <fullName>Services</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Subscription</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Term_Line_Item__c/Payment_Term_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Payment Term Line Item</label>
    <nameField>
        <displayFormat>PTL-{000000}</displayFormat>
        <label>Payment Term Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Term Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Term_Line_Item__c/fields/Offset_Measure__c.field-meta.xml
<CustomField>
    <fullName>Offset_Measure__c</fullName>
    <label>Offset Measure</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Days</fullName>
            </value>
            <value>
                <fullName>Months</fullName>
            </value>
            <value>
                <fullName>Years</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Term_Line_Item__c/fields/Offset_Units__c.field-meta.xml
<CustomField>
    <fullName>Offset_Units__c</fullName>
    <label>Offset Units</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Term_Line_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <inlineHelpText>The order in which the invoices will be created</inlineHelpText>
    <label>Order</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Term_Line_Item__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <referenceTo>Payment_Terms__c</referenceTo>
    <relationshipLabel>Payment Term Line Items</relationshipLabel>
    <relationshipName>Payment_Term_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Terms__c/Payment_Terms__c.object-meta.xml
<CustomObject>
    <description>Payment Terms Object that holds information on how billing a client should proceed based on specific invoicing requirements.</description>
    <label>Invoice Terms</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Payment Terms Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Terms__c/fields/Activation_Required__c.field-meta.xml
<CustomField>
    <fullName>Activation_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Activation required for invoicing</inlineHelpText>
    <label>Activation Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Terms__c/fields/Invoice_Split_Method__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Split_Method__c</fullName>
    <inlineHelpText>Pro-Rata: considers the activation date against the year end date  Equal: Equal Amounts across the number of invoices.</inlineHelpText>
    <label>Invoice Split Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Equal</fullName>
            </value>
            <value>
                <fullName>Percent Breakdown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AH_ActivityLineItem_Statics_Test.cls
/************************************************************************************************
Name            : AH_ActivityLineItem_Statics_Test
Author          : Sean Harris
Created Date    : 05/01/2019
Last Mod Date   : 05/01/2019
Last Mod By     : Sean Harris
NICC Reference  :
Description     : Test class for AH_ActivityLineItem_Statics
                :
*************************************************************************************************/
@isTest 
public class AH_ActivityLineItem_Statics_Test 
{

    // ======================================================================================================================================= 
    // = CREATE TEST DATA
    // ======================================================================================================================================= 
    @testSetup static void createTestData() 
    {
        
		system.debug(' *** START AH_ActivityLineItem_Statics_Test.createTestData() - QUERIES ISSUED = ' + Limits.getQueries());	
        
        Test.startTest();
        
        // CREATE A TEST ACCOUNT
        Account a = NI_TestClassData.createTestAccount(1);
        a.Name = 'APEX TEST AH_ActivityLineItem_Statics_Test ACCOUNT';
        a.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Property Account').getRecordTypeId();
        insert a;           
        
        // CREATE TEST PRODUCT GROUP RECORD
        Product_Group__c pgp = NI_TestClassData.createProductGroup(1, 'APEX TEST');
        insert pgp;        
        
        // CREATE TEST PRODUCT RECORD
        Product2 p2 = NI_TestClassData.createProduct2(1, pgp.Id, 'APEX-TEST-01', 'Subscription'); 
        p2.Product_Line__c = 'Delphi Single Property';
        p2.Revenue_Category__c = 'Services';
        p2.Unit__c = 'Subscription';
        p2.IsActive = true;
        p2.Description = 'APEX AH_ActivityLineItem_Statics_Test TEST';
        p2.Name = 'APEX AH_ActivityLineItem_Statics_Test TEST';
        p2.Duration_Months__c = 12;
        p2.Line__c = 'Delphi';
        p2.Edition__c = 'Enterprise';
        p2.Classification__c = 'TEST DATA';
        p2.Support_Classification__c = 'Gold';
        p2.Interface_Classification__c = 'PMS';
        p2.Corporate_Product_Group__c = 'Newmarket';        
        insert p2;        

        // CREATE TEST OPPORTUNITY RECORD
        Opportunity o = NI_TestClassData.createTestOpportunity(1, a.Id);
        o.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Non-HRM Opportunity').getRecordTypeId();
        o.Name = 'APEX TEST AH_ActivityLineItem_Statics_Test OPPORTUNITY';
        insert o;

        // CREATE SETTINGS RECORD (MANAGED)
        ffrr__Settings__c st = NI_TestClassData.createSettings();
        st.Name = 'APEX Activity Line Item';
        insert st;
        
        // CREATE TEMPLATE RECORD (MANAGED)
        ffrr__Template__c tp = NI_TestClassData.createffrrTemplate(st.Id);
        tp.Name = 'APEX TEST - Deliverable';
    	insert tp; 
        
        // CREATE TEST PAYMENT TERM
        Payment_Terms__c pt = NI_TestClassData.createInvoicePaymentTerms();
        pt.Name = '4 Installments';
        pt.Invoice_Split_Method__c = 'Equal';
        insert pt;
        
        // CREATE TEST PAYMENT TERM LINE ITEMS
        List<Payment_Term_Line_Item__c> lstPTLineItem = new List<Payment_Term_Line_Item__c>();
        
        Payment_Term_Line_Item__c ptLI1 = NI_TestClassData.createInvoicePaymentTermsLimeItem(pt.Id);
        ptLI1.Order__c = 1;
        ptLI1.Offset_Measure__c = 'Days';
        ptLI1.Offset_Units__c = 1;
        lstPTLineItem.add(ptLI1);
        
        Payment_Term_Line_Item__c ptLI2 = NI_TestClassData.createInvoicePaymentTermsLimeItem(pt.Id);
        ptLI2.Order__c = 2;
        ptLI2.Offset_Measure__c = 'Months';
        ptLI2.Offset_Units__c = 1;
        lstPTLineItem.add(ptLI2);
        
        Payment_Term_Line_Item__c ptLI3 = NI_TestClassData.createInvoicePaymentTermsLimeItem(pt.Id);
        ptLI3.Order__c = 3;
        ptLI3.Offset_Measure__c = 'Years';
        ptLI3.Offset_Units__c = 1;
        lstPTLineItem.add(ptLI3);
        
        Payment_Term_Line_Item__c ptLI4 = NI_TestClassData.createInvoicePaymentTermsLimeItem(pt.Id);
        ptLI3.Order__c = 4;
        lstPTLineItem.add(ptLI4);
        
        database.insert(lstPTLineItem); 

        // CREATE TEST BILLING CONTRACT RECORD
        Billing_Contract__c bc = NI_TestClassData.createBillingContract(10);
        bc.Account__c = a.Id;
        bc.Opportunity__c = o.Id;
        insert bc;

        // CREATE TEST ACTIVITY LINE ITEM RECORD
        Activity_Line_Item__c ali = NI_TestClassData.createActivityLineItem(bc.Id);
        ali.Activation_Date__c = Date.today();
        ali.Contract_Start_Date__c = Date.today().addMonths(1);
        ali.Contract_End_Date__c = Date.today().addMonths(2);
        ali.Product__c = p2.Id;
        ali.Payment_Terms__c = pt.Id;
        ali.Opp_Product_ID__c = p2.Id;
        ali.Activation_Required__c = true;
        ali.ffrrtemplate__c = tp.Id;
        ali.Contract_Amount__c = 1000; 
        ali.Units__c = 1;
        ali.Pro_Rated__c = false;
        ali.Revenue_Category__c = 'Support';
        //ali.Deployment_Instance__c = di.Id; 
        insert ali;

        List<Activity_Line_Item__c> lstALIAssert1 = new List<Activity_Line_Item__c>([SELECT Id 
                                                                                     FROM Activity_Line_Item__c
                                                                                     WHERE Revenue_Category__c IN ('Subscription', 'Support', 'Hosting and Support')
                                                                                     AND Pro_Rated__c = false 
                                                                                     AND Contract_Start_Date__c != null
                                                                                     AND Id =: ali.Id]);
        system.assertEquals(1, lstALIAssert1.size());		
        
        // CREATE TEST BILLING CONTRACT LINE ITEM RECORDS
        List<Billing_Contract_Line_Item__c> lstBCLIs = new List<Billing_Contract_Line_Item__c>();
        
        Billing_Contract_Line_Item__c blci1 = NI_TestClassData.createBillingContract(bc.Id, ali.Id);
        blci1.Split_Order__c = 1;
        blci1.Status__c = 'Active';
        blci1.Pro_Rated__c = true;
        lstBCLIs.add(blci1);
        
        Billing_Contract_Line_Item__c blci2 = NI_TestClassData.createBillingContract(bc.Id, ali.Id);
        blci2.Split_Order__c = 1;
        blci2.Status__c = 'Active';
        blci2.Activation_Required__c = true;
        blci2.Payment_Term_Line_Item__c = ptLI1.Id; 
        blci2.Pro_Rated__c = false;
        blci2.Revenue_Category__c = 'Support';
        lstBCLIs.add(blci2);
        
        Billing_Contract_Line_Item__c blci3 = NI_TestClassData.createBillingContract(bc.Id, ali.Id);
        blci3.Split_Order__c = 1;
        blci3.Status__c = 'Active';
        blci3.Activation_Required__c = true;
        blci3.Payment_Term_Line_Item__c = ptLI2.Id; 
        blci3.Pro_Rated__c = false;
        blci3.Revenue_Category__c = 'Hosting and Support';
        lstBCLIs.add(blci3);
        
        Billing_Contract_Line_Item__c blci4 = NI_TestClassData.createBillingContract(bc.Id, ali.Id);
        blci4.Split_Order__c = 1;
        blci4.Status__c = 'Active';
        blci4.Activation_Required__c = true;
        blci4.Payment_Term_Line_Item__c = ptLI3.Id; 
        blci4.Pro_Rated__c = false;
        blci4.Revenue_Category__c = 'Subscription'; 
        lstBCLIs.add(blci4);
         
        database.insert(lstBCLIs);
        
        Test.stopTest();
        
		system.debug(' ***  END  AH_ActivityLineItem_Statics_Test.createTestData() - QUERIES ISSUED = ' + Limits.getQueries());	
        
    }
   
    // ======================================================================================================================================= 
    // = TEST METHOD 1: 
    // ======================================================================================================================================= 
    @isTest static void test1() 
    {
		
		system.debug(' *** START AH_ActivityLineItem_Statics_Test.test1() - QUERIES ISSUED = ' + Limits.getQueries());	

        Product2 p2 = [SELECT Id FROM Product2 WHERE Name = 'APEX AH_ActivityLineItem_Statics_Test TEST'];
		Activity_Line_Item__c ali = [SELECT Id FROM Activity_Line_Item__c WHERE Product__c =: p2.Id];  
        
		Test.startTest();

        ali.Revenue_Category__c = 'Subscription';
        update ali;
        
		List<Billing_Contract_Line_Item__c> lstBLIAssert1 = new List<Billing_Contract_Line_Item__c>([SELECT Id FROM Billing_Contract_Line_Item__c WHERE Activity_Line_Item__c =: ali.Id]);
        system.assertEquals(4, lstBLIAssert1.size());        

        Test.stopTest();
        
		system.debug(' ***  END  AH_ActivityLineItem_Statics_Test.test1() - QUERIES ISSUED = ' + Limits.getQueries());	
        
    }
                
}