force-app/main/default/objects/Activity_Line_Item__c/Activity_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Activity Line Item</label>
    <nameField>
        <displayFormat>ACT-{00000}</displayFormat>
        <label>Activity Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Line Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity_Line_Item__c/fields/Activation_Required__c.field-meta.xml
<CustomField>
    <fullName>Activation_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activation Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Billing_Renewal_Lead_Time_Days__c.field-meta.xml
<CustomField>
    <fullName>Billing_Renewal_Lead_Time_Days__c</fullName>
    <inlineHelpText>Enter the lead time in number of days.  This will determine when billing items are eligible for invoicing and when renewals for this product should be processed.</inlineHelpText>
    <label>Billing / Renewal Lead Time (Days)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Contract_Amount__c.field-meta.xml
<CustomField>
    <fullName>Contract_Amount__c</fullName>
    <inlineHelpText>Sales Price from the Opp</inlineHelpText>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Activity End / Delivered Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Activity Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Contract_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Contract_Total_Amount__c</fullName>
    <formula>Contract_Amount__c * Units__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <label>Origin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Order</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Clone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Terms</label>
    <referenceTo>Payment_Terms__c</referenceTo>
    <relationshipLabel>Activity Line Item</relationshipLabel>
    <relationshipName>Activity_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Percent_of_Total__c.field-meta.xml
<CustomField>
    <fullName>Percent_of_Total__c</fullName>
    <formula>Fair_Value__c / Billing_Contract__r.Total_Fair_Value__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Fair Value / Total Fair Value</inlineHelpText>
    <label>Percent of Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Previous_ALI__c.field-meta.xml
<CustomField>
    <fullName>Previous_ALI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Link to the previous Activity Line that was used to create the renewal</inlineHelpText>
    <label>Previous ALI</label>
    <referenceTo>Activity_Line_Item__c</referenceTo>
    <relationshipLabel>Activity Line Item</relationshipLabel>
    <relationshipName>Activity_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Rev_Rec_BC_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Renewal_Base_Price__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Base_Price__c</fullName>
    <label>Renewal Base Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This is the date that renewals will be processed.</inlineHelpText>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Renewal_Increase_Amount__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Increase_Amount__c</fullName>
    <inlineHelpText>Represents the total difference between the current Activity Line Item and the previous Activity Line Item</inlineHelpText>
    <label>Renewal Increase Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Revenue_Recognized_to_Date__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Recognized_to_Date__c</fullName>
    <label>Revenue Recognized to Date</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Units__c.field-meta.xml
<CustomField>
    <fullName>Units__c</fullName>
    <description>NICC-035500 - Changed Decimal Places</description>
    <label>Units</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billing_Contract__c/Billing_Contract__c.object-meta.xml
<CustomObject>
    <label>Billing Contract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Billing Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Contract</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Contract__c/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contract End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billing_Contract__c/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/Billing_Contract_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Billing Contract Line Item</label>
    <nameField>
        <displayFormat>BL-{00000}</displayFormat>
        <label>Billing Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Activation_Required__c.field-meta.xml
<CustomField>
    <fullName>Activation_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Determined by the related Payment Terms</inlineHelpText>
    <label>Activation Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Activity_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Activity_Line_Item__c</fullName>
    <label>Activity Line Item</label>
    <referenceTo>Activity_Line_Item__c</referenceTo>
    <relationshipLabel>Billing Contract Line Items</relationshipLabel>
    <relationshipName>Billing_Contract_Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Terms</label>
    <referenceTo>Payment_Terms__c</referenceTo>
    <relationshipLabel>Billing Contract Line Items</relationshipLabel>
    <relationshipName>Billing_Contract_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Billing Contract Line Items</relationshipLabel>
    <relationshipName>Billing_Contract_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Term_Line_Item__c/Payment_Term_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Payment Term Line Item</label>
    <nameField>
        <displayFormat>PTL-{000000}</displayFormat>
        <label>Payment Term Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Term Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Term_Line_Item__c/fields/Invoice_Line_Description__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Line_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Standard Language that will be defaulted to the Billing Line item description</inlineHelpText>
    <label>Invoice Line Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Term_Line_Item__c/fields/Offset_Measure__c.field-meta.xml
<CustomField>
    <fullName>Offset_Measure__c</fullName>
    <label>Offset Measure</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Days</fullName>
            </value>
            <value>
                <fullName>Months</fullName>
            </value>
            <value>
                <fullName>Years</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Term_Line_Item__c/fields/Offset_Units__c.field-meta.xml
<CustomField>
    <fullName>Offset_Units__c</fullName>
    <label>Offset Units</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Term_Line_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <inlineHelpText>The order in which the invoices will be created</inlineHelpText>
    <label>Order</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Term_Line_Item__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <referenceTo>Payment_Terms__c</referenceTo>
    <relationshipLabel>Payment Term Line Items</relationshipLabel>
    <relationshipName>Payment_Term_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Term_Line_Item__c/fields/Percent_of_Total__c.field-meta.xml
<CustomField>
    <fullName>Percent_of_Total__c</fullName>
    <label>Percent of Total</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Payment_Terms__c/Payment_Terms__c.object-meta.xml
<CustomObject>
    <description>Payment Terms Object that holds information on how billing a client should proceed based on specific invoicing requirements.</description>
    <label>Invoice Terms</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Payment Terms Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Terms__c/fields/Activation_Required__c.field-meta.xml
<CustomField>
    <fullName>Activation_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Activation required for invoicing</inlineHelpText>
    <label>Activation Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Terms__c/fields/Bill_if_Activation_Date_comes_first__c.field-meta.xml
<CustomField>
    <fullName>Bill_if_Activation_Date_comes_first__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bill if Activation Date comes first?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Terms__c/fields/Billed_through_PSA__c.field-meta.xml
<CustomField>
    <fullName>Billed_through_PSA__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If true, then billing will occur from PSA Billing Events.</inlineHelpText>
    <label>Billed through PSA?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Terms__c/fields/Invoice_Split_Method__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Split_Method__c</fullName>
    <inlineHelpText>Pro-Rata: considers the activation date against the year end date  Equal: Equal Amounts across the number of invoices.</inlineHelpText>
    <label>Invoice Split Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Equal</fullName>
            </value>
            <value>
                <fullName>Percent Breakdown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Terms__c/fields/Offset_Date__c.field-meta.xml
<CustomField>
    <fullName>Offset_Date__c</fullName>
    <label>Offset Date</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Effective Date</fullName>
            </value>
            <value>
                <fullName>Activation Date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/billingContractRenewalHandler.cls
/************************************************************************************************
Name            : billingContractRenewalHandler Class
Author          : Sean Harris
Created Date    : 04/04/2016
Last Mod Date   : 08/31/2018 
Last Mod By     : Sean Harris
NICC Reference  :
Description     : Contains various methods for interacting with Billing Contracts
                : Updated 08/31/2018 per NICC-029803
                :
*************************************************************************************************/
public class billingContractRenewalHandler 
{

	// =========================================================================================
	//  Method to Process Renewals for Activity Lines
	// =========================================================================================
	public static void processBCRenewals(List<manageBillingContractRenewalController.aliWrapper> wrapperList)
	{
        
        List<Activity_Line_Item__c> aliInsertList = new List<Activity_Line_Item__c>();
        List<Activity_Line_Item__c> aliUpdateList = new List<Activity_Line_Item__c>();
        List<Billing_Contract_Line_Item__c> bliInsertList = new List<Billing_Contract_Line_Item__c>();
        Set<String> revenueCategoriesToApply = new Set<String>{'Support', 'Hosting and Support', 'Subscription'};
        
        Map<Id, Payment_Terms__c> pmtTermsMap = new Map<Id, Payment_Terms__c>([
            SELECT Id, Offset_Date__c, Activation_Required__c, Invoice_Split_Method__c, Billed_through_PSA__c, Bill_if_Activation_Date_comes_first__c,
            (SELECT Id, Order__c, Offset_Measure__c, Offset_Units__c, Percent_of_Total__c, Invoice_Line_Description__c
             FROM Payment_Term_Line_Items__r
             ORDER BY Order__c)
            FROM Payment_Terms__c]);

		// STEP 1: CREATE THE NEW ACTIVITY LINE ITEM BASED ON THE ONES IN THE WRAPPER
		for (manageBillingContractRenewalController.aliWrapper wrapper : wrapperList)
		{
			Activity_Line_Item__c newAli = wrapper.ali_object.clone(false, true, false, false);
			newAli.Contract_Start_Date__c = wrapper.ali_object.Contract_End_Date__c.addDays(1);
			newAli.Contract_End_Date__c = newAli.Contract_Start_Date__c.addMonths(wrapper.ali_object.Product__r.Duration_Months__c.intValue()).addDays(-1);
			newAli.Contract_Amount__c = wrapper.renewalAmount;
			newAli.Revenue_Recognized_to_Date__c = 0;
			newAli.Renewal_Base_Price__c = wrapper.renewalAmount;
			newAli.Renewal_Date__c = newAli.Contract_End_Date__c.addDays((wrapper.ali_object.Billing_Renewal_Lead_Time_Days__c * -1).intvalue());
			newAli.Units__c = wrapper.dummy_ali_object.Units__c;
			newAli.Origin__c = 'Renewal';
			newAli.Previous_ALI__c = wrapper.ali_object.id;
			newAli.Renewal_Increase_Amount__c = (wrapper.renewalAmount * wrapper.dummy_ali_object.Units__c) - wrapper.ali_object.Contract_Total_Amount__c;
			newAli.Origin__c = 'Renewal';
			newAli.Payment_Terms__c = wrapper.dummy_ali_object.Payment_Terms__c;
			newAli.Delivery_Offset_Months__c = null;
			newAli.Billing_Contract__c = wrapper.dummy_ali_object.Billing_Contract__c;
            newAli.Billing_Renewal_Lead_Time_Days__c = wrapper.ali_object.Billing_Renewal_Lead_Time_Days__c;
            newAli.Pro_Rated__c = false;
			newAli.Revenue_Category__c = wrapper.ali_object.Revenue_Category__c;
			aliInsertList.add(newAli);
			aliUpdateList.add(wrapper.ali_object);
		}
        
		insert aliInsertList;

		// STEP 2: CREATE THE NECESSARY BILLING LINES.
		for (Activity_Line_Item__c ali : aliInsertList)
        {
            
			Payment_Terms__c pmtTerms = pmtTermsMap.containsKey(ali.Payment_Terms__c) ? pmtTermsMap.get(ali.Payment_Terms__c) : null;

			Integer numberOfInvoicesToCreate = pmtTerms.Payment_Term_Line_Items__r.size();
			
			//Date invoiceDate = ali.Contract_Start_Date__c;
			//Date invoiceStartDate = ali.Contract_Start_Date__c;
            
            Date Contract_Start_Date = ali.Contract_Start_Date__c;
            Integer lead_Time = Integer.valueOf(ali.Billing_Renewal_Lead_Time_Days__c);
			Date invoiceDate = Contract_Start_Date.addDays(-lead_Time); 
            Date invoiceStartDate = invoiceDate;
            
			if (pmtTerms.Billed_through_PSA__c == true)
			{
				continue;	// do not create a billing contract line item since it will be invoiced out of psa
			}

			if (numberOfInvoicesToCreate == 1)
            {
				Billing_Contract_Line_Item__c bcli = new Billing_Contract_Line_Item__c();
				bcli.Invoice_Date__c = invoiceDate;
				bcli.Product__c = ali.Product__c;
				bcli.Billing_Contract__c = ali.Billing_Contract__c;
				bcli.Revenue_Category__c = ali.Revenue_Category__c;
				bcli.Opportunity__c = ali.Opportunity__c;
				bcli.Quantity__c = ali.Units__c;
				bcli.Unit_Price__c = ali.Contract_Amount__c;
				bcli.Total_Amount__c = ali.Contract_Amount__c * ali.Units__c;
				bcli.Payment_Terms__c = ali.Payment_Terms__c;
				bcli.Activation_Required__c = ali.Activation_Required__c;
				bcli.Deployment_Instance__c = ali.Deployment_Instance__c;
				bcli.Activity_Line_Item__c = ali.id;
                
				if (revenueCategoriesToApply.contains(bcli.Revenue_Category__c) && ali.Contract_Start_Date__c != null && ali.Contract_End_Date__c != null)
                {
					bcli.Line_Item_Description__c = bcli.Revenue_Category__c + ' - Start: ' + ali.Contract_Start_Date__c.format() + ' End: ' + ali.Contract_End_Date__c.format();
				}
                
				bliInsertList.add(bcli);
			}

			// NOTE PRO-RATA CALCULATIONS DO NOT APPLY FOR RENEWALS
			
			if (numberOfInvoicesToCreate > 1)
			{
                
				system.debug(' *** billingContractRenewalHandler - processBCRenewals - ENTER > 1 ***');
				Integer invoicesCreated = 0;

/*              
NICC-029803 (START)
                Map<Decimal, Decimal> invoiceAmountMap = new Map<Decimal, Decimal>();
                for (Payment_Term_Line_Item__c pmtLine : pmtTerms.Payment_Term_Line_Items__r) // populate the invoice amount map based on the order
                {
                    Decimal invoiceAmount;
                    if (pmtTerms.Invoice_Split_Method__c == 'Equal')
                    {
                        invoiceAmount = (((ali.Contract_Amount__c * ali.Units__c) / numberOfInvoicesToCreate)).setscale(2);
                        invoiceAmountMap.put(pmtLine.Order__c, invoiceAmount);
                    }
                    if (pmtTerms.Invoice_Split_Method__c == 'Percent Breakdown')
                    {
                        invoiceAmount = ((ali.Contract_Amount__c * ali.Units__c) * (pmtLine.Percent_of_Total__c/100)).setscale(2);
                        invoiceAmountMap.put(pmtLine.Order__c, invoiceAmount);
                    }
                }
NICC-029803 (END)
*/

                // NICC-029803 (START)
                Map<Decimal, Decimal> invoiceAmountMap = new Map<Decimal, Decimal>();
                Map<Decimal, Decimal> invoiceUnitPriceMap = new Map<Decimal, Decimal>();
                for (Payment_Term_Line_Item__c pmtLine : pmtTerms.Payment_Term_Line_Items__r) // populate the invoice amount map based on the order
                {
                    Decimal invoiceAmount;
                    Decimal unitPrice;
                    if (pmtTerms.Invoice_Split_Method__c == 'Equal')
                    {
                        invoiceAmount = (((ali.Contract_Amount__c * ali.Units__c) / numberOfInvoicesToCreate)).setscale(2);
                        unitPrice = (ali.Contract_Amount__c / numberOfInvoicesToCreate).setscale(2);
                        invoiceAmountMap.put(pmtLine.Order__c, invoiceAmount);
                        invoiceUnitPriceMap.put(pmtLine.Order__c, unitPrice);
                    }
                    if (pmtTerms.Invoice_Split_Method__c == 'Percent Breakdown')
                    {
                        invoiceAmount = ((ali.Contract_Amount__c * ali.Units__c) * (pmtLine.Percent_of_Total__c / 100)).setscale(2);
                        unitPrice = (ali.Contract_Amount__c * (pmtLine.Percent_of_Total__c / 100)).setscale(2);
                        invoiceAmountMap.put(pmtLine.Order__c, invoiceAmount);
                        invoiceUnitPriceMap.put(pmtLine.Order__c, unitPrice);
                    }
                }
                // NICC-029803 (END)

				Decimal billingLinesTotal = 0; // this will store the summed amount, we may need to adjust this for rounding
				Decimal roundingAdjustment = 0;
			
				for (Payment_Term_Line_Item__c pmtLine : pmtTerms.Payment_Term_Line_Items__r)
				{
					if (invoicesCreated != 0) // if this is not the first item in the list, then add months / days / years
					{
						if (pmtLine.Offset_Measure__c == 'Days' && pmtLine.Offset_Units__c != 0 && pmtLine.Offset_Units__c != null)
                        {
							invoiceDate = invoiceStartDate.addDays(pmtLine.Offset_Units__c.intValue());
						}
						if (pmtLine.Offset_Measure__c == 'Months' && pmtLine.Offset_Units__c != 0 && pmtLine.Offset_Units__c != null)
                        {
							invoiceDate = invoiceStartDate.addMonths(pmtLine.Offset_Units__c.intValue());
						}
						if (pmtLine.Offset_Measure__c == 'Years' && pmtLine.Offset_Units__c != 0 && pmtLine.Offset_Units__c != null)
                        {
							invoiceDate = invoiceStartDate.addYears(pmtLine.Offset_Units__c.intValue());
						}
					}
                    
					String lineDescription = pmtLine.Invoice_Line_Description__c != null ? pmtLine.Invoice_Line_Description__c : null;

					Billing_Contract_Line_Item__c bcli = new Billing_Contract_Line_Item__c();
					bcli.Invoice_Date__c = invoiceDate;
					bcli.Product__c = ali.Product__c;
					bcli.Billing_Contract__c = ali.Billing_Contract__c;
					bcli.Revenue_Category__c = ali.Revenue_Category__c;
					bcli.Payment_Term_Line_Item__c = pmtLine.id;
					bcli.Quantity__c = ali.Units__c;
                    // NICC-029803 (START)
                    //bcli.Unit_Price__c = invoiceAmountMap.get(pmtLine.Order__c);
                    //bcli.Total_Amount__c = invoiceAmountMap.get(pmtLine.Order__c);
                    bcli.Unit_Price__c = invoiceUnitPriceMap.get(pmtLine.Order__c).setScale(2);
                    bcli.Total_Amount__c = invoiceAmountMap.get(pmtLine.Order__c).setScale(2);
                    // NICC-029803 (END)
					bcli.Payment_Terms__c = ali.Payment_Terms__c;
					bcli.Activation_Required__c = ali.Activation_Required__c;
					bcli.Deployment_Instance__c = ali.Deployment_Instance__c;
					bcli.Activity_Line_Item__c = ali.id;
					bcli.Line_Item_Description__c = lineDescription;
                    
					if (bcli.Line_Item_Description__c == null || bcli.Line_Item_Description__c == '')
                    {
						if (revenueCategoriesToApply.contains(bcli.Revenue_Category__c) && ali.Contract_Start_Date__c != null && ali.Contract_End_Date__c != null)
                        {
							bcli.Line_Item_Description__c = bcli.Revenue_Category__c + ' - Start: ' + ali.Contract_Start_Date__c.format() + ' End: ' + ali.Contract_End_Date__c.format();
						}
					}

					billingLinesTotal += bcli.Total_Amount__c; 		// keep track of the total amount being applied to the lines

					invoicesCreated ++;
					if (invoicesCreated == numberOfInvoicesToCreate) //	this is the last item to create so account for any rounding.
					{
						roundingAdjustment = ali.Contract_Amount__c * ali.Units__c - billingLinesTotal;
						system.debug(' *** billingContractRenewalHandler - processBCRenewals - ENTER PAYMENT SPLIT - ROUNDING ADJUSTMENT *****');
						bcli.Unit_Price__c += roundingAdjustment;
						bcli.Total_Amount__c += roundingAdjustment;
						system.debug(' *** billingContractRenewalHandler - processBCRenewals - ENTER PAYMENT SPLIT - billingLinesTotal = ' + billingLinesTotal);
						system.debug(' *** billingContractRenewalHandler - processBCRenewals - ENTER PAYMENT SPLIT - ali.Contract_Amount__c * ali.Units__c = ' + ali.Contract_Amount__c * ali.Units__c);
						system.debug(' *** billingContractRenewalHandler - processBCRenewals - ENTER PAYMENT SPLIT - ROUNDING ADJUSTMENT = ' + roundingAdjustment);

					}
					bliInsertList.add(bcli);
					system.debug(' *** billingContractRenewalHandler - processBCRenewals - invoicesCreated = ' + invoicesCreated);
				}
			}
		}
        
		insert bliInsertList;
        
//		activityLineTriggerHandler.updateBillingLineDescriptions(aliInsertList);	// NICC-029729
		AH_ActivityLineItem_Statics.updateBillingLineDescriptions(aliInsertList);	// NICC-029729
        
		// STEP 3: UPDATE ANY ACTIVITY LINES THAT HAVE BEEN RENEWED AND INSERT NEW RECORDS
		for (Activity_Line_Item__c ali : aliUpdateList)
        {
			ali.Renewal_Processed__c = true;
		}
        
		update aliUpdateList;
        
	}
    
}