force-app/main/default/objects/Activity_Line_Item__c/Activity_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Activity Line Item</label>
    <nameField>
        <displayFormat>ACT-{00000}</displayFormat>
        <label>Activity Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Line Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity_Line_Item__c/fields/Softrax_Asset__c.field-meta.xml
<CustomField>
    <fullName>Softrax_Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Softrax Asset</label>
    <referenceTo>Softrax_Asset__c</referenceTo>
    <relationshipLabel>Activity Line Item</relationshipLabel>
    <relationshipName>Activity_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Org_Details__c/NI_Org_Details__c.object-meta.xml
<CustomObject>
    <description>Holds Org/Account specific details such as subscription connection credentials.</description>
    <label>NI Org Details</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Org Details ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Org Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_Org_Details_to_Accounts__c/NI_Org_Details_to_Accounts__c.object-meta.xml
<CustomObject>
    <description>Junction Object between NI Org Details and Account</description>
    <label>NI Org Details to Accounts</label>
    <nameField>
        <displayFormat>OD-{000000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NI Org Details to Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_Org_Details_to_Accounts__c/fields/AccountID__c.field-meta.xml
<CustomField>
    <fullName>AccountID__c</fullName>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Organization Details</relationshipLabel>
    <relationshipName>NI_Org_Details_to_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/NI_Org_Details_to_Accounts__c/fields/NIOrgDetailsID__c.field-meta.xml
<CustomField>
    <fullName>NIOrgDetailsID__c</fullName>
    <label>NI Org Details</label>
    <referenceTo>NI_Org_Details__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>NI_Org_Details_to_Accounts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/PollingResult__c/PollingResult__c.object-meta.xml
<CustomObject>
    <description>Salesforce.com Change Request: NICC-006221

Used for the HRM Monitoring Tools. Monitor how our customers are using the HRM application and whether there are any issues in their deployments, such as storage overage, etc.</description>
    <label>Polling Result</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Polling Result Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Polling Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PollingResult__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <complianceGroup>Normal</complianceGroup>
    <label>NI Org</label>
    <referenceTo>NI_Org_Details__c</referenceTo>
    <relationshipLabel>Polling Results</relationshipLabel>
    <relationshipName>Polling_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SFDC_CSP_Flash_Message__c/SFDC_CSP_Flash_Message__c.object-meta.xml
<CustomObject>
    <description>SFDC Customer Service Project</description>
    <label>Flash Message</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Flash Message</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flash Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Softrax_Asset__c/Softrax_Asset__c.object-meta.xml
<CustomObject>
    <label>Softrax Asset</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Sku</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Softrax Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Softrax_Asset__c/fields/Activity_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Activity_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity Line Item</label>
    <referenceTo>Activity_Line_Item__c</referenceTo>
    <relationshipLabel>Softrax Assets</relationshipLabel>
    <relationshipName>Softrax_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NI_ThreeSixtyViewController_Test.cls
/****************************************************************************************
Name            : NI_ThreeSixtyViewController_Test Test Class
Author          : Suzanne LeDuc
Created Date    : 4/8/2013
Last Mod Date   : 7/30/2013
Last Mod By     : Stuart Emery
NICC Reference  : NICC-006873
Description     : test Class for NI_ThreeSixtyViewController Class
                : Create a custom Visualforce Page that will show on a consolidated 
                : screen the open activities, cases, projects, opportunities etc for an 
                : account as well as information on their Org Details
                : 
******************************************************************************************/

public class NI_ThreeSixtyViewController_Test {

    public static testMethod void NI_ThreeSixtyViewController_Test() {
        PageReference pageRef = Page.View360;
        Test.setCurrentPage(pageRef);
      
        // Add parameters to page URL
        Account testAccount = NI_TestClassData.createTestAccount(1);
        insert testAccount;
        
        Id rtInit = NI_TestClassData.getRecordTypeId('NI_Org_Details__c', 'LOD Support Admin');
       
       
        NI_Org_Details__c od = NI_TestClassData.createTestNiOrgDetails(rtInit, 1, 'Salesforce Production');
        insert od;
        
        NI_Org_Details_to_Accounts__c orgDetailAccount = new NI_Org_Details_to_Accounts__c();
        orgDetailAccount.AccountID__c = testAccount.Id;
        orgDetailAccount.NIOrgDetailsID__c = od.Id;
        insert orgDetailAccount;
           
       
        ApexPages.currentPage().getParameters().put('accId', testAccount.Id);
      
        // Instantiate a new controller with all parameters in the page
        NI_ThreeSixtyViewController controller = new NI_ThreeSixtyViewController();
        Report caseReport = controller.getCasebyProduct();
        Report caseStatusReport = controller.getCasebyStatus();
        Report projectStatusReport = controller.getProjectStatus();
        Report OrgStatReport = controller.getOrgStats();
        Report orgUsageReport = controller.getOrgUsage();
        NI_Org_Details__c orgDetails = controller.getNiOrgDetails();
        List<PollingResult__c> pResults = controller.getpResults();
        //List<Softrax_Asset__c> assets = controller.getsAssets();
        List<Activity_Line_Item__c> actLines = controller.getActLineItems();
        List<SFDC_CSP_Flash_Message__c> messages = controller.getMessages();
        Account acct = controller.getAccount();
        List<Opportunity> opps = controller.getOpportunities();
        List<Task> tasks = controller.getTasks();
        List<Case> cases = controller.getCases();
        List<pse__Proj__c> projects = controller.getProjects();
        List<Asset> otherAssets = controller.getAssets();
      
    }
    }