force-app/main/default/objects/Activity_Line_Item__c/Activity_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Activity Line Item</label>
    <nameField>
        <displayFormat>ACT-{00000}</displayFormat>
        <label>Activity Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Line Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity_Line_Item__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Activity Line Item</relationshipLabel>
    <relationshipName>Activity_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Billing_Contract__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contract__c</fullName>
    <description>Revenue Recognition line detail on Billing Contract Object</description>
    <label>Billing Contract</label>
    <referenceTo>Billing_Contract__c</referenceTo>
    <relationshipLabel>Activity Line Items</relationshipLabel>
    <relationshipName>Rev_Rec_BC_Line_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Cancel_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Cancel_Line_Item__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to indicate that an Activity Line Item record should be cancelled.  This field was originally created for the Contracts Team to indicate which Activity Line Items should be cancelled when processing Opportunities.</description>
    <inlineHelpText>This field is used to indicate that an Activity Line Item record should be cancelled.  This field was originally created for the Contracts Team to indicate which Activity Line Items should be cancelled when processing Opportunities.</inlineHelpText>
    <label>Flagged For Cancellation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Activity End / Delivered Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Activity Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Contract_Total_Amount_Currency__c.field-meta.xml
<CustomField>
    <fullName>Contract_Total_Amount_Currency__c</fullName>
    <formula>Contract_Total_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Flagged_For_Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Flagged_For_Cancellation_Reason__c</fullName>
    <description>The reason that the &quot;Flagged for Cancellation&quot; check box has been checked.  This field is required if the &quot;Flagged for Cancellation&quot; check box is checked.</description>
    <inlineHelpText>The reason that the &quot;Flagged for Cancellation&quot; check box has been checked.  This field is required if the &quot;Flagged for Cancellation&quot; check box is checked.</inlineHelpText>
    <label>Flagged For Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cancellation_Reason</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Flagged_For_Cancellation_Record__c.field-meta.xml
<CustomField>
    <fullName>Flagged_For_Cancellation_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>NICC-023634</description>
    <label>Flagged For Cancellation Record</label>
    <referenceTo>NI_Cancellation__c</referenceTo>
    <relationshipLabel>Activity Line Item</relationshipLabel>
    <relationshipName>Activity_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Rev_Rec_BC_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/SKU__c.field-meta.xml
<CustomField>
    <fullName>SKU__c</fullName>
    <formula>Product__r.ProductCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Product Code</inlineHelpText>
    <label>SKU</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Units__c.field-meta.xml
<CustomField>
    <fullName>Units__c</fullName>
    <description>NICC-035500 - Changed Decimal Places</description>
    <label>Units</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billing_Contract__c/Billing_Contract__c.object-meta.xml
<CustomObject>
    <label>Billing Contract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Billing Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Contract</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Contract__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billing Contract</relationshipLabel>
    <relationshipName>Billing_Contract</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing_Contract__c/fields/Contract_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_End_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contract End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billing_Contract__c/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NI_Cancellation__c/NI_Cancellation__c.object-meta.xml
<CustomObject>
    <label>Cancellation</label>
    <nameField>
        <displayFormat>CXL-{00000}</displayFormat>
        <label>Cancellation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cancellations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_Cancellation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account related to the Deployment Instance. This field is automatically updated based on the Deployment Instance and cannot be edited manually.</description>
    <inlineHelpText>Account related to the Deployment Instance. This field is automatically updated based on the Deployment Instance and cannot be edited manually.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>NI_Cancellations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Cancellation__c/fields/Activity_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Activity_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Activity Line Item related to the Deployment Instance that is being cancelled</description>
    <label>Activity Line Item</label>
    <referenceTo>Activity_Line_Item__c</referenceTo>
    <relationshipLabel>Cancellations</relationshipLabel>
    <relationshipName>Cancellations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Cancellation__c/fields/Product2__c.field-meta.xml
<CustomField>
    <fullName>Product2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Cancellations</relationshipLabel>
    <relationshipName>Cancellations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Cancellation__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Product Name of the Deployment Instance</description>
    <formula>Deployment_Instance__r.Product2.Name</formula>
    <inlineHelpText>Product Name of the Deployment Instance</inlineHelpText>
    <label>Product</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_Cancellation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>User Error</fullName>
            </value>
            <value>
                <fullName>Pending Retention</fullName>
                <default>true</default>
                <label>Pending Retention</label>
            </value>
            <value>
                <fullName>Flagged to be Cancelled</fullName>
            </value>
            <value>
                <fullName>Successfully Retained</fullName>
            </value>
            <value>
                <fullName>Late Cancellation Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Cancellation_Reason.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Billing Contract Re-Negotiated / Moved to Bundle Pricing</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Exit (Leaving all together)</fullName>
    </customValue>
    <customValue>
        <fullName>Extract / Append</fullName>
    </customValue>
    <customValue>
        <fullName>Product Replacement/Swap</fullName>
    </customValue>
    <customValue>
        <fullName>Upgrade /Migration</fullName>
    </customValue>
    <customValue>
        <fullName>User Reduction</fullName>
    </customValue>
    <description>Used for pick lists that contain the reasons that customers are cancelling</description>
    <masterLabel>Cancellation Reason</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AH_ActivityLineItemCancExt.cls
/****************************************************************************************
Name            : AH_ActivityLineItemCancExt Class
Author          : Ria Chawla
Created Date    : 08/03/2017
Last Mod Date   : 08/08/2017
Last Mod By     : Ria Chawla
NICC Reference  : 
Description     : Controller for the AH_ActivityLineItemsCancView Visualforce page 
                : The AH_ActivityLineItemsCancView page is used by the Contracts Team 
                : to identify Activity Line Items that need to be cancelled as part of the 
                : related Cancellation record. 
******************************************************************************************/
public class AH_ActivityLineItemCancExt 
{
    
    private NI_Cancellation__c cancObj;
    
    // USED TO ENABLE OR DISABLE THE CANCEL CHECKBOX ON THE VF PAGE  
    public Boolean bDisabled {get; set;}
    
    // WRAPPER CLASS LIST TO HOLD THE ACTIVITY LINE ITEMS
    public List<actLineItemWrapper> lstActLineItems {get; set;}
    
    public AH_ActivityLineItemCancExt(ApexPages.StandardController stdController)
    {     
        NI_Cancellation__c cn = (NI_Cancellation__c)stdController.getRecord();
        this.cancObj = [SELECT Id, Account__c, Product2__c FROM NI_Cancellation__c WHERE Id =: cn.Id];
        // CALL THE METHODS TO POPULATE THE LISTS
        disableListEdit();      
        //EnableListEdit();
    } 
    
    //METHOD TO POPULATE A PICKLIST WITH THE VALUES FROM THE FLAGGED FOR CANCELLATION REASON FIELD.  ADDED BY STUART EMERY ON 5/17/2017
    public List<SelectOption> getFlaggForCancellationReasonOptionList(){
        List<SelectOption> selOptionLst = new List<SelectOption>();
        Schema.DescribeFieldResult al = Activity_Line_Item__c.Flagged_For_Cancellation_Reason__c.getDescribe();
        List<Schema.PickListEntry> reasonList = al.getPickListValues();
        selOptionLst.add(new SelectOption('','--None--'));
        for(Schema.PickListEntry obj:reasonList){
            selOptionLst.add(new SelectOption(obj.getLabel(),obj.getValue()));
        }
        return selOptionLst;
    }
    
    public void disableListEdit()
    {
        bDisabled = true;
        getActivityLineItems(); 
    }
    
    public void EnableListEdit()
    {
        bDisabled = false;
        getActivityLineItems();
    }
    
    // QUERY TO RETURN A LIST OF ACTIVITY LINE ITEMS
    public List<actLineItemWrapper> getActivityLineItems() 
    {
        
        lstActLineItems = new List<actLineItemWrapper>();
        
        for (Activity_Line_Item__c ali : 
             [SELECT Id, Name, Cancel_Line_Item__c, SKU__c, Product__r.Name, Contract_Start_Date__c, Contract_End_Date__c, Units__c, Status__c, 
              Contract_Total_Amount_Currency__c, Flagged_For_Cancellation_Reason__c, Flagged_For_Cancellation_Record__c,
              Billing_Contract__c, Product__c
              FROM Activity_Line_Item__c 
              WHERE Billing_Contract__r.Account__c =: cancObj.Account__c 
              AND Product__c =: cancObj.Product2__c
              AND Status__c = 'Active' 
              ORDER BY Product_Description__c]) 
        {
            system.debug('ali'+ali);
            lstActLineItems.add(new actLineItemWrapper(ali));
        }   
        
        return lstActLineItems;
        
    } 
    
    public PageReference saveSelected() 
    {        
        
        // LIST OF ACTIVITY LINE ITEMS THAT WILL BE POPULATED WITH ONLY THE SELECTED ACTIVITY LINE ITEMS
        List<Activity_Line_Item__c> lstSelectedLineItems = new List<Activity_Line_Item__c>();

        Set<Id> selBillingContractIdSet = new Set<Id>();
        Set<Id> selProductIdSet = new Set<Id>();
        
        /* COMMENTED THIS FUNCTIONALITY PER HEATHER'S REQUEST 
        //Set<Id> nonselBillingContractIdSet = new Set<Id>();
        //Set<Id> nonselProductIdSet = new Set<Id>();
        List<c2g__codaInvoiceLineItem__c> selSalesInvLineItemList = new List<c2g__codaInvoiceLineItem__c>();
        //List<c2g__codaInvoiceLineItem__c> nonSelsalesInvLineItemList = new List<c2g__codaInvoiceLineItem__c>();
        List<c2g__codaInvoiceLineItem__c> salesInvLineItemToUpdate = new List<c2g__codaInvoiceLineItem__c>();
        Map<String, c2g__codaInvoiceLineItem__c> mapInvLineItem = new Map<String, c2g__codaInvoiceLineItem__c>();
        */
        
        // LIST OF ACTIVITY LINE ITEMS THAT WILL BE POPULATED WITH ONLY THE NON-SELECTED ACTIVITY LINE ITEMS
        List<Activity_Line_Item__c> lstNonSelectedLineItems = new List<Activity_Line_Item__c>();  
        
        // LIST OF SELECTED ACTIVITY LINE ITEMS TO UPDATE  
        List<Activity_Line_Item__c> lstActLineItemsToUpdate = new List<Activity_Line_Item__c>();
        
        // LOOP THROUGH OUR lstActLineItems LIST TO SEE IF THE SELECTED PROPERTY IS SET TO TRUE AND ADD THE RECORD TO THE lstSelectedAssets LIST OR THE lstNonSelectedLineItems LIST
        for (actLineItemWrapper li : lstActLineItems) 
        {   
            if (li.isSelected == true) 
            {         
                lstSelectedLineItems.add(li.ali);
            }
            else
            {
                lstNonSelectedLineItems.add(li.ali);
                //selBillingContractIdSet.add(li.ali.Billing_Contract__c);
                //selProductIdSet.add(li.ali.Product__c);
            } 
            
            selBillingContractIdSet.add(li.ali.Billing_Contract__c);
            selProductIdSet.add(li.ali.Product__c);
        }  
        
        /* COMMENTED THIS FUNCTIONALITY PER HEATHER'S REQUEST 
        system.debug('selBillingContractIdSet'+selBillingContractIdSet);
        system.debug('selProductIdSet'+selProductIdSet);
        if (selBillingContractIdSet.size() > 0 || selProductIdSet.size() > 0)
        {
            selSalesInvLineItemList = [SELECT Id, Name, Activity_Line_Item__c, c2g__Invoice__c, c2g__Product__c,
                                       Billing_Contract__c FROM c2g__codaInvoiceLineItem__c
                                       WHERE Billing_Contract__c IN :selBillingContractIdSet AND
                                       c2g__Product__c IN :selProductIdSet];
        }
		
        
        for (c2g__codaInvoiceLineItem__c invLineItem : selSalesInvLineItemList)
        {
            String mapKey = invLineItem.Billing_Contract__c+''+invLineItem.Activity_Line_Item__c+''+invLineItem.c2g__Product__c;
            mapInvLineItem.put(mapKey, invLineItem);
        }
        */
        
        // LOOP THROUGH THE lstSelectedLineItems LIST AND SET THE Cancel__c FIELD TO 'TRUE' FOR THE SELECTED RECORDS AND ADD THEM TO THE lstActLineItemsToUpdate LIST 
        for (Activity_Line_Item__c s : lstSelectedLineItems)
        {
            if (s.Flagged_For_Cancellation_Reason__c == null)
            { 
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, System.Label.AH_ActivityLineItemOpptyView_Save_Error));
            }
            else
            {
                s.Cancel_Line_Item__c = true;
                s.Flagged_For_Cancellation_Record__c = cancObj.Id;
                lstActLineItemsToUpdate.add(s);
                /* COMMENTED THIS FUNCTIONALITY PER HEATHER'S REQUEST 
                String searchKey = s.Billing_Contract__c+''+s.Id+''+s.Product__c;
                
                if(mapInvLineItem.containsKey(searchKey)){
                    c2g__codaInvoiceLineItem__c invObjectToUpdate = mapInvLineItem.get(searchKey);
                    invObjectToUpdate.Flagged_For_Cancellation_Record__c = cancObj.Id;
                    invObjectToUpdate.Flagged_For_Cancellation__c = true;
                    invObjectToUpdate.Flagged_For_Cancellation_Reason__c = s.Flagged_For_Cancellation_Reason__c;
                    salesInvLineItemToUpdate.add(invObjectToUpdate);
                }
				*/
            }     
        }
        
        // LOOP THROUGH THE lstNonSelectedLineItems LIST AND SET THE Cancel__c FIELD TO 'FALSE' FOR THE SELECTED RECORDS AND ADD THEM TO THE lstActLineItemsToUpdate LIST   
        for (Activity_Line_Item__c n : lstNonSelectedLineItems)
        {

            n.Cancel_Line_Item__c = false;
            n.Flagged_For_Cancellation_Record__c = null;
            n.Flagged_For_Cancellation_Reason__c = null;
            lstActLineItemsToUpdate.add(n);
            /* COMMENTED THIS FUNCTIONALITY PER HEATHER'S REQUEST 
            String searchKey = n.Billing_Contract__c+''+n.Id+''+n.Product__c;

            if(mapInvLineItem.containsKey(searchKey)){
                c2g__codaInvoiceLineItem__c invObjectToUpdate = mapInvLineItem.get(searchKey);
                invObjectToUpdate.Flagged_For_Cancellation_Record__c = null;
                invObjectToUpdate.Flagged_For_Cancellation__c = false;
                invObjectToUpdate.Flagged_For_Cancellation_Reason__c = null;
                salesInvLineItemToUpdate.add(invObjectToUpdate);
            }
			*/
        }  

		/* COMMENTED THIS FUNCTIONALITY PER HEATHER'S REQUEST        
        for(c2g__codaInvoice__c salesInv : salesInvList)
		{
            system.debug('in sales inv for each');
            if(!selectedMap.isEmpty())
			{
                SYSTEM.debug('selectedMap');
                if(selectedMap.containsKey(salesInv.Billing_Contract__c)){
                    salesInv.Cancel_Invoice__c = true;
                    salesInv.Flagged_For_Cancellation_Record__c = cancObj.Id;
                    if(billingIdCancReason.containsKey(salesInv.Billing_Contract__c)){
                        salesInv.Flagged_For_Cancellation_Reason__c = billingIdCancReason.get(salesInv.Billing_Contract__c);
                    }
                    salesInvListToUpdate2.add(salesInv);
                }
            }
            system.debug('check');
            if(!nonSelectedMap.isEmpty()){
                SYSTEM.debug('nonSelectedMap');
                if(nonSelectedMap.containsKey(salesInv.Billing_Contract__c)){
                    salesInv.Cancel_Invoice__c = false;
                    salesInv.Flagged_For_Cancellation_Record__c = null;
                    salesInv.Flagged_For_Cancellation_Reason__c = null;
                    salesInvListToUpdate.add(salesInv);
                }
            }
            
        }
		*/
        
        // USE DATABASE DML METHOD TO UPDATE ALL OF THE SELECTED AND NON-SELECTED RECORDS
        if (lstActLineItemsToUpdate.size() > 0)
        {
            database.update(lstActLineItemsToUpdate);
        } 
        
// COMMENTED THIS FUNCTIONALITY PER HEATHER'S REQUEST         
//        if (!salesInvLineItemToUpdate.isEmpty())
//        {
//            database.update(salesInvLineItemToUpdate);
//        }
        
        // SET THE LIST TO NULL SO A NEW LIST IS CREATED
        lstActLineItems.Clear(); 
        disableListEdit(); 
        
        return null;
        
    }
    
    public pageReference changeSelected()
    {
        //if (li.isSelected == true)
        //{        
        // }
        return null;
    }

    // WRAPPER CLASS TO BUILD THE SOFTRAX ASSETS LIST  
    public class actLineItemWrapper 
    {
        public Activity_Line_Item__c ali {get; set;}
        public Boolean isSelected {get; set;}
        public Id idActLineItem {get; set;}
        
        public actLineItemWrapper(Activity_Line_Item__c a) 
        {
            ali = a;
            idActLineItem = ali.Id;  
            if (ali.Cancel_Line_Item__c) 
            {
                isSelected = true;
            }
            else
            {
                isSelected = false; 
            }
        }
    }
    
}