force-app/main/default/objects/Activity_Line_Item__c/Activity_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Activity Line Item</label>
    <nameField>
        <displayFormat>ACT-{00000}</displayFormat>
        <label>Activity Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Line Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity_Line_Item__c/fields/Billing_Contract__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contract__c</fullName>
    <description>Revenue Recognition line detail on Billing Contract Object</description>
    <label>Billing Contract</label>
    <referenceTo>Billing_Contract__c</referenceTo>
    <relationshipLabel>Activity Line Items</relationshipLabel>
    <relationshipName>Rev_Rec_BC_Line_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <label>Origin</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Order</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Clone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Previous_ALI__c.field-meta.xml
<CustomField>
    <fullName>Previous_ALI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Link to the previous Activity Line that was used to create the renewal</inlineHelpText>
    <label>Previous ALI</label>
    <referenceTo>Activity_Line_Item__c</referenceTo>
    <relationshipLabel>Activity Line Item</relationshipLabel>
    <relationshipName>Activity_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billing_Contract__c/Billing_Contract__c.object-meta.xml
<CustomObject>
    <label>Billing Contract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Billing Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Contract</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Contract__c/fields/Billing_Hold__c.field-meta.xml
<CustomField>
    <fullName>Billing_Hold__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Hold on Billing</description>
    <inlineHelpText>Temporarily prevents this billing contract from creating Sales Invoices</inlineHelpText>
    <label>Billing Hold</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billing_Contract__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The FFA Company that will house this invoice</inlineHelpText>
    <label>Company</label>
    <referenceTo>c2g__codaCompany__c</referenceTo>
    <relationshipLabel>Billing Contract</relationshipLabel>
    <relationshipName>Billing_Contract</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing_Contract__c/fields/Exclude_Automated_Invoicing__c.field-meta.xml
<CustomField>
    <fullName>Exclude_Automated_Invoicing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NICC-033283</description>
    <inlineHelpText>When this field is checked, the Billing Contract record will not be included in the automated invoicing job.  This field is updated by the Billing Team in Finance</inlineHelpText>
    <label>Exclude Automated Invoicing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billing_Contract__c/fields/Ready_to_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Ready_to_Invoice__c</fullName>
    <formula>Ready_to_Invoice_Numeric__c &gt; 0
&amp;&amp;
Billing_Hold__c = false</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Set to true if one or more billing line items are eligible to be invoiced</inlineHelpText>
    <label>Ready to Invoice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/Billing_Contract_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Billing Contract Line Item</label>
    <nameField>
        <displayFormat>BL-{00000}</displayFormat>
        <label>Billing Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Activity_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Activity_Line_Item__c</fullName>
    <label>Activity Line Item</label>
    <referenceTo>Activity_Line_Item__c</referenceTo>
    <relationshipLabel>Billing Contract Line Items</relationshipLabel>
    <relationshipName>Billing_Contract_Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Billing_Contract__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contract__c</fullName>
    <description>Billing Contract line item detail for Billing Contract object</description>
    <label>Billing Contract</label>
    <referenceTo>Billing_Contract__c</referenceTo>
    <relationshipLabel>Billing Contract Line Items</relationshipLabel>
    <relationshipName>Billing_Contract_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Billing_Hold__c.field-meta.xml
<CustomField>
    <fullName>Billing_Hold__c</fullName>
    <description>NICC-046977 - Billing Hold Checkbox - from the Billing Contract Record</description>
    <formula>Billing_Contract__r.Billing_Hold__c</formula>
    <inlineHelpText>Billing Hold Checkbox - from the Billing Contract Record</inlineHelpText>
    <label>Billing Hold</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <description>NICC-046977 - Company - from the Billing Contract record</description>
    <formula>Billing_Contract__r.Company__r.Name</formula>
    <inlineHelpText>Company - from the Billing Contract record</inlineHelpText>
    <label>Company</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Exclude_Automated_Invoicing__c.field-meta.xml
<CustomField>
    <fullName>Exclude_Automated_Invoicing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exclude Automated Invoicing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Invoiced__c.field-meta.xml
<CustomField>
    <fullName>Invoiced__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invoiced</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Ready_to_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Ready_to_Invoice__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Will be set to true / false by a workflow rule based on today&apos;s date</inlineHelpText>
    <label>Ready to Invoice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>IF( Total_Amount__c &lt; 0 , &quot;Credit&quot; , &quot;Invoice&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Run_History__c/Job_Run_History__c.object-meta.xml
<CustomObject>
    <label>Job Run History</label>
    <nameField>
        <displayFormat>Run History-{000000}</displayFormat>
        <label>Job Run History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Run Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Run_History__c/fields/Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Created_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Created Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Job_Run_History__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>User</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AH_SINManager_Sched_Renewals.cls
/****************************************************************************************
Name            : AH_SINManager_Sched_Renewals
Author          : Bhuleshwar Deshpande
Created Date    : 11/02/2018     
Modified Date   : 11/22/2019                  
Last Mod By     : Bhuleshwar Deshpande   
NICC Reference  : 
Description     : Class to schedule AH_SINManager_Batch class
                :
                :
******************************************************************************************/
global class AH_SINManager_Sched_Renewals implements Schedulable 
{
        
    global void execute(SchedulableContext sc)
    {
        // CHANGE IN EXISTING QUERY  
        String  groupByQuery = 'SELECT Billing_Contract__c, COUNT(ID) recCount ';
                groupByQuery += 'FROM Billing_Contract_Line_Item__c ';
                groupByQuery += 'WHERE Ready_to_Invoice__c = true ';
                groupByQuery += 'AND Invoiced__c = false ';
                groupByQuery += 'AND Total_Amount__c >= 0 ';
                groupByQuery += 'AND Type__c != \'Credit\' ';
                groupByQuery += 'AND Activity_Line_Item__r.Origin__c = \'Renewal\'  ';
                groupByQuery += 'AND Billing_Contract__r.Exclude_Automated_Invoicing__c = false  ';
                groupByQuery += 'AND Billing_Contract__r.Billing_Hold__c = FALSE  ' ; 
                groupByQuery += 'AND Billing_Contract__r.Company__r.Exclude_from_Automated_Renewal_Invoicing__c = false ' ;

                groupByQuery += 'GROUP BY Billing_Contract__c ';
               
            
        system.debug(' **** groupByQuery = ' + groupByQuery);
        
        Set<String> bcQueryIds = new Set<String>();
        integer iMode = 1;
        
        AggregateResult[] groupedResults = Database.query(groupByQuery);        
        
        if (groupedResults != null && groupedResults.size() > 0)
        {
            for (AggregateResult ar : groupedResults)   
            {
                bcQueryIds.add(String.valueOf(ar.get('Billing_Contract__c')));
            }
        }  
        
        //REPLACE BATCH CLASS AH_BatchCreateInvoices WITH AH_SINManager_Batch
        AH_SINManager_Batch batchable = new AH_SINManager_Batch(bcQueryIds,iMode);
        Database.executeBatch(batchable, 1); 
       
        system.debug('Schedule class execution completed...');
        
        // CODE TO CREATE JOB SCHEDULED RECORD IN RUN HISTORIES OBJECT
        Job_Run_History__c runHist = new Job_Run_History__c();
        //runHist.Apex_Class__c = 'AH_Schedule_SalesInvoices';
        runHist.Apex_Class__c = 'AH_SINManager_Sched_Renewals';
        runHist.Status__c = 'Queued';
        runHist.Target_Object__c = 'Sales Invoice';
        runHist.User__c = UserInfo.getUserName();
        runHist.Created_Date__c = Datetime.now();
        
        insert runHist;
        
    }                
    
}