force-app/main/default/objects/Activity_Line_Item__c/Activity_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Activity Line Item</label>
    <nameField>
        <displayFormat>ACT-{00000}</displayFormat>
        <label>Activity Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Line Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity_Line_Item__c/fields/Activation_Date__c.field-meta.xml
<CustomField>
    <fullName>Activation_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Activation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Activation_Required__c.field-meta.xml
<CustomField>
    <fullName>Activation_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Activation Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Auto_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renewal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates line item will be renewed automatically</description>
    <inlineHelpText>Indicates line item will be renewed automatically</inlineHelpText>
    <label>Renewal Eligible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Billing_Contract__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contract__c</fullName>
    <description>Revenue Recognition line detail on Billing Contract Object</description>
    <label>Billing Contract</label>
    <referenceTo>Billing_Contract__c</referenceTo>
    <relationshipLabel>Activity Line Items</relationshipLabel>
    <relationshipName>Rev_Rec_BC_Line_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Deployment_Instance__c.field-meta.xml
<CustomField>
    <fullName>Deployment_Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deployment Instance</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Activity Line Item</relationshipLabel>
    <relationshipName>Activity_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Activity Line Item</relationshipLabel>
    <relationshipName>Activity_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Terms</label>
    <referenceTo>Payment_Terms__c</referenceTo>
    <relationshipLabel>Activity Line Item</relationshipLabel>
    <relationshipName>Activity_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billing_Contract__c/Billing_Contract__c.object-meta.xml
<CustomObject>
    <label>Billing Contract</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Billing Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Billing Contract</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Contract__c/fields/Activation_Date__c.field-meta.xml
<CustomField>
    <fullName>Activation_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Activation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billing_Contract__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <formula>if(ISBLANK(Invoice_Date_Override__c) = true, Next_Invoice_Date__c, Invoice_Date_Override__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billing_Contract__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Billing Contract</relationshipLabel>
    <relationshipName>Billing_Contract</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/Billing_Contract_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Billing Contract Line Item</label>
    <nameField>
        <displayFormat>BL-{00000}</displayFormat>
        <label>Billing Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Activation_Required__c.field-meta.xml
<CustomField>
    <fullName>Activation_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Determined by the related Payment Terms</inlineHelpText>
    <label>Activation Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Activity_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Activity_Line_Item__c</fullName>
    <label>Activity Line Item</label>
    <referenceTo>Activity_Line_Item__c</referenceTo>
    <relationshipLabel>Billing Contract Line Items</relationshipLabel>
    <relationshipName>Billing_Contract_Line_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Auto_Renew__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renew__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto-Renew?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Auto_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renewal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox if line item is automatically renewed</description>
    <inlineHelpText>Checkbox if line item is automatically renewed</inlineHelpText>
    <label>Auto-Renewal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Billing_Contract__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contract__c</fullName>
    <description>Billing Contract line item detail for Billing Contract object</description>
    <label>Billing Contract</label>
    <referenceTo>Billing_Contract__c</referenceTo>
    <relationshipLabel>Billing Contract Line Items</relationshipLabel>
    <relationshipName>Billing_Contract_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Billing_Notification_Date__c.field-meta.xml
<CustomField>
    <fullName>Billing_Notification_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Billing Notification Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Cancelled__c.field-meta.xml
<CustomField>
    <fullName>Cancelled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cancelled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Credit_Processed__c.field-meta.xml
<CustomField>
    <fullName>Credit_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Will be marked true if a credit has been processed for this line item</inlineHelpText>
    <label>Credit Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Deployment_Instance__c.field-meta.xml
<CustomField>
    <fullName>Deployment_Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deployment Instance</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Billing Contract Line Items</relationshipLabel>
    <relationshipName>Billing_Contract_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Dimension_2__c.field-meta.xml
<CustomField>
    <fullName>Dimension_2__c</fullName>
    <formula>Product__r.Dimension_2__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dimension 2</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Dimension_3__c.field-meta.xml
<CustomField>
    <fullName>Dimension_3__c</fullName>
    <formula>Product__r.Dimension_3__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dimension 3</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <formula>Activity_Line_Item__r.Contract_End_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/FFA_Currency__c.field-meta.xml
<CustomField>
    <fullName>FFA_Currency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FFA Currency</label>
    <referenceTo>c2g__codaAccountingCurrency__c</referenceTo>
    <relationshipLabel>Billing Contract Line Items</relationshipLabel>
    <relationshipName>Billing_Contract_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Invoiced__c.field-meta.xml
<CustomField>
    <fullName>Invoiced__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invoiced</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Line_Item_Description__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Provide information on line items</inlineHelpText>
    <label>Line Item Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Opp_Line_Item_ID__c.field-meta.xml
<CustomField>
    <fullName>Opp_Line_Item_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Opp Line Item ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Billing Contract Line Items</relationshipLabel>
    <relationshipName>Billing_Contract_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <formula>if(ISBLANK(Sales_Invoice_Line_Item__c) = true,&apos;N/A&apos;, Sales_Invoice_Line_Item__r.c2g__Invoice__r.c2g__PaymentStatus__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Payment_Term_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Payment_Term_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Term Line Item</label>
    <referenceTo>Payment_Term_Line_Item__c</referenceTo>
    <relationshipLabel>Billing Contract Line Items</relationshipLabel>
    <relationshipName>Billing_Contract_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Terms__c/Payment_Terms__c.object-meta.xml
<CustomObject>
    <description>Payment Terms Object that holds information on how billing a client should proceed based on specific invoicing requirements.</description>
    <label>Invoice Terms</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Payment Terms Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Terms__c/fields/Activation_Required__c.field-meta.xml
<CustomField>
    <fullName>Activation_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Activation required for invoicing</inlineHelpText>
    <label>Activation Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/billingContractCreditController.cls
/**************************************************************************************
// Name          : billingContractCreditController
// Date          : 4/19/16
// Description   : Controller for the cancellation page
// Author        : CLD Partners
***************************************************************************************/

public class billingContractCreditController {
	public List<bliWrapper> wrapperList {get; set;}
	public Billing_Contract_Line_Item__c dummyLine {get; set;}
	public Boolean isAllChecked {get; set;}
	public Billing_Contract__c billingContract {get; set;}
	public id billingContractid {get; set;}

	public billingContractCreditController(ApexPages.StandardController controller) {
		dummyLine = new Billing_Contract_Line_Item__c();
		this.billingContract = (Billing_Contract__c)controller.getRecord(); 
		fetchData();
	}

	public void fetchData(){
		wrapperList = new List<bliWrapper>();
		for(Billing_Contract_Line_Item__c billLine : [
        	SELECT
	        	Activation_Date__c,
				Activation_Required__c,
				Activity_Line_Item__c,
				Auto_Renew__c,
				Auto_Renewal__c,
				Billing_Contract__c,
				Billing_Notification_Date__c,
				Cancelled__c,
				Credit_Processed__c,
				Deployment_Instance__c,
				Dimension_2__c,
				Dimension_3__c,
				End_Date__c,
				FFA_Currency__c,
				Invoice_Date__c,
				Invoiced__c,
				Line_Item_Description__c,
				Opp_Line_Item_ID__c,
				Opportunity__c,
				Payment_Status__c,
				Payment_Term_Line_Item__c,
				Payment_Terms__c,
				Pro_Rated__c,
				Product_Package_Item__c,
				Product_Package__c,
				Product__c,
				Product__r.Name,
				Quantity__c,
				Ready_for_Annual_Invoice__c,
				Ready_to_Credit__c,
				Ready_to_Invoice__c,
				Renewal_Quantity__c,
				Revenue_Category__c,
				SKU__c,
				Sales_Invoice_Line_Item__c,
				Split_Order__c,
				Start_Date__c,
				Status__c,
				Total_Amount__c,
				Type__c,
				Unit_Price__c
        	FROM Billing_Contract_Line_Item__c
        	WHERE Billing_Contract__c = :billingContract.id
        	AND Type__c = 'Invoice'
        	AND Invoiced__c = true])
    	{
    		bliWrapper wrapper = new bliWrapper();
    		wrapper.bliObject = billLine;
    		wrapper.dummy_bliObject.Quantity__c = billLine.Quantity__c;
    		wrapper.dummy_bliObject.Unit_Price__c = (billLine.Unit_Price__c)*-1;
    		wrapper.check = false;
    		wrapper.disabled = billLine.Credit_Processed__c;
    		wrapperList.add(wrapper);
    	}
	}

	public PageReference backToBC(){
        PageReference ref = new PageReference('/'+billingContract.Id); 
        return ref; 
    }

	public void processCredit()
	{
		List<bliWrapper> creditList = new List<bliWrapper>();
		for(bliWrapper wrapper : wrapperList){
			if(wrapper.check == true){
				creditList.add(wrapper);
				if(wrapper.dummy_bliObject.Unit_Price__c > 0){
					ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Attention: you must enter a negative amount!')); 
					return;
				}
			}
		}

		Try{
			billingContractCreditHandler.processBCCredits(creditList);
			for(bliWrapper wrapper : wrapperList){
				if(wrapper.check == true){
					wrapper.check = false;
					wrapper.disabled = true;
				}
			}
			fetchData();
			ApexPages.addMessage(new ApexPages.message(ApexPages.severity.CONFIRM,'Credit Successful!'));
		}
		Catch(Exception e){
			ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,e.getMessage() + '\n Line: '+e.getLineNumber() +'\n Cause:'+e.getCause())); 
		}
	}

	public class bliWrapper{
        public Billing_Contract_Line_Item__c bliObject {get;set;}
        public Billing_Contract_Line_Item__c dummy_bliObject {get;set;}
        public boolean check {get;set;}
        public boolean disabled {get;set;}
        public Renewal_Pricing_Entry__c rpe {get;set;}
        public decimal renewalAmount {get;set;}
        public bliWrapper(){
            bliObject = new Billing_Contract_Line_Item__c();
            dummy_bliObject = new Billing_Contract_Line_Item__c();
            check = false;
        }
    }
}