force-app/main/default/objects/IT_Hardware_Asset__c/IT_Hardware_Asset__c.object-meta.xml
<CustomObject>
    <description>Hardware assets in inventory.</description>
    <label>IT Hardware Asset</label>
    <nameField>
        <displayFormat>HW-{00000}</displayFormat>
        <label>IT Hardware Asset ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IT Hardware Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/IT_Hardware_Asset__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User assigned to hardware asset ID.</description>
    <inlineHelpText>User assigned to hardware asset ID.</inlineHelpText>
    <label>Custodian</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>IT_Hardware_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IT_Hardware_Model__c/IT_Hardware_Model__c.object-meta.xml
<CustomObject>
    <description>IT hardware models for internal use.</description>
    <label>IT Hardware Model</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>IT Hardware Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IT Hardware Models</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/IT_Hardware_Asset_TriggerHandler_Test.cls
/****************************************************************************************
Name            : IT_Hardware_Asset_TriggerHandler_Test Test Class
Author          : Stuart Emery
Created Date    : 4/1/2015
Last Mod Date   : 4/1/2015
Last Mod By     : Stuart Emery
NICC Reference  : 
Description     : test Class for the IT_Hardware_Asset_TriggerHandler Class
                : 
******************************************************************************************/
@isTest (SeeAllData=false)
private class IT_Hardware_Asset_TriggerHandler_Test {
    
    static testMethod void singleInsertTest() 
    {    
        
        // CREATE A TEST USER WITH THE NI ADMINISTRATOR PROFILE
        User u = NI_TestClassData.createTestUser(1, 'NI Administrator');
        insert u;
        
        //CREATE A TEST HARDWARE MODEL RECORD
        IT_Hardware_Model__c hm = NI_TestClassData.createITHardwareModel(1);
        insert hm;
        
        //TEST THE AFTER INSERT TRIGGER LOGIC
        Test.startTest();
        
        IT_Hardware_Asset__c ha = NI_TestClassData.createITHardwareAsset(1, hm.Id);
        ha.User__c = u.Id;  //ADD THE TEST USER AS THE CUSTODIAN FOR THE HARDWARE ASSET RECORD
        insert ha;
        
        Test.stopTest();
        
        //VERIFY THAT THE CUSTODIAN WAS ADDED TO THE IT HARDWARE ASSET SHARE
        List<IT_Hardware_Asset__Share> lstShares = [SELECT UserOrGroupId 
                                                    FROM IT_Hardware_Asset__Share 
                                                    WHERE ParentId =: ha.Id 
                                                    AND UserOrGroupId =: u.Id];
        System.assertEquals(1, lstShares.size());
        
    }
    //================================================================================================================================================    
    static testMethod void singleUpdateTest() 
    {    
        
        // CREATE A TEST USER TO USE WHEN THE RECORD IS INSERTED
        User u = NI_TestClassData.createTestUser(1, 'NI Administrator');
        insert u;
        
        // CREATE A TEST USER TO USE WHEN THE RECORD IS UPDATED
        User u2 = NI_TestClassData.createTestUser(2, 'NI Administrator');
        insert u2;
        
        //CREATE A TEST HARDWARE MODEL RECORD
        IT_Hardware_Model__c hm = NI_TestClassData.createITHardwareModel(1);
        insert hm;
        
        IT_Hardware_Asset__c ha = NI_TestClassData.createITHardwareAsset(1, hm.Id);
        ha.User__c = u.Id;  //ADD THE TEST USER AS THE CUSTODIAN FOR THE HARDWARE ASSET RECORD
        insert ha;
        
        //TEST THE AFTER UPDATE TRIGGER LOGIC
        Test.startTest();
        
        ha.User__c = u2.Id;
        update ha;
        
        Test.stopTest();
        
        //VERIFY THAT THE ORIGINAL CUSTODIAN WAS REMOVED FROM THE HARDWARE ASSET SHARE
        List<IT_Hardware_Asset__Share> lstSharesRemoved = [SELECT UserOrGroupId 
                                                           FROM IT_Hardware_Asset__Share 
                                                           WHERE ParentId =: ha.Id 
                                                           AND UserOrGroupId =: u.Id];
        System.assertEquals(0, lstSharesRemoved.size());
        
        
        //VERIFY THAT THE NEW CUSTODIAN WAS ADDED TO THE IT HARDWARE ASSET SHARE
        List<IT_Hardware_Asset__Share> lstSharesAdded = [SELECT UserOrGroupId 
                                                         FROM IT_Hardware_Asset__Share 
                                                         WHERE ParentId =: ha.Id 
                                                         AND UserOrGroupId =: u2.Id];
        System.assertEquals(1, lstSharesAdded.size());
        
    }
    
}