force-app/main/default/objects/IT_Hardware_Asset__c/IT_Hardware_Asset__c.object-meta.xml
<CustomObject>
    <description>Hardware assets in inventory.</description>
    <label>IT Hardware Asset</label>
    <nameField>
        <displayFormat>HW-{00000}</displayFormat>
        <label>IT Hardware Asset ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IT Hardware Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/IT_Hardware_Asset__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User assigned to hardware asset ID.</description>
    <inlineHelpText>User assigned to hardware asset ID.</inlineHelpText>
    <label>Custodian</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>IT_Hardware_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IT_Hardware_Model__c/IT_Hardware_Model__c.object-meta.xml
<CustomObject>
    <description>IT hardware models for internal use.</description>
    <label>IT Hardware Model</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>IT Hardware Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IT Hardware Models</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/IT_Software_Asset__c/IT_Software_Asset__c.object-meta.xml
<CustomObject>
    <description>Software asset records and assignments</description>
    <label>IT Software Asset</label>
    <nameField>
        <displayFormat>SWA-{00000}</displayFormat>
        <label>IT Software Asset</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IT Software Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/IT_Software_Asset__c/fields/Assigned_User__c.field-meta.xml
<CustomField>
    <fullName>Assigned_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User whom is assigned to software package.</description>
    <label>Assigned User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>IT_Software_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IT_Software_Package__c/IT_Software_Package__c.object-meta.xml
<CustomObject>
    <description>Software vendors and packages that can be deployed to internal users.</description>
    <label>IT Software Package</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>IT Software Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IT Software Packages</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/IT_UserDatabaseCtrlr_Test.cls
/****************************************************************************************
Name            : IT_UserDatabaseCtrlr_Test Test Class
Author          : Stuart Emery
Created Date    : 4/3/2015
Last Mod Date   : 4/3/2015
Last Mod By     : Stuart Emery
NICC Reference  : 
Description     : test Class for the IT_UserDatabaseCtrlr Class
                : 
******************************************************************************************/
@isTest (SeeAllData=false)
private class IT_UserDatabaseCtrlr_Test {
    
    static testMethod void myUnitTest() 
    {    
        
        // CREATE A TEST USER WITH THE NI ADMINISTRATOR PROFILE
        User u = NI_TestClassData.createTestUser(1, 'NI Administrator');
        insert u;
        
        //CREATE A TEST HARDWARE MODEL RECORD
        IT_Hardware_Model__c hm = NI_TestClassData.createITHardwareModel(1);
        insert hm;
        
        //CREATE A TEST HARDWARE ASSET RECORD
        IT_Hardware_Asset__c ha = NI_TestClassData.createITHardwareAsset(1, hm.Id);
        ha.User__c = u.Id;  //ADD THE TEST USER AS THE CUSTODIAN FOR THE HARDWARE ASSET RECORD
        insert ha;
        
        //CREATE A TEST SOFTWARE PACKAGE RECORD
        IT_Software_Package__c sp = NI_TestClassData.createITSoftwarePackage(1);
        insert sp;
        
         //CREATE A TEST SOFTWARE ASSET RECORD
        IT_Software_Asset__c sa = NI_TestClassData.createITSoftwareAsset(1, sp.Id);
        sa.Assigned_User__c = u.Id;  //ADD THE TEST USER AS THE CUSTODIAN FOR THE SOFTWARE ASSET RECORD
        insert sa;
        
         //INSTANTIATE CONTROLLER
       IT_UserDatabaseCtrlr ctrl = new IT_UserDatabaseCtrlr(new ApexPages.StandardController(u)); 
        
        
    }

}