force-app/main/default/objects/IT_Hardware_Asset__c/IT_Hardware_Asset__c.object-meta.xml
<CustomObject>
    <description>Hardware assets in inventory.</description>
    <label>IT Hardware Asset</label>
    <nameField>
        <displayFormat>HW-{00000}</displayFormat>
        <label>IT Hardware Asset ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IT Hardware Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/IT_Hardware_Asset__c/fields/Acquisition_Date__c.field-meta.xml
<CustomField>
    <fullName>Acquisition_Date__c</fullName>
    <description>Acquisition date of the hardware asset.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date asset was acquired.</inlineHelpText>
    <label>Warranty Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/IT_Hardware_Asset__c/fields/Asset_Tag_Number__c.field-meta.xml
<CustomField>
    <fullName>Asset_Tag_Number__c</fullName>
    <description>Asset tag number of this device</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Enter the asset tag number of this device</inlineHelpText>
    <label>Asset Tag Number</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IT_Hardware_Asset__c/fields/Date_Purchased__c.field-meta.xml
<CustomField>
    <fullName>Date_Purchased__c</fullName>
    <formula>Purchase_Order__r.SCMC__Purchase_Order_Date__c</formula>
    <inlineHelpText>Date the order was placed.</inlineHelpText>
    <label>Date Purchased</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/IT_Hardware_Asset__c/fields/Deployment_Type__c.field-meta.xml
<CustomField>
    <fullName>Deployment_Type__c</fullName>
    <description>Is device physical or virtual?</description>
    <inlineHelpText>Is device physical or virtual?</inlineHelpText>
    <label>Deployment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Physical</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IT_Hardware_Asset__c/fields/HardwareType__c.field-meta.xml
<CustomField>
    <fullName>HardwareType__c</fullName>
    <formula>TEXT( Product_ID__r.Hardware_Type__c )</formula>
    <label>Hardware Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IT_Hardware_Asset__c/fields/Lifecycle_Date__c.field-meta.xml
<CustomField>
    <fullName>Lifecycle_Date__c</fullName>
    <description>The date the hardware is due to lifecycle.  The formula refers to a combination of the Acquisition Date and Hardware Type fields.</description>
    <formula>IF ( 
OR ( 
HardwareType__c = &quot;Firewall&quot;, 
HardwareType__c = &quot;Network Switch&quot;, 
HardwareType__c = &quot;Phone&quot;, 
HardwareType__c = &quot;Phone Equipment&quot;, 
HardwareType__c = &quot;SAN&quot;, 
HardwareType__c = &quot;SAN Switch&quot;, 
HardwareType__c = &quot;Server Hardware&quot;, 
HardwareType__c = &quot;Storage Array&quot; 
), Acquisition_Date__c + 2556, 
IF ( 
OR ( 
HardwareType__c = &quot;Monitor&quot;, 
HardwareType__c = &quot;Server&quot;, 
HardwareType__c = &quot;Workstation&quot; 
), Acquisition_Date__c + 1826, 
IF ( 
OR ( 
HardwareType__c = &quot;Docking Station&quot;, 
HardwareType__c = &quot;Laptop&quot; 
), Acquisition_Date__c + 1096, 
null 
) 
) 
)</formula>
    <inlineHelpText>The projected lifecycle date of the hardware based on Acquisition Date and Hardware Type.</inlineHelpText>
    <label>Lifecycle Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/IT_Hardware_Asset__c/fields/Manufacturer__c.field-meta.xml
<CustomField>
    <fullName>Manufacturer__c</fullName>
    <description>The manufacturer of the hardware model.</description>
    <formula>TEXT(Product_ID__r.Manufacturer__c)</formula>
    <inlineHelpText>The manufacturer of the hardware model.</inlineHelpText>
    <label>Manufacturer</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IT_Hardware_Asset__c/fields/Model_Description__c.field-meta.xml
<CustomField>
    <fullName>Model_Description__c</fullName>
    <description>The description of the hardware model name.</description>
    <formula>Product_ID__r.Model_Description__c</formula>
    <inlineHelpText>The description of the hardware model name.</inlineHelpText>
    <label>Model Description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IT_Hardware_Asset__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of this asset</description>
    <inlineHelpText>Status of this asset</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Available Inventory</fullName>
            </value>
            <value>
                <fullName>Currently Being Configured</fullName>
            </value>
            <value>
                <fullName>Deployed</fullName>
            </value>
            <value>
                <fullName>FRU</fullName>
            </value>
            <value>
                <fullName>Needs Repair</fullName>
            </value>
            <value>
                <fullName>Reserved Inventory</fullName>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
            <value>
                <fullName>Lifecycle Transition</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IT_Hardware_Asset__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User assigned to hardware asset ID.</description>
    <inlineHelpText>User assigned to hardware asset ID.</inlineHelpText>
    <label>Custodian</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserType</field>
            <operation>equals</operation>
            <value>Standard</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>IT_Hardware_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IT_Software_Asset__c/IT_Software_Asset__c.object-meta.xml
<CustomObject>
    <description>Software asset records and assignments</description>
    <label>IT Software Asset</label>
    <nameField>
        <displayFormat>SWA-{00000}</displayFormat>
        <label>IT Software Asset</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>IT Software Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/IT_Software_Asset__c/fields/Assigned_User__c.field-meta.xml
<CustomField>
    <fullName>Assigned_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User whom is assigned to software package.</description>
    <label>Assigned User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>IT_Software_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IT_Software_Asset__c/fields/Date_Purchased__c.field-meta.xml
<CustomField>
    <fullName>Date_Purchased__c</fullName>
    <description>Date software package was purchased.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Date Purchased</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/IT_Software_Asset__c/fields/License_Status__c.field-meta.xml
<CustomField>
    <fullName>License_Status__c</fullName>
    <description>Status of the license provisioning.</description>
    <label>License Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
                <default>true</default>
                <label>Assigned</label>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IT_Software_Asset__c/fields/Software_Package_Name__c.field-meta.xml
<CustomField>
    <fullName>Software_Package_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Software Package Name</label>
    <referenceTo>IT_Software_Package__c</referenceTo>
    <relationshipLabel>IT Software Assets</relationshipLabel>
    <relationshipName>IT_Software_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IT_Software_Asset__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <formula>TEXT(Software_Package_Name__r.Vendor_Name__c)</formula>
    <label>Vendor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IT_UserDatabaseCtrlr.cls
/****************************************************************************************
Name            : IT_UserDatabaseCtrlr Class
Author          : Stuart Emery
Created Date    : 3/23/2015
Last Mod Date   : 4/3/2015
Last Mod By     : Stuart Emery
NICC Reference  : 
Description     : Controller Extension for the IT_UserDatabase Visualforce page
                :              
******************************************************************************************/
public class IT_UserDatabaseCtrlr {
    
    Public User usr {get; set;}
    
    //LIST TO HOLD THE HARDWARE RECORDS  
    public List<IT_Hardware_Asset__c> lstHardware {get; set;}
    
    //LIST TO HOLD THE SOFTWARE LICENSE RECORDS  
    public List<IT_Software_Asset__c> lstSoftware {get; set;}
    
    //LIST TO HOLD THE FORCE.COM LICENSE RECORDS  
    public List<UserPackageLicense> lstUserPackageLicense {get; set;}
    
    private ApexPages.StandardController stdCtrl;
    public Id id; 
    
    
    public IT_UserDatabaseCtrlr(ApexPages.StandardController stdController)
    {                      
        id = ApexPages.CurrentPage().getParameters().get('Id');            
        
        this.stdCtrl = stdController;
        this.usr = (User)stdController.getRecord();
        
        lstHardware = [SELECT Id, Name, Asset_Tag_Number__c, Acquisition_Date__c, Deployment_Type__c, HardwareType__c, 
                       Manufacturer__c, Model_Description__c, Status__c, Lifecycle_Date__c 
                       FROM IT_Hardware_Asset__c 
                       WHERE User__c =: id];
        
        lstSoftware = [SELECT Id, Name, Assigned_User__c, Date_Purchased__c, Software_Package_Name__c, Vendor__c, License_Status__c
                       FROM IT_Software_Asset__c 
                       WHERE Assigned_User__c =: id];
        
        lstUserPackageLicense = [SELECT PackageLicenseId, UserId, PackageLicense.NamespacePrefix,PackageLicense.Status, PackageLicense.ExpirationDate 
                                 FROM UserPackageLicense
                                 WHERE UserId =: id];
        
    }    
    
}