force-app/main/default/objects/AH_SFDC_Source_Change__c/AH_SFDC_Source_Change__c.object-meta.xml
<CustomObject>
    <description>Junction object between NI_Change_Control__c &amp; AH_SFDC_Source_Control__c</description>
    <label>Salesforce Source Code Change</label>
    <nameField>
        <displayFormat>SSC-{0000000}</displayFormat>
        <label>Source Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesforce Source Code Changes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_SFDC_Source_Change__c/fields/AH_SFDC_Source_Control__c.field-meta.xml
<CustomField>
    <fullName>AH_SFDC_Source_Control__c</fullName>
    <label>Salesforce Source Control</label>
    <referenceTo>AH_SFDC_Source_Control__c</referenceTo>
    <relationshipName>Source_Code_Changes</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AH_SFDC_Source_Change__c/fields/NI_Change_Control__c.field-meta.xml
<CustomField>
    <fullName>NI_Change_Control__c</fullName>
    <label>NI Change Control</label>
    <referenceTo>NI_Change_Control__c</referenceTo>
    <relationshipName>Source_Code_Changes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AH_SFDC_Source_Control__c/AH_SFDC_Source_Control__c.object-meta.xml
<CustomObject>
    <description>Object that stores information about Apex Classes, Apex Triggers, Visualforce Pages, Visualforce Components</description>
    <label>Salesforce Source Control</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>SFDC Source Control Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Salesforce Source Control</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_SFDC_Source_Control__c/fields/API_Name__c.field-meta.xml
<CustomField>
    <fullName>API_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AH_SFDC_Source_Control__c/fields/CRC__c.field-meta.xml
<CustomField>
    <fullName>CRC__c</fullName>
    <label>CRC</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AH_SFDC_Source_Control__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Label</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AH_SFDC_Source_Control__c/fields/Salesforce_ID__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Salesforce ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AH_SFDC_Source_Control__c/fields/Salesforce_Source_Type__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Source_Type__c</fullName>
    <label>Salesforce Source Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Salesforce_Source_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AH_SFDC_Source_Control__c/fields/Source_Last_Modified__c.field-meta.xml
<CustomField>
    <fullName>Source_Last_Modified__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Source Last Modified</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AH_SFDC_Source_Control__c/fields/Source_Last_Modified_By__c.field-meta.xml
<CustomField>
    <fullName>Source_Last_Modified_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source Last Modified By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Salesforce_Source_Control</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AH_SFDC_Source_Control__c/fields/Syntax__c.field-meta.xml
<CustomField>
    <fullName>Syntax__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Syntax</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NI_Change_Control__c/NI_Change_Control__c.object-meta.xml
<CustomObject>
    <description>Object for the details for the NI Change Control application</description>
    <label>NI Change Control</label>
    <nameField>
        <displayFormat>NICC-{000000}</displayFormat>
        <label>NI Change Control Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NI Change Control Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_Change_Control__c/fields/Environment_s_Affected__c.field-meta.xml
<CustomField>
    <fullName>Environment_s_Affected__c</fullName>
    <description>NICC-022658</description>
    <inlineHelpText>Please select the environments where this change will be  deployed</inlineHelpText>
    <label>Environment(s) Affected</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Production</fullName>
            </value>
            <value>
                <fullName>Sandbox - SBFULL</fullName>
            </value>
            <value>
                <fullName>Sandbox - UAT</fullName>
            </value>
            <value>
                <fullName>Release</fullName>
            </value>
            <value>
                <fullName>Sandbox</fullName>
            </value>
            <value>
                <fullName>Staging</fullName>
            </value>
            <value>
                <fullName>UAT / Preview</fullName>
            </value>
            <value>
                <fullName>Sandbox - FFA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Salesforce_Source_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Apex Class</fullName>
    </customValue>
    <customValue>
        <fullName>Apex Trigger</fullName>
    </customValue>
    <customValue>
        <fullName>Process Builder</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
        <default>true</default>
        <label>Unknown</label>
    </customValue>
    <customValue>
        <fullName>Validation Rule</fullName>
    </customValue>
    <customValue>
        <fullName>Visualforce Component</fullName>
    </customValue>
    <customValue>
        <fullName>Visualforce Page</fullName>
    </customValue>
    <masterLabel>Salesforce Source Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AH_RFCSourceChanges_Test.cls
/************************************************************************************************************************
Name            : AH_RFCSourceChanges_Test Test Class
Author          : Sean Harris
Created Date    : 06/04/2018
Last Mod Date   : 06/04/2018
Last Mod By     : Sean Harris
NICC Reference  : 
Description		: Test for AH_RFCSourceChanges Controller Class
     			: 
*************************************************************************************************************************/
@isTest
public class AH_RFCSourceChanges_Test 
{
    
    // =============================================================================================================
    //  TEST DATA CREATION 
    // =============================================================================================================
    static testMethod void testAH_RFCSourceChanges1() 
    {

        Test.startTest();
        
        // CREATE A TEST ACCOUNT RECORD
        Account a = NI_TestClassData.createTestAccount(1);
        insert a;         
        List<Account> lstAccountAsserts = new List<Account>([SELECT Id FROM Account]);
        system.assertEquals(1, lstAccountAsserts.Size(), 'Failed to create test Account record in AH_RFCSourceChanges_Test.testAH_RFCSourceChanges1()');         

        // CREATE NICC RECORD
		Id rtId = NI_TestClassData.getRecordTypeId('NI_Change_Control__c', 'Salesforce.com Change Request'); 
        
        NI_Change_Control__c nicc = NI_TestClassData.createNIChangeControl(1, 'APEX TEST'); 
        nicc.RecordTypeId = rtId; 
        nicc.Environment_s_Affected__c = 'Sandbox - SBFULL'; 
        insert nicc; 
                
        // CREATE TEST SALESFORCE SOURCE CONTROL RECORDS 
        List<AH_SFDC_Source_Control__c> lstSSCInserts = new List<AH_SFDC_Source_Control__c>();
        
        // APEX CLASS 
        AH_SFDC_Source_Control__c s1 = new AH_SFDC_Source_Control__c();
        s1.API_Name__c = 'NI_TestClassData';
        s1.Salesforce_Source_Type__c = 'Apex Class';
        s1.CRC__c = 997391997;
        s1.Description__c = 'test class';
        s1.Label__c = 'NI_TestClassData';
        s1.Salesforce_ID__c = '01p600000000iZh';
        s1.Syntax__c = 'if then else...';
        s1.Source_Last_Modified__c = system.now();
        s1.Source_Last_Modified_By__c = UserInfo.getUserId();
        lstSSCInserts.add(s1);

        // APEX CLASS 
        AH_SFDC_Source_Control__c s4 = new AH_SFDC_Source_Control__c();
        s4.API_Name__c = 'NI_TestClassData_Test';
        s4.Salesforce_Source_Type__c = 'Apex Class';
        s4.CRC__c = 997391997;
        s4.Description__c = 'test class';
        s4.Label__c = 'NI_TestClassData_Test';
        s4.Salesforce_ID__c = '01p600000000iZi';
        s4.Syntax__c = 'if then else...';
        s4.Source_Last_Modified__c = system.now();
        s4.Source_Last_Modified_By__c = UserInfo.getUserId();
        lstSSCInserts.add(s4); 
        
        // APEX TRIGGER  
        AH_SFDC_Source_Control__c s2 = new AH_SFDC_Source_Control__c();
        s2.API_Name__c = 'NI_OpportunityLineItem_BeforeInsertUpdate';
        s2.Salesforce_Source_Type__c = 'Apex Trigger';
        s2.CRC__c = 1626939573;
        s2.Description__c = 'test trigger';
        s2.Label__c = 'NI_OpportunityLineItem_BeforeInsertUpdate';
        s2.Salesforce_ID__c = '01q320000004VKgAAM';
        s2.Syntax__c = 'if then else...';
        s2.Source_Last_Modified__c = system.now();
        s2.Source_Last_Modified_By__c = UserInfo.getUserId(); 
        lstSSCInserts.add(s2);

        // PROCESS BUILDER 
        AH_SFDC_Source_Control__c s3 = new AH_SFDC_Source_Control__c();
        s3.API_Name__c = 'NI_Case_Auto_Email_for_Amadeus_PMS_v3';
        s3.Salesforce_Source_Type__c = 'Process Builder';
        // s3.CRC__c = 0;
        s3.Description__c = 'test process builder';
        s3.Label__c = 'Case Auto Email for Amadeus PMS v3';
        s3.Salesforce_ID__c = '01p32000000VSoeAAG';
        // s3.Syntax__c = '';
        s3.Source_Last_Modified__c = system.now();
        s3.Source_Last_Modified_By__c = UserInfo.getUserId();        
		lstSSCInserts.add(s3);

        database.insert(lstSSCInserts);

        // ASSERT THAT SSC RECORDS WERE CREATED
        List<AH_SFDC_Source_Control__c> lstSSCAssert1s = new List<AH_SFDC_Source_Control__c>([SELECT Id FROM AH_SFDC_Source_Control__c]); 
        system.assertEquals(4, lstSSCAssert1s.size()); 
        
        // CREATE SF SOURCE CHANGE RECORD 
        AH_SFDC_Source_Change__c sc1 = new AH_SFDC_Source_Change__c();
        sc1.AH_SFDC_Source_Control__c = [SELECT Id FROM AH_SFDC_Source_Control__c WHERE API_Name__c = 'NI_TestClassData_Test' LIMIT 1].Id;
        sc1.NI_Change_Control__c = nicc.Id;
        insert sc1;
        
        Test.stopTest();
        
        // =============================================================================================================
        // 		VISUALFORCE PAGE TESTING
        // =============================================================================================================
                
        // PAGE REFERENCE        
        PageReference pageRef = Page.AH_RFCSourceChanges;

        // ADD URL PARAM
        pageRef.getParameters().put('id', nicc.Id);        
        
        // SET TEST PAGE
		Test.setCurrentPage(pageRef); 
        
        // INSTANTIATE VISUALFORCE PAGE CONTROLLER
        AH_RFCSourceChanges ctrl = new AH_RFCSourceChanges(new ApexPages.StandardController(nicc));            

        // ASSERT THAT 1 (OF 2 TEST RECORD AVAILABLE) SF SOURCE CHANGE IS ATTACHED TO NICC 
        system.assertEquals(1, ctrl.lstSelectedSSCs.size());
        
        // ASSERT THAT 1 (OF 2 TEST RECORD AVAILABLE) SF SOURCE IS AVAILABLE TO CHOOSE 
        system.assertEquals(1, ctrl.lstUserSelections.size());
        
        // CHECK ALL COMPONENT CHECKBOXES
        ctrl.bApexClasses = true;
        ctrl.bApexTriggers = true;
        ctrl.bVFPages = true;
        ctrl.bVFComponents = true; 
        ctrl.bProcessBuilders = true; 
        ctrl.bValidationRules = true;
        
        // DO SEARCH 
        ctrl.strKeyword = 'NI_';
        ctrl.doSearch();
        
        // ASSERT THAT 3 (OF 4 TEST RECORD AVAILABLE) SF SOURCE ARE RETURNED IN SEARCH AND ARE AVAILABLE TO CHOOSE 
        system.assertEquals(3, ctrl.lstUserSelections.size());
        
        // CHECK 1st SELECTION
        ctrl.lstUserSelections.get(0).isSelected = true;

        // ADD SELECTED 
        ctrl.addSelected();
            
        // SAVE SELECTED
        ctrl.saveRecord();
        
        // ASSERT THAT 2 (OF 4 TEST RECORD AVAILABLE) SF SOURCE CHANGE IS ATTACHED TO NICC 
        List<AH_SFDC_Source_Change__c> lstAssertSFSourceChange1 = new List<AH_SFDC_Source_Change__c>([
            SELECT Id 
            FROM AH_SFDC_Source_Change__c 
            WHERE NI_Change_Control__c =: nicc.Id]);        
        system.assertEquals(2, lstAssertSFSourceChange1.size());  
        
        // ASSERT THAT 2 (OF 4 TEST RECORD AVAILABLE) SF SOURCE ARE RETURNED IN SEARCH AND ARE AVAILABLE TO CHOOSE 
        system.assertEquals(2, ctrl.lstUserSelections.size());        

        // CHECK 1st SELECTION
        ctrl.lstSelectedSSCs.get(0).isSelected = true;
        
        // REMOVE SELECTED 
        ctrl.removeSelected();
            
        // SAVE SELECTED
        ctrl.saveRecord();
        
        // ASSERT THAT 2 (OF 4 TEST RECORD AVAILABLE) SF SOURCE CHANGE IS ATTACHED TO NICC 
        List<AH_SFDC_Source_Change__c> lstAssertSFSourceChange2 = new List<AH_SFDC_Source_Change__c>([
            SELECT Id 
            FROM AH_SFDC_Source_Change__c 
            WHERE NI_Change_Control__c =: nicc.Id]);        
        system.assertEquals(1, lstAssertSFSourceChange2.size());  
        
        // ASSERT THAT 3 (OF 4 TEST RECORD AVAILABLE) SF SOURCE ARE RETURNED IN SEARCH AND ARE AVAILABLE TO CHOOSE 
        system.assertEquals(3, ctrl.lstUserSelections.size());         
        
        // TODO: ERROR Methods defined as TestMethod do not support Web service callouts
        // ctrl.syncSource();

        // TEST OPENING THE PAGE WITH NO URL PARAM 
        // PAGE REFERENCE        
        PageReference pageRef2 = Page.AH_RFCSourceChanges;

        // SET TEST PAGE
		Test.setCurrentPage(pageRef2); 
        
        // INSTANTIATE VISUALFORCE PAGE CONTROLLER
        AH_RFCSourceChanges ctrl2 = new AH_RFCSourceChanges(new ApexPages.StandardController(nicc));  
        
        // ASSERT
        system.assertEquals('ERROR: No NICC Id Param', ctrl2.pageSubTitle); 
        
    }
    
}