force-app/main/default/objects/DI_Management__c/DI_Management__c.object-meta.xml
<CustomObject>
    <description>NICC-015381 - Manage core peripheral DI&apos;s</description>
    <label>DI Management</label>
    <nameField>
        <displayFormat>DIM-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DI Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DI_Management__c/fields/Core_DI_Index__c.field-meta.xml
<CustomField>
    <fullName>Core_DI_Index__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Core DI Index</label>
    <referenceTo>NI_DeploymentInstanceIndex__c</referenceTo>
    <relationshipLabel>DI Management</relationshipLabel>
    <relationshipName>DI_Management</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DI_Management__c/fields/Peripheral_DI_Product__c.field-meta.xml
<CustomField>
    <fullName>Peripheral_DI_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Peripheral DI Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.DI_Index__c</field>
            <operation>notEqual</operation>
            <valueField>$Source.Core_DI_Index__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>DI Management</relationshipLabel>
    <relationshipName>DI_Management</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DI_Management__c/fields/Product_DI_Index__c.field-meta.xml
<CustomField>
    <fullName>Product_DI_Index__c</fullName>
    <formula>Peripheral_DI_Product__r.DI_Index__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product DI Index</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DI_Management__c/fields/Relationship__c.field-meta.xml
<CustomField>
    <fullName>Relationship__c</fullName>
    <description>This object was originally created to manage the Core-Peripheral DI relationship.  This field was added to support future potential use of this object for the management of other DI related needs.</description>
    <inlineHelpText>Core-Peripheral: Always create a Peripheral DI
Franchisor: Only create a Peripheral DI on Accounts associated to the specified Franchisor</inlineHelpText>
    <label>Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Core-Peripheral</fullName>
                <default>true</default>
                <label>Core-Peripheral</label>
            </value>
            <value>
                <fullName>Franchisor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DI_Management__c/fields/Unique_Record__c.field-meta.xml
<CustomField>
    <fullName>Unique_Record__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Unique DI Index ProductID Relationship</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/DI_Management__c/fields/UniqueCoreDiDiIndex__c.field-meta.xml
<CustomField>
    <fullName>UniqueCoreDiDiIndex__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Unique CoreDi &amp; Product DI-Index</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/DI_Management_TriggerHandler.cls
public class DI_Management_TriggerHandler {
	
    public void OnBeforeInsert(List<DI_Management__c> newTrigger)
    {
    	set<string> prodDIIndex = new set<string>();
        for(DI_Management__c dim: newTrigger){
            dim.Unique_Record__c = dim.Core_DI_Index__c+''+dim.Peripheral_DI_Product__c+dim.Relationship__c;
            
            dim.UniqueCoreDiDiIndex__c = dim.Core_DI_Index__c+''+dim.Product_DI_Index__c;
        }
    }
    public void OnBeforeUpdate(List<DI_Management__c> newTrigger,Map<Id, DI_Management__c> oldMapTrigger)
    {
        for(DI_Management__c dim: newTrigger){
            dim.Unique_Record__c = dim.Core_DI_Index__c+''+dim.Peripheral_DI_Product__c+dim.Relationship__c;
            dim.UniqueCoreDiDiIndex__c = dim.Core_DI_Index__c+''+dim.Product_DI_Index__c;
        }
    }
}