force-app/main/default/objects/IMT_Migration_Set__c/IMT_Migration_Set__c.object-meta.xml
<CustomObject>
    <description>Used for budgeting and scheduling migrations sets for the GRS migrations</description>
    <label>Scheduling Set</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Scheduling Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scheduling Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IMT_Migration_Set__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>Start</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Start</inlineHelpText>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/IMT_Migration_Set__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Status of Migration Set.  Open - Available for scheduling.  Closed - No longer available for scheduling.  Complete - Migration set is in the past and can no longer be modified.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NI_IMT_Chatter_Settings__c/NI_IMT_Chatter_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings for IMT chatter</description>
    <label>NI IMT Chatter Settings</label>
</CustomObject>

force-app/main/default/objects/NI_IMT_Chatter_Settings__c/fields/Chatter_Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Chatter_Group_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Chatter Group Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_IMT_Chatter_Settings__c/fields/Community_Name__c.field-meta.xml
<CustomField>
    <fullName>Community_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Community Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NI_IMT_SchedulingSet22DaysPriorScheduler.cls
/************************************************************************************************
Name            : NI_IMT_SchedulingSet22DaysPriorBatch Class
Author          : Damodar Raut
Created Date    : 05/19/2016 
Last Mod Date   :  
Last Mod By     : 
NICC Reference  : 
Description     : Class that post to global super user 22 days prior to scheduling set date
                : 
*************************************************************************************************/
global class NI_IMT_SchedulingSet22DaysPriorScheduler implements Schedulable {
    global void execute(SchedulableContext sc) {
        //find scheduling set meeting the 22 days prior date
    	Date chckdate = system.today().addDays(-22);
		IMT_Migration_Set__c schdlSet = [SELECT Name,Start__c,Status__c FROM IMT_Migration_Set__c WHERE Start__c = :chckdate];
		if(schdlSet != NULL) {
			//If scheduling set has tentaive assignments post chatter to global super user group
			List<pse__Assignment__c> tentativeAssignments = [SELECT Name FROM pse__Assignment__c WHERE pse__Status__c = 'Tentative' AND IMT_Migration_Set__c = :schdlSet.Id];
			if(tentativeAssignments.size() > 0) {
				String communityName = String.valueOf(NI_IMT_Chatter_Settings__c.getValues('Default').get('Community_Name__c'));
				String chatterGroupName = String.valueOf(NI_IMT_Chatter_Settings__c.getValues('Default').get('Chatter_Group_Name__c'));
				if(String.isBlank(communityName) || String.isBlank(chatterGroupName)) {
					system.debug('Community Name and Chatter Group Name can\'t be blank.');
				}
				else {
					Network imtNetwork = [SELECT id, name FROM Network WHERE Name = :communityName];
					CollaborationGroup grp = [SELECT Id,name FROM CollaborationGroup where name = :chatterGroupName];
					if(imtNetwork != NULL && grp!=NULL) {					
						// POST GLOBAL SUPER USER CHATTER
						String postText = '';
						postText = 'There are tentative assignments on the scheduling set '+ schdlSet.Name +'\nDate: ' + schdlSet.Start__c ;
						if(!Test.isRunningTest()){
							ConnectApi.FeedElement feedElement = ConnectApi.ChatterFeeds.postFeedElement(imtNetwork.Id, grp.Id, ConnectApi.FeedElementType.FeedItem, postText);
						}		    	
					}
					else {
						system.debug('Community Name or Chatter Group not found.');
					}
				}			
			}
		}
     }
}