force-app/main/default/objects/NI_Employee_Performance_Evaluation__c/NI_Employee_Performance_Evaluation__c.object-meta.xml
<CustomObject>
    <description>Employee Performance Evaluation</description>
    <label>NI Employee Performance Evaluation</label>
    <nameField>
        <displayFormat>Eval-{0}-{YYYY}</displayFormat>
        <label>Eval #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NI Employee Performance Evaluation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_Employee_Performance_Evaluation__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the Employee being reviewed</description>
    <label>Employee Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>NI_Employee_Performance_Evaluation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Employee_Performance_Evaluation__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <description>Job Title</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Job Title</inlineHelpText>
    <label>Job Title</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_Employee_Performance_Evaluation__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the manager of the employee</description>
    <label>Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>NI_Employee_Performance_Evaluation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Employee_Performance_Evaluation__c/fields/Performance_Evaluation_Year__c.field-meta.xml
<CustomField>
    <fullName>Performance_Evaluation_Year__c</fullName>
    <label>Performance Evaluation Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NI_Employee_Performance_Evaluation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Employee Completed</fullName>
            </value>
            <value>
                <fullName>Employee Draft</fullName>
                <default>true</default>
                <label>Employee Draft</label>
            </value>
            <value>
                <fullName>Manager Draft</fullName>
            </value>
            <value>
                <fullName>Manager Completed</fullName>
            </value>
            <value>
                <fullName>Manager Rejected</fullName>
            </value>
            <value>
                <fullName>Evaluation Complete</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NI_Employee_Performance_Evaluation__c/fields/Time_in_Position__c.field-meta.xml
<CustomField>
    <fullName>Time_in_Position__c</fullName>
    <description>The length of time the employee has been in this position</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>How long have you been in your current position? For example, 1 year and 3 months.</inlineHelpText>
    <label>Time in Position</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_Employee_Performance_Evaluation__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <formula>$User.Title</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_PE_Assessment__c/NI_PE_Assessment__c.object-meta.xml
<CustomObject>
    <description>Assessment Object for the NI Employee Performance Evaluation</description>
    <label>Assessment</label>
    <nameField>
        <displayFormat>AN-{0000}</displayFormat>
        <label>Assessment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_PE_Assessment__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Innovation</fullName>
            </value>
            <value>
                <fullName>Management Skills</fullName>
            </value>
            <value>
                <fullName>Ownership</fullName>
            </value>
            <value>
                <fullName>Relationships</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NI_PE_Assessment__c/fields/NI_Employee_Performance_Evaluation__c.field-meta.xml
<CustomField>
    <fullName>NI_Employee_Performance_Evaluation__c</fullName>
    <label>NI Employee Performance Evaluation</label>
    <referenceTo>NI_Employee_Performance_Evaluation__c</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NI_PerfEval_Goals__c/NI_PerfEval_Goals__c.object-meta.xml
<CustomObject>
    <label>Goal</label>
    <nameField>
        <displayFormat>GOAL-{0}</displayFormat>
        <label>Eval Goal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_PerfEval_Goals__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <inlineHelpText>Performance Goals are specific to your job.
Personal/Career Development Goals are related to gaining new skills.</inlineHelpText>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Performance Goal</fullName>
            </value>
            <value>
                <fullName>Personal/Career Development Goal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NI_PerfEval_Goals__c/fields/Current_Previous_Year__c.field-meta.xml
<CustomField>
    <fullName>Current_Previous_Year__c</fullName>
    <label>Current/Previous Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Goal From Last Year</fullName>
            </value>
            <value>
                <fullName>Goal For Coming Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NI_PerfEval_Goals__c/fields/Employee_Performance_Evaluation__c.field-meta.xml
<CustomField>
    <fullName>Employee_Performance_Evaluation__c</fullName>
    <label>Employee Performance Evaluation</label>
    <referenceTo>NI_Employee_Performance_Evaluation__c</referenceTo>
    <relationshipName>PerfEval_Goals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NI_PerfEval_Goals__c/fields/Goal__c.field-meta.xml
<CustomField>
    <fullName>Goal__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Each goal should be entered individually.</inlineHelpText>
    <label>Goal</label>
    <length>10000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/NI_PerfEval_Goals__c/fields/Set_By__c.field-meta.xml
<CustomField>
    <fullName>Set_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The person who set this goal</description>
    <inlineHelpText>The person who set this goal</inlineHelpText>
    <label>Set By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Goals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_PerfEval_Goals__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Use for goals from last year only.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Current_Previous_Year__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Partially Complete</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>Removed from Goals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Performance_Evaluations_Assessments__c/Performance_Evaluations_Assessments__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Lists all of the default records for the Assessment Object</description>
    <label>Performance Evaluations Assessments</label>
</CustomObject>

force-app/main/default/objects/Performance_Evaluations_Assessments__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Category</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NI_PerfEval_Clone_Ext.cls
/****************************************************************************************
Name            : NI_PerfEval_Clone_Ext Class
Author          : Stuart Emery
Created Date    : 10/24/2015
Last Mod Date   : 10/24/2015
Last Mod By     : Stuart Emery
NICC Reference  : 
Description     : Class that handles events in VF Pages:
                :    NI_PerfEval_Clone
                :
******************************************************************************************/
public class NI_PerfEval_Clone_Ext {
    
    //added an instance varaible for the standard controller
    private ApexPages.StandardController controller {get; set;}
    // add the instance for the variables being passed by id on the url
    private NI_Employee_Performance_Evaluation__c pe {get;set;}
    // set the id of the record that is created -- ONLY USED BY THE TEST CLASS
    public ID newRecordId {get;set;}
    
    // initialize the controller
    public NI_PerfEval_Clone_Ext(ApexPages.StandardController controller) 
    { 
        // initialize the stanrdard controller
        this.controller = controller;
        // load the current record
        pe = (NI_Employee_Performance_Evaluation__c)controller.getRecord(); 
    }
    
    // method called from the VF's action attribute to clone the Change Request
    public PageReference cloneWithGoals() 
    {
        
          //GET RECORDTYPE ID FOR THE "EMPLOYEE STAGE" RECORD TYPE ON THE PERFORMANCE EVALUATION OBJECT
        Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.NI_Employee_Performance_Evaluation__c; 
        Map<String, Schema.RecordTypeInfo> PerfEvalRecordTypeInfo = cfrSchema.getRecordTypeInfosByName(); 
        Id rtEmployeeStageId = PerfEvalRecordTypeInfo.get('Employee Stage').getRecordTypeId();
        
        // LIST OF CLONED GOALS FOR INSERT 
        List<NI_PerfEval_Goals__c> lstGoalsToInsert = new List<NI_PerfEval_Goals__c>();
        
        // LIST OF ALL RELATED GOALS BELONGING TO PERFORMANCE EVALUATIONS
        List<NI_PerfEval_Goals__c> lstGoals = new List<NI_PerfEval_Goals__c>([
            SELECT Id, 	Category__c, Current_Previous_Year__c, Employee_Performance_Evaluation__c, Goal__c, Set_By__c
            FROM NI_PerfEval_Goals__c 
            WHERE Employee_Performance_Evaluation__c = : pe.Id 
            AND Current_Previous_Year__c = 'Goal For Coming Year'
        ]);
        
        // SET SAVE POINT FOR ROLLBACK 
        //Savepoint sp = Database.setSavepoint();
        NI_Employee_Performance_Evaluation__c newPE = new NI_Employee_Performance_Evaluation__c();  
        
        
        NI_Employee_Performance_Evaluation__c currentPE = [SELECT Id, Employee_Name__c, Employee_Name__r.ManagerId, Job_Title__c, Performance_Evaluation_Year__c,  
                                                           Status__c, Time_in_Position__c, Title__c, RecordTypeId
                                                           FROM NI_Employee_Performance_Evaluation__c                         
                                                           WHERE Id = : pe.id];
        
        Date currDate = Date.today();
        newPE.RecordTypeId = rtEmployeeStageId;                   
        newPE.Employee_Name__c = currentPE.Employee_Name__c;
        newPE.Job_Title__c = currentPE.Job_Title__c;
        newPE.Performance_Evaluation_Year__c = String.valueOf(currDate.Year());
        newPE.Status__c = 'Employee Draft';
        newPE.Time_in_Position__c = currentPE.Time_in_Position__c;
        newPE.Manager__c = currentPE.Employee_Name__r.ManagerId;
        
        
        // INSERT CLONED PERFORMANCE EVALUATION RECORD        
        insert newPE;
        
        //VARIABLE TO HOLD THE ID OF THE NEW PERFORMANCE EVALUATION RECORD
        newRecordId = newPE.Id;
 
 //========================================================       
 //       CREATE ASSESSMENT RECORDS
 //========================================================
        
        //LIST TO HOLD THE PERFORMANCE EVALUDATION ASSESSMENT CUSTOM SETTINGS RECORDS  
        List<Performance_Evaluations_Assessments__c> lstCS = Performance_Evaluations_Assessments__c.getall().values();
        
        if (lstCS.size() < 1)
        {
            System.debug('THERE ARE NO RECORDS IN THE Performance_Evaluations_Assessments__c CUSTOM SETTING');
        }
        else
        {             
            //LIST TO HOLD THE PRODUCT CODE VALUE FROM THE CUSTOM SETTING  
            List<NI_PE_Assessment__c> lstAssessmentsToInsert = new List<NI_PE_Assessment__c>();
            
            for (Performance_Evaluations_Assessments__c p : lstCS)
            {
                NI_PE_Assessment__c a = new NI_PE_Assessment__c();
                a.NI_Employee_Performance_Evaluation__c = newPE.Id;
                a.Category__c = p.Category__c;        
                a.Description__c = p.Description__c;
                lstAssessmentsToInsert.add(a); 
            }    
            
            Database.insert(lstAssessmentsToInsert);
        }        
        
        
        // LOOP THROUGH ALL RELATED ARTIFACTS AND ADD TO INSERT LIST
        for (NI_PerfEval_Goals__c g : lstGoals)
        {            
            NI_PerfEval_Goals__c newG = new NI_PerfEval_Goals__c();
            newG.Category__c = g.Category__c; 
            newG.Current_Previous_Year__c = 'Goal From Last Year';
            newG.Employee_Performance_Evaluation__c = newPE.Id;
            newG.Goal__c = g.Goal__c;
            newG.Set_By__c = g.Set_By__c;
            lstGoalsToInsert.add(newG);         
        }
        
        //USE DATABASE DML METHOD TO INSERT GOALS
        if(lstGoalsToInsert.size() > 0)
        {
            Database.SaveResult[] results = Database.insert(lstGoalsToInsert,true);
            for(Database.SaveResult sr: results)
            {
                if(!sr.isSuccess())
                {
                    Database.Error err = sr.getErrors()[0];
                    System.debug(err.getMessage());
                }
            }
        }                     
        //return new PageReference('/'+ newPE.id +'/e?retURL=%2F'+newPE.id);
        return new PageReference('/'+ newPE.id);
    }       
}