force-app/main/default/objects/Customer_Community_Alerts__c/Customer_Community_Alerts__c.object-meta.xml
<CustomObject>
    <label>Customer Community Alerts</label>
    <nameField>
        <displayFormat>ALRT{0000}</displayFormat>
        <label>Customer Community Alerts Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Community Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Community_Alerts__c/fields/Alert_Message__c.field-meta.xml
<CustomField>
    <fullName>Alert_Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Alert Message</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Customer_Community_Alerts__c/fields/Font_Color__c.field-meta.xml
<CustomField>
    <fullName>Font_Color__c</fullName>
    <label>Font Color</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
                <default>true</default>
                <label>Red</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Community_Alerts__c/fields/Font_Size__c.field-meta.xml
<CustomField>
    <fullName>Font_Size__c</fullName>
    <label>Font Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10pt</fullName>
            </value>
            <value>
                <fullName>12pt</fullName>
            </value>
            <value>
                <fullName>14pt</fullName>
                <default>true</default>
                <label>14pt</label>
            </value>
            <value>
                <fullName>16pt</fullName>
            </value>
            <value>
                <fullName>20pt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Community_Alerts__c/fields/Show_in_Community__c.field-meta.xml
<CustomField>
    <fullName>Show_in_Community__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When checked the alert will appear in the Customer Community</inlineHelpText>
    <label>Show in Community</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AH_CC_Alerts.cls
/****************************************************************************************
Name            : AH_CC_Alerts
Author          : Sean Harris
Created Date    : 12/10/2019
Last Mod Date   : 12/10/2019
Last Mod By     : Sean Harris
NICC Reference  : 
Description     : Controller class for AH_CC_Alerts VF page
                : 
******************************************************************************************/
public class AH_CC_Alerts 
{
    
    public List<message> lstMsgs {get; set;}  
    public boolean hasMsgs {get; set;}  
    
    public AH_CC_Alerts()
    {   
        
        hasMsgs = false;
        
        List<Customer_Community_Alerts__c> lst = new List<Customer_Community_Alerts__c>(
            [SELECT Alert_Message__c, Font_Color__c, Font_Size__c 
             FROM Customer_Community_Alerts__c 
             WHERE Show_in_Community__c = true]);
        
        if (!lst.isEmpty()) 
        {
            
            hasMsgs = true;
            lstMsgs = new List<message>();
            
            for (Customer_Community_Alerts__c x : lst)
            {
                message msg = new message(x.Alert_Message__c, x.Font_Size__c, x.Font_Color__c);
                lstMsgs.add(msg);
            }            
            
        }

    }    
    
    public class message
    {  
    	public String strMessage {get; set;}
        public String strFontSize {get; set;} 
        public String strFontColor {get; set;}

        public message(String p1, String p2, String p3)
        {
            this.strMessage = p1;
            this.strFontSize = p2;
            this.strFontColor = p3;
        }
    }
    
}