force-app/main/default/objects/Customer_Community_Alerts__c/Customer_Community_Alerts__c.object-meta.xml
<CustomObject>
    <label>Customer Community Alerts</label>
    <nameField>
        <displayFormat>ALRT{0000}</displayFormat>
        <label>Customer Community Alerts Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Community Alerts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Community_Alerts__c/fields/Alert_Message__c.field-meta.xml
<CustomField>
    <fullName>Alert_Message__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Alert Message</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Customer_Community_Alerts__c/fields/Font_Color__c.field-meta.xml
<CustomField>
    <fullName>Font_Color__c</fullName>
    <label>Font Color</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
                <default>true</default>
                <label>Red</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Community_Alerts__c/fields/Font_Size__c.field-meta.xml
<CustomField>
    <fullName>Font_Size__c</fullName>
    <label>Font Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10pt</fullName>
            </value>
            <value>
                <fullName>12pt</fullName>
            </value>
            <value>
                <fullName>14pt</fullName>
                <default>true</default>
                <label>14pt</label>
            </value>
            <value>
                <fullName>16pt</fullName>
            </value>
            <value>
                <fullName>20pt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Community_Alerts__c/fields/Show_in_Community__c.field-meta.xml
<CustomField>
    <fullName>Show_in_Community__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When checked the alert will appear in the Customer Community</inlineHelpText>
    <label>Show in Community</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AH_CC_Alerts_Test.cls
/****************************************************************************************
Name            : AH_CC_Alerts_Test
Author          : Sean Harris
Created Date    : 12/10/2019
Last Mod Date   : 12/10/2019
Last Mod By     : Sean Harris
NICC Reference  : 
Description     : 
                : 
******************************************************************************************/
@isTest
public class AH_CC_Alerts_Test 
{

    // =======================================================================================================================================
    // = CREATE TEST DATA: 
    // =======================================================================================================================================    
    @testSetup static void createTestData()  
    {
        
        Customer_Community_Alerts__c cca = new Customer_Community_Alerts__c();
        cca.Alert_Message__c = 'test message';
        cca.Font_Color__c = 'Red';
        cca.Font_Size__c = '12pt';
        cca.Show_in_Community__c = false;
		insert cca;
             	   
    }
    
    // =======================================================================================================================================
    // = TEST METHOD 1: UNIT TESTING FOR COMMUNITY ALERT VF PAGE
    // =======================================================================================================================================
    @isTest static void test1() 
    {    
             
        PageReference pr = Page.AH_CC_Alerts;
        Test.setCurrentPage(pr);
        AH_CC_Alerts ctrl = new AH_CC_Alerts();  
        
        //system.assertEquals(1, ctrl.lstMsgs.size());
        system.assertEquals(false, ctrl.hasMsgs);
        
    }
    
    // =======================================================================================================================================
    // = TEST METHOD 2: UNIT TESTING FOR COMMUNITY ALERT VF PAGE
    // =======================================================================================================================================
    @isTest static void test2() 
    {   
        
        Customer_Community_Alerts__c cca = [SELECT Id, Show_in_Community__c FROM Customer_Community_Alerts__c LIMIT 1];
        cca.Show_in_Community__c = true;  
        update cca;
        
        PageReference pr = Page.AH_CC_Alerts;
        Test.setCurrentPage(pr);
        AH_CC_Alerts ctrl = new AH_CC_Alerts();  
        
        system.assertEquals(1, ctrl.lstMsgs.size());
        system.assertEquals(true, ctrl.hasMsgs);
        
    }
    
}