force-app/main/default/objects/NI_IMT_Property__c/NI_IMT_Property__c.object-meta.xml
<CustomObject>
    <description>Salesforce.com Change Request: NICC-016935

Used by the IMT Implementation Tool Customer Community to capture the individual hotels that are part of the hotel corporation. These records will be linked to the corresponding record on the standard Account object via a lookup field.</description>
    <label>Property</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_IMT_Property__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_IMT_Property__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Country</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_IMT_Property__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Main Property Phone Number</inlineHelpText>
    <label>Main Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/NI_IMT_Property__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>State</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IMTLocalTimeCtrl.cls
// DISABLED "IMT" Implementation Tool designed for IHG 
/****************************************************************************************
Name            : IMTLocalTimeCtrl
Author          : Damodar Raut
Created Date    : 04/01/2016
Last Mod Date   :  
Last Mod By     : 
NICC Reference  : 
Description     : controller class for the visualforce page NI_IMT_Property_Local_Time
				: 
				: 
******************************************************************************************/
public with sharing class IMTLocalTimeCtrl 
{
    
    private String offset;
    public Decimal freq {set; get;}
    private String sEnd;
    public String ctTime {set; get;} 
    
    public IMTLocalTimeCtrl(ApexPages.StandardController stdController) 
    { 
             
        NI_IMT_Property__c rec = (NI_IMT_Property__c) stdController.getRecord();
        // the fields needs to be outputted first in the visualforce page so that they
        // can be used here.
        // <apex:outputText value="{!NI_IMT_Property__c.Country__c}" rendered="false"/>
        // <apex:outputText value="{!NI_IMT_Property__c.State__c}" rendered="false"/>
        // <apex:outputText value="{!NI_IMT_Property__c.City__c}" rendered="false"/>
        // <apex:outputText value="{!NI_IMT_Property__c.Phone__c}" rendered="false"/>
        // Otherwise you need to do an explicty query for these fields
        CalculateLocalTime(rec.Country__c, rec.State__c, rec.City__c, rec.Phone__c);        
    }
    
    private void CalculateLocalTime(String sCountry, String sState, String sCity, String sPhone) 
    {        
/*        
        String s = tz.LocalTime.CalculateLocalTime(sCountry, sState, sCity, sPhone);
		JSONParser parser = JSON.createParser(s);
        parser.nextToken();
        parser.nextValue();
        offset = parser.getText();
        parser.nextToken();
        parser.nextValue();
        sEnd = parser.getText();
        if(sEnd == 'N/A') sEnd = '';  

        freq = tz.LocalTime.getFrequency(); // update every minute
*/ 
        
        refreshTime();
       
    }

    public PageReference refreshTime() 
    {
/*        
        if(offset!='N/A') ctTime = tz.LocalTime.getLocalTimeString(Decimal.valueof(offset)) + ' ' + sEnd;
        else ctTime = 'Unknown'; 
*/
        return null;
    } 

}