force-app/main/default/objects/NI_Change_Control__c/NI_Change_Control__c.object-meta.xml
<CustomObject>
    <description>Object for the details for the NI Change Control application</description>
    <label>NI Change Control</label>
    <nameField>
        <displayFormat>NICC-{000000}</displayFormat>
        <label>NI Change Control Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NI Change Control Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_Change_Control__c/fields/Change_Status__c.field-meta.xml
<CustomField>
    <fullName>Change_Status__c</fullName>
    <description>Status of the change</description>
    <inlineHelpText>Status of the change</inlineHelpText>
    <label>Change Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved - Standard Change</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Closed – Escalated</fullName>
            </value>
            <value>
                <fullName>Closed - Failed</fullName>
            </value>
            <value>
                <fullName>Closed - Implemented</fullName>
            </value>
            <value>
                <fullName>Closed - Not Implemented</fullName>
            </value>
            <value>
                <fullName>Compile</fullName>
            </value>
            <value>
                <fullName>CRB Approved</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Pending CRB Approval</fullName>
            </value>
            <value>
                <fullName>Pending Manager Approval</fullName>
            </value>
            <value>
                <fullName>Pending Business Owner Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AH_CancelRFC_Cntlr.cls
/****************************************************************************************
Name            : AH_CancelRFC_Cntlr Class 
Author          : Shashikant Nikam
Created Date    : 08/21/2019
Last Mod Date   : 10/13/2020
Last Mod By     : Sean Harris
NICC Reference  : 
Description     : Controller for CancelRFC Lightning component
				: 10/13/2020 added "without sharing" for critical update release.
				:  
******************************************************************************************/
public without sharing class AH_CancelRFC_Cntlr 
{
    @AuraEnabled
    public static void updateRecord(string recordId)
    {
        try 
        {
            NI_Change_Control__c record = [SELECT Id, Change_Status__c FROM NI_Change_Control__c WHERE Id =: recordId];
            record.Change_Status__c = 'Cancelled';
            Database.update(record);
        }
        catch(Exception e)
        {
            system.debug('Exception found : ' + e);
        }
    }
}