force-app/main/default/objects/AH_Project_Backlog_Workstreams__c/AH_Project_Backlog_Workstreams__c.object-meta.xml
<CustomObject>
    <label>Project Backlog Workstream</label>
    <nameField>
        <displayFormat>PBW-{00000}</displayFormat>
        <label>Project Backlog Workstreams Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Backlog Workstreams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_Project_Backlog_Workstreams__c/fields/Hourly_Cost__c.field-meta.xml
<CustomField>
    <fullName>Hourly_Cost__c</fullName>
    <description>Hourly cost for this workstream</description>
    <label>Hourly Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AH_Project_Backlog_Workstreams__c/fields/Workstream_Name__c.field-meta.xml
<CustomField>
    <fullName>Workstream_Name__c</fullName>
    <label>Workstream Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Amadeus_Hospitality_Workstreams</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AH_Workstream__c/AH_Workstream__c.object-meta.xml
<CustomObject>
    <description>NICC-046276

Custom Object used to capture costs related to Hospitality Workstreams.  This object is a restricted object.  This is owned by Controlling.   No one outside of Controlling should have access to this object</description>
    <label>AH Workstream</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Workstream Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AH Workstreams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_Workstream__c/fields/Hourly_Cost__c.field-meta.xml
<CustomField>
    <fullName>Hourly_Cost__c</fullName>
    <formula>All_in_Costs__c / 2080</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hourly Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NI_TriggerBypassSwitches__c/NI_TriggerBypassSwitches__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>NICC-010252: Global Custom Setting for Trigger Bypassing

Used to turn off code execution on triggers globally or per specific object(s).</description>
    <label>NI Trigger Bypass Switches</label>
</CustomObject>

force-app/main/default/objects/NI_TriggerBypassSwitches__c/fields/Bypass_AH_Project_Backlog_Workstreams_c__c.field-meta.xml
<CustomField>
    <fullName>Bypass_AH_Project_Backlog_Workstreams_c__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Bypass triggers on the AH_Project_Backlog_Workstreams__c Object</description>
    <inlineHelpText>Bypass triggers on the AH_Project_Backlog_Workstreams__c Object</inlineHelpText>
    <label>Bypass AH_Project_Backlog_Workstreams__c</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Amadeus_Hospitality_Workstreams.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accounting</fullName>
    </customValue>
    <customValue>
        <fullName>Billing</fullName>
    </customValue>
    <customValue>
        <fullName>Collections</fullName>
    </customValue>
    <customValue>
        <fullName>Commercial Operations</fullName>
    </customValue>
    <customValue>
        <fullName>Contract Management</fullName>
    </customValue>
    <customValue>
        <fullName>Corporate Business Systems</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Delivery / Implementations</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Experience</fullName>
    </customValue>
    <customValue>
        <fullName>Enterprise Program Delivery</fullName>
    </customValue>
    <customValue>
        <fullName>Legal</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>People &amp; Culture</fullName>
    </customValue>
    <customValue>
        <fullName>Revenues</fullName>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Services</fullName>
        <isActive>false</isActive>
        <label>Professional Services</label>
    </customValue>
    <customValue>
        <fullName>Finance and Accounting</fullName>
        <isActive>false</isActive>
        <label>Finance and Accounting</label>
    </customValue>
    <customValue>
        <fullName>Media</fullName>
        <isActive>false</isActive>
        <label>Media</label>
    </customValue>
    <customValue>
        <fullName>Customer Care</fullName>
        <isActive>false</isActive>
        <label>Customer Care</label>
    </customValue>
    <customValue>
        <fullName>Sales Ops</fullName>
        <isActive>false</isActive>
        <label>Sales Ops</label>
    </customValue>
    <masterLabel>Amadeus Hospitality Workstreams</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AH_ProjBacklogWorkstream_TriggerHandler.cls
/****************************************************************************************
Name            : AH_ProjBacklogWorkstream_TriggerHandler Class 
Author          : Stuart Emery
Created Date    : 11/22/2020
Last Mod Date   : 11/22/2020 
Last Mod By     : Stuart Emery
NICC Reference  : NICC-047197
Description     : Class that handles all trigger code for the 
                : AH_Project_Backlog_Workstreams__c Object
				:
******************************************************************************************/
public class AH_ProjBacklogWorkstream_TriggerHandler {
    
    private NI_TriggerBypassSwitches__c bpSwitch {get; set;}
    
    public AH_ProjBacklogWorkstream_TriggerHandler()
    {
        
        system.debug(' *** ENTERING AH_ProjBacklogWorkstream_TriggerHandler CONSTRUCTOR - QUERIES ISSUED = ' + Limits.getQueries());
        
        // GET TRIGGER HANDLER BYPASS SWITCH VALUE
        bpSwitch = NI_TriggerBypassSwitches__c.getOrgDefaults();  
        
        system.debug(' *** EXITING AH_ProjBacklogWorkstream_TriggerHandler CONSTRUCTOR - QUERIES ISSUED = ' + Limits.getQueries());
        
    }
    
    //================================================================================    
    public void OnBeforeInsert(List<AH_Project_Backlog_Workstreams__c> newTrigger)
    {   
        if (!bpSwitch.Bypass_AH_Project_Backlog_Workstreams_c__c)
        {
            
            System.debug(' *** ENTERING AH_ProjBacklogWorkstream_TriggerHandler.OnAfterInsert()');
            
            //CALL THE METHOD TO POPULATE THE HOURLY COST
            Update_HourlyCost(newTrigger);            
        }
    }
    //================================================================================================================ 
    public void OnBeforeUpdate(List<AH_Project_Backlog_Workstreams__c> newTrigger, Map<Id, AH_Project_Backlog_Workstreams__c> oldMapTrigger)
    {   
        if (!bpSwitch.Bypass_AH_Project_Backlog_Workstreams_c__c)
        {
            System.debug(' *** ENTERING AH_ProjBacklogWorkstream_TriggerHandler.OnBeforeUpdate()');
            List<AH_Project_Backlog_Workstreams__c> lstWsToUpdate = new  List<AH_Project_Backlog_Workstreams__c>();
            
            for(AH_Project_Backlog_Workstreams__c ws : newTrigger)
            {
                AH_Project_Backlog_Workstreams__c oldWs = oldMapTrigger.get(ws.Id);
                if((ws.Workstream_Name__c != oldWs.Workstream_Name__c) && (ws.Workstream_Name__c != null))
                {
                    lstWsToUpdate.add(ws);
                }
            }         
            
            
            //CALL THE METHOD TO POPULATE THE HOURLY COST    
            Update_HourlyCost(lstWsToUpdate); 
        }  
    }
    
    //=================================================================================================================   
    public void Update_HourlyCost(List<AH_Project_Backlog_Workstreams__c> newTrigger)
    {
        system.debug('*** ENTERING AH_ProjBacklogWorkstream_TriggerHandler.Update_HourlyCost()'); 
        
        Map<String, AH_Workstream__c> mapWS = new Map<String, AH_Workstream__c>();
        
        for(AH_Workstream__c ahws : [SELECT Id, Name, Hourly_Cost__c FROM AH_Workstream__c
                                     WHERE Active__c = true])
        {
            mapWS.put(ahws.Name, ahws);
        } 
        
        //LOOP THROUGH THE INSERTED PROJECT BACKLOG WORKSTREAM RECORDS AND POPULATE THE HOURLY COST FIELD
        for (AH_Project_Backlog_Workstreams__c ws : newTrigger)
        {
            //SEE IF THE PROJECT BACKLOG WORKSTREAM RECORD HAS A MATCHING AH WORKSTREAM RECORD.
            If(mapWS.containsKey(ws.Workstream_Name__c))
            {
                
                //IF A MATCHING RECORD IS FOUND, UPDATE THE HOURLY COST TO MATCH THE AH WORKSTREAM RECORD
                
                system.debug('WORKSTREAM MAP: ' + mapWS.get(ws.Workstream_Name__c).Id);
                if(mapWS.get(ws.Workstream_Name__c).Hourly_Cost__c != null)
                {
                    ws.Hourly_Cost__c = mapWS.get(ws.Workstream_Name__c).Hourly_Cost__c;
                }
                
            }
        }        
    }
    
}