force-app/main/default/objects/NI_Product_Release__c/NI_Product_Release__c.object-meta.xml
<CustomObject>
    <description>Salesforce.com Change Request: NICC-008718</description>
    <label>Product Release</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Releases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_Product_Release__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Group</label>
    <referenceTo>Product_Group__c</referenceTo>
    <relationshipLabel>Product Releases</relationshipLabel>
    <relationshipName>Product_Releases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Product_Release__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>NICC-020498: name changed to Development Status</description>
    <inlineHelpText>Development Status</inlineHelpText>
    <label>Development Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planning</fullName>
                <default>true</default>
                <label>Planning</label>
            </value>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Group__c/Product_Group__c.object-meta.xml
<CustomObject>
    <label>Product Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SFDC_CSP_Version__c/SFDC_CSP_Version__c.object-meta.xml
<CustomObject>
    <description>SFDC Customer Service Project</description>
    <label>Version</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Version Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SFDC_CSP_Version__c/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Denotes if the version is inactive for reporting and filtering.</description>
    <label>Inactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SFDC_CSP_Version__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Group</label>
    <referenceTo>Product_Group__c</referenceTo>
    <relationshipLabel>Versions</relationshipLabel>
    <relationshipName>Versions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SFDC_CSP_Version__c/fields/Product_Release__c.field-meta.xml
<CustomField>
    <fullName>Product_Release__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Release</label>
    <referenceTo>NI_Product_Release__c</referenceTo>
    <relationshipLabel>Versions</relationshipLabel>
    <relationshipName>Versions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NI_Product_Release_TriggerHandler.cls
/************************************************************************************************
Name            : NI_Product_Release_TriggerHandler Class
Author          : Sean Harris
Created Date    : 01/22/2016
Last Mod Date   : 01/22/2016
Last Mod By     : Sean Harris
NICC Reference  : 
Description     : Class that handles all trigger code for the NI_Product_Release__c Object
:
:
*************************************************************************************************/
public class NI_Product_Release_TriggerHandler
{
    
    public NI_Product_Release_TriggerHandler()
    {
    }
    
//	public void OnBeforeInsert(List<NI_Product_Release__c> newTrigger)
//    {
        
//    }
    
//    public void OnBeforeUpdate(List<NI_Product_Release__c> newTrigger)
//    {

//    }
    
//    public void OnBeforeDelete(List<NI_Product_Release__c> newTrigger)
//    {
        
//    }
    
    public void OnAfterInsert(List<NI_Product_Release__c> newTrigger)
    {
        if (!NI_FUNCTIONS.bypassTriggerCode('PRODUCT RELEASE'))
        {                     
        	syncVersion(newTrigger);
        }
    }
    
    public void OnAfterUpdate(List<NI_Product_Release__c> newTrigger)
    {
        if (!NI_FUNCTIONS.bypassTriggerCode('PRODUCT RELEASE'))
        {                     
			syncVersion(newTrigger);
        }
    }
    
//    public void OnAfterDelete(List<NI_Product_Release__c> newTrigger)
//    {
        
//    }
    
//    public void OnAfterUnDelete(List<NI_Product_Release__c> newTrigger)
//    {
        
//    }   
    
    private void syncVersion(List<NI_Product_Release__c> nTrig)
    {
        
        List<SFDC_CSP_Version__c> lstVersions = new List<SFDC_CSP_Version__c>();
        
        // CREATE LIST OF VERSIONS FOR ALL PRODUCT RELEASES WITH STATUS OF "Released" 
        for (NI_Product_Release__c pr : nTrig) 
        { 
            if (pr.Status__c == 'Released') 
            { 
                if (pr.Product_Group__c != null) 
                { 
                    SFDC_CSP_Version__c v = new SFDC_CSP_Version__c(); 
                    v.Product_Group__c = pr.Product_Group__c; 
                    v.Inactive__c = false; 
                    v.Name = pr.Name; 
                    v.Product_Release__c = pr.Id; 
                    lstVersions.add(v); 
                } 
            } 
        } 
        
        for (SFDC_CSP_Version__c lstVers : [SELECT Id, Name, Product_Release__c FROM SFDC_CSP_Version__c])
        {
            for (SFDC_CSP_Version__c vs : lstVersions)
            {
                if (lstVers.Product_Release__c == vs.Product_Release__c) 
                {
                    vs.Id = lstVers.Id;
                }
            }
        }
        
        Database.upsert(lstVersions);
                        
    }
    
    
}