force-app/main/default/objects/NI_Product_Release__c/NI_Product_Release__c.object-meta.xml
<CustomObject>
    <description>Salesforce.com Change Request: NICC-008718</description>
    <label>Product Release</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Release Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Releases</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_Product_Release__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Group</label>
    <referenceTo>Product_Group__c</referenceTo>
    <relationshipLabel>Product Releases</relationshipLabel>
    <relationshipName>Product_Releases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Product_Release__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>NICC-020498: name changed to Development Status</description>
    <inlineHelpText>Development Status</inlineHelpText>
    <label>Development Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planning</fullName>
                <default>true</default>
                <label>Planning</label>
            </value>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Group__c/Product_Group__c.object-meta.xml
<CustomObject>
    <label>Product Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SFDC_CSP_Version__c/SFDC_CSP_Version__c.object-meta.xml
<CustomObject>
    <description>SFDC Customer Service Project</description>
    <label>Version</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Version Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SFDC_CSP_Version__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Group</label>
    <referenceTo>Product_Group__c</referenceTo>
    <relationshipLabel>Versions</relationshipLabel>
    <relationshipName>Versions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NI_Product_Release_TriggerHandler_Test.cls
/****************************************************************************************
Name            : NI_Product_Release_TriggerHandler_Test Class
Author          : Sean Harris
Created Date    : 1/27/2016
Last Mod Date   : 1/27/2016
Last Mod By     : Sean Harris
NICC Reference  : 
Description     : 
                : 
                : 
******************************************************************************************/
@isTest //(SeeAllData=true)
public class NI_Product_Release_TriggerHandler_Test
{

    public static testMethod void testTrigHandler() 
    {

        Date myDate1 = Date.newInstance(2015, 1, 1);
		Date myDate2 = Date.newInstance(2015, 1, 1);
                
        User ManagerId = NI_TestClassData.createTestUser(1, 'NI Administrator'); 
        insert ManagerId;

        Product_Group__c pgp = NI_TestClassData.createProductGroup(1, 'Apex Test Group');
        insert pgp;

        List<SFDC_CSP_Version__c> lstVersions = new List<SFDC_CSP_Version__c>();
            
        SFDC_CSP_Version__c vrs01 = NI_TestClassData.createVersion('v1.', pgp.Id, 1);
        lstVersions.Add(vrs01);
        SFDC_CSP_Version__c vrs02 = NI_TestClassData.createVersion('v2.', pgp.Id, 2);
        lstVersions.Add(vrs02);
        SFDC_CSP_Version__c vrs03 = NI_TestClassData.createVersion('v3.', pgp.Id, 3);
        lstVersions.Add(vrs03);
        
        Database.insert(lstVersions);
        
        NI_Product_Release__c prdRel = NI_TestClassData.createTestNI_Product_Release(pgp.Id, ManagerId.Id, 201);
        insert prdRel;
        
        prdRel.Status__c = 'Released'; 
        update prdRel;
        
        prdRel.Name = 'v1.1'; 
        update prdRel;

    }

}