force-app/main/default/objects/NI_Cancellation__c/NI_Cancellation__c.object-meta.xml
<CustomObject>
    <label>Cancellation</label>
    <nameField>
        <displayFormat>CXL-{00000}</displayFormat>
        <label>Cancellation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cancellations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_Cancellation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account related to the Deployment Instance. This field is automatically updated based on the Deployment Instance and cannot be edited manually.</description>
    <inlineHelpText>Account related to the Deployment Instance. This field is automatically updated based on the Deployment Instance and cannot be edited manually.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>NI_Cancellations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Cancellation__c/fields/Cancellation_Notes__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Notes__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cancellation Notes</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NI_Cancellation__c/fields/Competitor_Lost_To__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Lost_To__c</fullName>
    <description>Competitor the customer switched to</description>
    <inlineHelpText>Competitor the customer switched to</inlineHelpText>
    <label>Competitor Lost To</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ad Astra</fullName>
            </value>
            <value>
                <fullName>Amadeus</fullName>
            </value>
            <value>
                <fullName>Artifax</fullName>
            </value>
            <value>
                <fullName>Caterease Software</fullName>
            </value>
            <value>
                <fullName>CaterEdge Software</fullName>
            </value>
            <value>
                <fullName>CaterPro Software</fullName>
            </value>
            <value>
                <fullName>CITY - Marriott</fullName>
            </value>
            <value>
                <fullName>CMX</fullName>
            </value>
            <value>
                <fullName>Envision</fullName>
            </value>
            <value>
                <fullName>Event Master PLUS by CBORD</fullName>
            </value>
            <value>
                <fullName>EventPro Planner</fullName>
            </value>
            <value>
                <fullName>Events Perfect</fullName>
            </value>
            <value>
                <fullName>Five Star Hotel Systems</fullName>
            </value>
            <value>
                <fullName>Hospitality Solutions Int&apos;l (HSI)</fullName>
            </value>
            <value>
                <fullName>Hotel Catalyst</fullName>
            </value>
            <value>
                <fullName>Hotel Concepts</fullName>
            </value>
            <value>
                <fullName>Hotel SalesPro</fullName>
            </value>
            <value>
                <fullName>InnFusion</fullName>
            </value>
            <value>
                <fullName>IQWARE</fullName>
            </value>
            <value>
                <fullName>ISAC - Starwood</fullName>
            </value>
            <value>
                <fullName>Kinetic Solutions</fullName>
            </value>
            <value>
                <fullName>Knowland Group</fullName>
            </value>
            <value>
                <fullName>Maestro Sales &amp; Catering Suite</fullName>
            </value>
            <value>
                <fullName>MeetingMatrix International</fullName>
            </value>
            <value>
                <fullName>Micros Systems, Inc.</fullName>
            </value>
            <value>
                <fullName>Multi-Systems, Inc.</fullName>
            </value>
            <value>
                <fullName>NFS Hospitality Corporation</fullName>
            </value>
            <value>
                <fullName>Northwind</fullName>
            </value>
            <value>
                <fullName>Ohio Reader Board</fullName>
            </value>
            <value>
                <fullName>On Q</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NI_Cancellation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Primary property contact for this cancellation request.</description>
    <inlineHelpText>Primary property contact for this cancellation request.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>NI_Cancellations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Cancellation__c/fields/Deployment_Instance__c.field-meta.xml
<CustomField>
    <fullName>Deployment_Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Deployment Instance related to this cancellation</description>
    <inlineHelpText>Deployment Instance related to this cancellation</inlineHelpText>
    <label>Deployment Instance</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Asset.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset</referenceTo>
    <relationshipName>NI_Cancellations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Cancellation__c/fields/Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Effective_Date__c</fullName>
    <defaultValue>DATE(2025,12,31)</defaultValue>
    <description>Date the cancellation takes effect</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date the cancellation takes effect</inlineHelpText>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NI_Cancellation__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Related Customer Engagement Record</description>
    <inlineHelpText>Related Customer Engagement Record</inlineHelpText>
    <label>Engagement</label>
    <referenceTo>NI_Customer_Relations_Engagement__c</referenceTo>
    <relationshipName>NI_Cancellations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Cancellation__c/fields/General_Reason__c.field-meta.xml
<CustomField>
    <fullName>General_Reason__c</fullName>
    <description>General reason the customer is cancelling
Updated NICC-026959
Updated NICC-030510</description>
    <inlineHelpText>General reason the customer is cancelling</inlineHelpText>
    <label>General Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Affiliation Change</fullName>
            </value>
            <value>
                <fullName>Property Closure</fullName>
            </value>
            <value>
                <fullName>Selected Alternative Product</fullName>
            </value>
            <value>
                <fullName>User Reduction</fullName>
            </value>
            <value>
                <fullName>Budget</fullName>
            </value>
            <value>
                <fullName>Cost Does Not Justify Benefit</fullName>
            </value>
            <value>
                <fullName>Not Using the System</fullName>
            </value>
            <value>
                <fullName>Functional Deficiencies</fullName>
            </value>
            <value>
                <fullName>Poor Customer Support</fullName>
            </value>
            <value>
                <fullName>Performance</fullName>
            </value>
            <value>
                <fullName>Product End of Life</fullName>
            </value>
            <value>
                <fullName>Covid-19</fullName>
            </value>
            <value>
                <fullName>Transitional Subscriber</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NI_Cancellation__c/fields/Management_Company__c.field-meta.xml
<CustomField>
    <fullName>Management_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The account&apos;s Management Company at the time the cancellation request was submitted. This field is automatically updated based on the Deployment Instance and cannot be edited manually.</description>
    <inlineHelpText>The account&apos;s Management Company at the time the cancellation request was submitted. This field is automatically updated based on the Deployment Instance and cannot be edited manually.</inlineHelpText>
    <label>Management Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>NI_Cancellations_MgmntCo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Cancellation__c/fields/Master_Cancellation_Record__c.field-meta.xml
<CustomField>
    <fullName>Master_Cancellation_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The NI Cancellation record that this NI Cancellation record was created from</description>
    <inlineHelpText>The NI Cancellation record that this NI Cancellation record was created from</inlineHelpText>
    <label>Master Cancellation Record</label>
    <referenceTo>NI_Cancellation__c</referenceTo>
    <relationshipName>NI_ChildCancellations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Cancellation__c/fields/Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Product_Code__c</fullName>
    <description>Product Code related to the Cancellation
NICC-034374 - Changed to point to Product2</description>
    <formula>Product2__r.ProductCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Product Code related to the Cancellation</inlineHelpText>
    <label>Product Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_Cancellation__c/fields/Reviewed_By_Fulfillment__c.field-meta.xml
<CustomField>
    <fullName>Reviewed_By_Fulfillment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Salesforce.com Change Request:  NICC-010799

Updated by Fulfillment once they have reviewed the Cancellation</description>
    <inlineHelpText>Updated by Fulfillment once they have reviewed the Cancellation</inlineHelpText>
    <label>Reviewed By Fulfillment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NI_Cancellation__c/fields/Specific_Reason__c.field-meta.xml
<CustomField>
    <fullName>Specific_Reason__c</fullName>
    <description>Specific reason the customer is cancelling
Updated NICC-030510</description>
    <inlineHelpText>Specific reason the customer is cancelling</inlineHelpText>
    <label>Specific Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Backlog Cancellation</fullName>
            </value>
            <value>
                <fullName>Brand</fullName>
            </value>
            <value>
                <fullName>Connectivity</fullName>
            </value>
            <value>
                <fullName>Cost does not justify benefit</fullName>
            </value>
            <value>
                <fullName>Discontinued By NI</fullName>
            </value>
            <value>
                <fullName>End of Free Trial</fullName>
            </value>
            <value>
                <fullName>Expense Reduction</fullName>
            </value>
            <value>
                <fullName>Franchisor</fullName>
            </value>
            <value>
                <fullName>Functional Deficiencies</fullName>
            </value>
            <value>
                <fullName>Internal Migration</fullName>
            </value>
            <value>
                <fullName>Lead volume too low</fullName>
            </value>
            <value>
                <fullName>Management Company</fullName>
            </value>
            <value>
                <fullName>Non-Payment</fullName>
            </value>
            <value>
                <fullName>Not using the system</fullName>
            </value>
            <value>
                <fullName>Ownership Group</fullName>
            </value>
            <value>
                <fullName>Performance</fullName>
            </value>
            <value>
                <fullName>Poor Customer Support</fullName>
            </value>
            <value>
                <fullName>Poor Quality</fullName>
            </value>
            <value>
                <fullName>Too Robust</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NI_Cancellation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>User Error</fullName>
            </value>
            <value>
                <fullName>Pending Retention</fullName>
                <default>true</default>
                <label>Pending Retention</label>
            </value>
            <value>
                <fullName>Flagged to be Cancelled</fullName>
            </value>
            <value>
                <fullName>Successfully Retained</fullName>
            </value>
            <value>
                <fullName>Late Cancellation Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NI_CancellationChildAccountsController.cls
/****************************************************************************************
Name            : NI_CancellationChildAccountsController Class
Author          : Stuart Emery
Created Date    : 9/27/2013
Last Mod Date   : 1/20/2015
Last Mod By     : Stuart Emery
NICC Reference  : NICC-008353
Description     : Controller for the NI_CancellationChildAccountsVF Visualforce page.
                : This controller displays the Deployment Instance records of Accounts
                : that have the Account of the current NI Cancellation record as the
                : Parent Account. Only Deployment Instances that match the DI of the
                : current NI Cancellation record are displayed                
******************************************************************************************/
public with sharing class NI_CancellationChildAccountsController 
{
     
    NI_Cancellation__c cxl {get; set;}
    public List<childAccountWrapper> lstChildAccounts {get; set;}	// WRAPPER CLASS LIST TO HOLD THE CHILD ACCOUNTS 
    public Boolean bShowCancel {get; set;}		// USED TO CONDITIONALLY RENDER THE CANCEL BUTTON  
    public Boolean bShowCreate {get; set;}		// USED TO CONDITIONALLY RENDER THE CREATE CANCELLATION RECORDS BUTTON  
    public Boolean bShowClose {get; set;}		// USED TO CONDITIONALLY RENDER THE CLOSE BUTTON  
    
    public NI_CancellationChildAccountsController(ApexPages.StandardController stdController)
    {                                  
        
        if (ApexPages.CurrentPage().getParameters().containsKey('id')) 
        {  
            
            Id cxlId = ApexPages.CurrentPage().getParameters().get('id');
            
            cxl = ([SELECT Id, Deployment_Instance__c, Reviewed_By_Fulfillment__c, Management_Company__c, Account__c, 
                    Account__r.Name, Product_Code__c, Effective_Date__c, General_Reason__c, 
                    Specific_Reason__c, Status__c, Competitor_Lost_To__c, Contact__c, 
                    Engagement__c, Cancellation_Notes__c 
                    FROM NI_Cancellation__c 
                    WHERE Id =: cxlId 
                    LIMIT 1]);             
            
            // CALL THE METHODS TO POPULATE THE LISTS
            getChildAccounts();                        
            
        }
        
    }
    
    // QUERY TO RETURN A LIST OF CHILD DEPLOYMENT INSTANCES AND ACCOUNTS
    public List<childAccountWrapper> getChildAccounts()
    {
        bShowCancel = false;
        bShowCreate = false;
        bShowClose = true;
        
        List<NI_Cancellation__c> lstAllCancellations = [SELECT Id, Name, Deployment_Instance__c 
                                                        FROM NI_Cancellation__c
                                                        WHERE Account__r.ParentId =: cxl.Account__c];      
        
        Set<Id> setDIs = new Set<Id>();    
        
        if (lstAllCancellations.size() > 0)
        {
            for (NI_Cancellation__c nic : lstAllCancellations)
            {
                setDIs.Add(nic.Deployment_Instance__c);
            }         
        }
        
        if (lstChildAccounts == null) 
        {
            lstChildAccounts = new List<childAccountWrapper>();
            for (Asset di: [SELECT a.Id, a.AccountId, a.Account.Name, a.Account.AccountNumber, 
                            a.Account.ParentId, a.Name, a.Product2.ProductCode,a.Quantity, 
                            a.Product2.Family,a.Status 
                            FROM Asset a
                            WHERE a.Account.ParentId = : cxl.Account__c
                            AND a.Product2.ProductCode = : cxl.Product_Code__c
                            AND a.Status != 'Inactive'
                            AND a.Id NOT IN : setDIs   
                            ORDER BY a.Account.Name ASC]) 
            {
                
                // AS EACH DEPLOYMENT INSTANCE RECORD IS PROCESSED WE CREATE A NEW childAccountWrapper OBJECT AND ADD IT TO THE lstChildAccounts LIST
                lstChildAccounts.add(new childAccountWrapper(di));
            }
        }
        
        if (lstChildAccounts.size() > 0)
        {
            bShowCancel = true;
            bShowCreate = true;
            bShowClose = false;
        }  
        
        return lstChildAccounts;
        
    } 
    
    public PageReference saveSelected() 
    {
        
        bShowCancel = false;
        bShowCreate = false;
        bShowClose = true;         
        
        //LIST OF DEPLOYMENT INSTANCES ASSETS THAT WILL BE POPULATED WITH ONLY THE SELECTED CHILD ACCOUNT ASSETS
        List<Asset> lstSelectedAssets = new List<Asset>();  
        
        //LIST OF NI CANCELLATION RECORDS TO INSERT  
        List<NI_Cancellation__c> lstNICancellationsToInsert = new List<NI_Cancellation__c>();
        
        for (childAccountWrapper w : lstChildAccounts) 
        {
            if (w.isSelected == true) 
            {
                lstSelectedAssets.add(w.Di);
            }
        } 
        
        // LOOP THROUGH THE lstSelectedAssets LIST AND SET THE Cancel__c FIELD TO 'TRUE' FOR THE SELECTED RECORDS AND ADD THEM TO THE lstNICancellationsToInsert LIST 
        for (asset a : lstSelectedAssets)
        {
            NI_Cancellation__c nc = new NI_Cancellation__c();
            nc.Master_Cancellation_Record__c = cxl.Id;
            nc.Deployment_Instance__c = a.Id;
            nc.General_Reason__c = cxl.General_Reason__c;
            nc.Specific_Reason__c = cxl.Specific_Reason__c;
            nc.Effective_Date__c = cxl.Effective_Date__c;
            nc.Status__c = cxl.Status__c;
            nc.Competitor_Lost_To__c = cxl.Competitor_Lost_To__c;
            nc.Contact__c = cxl.Contact__c;
            nc.Engagement__c = cxl.Engagement__c;
            nc.Cancellation_Notes__c = cxl.Cancellation_Notes__c;
            lstNICancellationsToInsert.add(nc);
        }      
        
        // USE DATABASE DML METHOD TO UPDATE ALL OF THE SELECTED AND NON-SELECTED RECORDS
        if (lstNICancellationsToInsert.size() > 0)
        {
            integer intSuccess = 0;
            Database.SaveResult[] results = Database.insert(lstNICancellationsToInsert,false);
            for (Database.SaveResult sr: results)
            {
                if (!sr.isSuccess())
                {
                    Database.Error err = sr.getErrors()[0];
                    ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.ERROR,err.getMessage())); 
                }
                else
                {
                    intSuccess += 1;
                    system.debug('Successfully inserted NI Cancellation record. NI CANCELLATION ID: ' + sr.getId());
                }
            }
            ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Total NI Cancellation records created:  ' + intSuccess));
        }
        
        return null;
        
    }      
    
    //============================================================================================================                  
    // WRAPPER CLASS 
    //============================================================================================================ 
    public class childAccountWrapper
    {
        
        public Asset di {get; set;}
        public Boolean isSelected {get; set;}
//        public Boolean isDisabled {get; set;}
//        public Boolean disableEdit {get; set;}
//        public Boolean disableSave {get; set;}
//        public Boolean disableCancel {get; set;}
        public Id idAsset {get; set;}
        
        public childAccountWrapper(Asset a) 
        {
            di = a;
            idAsset = di.Id;
            isSelected = false;
        }
        
    }
    
}