force-app/main/default/objects/NI_Global_Acceptance_Criterion__c/NI_Global_Acceptance_Criterion__c.object-meta.xml
<CustomObject>
    <description>Salesforce.com Change Request: NICC-018290

Used to capture acceptance criteria for NI Project Backlog records</description>
    <label>Global Acceptance Criterion</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Acceptance Criterion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Global Acceptance Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_Global_Acceptance_Criterion__c/fields/Applicable_Object__c.field-meta.xml
<CustomField>
    <fullName>Applicable_Object__c</fullName>
    <label>Applicable Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Object_List</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NI_Global_Acceptance_Criterion__c/fields/Given__c.field-meta.xml
<CustomField>
    <fullName>Given__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>&quot;Given&quot;  statement of the acceptance criterion logic.  These are the conditions that must be met in order to initiate the acceptance criterion.  For example:  &quot;Given that I am logged in as System Admin...&quot;</inlineHelpText>
    <label>Given</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NI_Global_Acceptance_Criterion__c/fields/Then__c.field-meta.xml
<CustomField>
    <fullName>Then__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>&quot;Then&quot; statement of the acceptance criterion.  This is what the outcome should be</inlineHelpText>
    <label>Then</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NI_Project_Acceptance_Criterion__c/NI_Project_Acceptance_Criterion__c.object-meta.xml
<CustomObject>
    <label>Project Acceptance Criterion</label>
    <nameField>
        <displayFormat>PAC-{00000}</displayFormat>
        <label>Acceptance Criterion</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Acceptance Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_Project_Acceptance_Criterion__c/fields/Applicable_Object__c.field-meta.xml
<CustomField>
    <fullName>Applicable_Object__c</fullName>
    <label>Applicable Object</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Object_List</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NI_Project_Acceptance_Criterion__c/fields/Given__c.field-meta.xml
<CustomField>
    <fullName>Given__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>&quot;Given&quot;  statement of the acceptance criterion logic.  These are the conditions that must be met in order to initiate the acceptance criterion.  For example:  &quot;Given that I am logged in as System Admin...&quot;</inlineHelpText>
    <label>Given</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NI_Project_Acceptance_Criterion__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_Project_Acceptance_Criterion__c/fields/NI_Global_Acceptance_Criterion__c.field-meta.xml
<CustomField>
    <fullName>NI_Global_Acceptance_Criterion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Global Acceptance Criterion</label>
    <referenceTo>NI_Global_Acceptance_Criterion__c</referenceTo>
    <relationshipLabel>Project Acceptance Criteria</relationshipLabel>
    <relationshipName>Project_Acceptance_Criteria</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Project_Acceptance_Criterion__c/fields/NI_Project_Backlog__c.field-meta.xml
<CustomField>
    <fullName>NI_Project_Backlog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>NI_Project_Backlog__c</referenceTo>
    <relationshipName>Project_Acceptance_Criteria</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Project_Acceptance_Criterion__c/fields/Then__c.field-meta.xml
<CustomField>
    <fullName>Then__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>&quot;Then&quot; statement of the acceptance criterion.  This is what the outcome should be</inlineHelpText>
    <label>Then</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NI_Project_Acceptance_Criterion__c/fields/When__c.field-meta.xml
<CustomField>
    <fullName>When__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>&quot;When&quot; statement of the acceptance criterion.  This is the action that is being performed in order to achieve the desired outcome.  For example:  &quot;When I click the submit for approval button...&quot;</inlineHelpText>
    <label>When</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NI_Project_Backlog__c/NI_Project_Backlog__c.object-meta.xml
<CustomObject>
    <description>Updated 12/19/2020 per NICC-047197:  Changed Object Label to &quot;AH Project Backlog&quot;
Corporate Systems related projects that are submitted to IT, and executed by the IT Business Systems Team.</description>
    <label>AH Project Backlog</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AH Project Backlog</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Object_List.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acceptance Criterion</fullName>
    </customValue>
    <customValue>
        <fullName>Accolade</fullName>
    </customValue>
    <customValue>
        <fullName>Account</fullName>
    </customValue>
    <customValue>
        <fullName>Account Association</fullName>
    </customValue>
    <customValue>
        <fullName>Account Group</fullName>
    </customValue>
    <customValue>
        <fullName>Account Group Line</fullName>
    </customValue>
    <customValue>
        <fullName>Account Order History</fullName>
    </customValue>
    <customValue>
        <fullName>Acct Plan</fullName>
    </customValue>
    <customValue>
        <fullName>Activity Line Item</fullName>
    </customValue>
    <customValue>
        <fullName>AH_Case_Solution</fullName>
    </customValue>
    <customValue>
        <fullName>AH_ Related Opportunity Line items</fullName>
    </customValue>
    <customValue>
        <fullName>AH Batch Apex Result</fullName>
    </customValue>
    <customValue>
        <fullName>AH Case Flag Preferences</fullName>
    </customValue>
    <customValue>
        <fullName>AH Case Flags History Tracking</fullName>
    </customValue>
    <customValue>
        <fullName>AH Case Flags Store Types</fullName>
    </customValue>
    <customValue>
        <fullName>AH CRS Billing Notification</fullName>
    </customValue>
    <customValue>
        <fullName>AH Error Log</fullName>
    </customValue>
    <customValue>
        <fullName>AH FFA Sales Invoice Trigger Handler</fullName>
    </customValue>
    <customValue>
        <fullName>AH IT Request CR Field Mapping</fullName>
    </customValue>
    <customValue>
        <fullName>AH IT Request CR Record Type Mapping</fullName>
    </customValue>
    <customValue>
        <fullName>AH IT Request Settings</fullName>
    </customValue>
    <customValue>
        <fullName>AH Milestone Settings</fullName>
    </customValue>
    <customValue>
        <fullName>AH Opportunity Related Account</fullName>
    </customValue>
    <customValue>
        <fullName>AH Partner Community Record Share</fullName>
    </customValue>
    <customValue>
        <fullName>AH Products Family-Unit</fullName>
    </customValue>
    <customValue>
        <fullName>AH Requisition Fields to Clone</fullName>
    </customValue>
    <customValue>
        <fullName>AH Salesforce Instance</fullName>
    </customValue>
    <customValue>
        <fullName>AH Salesforce Instance to Notification</fullName>
    </customValue>
    <customValue>
        <fullName>AH Salesforce Trust Impact/Event</fullName>
    </customValue>
    <customValue>
        <fullName>AH Salesforce Trust Notification</fullName>
    </customValue>
    <masterLabel>Object List</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/DetailUpdateButtonController_Test.cls
/****************************************************************************************
Name            : DetailUpdateButtonController_Test Class
Author          : Supriya Galinde
Created Date    : 3/20/2017
Last Mod Date   : 4/6/2017
Last Mod By     : Supriya Galinde
NICC Reference  : 
Description     : test Class for DetailUpdateButtonController Class
:  
******************************************************************************************/
@isTest
public class DetailUpdateButtonController_Test 
{
    static testMethod void testMethod1()
    {
        
        List<NI_Project_Backlog__c> projBacklogList = new List<NI_Project_Backlog__c>();
        NI_Project_Backlog__c projBacklog1 = NI_TestClassData.createTestProjectBacklog(1);
        projBacklogList.add(projBacklog1);
        insert projBacklogList;
        
        List<NI_Global_Acceptance_Criterion__c> gacList = new List<NI_Global_Acceptance_Criterion__c>();
        NI_Global_Acceptance_Criterion__c objGac1 = NI_TestClassData.createTestGAC(1, 'Account');
        insert objGac1;
        
        NI_Project_Acceptance_Criterion__c objPac1 = NI_TestClassData.createTestPAC(1, projBacklog1.Id, 'Account');
        insert objPac1;
        
        objPac1.Then__c = 'Test Then123';
        update objPac1;
        
        objGac1 = [SELECT Name,Given__c,when__c,then__c, Applicable_Object__c FROM NI_Global_Acceptance_Criterion__c WHERE Name ='Test GAC 1'];
        DetailUpdateButtonController.updateGAC(objPac1.Id);
        
        List<NI_Project_Acceptance_Criterion__c> lstPAC = new List<NI_Project_Acceptance_Criterion__c>();
        lstPAC = [select Name__c,Applicable_Object__c, Given__c,when__c,then__c from NI_Project_Acceptance_Criterion__c where Name__c = 'Test Name1'];
        system.debug('lstPAC'+lstPAC);
        
        List<NI_Global_Acceptance_Criterion__c> lstGAC = new List<NI_Global_Acceptance_Criterion__c>();
        lstGAC = [select Name,Given__c,when__c,then__c, Applicable_Object__c from NI_Global_Acceptance_Criterion__c where Name = 'Test Name1'];
        system.debug('lstGAc'+lstGAC);
        
        System.assertEquals(objPAC1.Then__c, 'Test Then123');
    }
    
    static testMethod void testMethod2()
    { 
        List<NI_Project_Backlog__c> projBacklogList = new List<NI_Project_Backlog__c>();
        NI_Project_Backlog__c projBacklog2 = NI_TestClassData.createTestProjectBacklog(2);
        projBacklogList.add(projBacklog2);
        insert projBacklogList;
        
        NI_Project_Acceptance_Criterion__c objPac2 = NI_TestClassData.createTestPAC(2, projBacklog2.Id, 'Account');
        insert objPac2;
        
        objPac2.Name__c = 'Test Name123';
        update objPac2;
        
        DetailUpdateButtonController.updateGAC(objPAC2.Id);
        List<NI_Project_Acceptance_Criterion__c> lstPAC2 = new List<NI_Project_Acceptance_Criterion__c>();
        lstPAC2 = [select Name__c,Applicable_Object__c,Given__c,when__c,then__c from NI_Project_Acceptance_Criterion__c where Name__c = 'Test Name2'];
        system.debug('lstPAC2'+lstPAC2);
        
        System.assertEquals(objPac2.Name__c, 'Test Name123');
    }
}