force-app/main/default/objects/NI_Global_Acceptance_Criterion__c/NI_Global_Acceptance_Criterion__c.object-meta.xml
<CustomObject>
    <description>Salesforce.com Change Request: NICC-018290

Used to capture acceptance criteria for NI Project Backlog records</description>
    <label>Global Acceptance Criterion</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Acceptance Criterion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Global Acceptance Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_Project_Acceptance_Criterion__c/NI_Project_Acceptance_Criterion__c.object-meta.xml
<CustomObject>
    <label>Project Acceptance Criterion</label>
    <nameField>
        <displayFormat>PAC-{00000}</displayFormat>
        <label>Acceptance Criterion</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Acceptance Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_Project_Acceptance_Criterion__c/fields/NI_Global_Acceptance_Criterion__c.field-meta.xml
<CustomField>
    <fullName>NI_Global_Acceptance_Criterion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Global Acceptance Criterion</label>
    <referenceTo>NI_Global_Acceptance_Criterion__c</referenceTo>
    <relationshipLabel>Project Acceptance Criteria</relationshipLabel>
    <relationshipName>Project_Acceptance_Criteria</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Project_Acceptance_Criterion__c/fields/NI_Project_Backlog__c.field-meta.xml
<CustomField>
    <fullName>NI_Project_Backlog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>NI_Project_Backlog__c</referenceTo>
    <relationshipName>Project_Acceptance_Criteria</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Project_Backlog__c/NI_Project_Backlog__c.object-meta.xml
<CustomObject>
    <description>Updated 12/19/2020 per NICC-047197:  Changed Object Label to &quot;AH Project Backlog&quot;
Corporate Systems related projects that are submitted to IT, and executed by the IT Business Systems Team.</description>
    <label>AH Project Backlog</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AH Project Backlog</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/NI_GAC_TriggerHandler_Test.cls
/****************************************************************************************
Name            : NI_GAC_TriggerHandler_Test Class
Author          : Supriya Galinde
Created Date    : 3/20/2017
Last Mod Date   : 4/6/2017
Last Mod By     : Supriya Galinde
NICC Reference  : NICC-021925 
Description     : test Class for NI_Global_Acceptance_TriggerHandler Class
				:  
******************************************************************************************/
@isTest
public class NI_GAC_TriggerHandler_Test 
{
    static testMethod void testMethod1()
    {
        List<NI_Project_Backlog__c> projBacklogList = new List<NI_Project_Backlog__c>();
        NI_Project_Backlog__c projBacklog1 = NI_TestClassData.createTestProjectBacklog(1);
        projBacklogList.add(projBacklog1);
        insert projBacklogList;
        
        NI_Project_Acceptance_Criterion__c objPac1 = NI_TestClassData.createTestPAC(1, projBacklog1.Id, 'Account');
        insert objPac1;
        
        List<NI_Global_Acceptance_Criterion__c> gacList = new List<NI_Global_Acceptance_Criterion__c>();
        NI_Global_Acceptance_Criterion__c objGac1 = NI_TestClassData.createTestGAC(1, 'Account');
        insert objGac1;
        
        objPac1.NI_Global_Acceptance_Criterion__c = objGac1.Id;
        update objPac1;
        
        System.assertEquals(objPac1.NI_Global_Acceptance_Criterion__c, objGac1.Id);
    }
}