force-app/main/default/objects/NI_Global_Acceptance_Criterion__c/NI_Global_Acceptance_Criterion__c.object-meta.xml
<CustomObject>
    <description>Salesforce.com Change Request: NICC-018290

Used to capture acceptance criteria for NI Project Backlog records</description>
    <label>Global Acceptance Criterion</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Acceptance Criterion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Global Acceptance Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_Global_Acceptance_Criterion__c/fields/Applicable_Object__c.field-meta.xml
<CustomField>
    <fullName>Applicable_Object__c</fullName>
    <label>Applicable Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Object_List</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NI_Global_Acceptance_Criterion__c/fields/Given__c.field-meta.xml
<CustomField>
    <fullName>Given__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>&quot;Given&quot;  statement of the acceptance criterion logic.  These are the conditions that must be met in order to initiate the acceptance criterion.  For example:  &quot;Given that I am logged in as System Admin...&quot;</inlineHelpText>
    <label>Given</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NI_Global_Acceptance_Criterion__c/fields/Then__c.field-meta.xml
<CustomField>
    <fullName>Then__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>&quot;Then&quot; statement of the acceptance criterion.  This is what the outcome should be</inlineHelpText>
    <label>Then</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NI_Project_Acceptance_Criterion__c/NI_Project_Acceptance_Criterion__c.object-meta.xml
<CustomObject>
    <label>Project Acceptance Criterion</label>
    <nameField>
        <displayFormat>PAC-{00000}</displayFormat>
        <label>Acceptance Criterion</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Acceptance Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_Project_Acceptance_Criterion__c/fields/Applicable_Object__c.field-meta.xml
<CustomField>
    <fullName>Applicable_Object__c</fullName>
    <label>Applicable Object</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Object_List</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NI_Project_Acceptance_Criterion__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Comments</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/NI_Project_Acceptance_Criterion__c/fields/Developer_Org_Status__c.field-meta.xml
<CustomField>
    <fullName>Developer_Org_Status__c</fullName>
    <description>Status for the Developer Org</description>
    <label>Developer Org Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NI_Project_Acceptance_Criterion__c/fields/Given__c.field-meta.xml
<CustomField>
    <fullName>Given__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>&quot;Given&quot;  statement of the acceptance criterion logic.  These are the conditions that must be met in order to initiate the acceptance criterion.  For example:  &quot;Given that I am logged in as System Admin...&quot;</inlineHelpText>
    <label>Given</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NI_Project_Acceptance_Criterion__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_Project_Acceptance_Criterion__c/fields/NI_Global_Acceptance_Criterion__c.field-meta.xml
<CustomField>
    <fullName>NI_Global_Acceptance_Criterion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Global Acceptance Criterion</label>
    <referenceTo>NI_Global_Acceptance_Criterion__c</referenceTo>
    <relationshipLabel>Project Acceptance Criteria</relationshipLabel>
    <relationshipName>Project_Acceptance_Criteria</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Project_Acceptance_Criterion__c/fields/NI_Project_Backlog__c.field-meta.xml
<CustomField>
    <fullName>NI_Project_Backlog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>NI_Project_Backlog__c</referenceTo>
    <relationshipName>Project_Acceptance_Criteria</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Project_Acceptance_Criterion__c/fields/Production_Org_Status__c.field-meta.xml
<CustomField>
    <fullName>Production_Org_Status__c</fullName>
    <description>Acceptance criterion Status for the Production org</description>
    <label>Production Org Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NI_Project_Acceptance_Criterion__c/fields/QA_Org_Status__c.field-meta.xml
<CustomField>
    <fullName>QA_Org_Status__c</fullName>
    <description>Acceptance criterion Status in the QA org.  If you are not using a QA org, select &quot;N/A&quot;</description>
    <label>QA Org Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NI_Project_Acceptance_Criterion__c/fields/Then__c.field-meta.xml
<CustomField>
    <fullName>Then__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>&quot;Then&quot; statement of the acceptance criterion.  This is what the outcome should be</inlineHelpText>
    <label>Then</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NI_Project_Acceptance_Criterion__c/fields/UAT_Org_Status__c.field-meta.xml
<CustomField>
    <fullName>UAT_Org_Status__c</fullName>
    <description>Acceptance criterion Status for the UAT org.</description>
    <label>UAT Org Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NI_Project_Acceptance_Criterion__c/fields/When__c.field-meta.xml
<CustomField>
    <fullName>When__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>&quot;When&quot; statement of the acceptance criterion.  This is the action that is being performed in order to achieve the desired outcome.  For example:  &quot;When I click the submit for approval button...&quot;</inlineHelpText>
    <label>When</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NI_Project_Backlog__c/NI_Project_Backlog__c.object-meta.xml
<CustomObject>
    <description>Updated 12/19/2020 per NICC-047197:  Changed Object Label to &quot;AH Project Backlog&quot;
Corporate Systems related projects that are submitted to IT, and executed by the IT Business Systems Team.</description>
    <label>AH Project Backlog</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AH Project Backlog</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Object_List.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acceptance Criterion</fullName>
    </customValue>
    <customValue>
        <fullName>Accolade</fullName>
    </customValue>
    <customValue>
        <fullName>Account</fullName>
    </customValue>
    <customValue>
        <fullName>Account Association</fullName>
    </customValue>
    <customValue>
        <fullName>Account Group</fullName>
    </customValue>
    <customValue>
        <fullName>Account Group Line</fullName>
    </customValue>
    <customValue>
        <fullName>Account Order History</fullName>
    </customValue>
    <customValue>
        <fullName>Acct Plan</fullName>
    </customValue>
    <customValue>
        <fullName>Activity Line Item</fullName>
    </customValue>
    <customValue>
        <fullName>AH_Case_Solution</fullName>
    </customValue>
    <customValue>
        <fullName>AH_ Related Opportunity Line items</fullName>
    </customValue>
    <customValue>
        <fullName>AH Batch Apex Result</fullName>
    </customValue>
    <customValue>
        <fullName>AH Case Flag Preferences</fullName>
    </customValue>
    <customValue>
        <fullName>AH Case Flags History Tracking</fullName>
    </customValue>
    <customValue>
        <fullName>AH Case Flags Store Types</fullName>
    </customValue>
    <customValue>
        <fullName>AH CRS Billing Notification</fullName>
    </customValue>
    <customValue>
        <fullName>AH Error Log</fullName>
    </customValue>
    <customValue>
        <fullName>AH FFA Sales Invoice Trigger Handler</fullName>
    </customValue>
    <customValue>
        <fullName>AH IT Request CR Field Mapping</fullName>
    </customValue>
    <customValue>
        <fullName>AH IT Request CR Record Type Mapping</fullName>
    </customValue>
    <customValue>
        <fullName>AH IT Request Settings</fullName>
    </customValue>
    <customValue>
        <fullName>AH Milestone Settings</fullName>
    </customValue>
    <customValue>
        <fullName>AH Opportunity Related Account</fullName>
    </customValue>
    <customValue>
        <fullName>AH Partner Community Record Share</fullName>
    </customValue>
    <customValue>
        <fullName>AH Products Family-Unit</fullName>
    </customValue>
    <customValue>
        <fullName>AH Requisition Fields to Clone</fullName>
    </customValue>
    <customValue>
        <fullName>AH Salesforce Instance</fullName>
    </customValue>
    <customValue>
        <fullName>AH Salesforce Instance to Notification</fullName>
    </customValue>
    <customValue>
        <fullName>AH Salesforce Trust Impact/Event</fullName>
    </customValue>
    <customValue>
        <fullName>AH Salesforce Trust Notification</fullName>
    </customValue>
    <masterLabel>Object List</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/NI_PACEditPageController.cls
/************************************************************************************************
Name            : NI_PACEditPageController  Class
Author          : Supriya Galinde
Created Date    : 4/3/2017
Last Mod Date   : 4/6/2017
Last Mod By     : Supriya Galinde
NICC Reference  : 
Description     : Class that handles code for the Edit button on Project Acceptance Criterion Visualforce page.
:
*************************************************************************************************/
public class NI_PACEditPageController {
    Id ProjectId;    
    public NI_Project_Acceptance_Criterion__c pacObject{get; set;}
    public NI_Global_Acceptance_Criterion__c objGlobal{get; set;}
    public NI_Global_Acceptance_Criterion__c objGlobalOnSave{get; set;}
    public Boolean executeJS{get; set;}
    //List<NI_Global_Acceptance_Criterion__c> gacList = new List<NI_Global_Acceptance_Criterion__c>();        
    private ApexPages.StandardController controller;
    
    /*public NI_PACEditPageController(){
        
    }*/
    
    //Below constructor will get the record id of a controller. 
    public NI_PACEditPageController(ApexPages.StandardController controller){
        this.controller = controller; 
        projectId = controller.getRecord().id;
        
        pacObject = new NI_Project_Acceptance_Criterion__c();
        pacObject = [SELECT Id, Name, Name__c, NI_Global_Acceptance_Criterion__c, NI_Project_Backlog__c, Given__c, 
                     When__c, Then__c, Applicable_Object__c, Production_Org_Status__c, 
                     UAT_Org_Status__c, Developer_Org_Status__c,QA_Org_Status__c, Comments__c 
                     FROM NI_Project_Acceptance_Criterion__c WHERE Id =: projectId]; 
        
        objGlobal = new NI_Global_Acceptance_Criterion__c();        
        
        if(pacObject.NI_Global_Acceptance_Criterion__c != null){
            system.debug('in if1');
            objGlobal = [SELECT Id,Name, Given__c, When__c, Then__c FROM NI_Global_Acceptance_Criterion__c 
                         WHERE Id =: pacObject.NI_Global_Acceptance_Criterion__c];
            system.debug('objGlobal'+objGlobal);            
        }
    }
    
    //For cancel button. When user edits the name field and click on cancel button without saving the record the user gets a popup to save the record 
    //with the matching name of GAC.
    public PageReference DoCancel(){
        executeJS = true;
        try{
            system.debug('Pac Name======>'+pacObject.Name__c);
            system.debug('Pac Name======>'+pacObject.NI_Global_Acceptance_Criterion__c);
            if(pacObject.Name__c == null || pacObject.Name__c != objGlobal.Name){
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Save the record with matching Name of Global Acceptance Criterion.');
                ApexPages.addMessage(myMsg);
                return null;             
            }
            else{
                PageReference orderPage = new PageReference('/'+pacObject.id);
                orderPage.setRedirect(true);
                return orderPage;
            }   
        }
        Catch(Exception e){
            system.debug('Exception due to ----->'+e.getMessage()+e.getLineNumber());
            return null;
        }       
    } 
    
    //for save button click. It will check if name is same and then will save the record and will 
    //update the remaining fields in PAC else it will display an error message.
    public Pagereference DoSave(){
        executeJS = false;
        system.debug('pacObject.Name__c'+pacObject.Name__c);
        system.debug('pacObject.NI_Global_Acceptance_Criterion__c'+pacObject.NI_Global_Acceptance_Criterion__c);
        if(pacObject.NI_Global_Acceptance_Criterion__c != null){
            objGlobalOnSave = [SELECT Id, Name FROM NI_Global_Acceptance_Criterion__c 
                         WHERE Id =: pacObject.NI_Global_Acceptance_Criterion__c];
        }
        try{
            if(objGlobalOnSave != null && pacObject.Name__c == objGlobalOnSave.Name){
                update pacObject;
                PageReference orderPage = new PageReference('/'+pacObject.id);
                orderPage.setRedirect(true);
                return orderPage;          
            }  
            else{
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Save the record with matching Name of GAC.');
                ApexPages.addMessage(myMsg);
                return null;
            }  
        }
        Catch(Exception e){
            system.debug('Exception due to ----->'+e.getMessage()+e.getLineNumber());
            return null;
        }       
    }
    
    //Save & New will save a record and redirect to a new page. While saving it will check if the name of PAC and GAC is same if not then
    //receive a error message which will say to save a record with matching name. 
    public PageReference DoSaveNew() {
        executeJS = false;
        Id id = controller.getId();
        Boolean saveAndNew = false;
         if(pacObject.NI_Global_Acceptance_Criterion__c != null){
            objGlobalOnSave = [SELECT Id, Name FROM NI_Global_Acceptance_Criterion__c 
                         WHERE Id =: pacObject.NI_Global_Acceptance_Criterion__c];
        }
        system.debug('id'+id);
        //if name is equal then update PAC.
        if(objGlobalOnSave != null && pacObject.Name__c == objGlobalOnSave.Name)
        {
            system.debug('match names');
            update pacObject;
            saveAndNew = true;          
        }
        //name dosesn't match then show error message.
        else
        {
            system.debug('in else err');
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'Save the record with matching Name of GAC.');
            ApexPages.addMessage(myMsg);
            return null;
        } 
        //redirect to new page.
        if(saveAndNew){
            Apexpages.currentPage().setRedirect(true);
            return new PageReference('/'+controller.getRecord().getSObjectType().getDescribe().getKeyPrefix()+'/e?retURL='+pacObject.Id);
        }
        else
            return null;
    }
}