force-app/main/default/objects/NI_Global_Acceptance_Criterion__c/NI_Global_Acceptance_Criterion__c.object-meta.xml
<CustomObject>
    <description>Salesforce.com Change Request: NICC-018290

Used to capture acceptance criteria for NI Project Backlog records</description>
    <label>Global Acceptance Criterion</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Acceptance Criterion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Global Acceptance Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_Global_Acceptance_Criterion__c/fields/Applicable_Object__c.field-meta.xml
<CustomField>
    <fullName>Applicable_Object__c</fullName>
    <label>Applicable Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Object_List</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NI_Global_Acceptance_Criterion__c/fields/Given__c.field-meta.xml
<CustomField>
    <fullName>Given__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>&quot;Given&quot;  statement of the acceptance criterion logic.  These are the conditions that must be met in order to initiate the acceptance criterion.  For example:  &quot;Given that I am logged in as System Admin...&quot;</inlineHelpText>
    <label>Given</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NI_Global_Acceptance_Criterion__c/fields/Then__c.field-meta.xml
<CustomField>
    <fullName>Then__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>&quot;Then&quot; statement of the acceptance criterion.  This is what the outcome should be</inlineHelpText>
    <label>Then</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NI_Project_Acceptance_Criterion__c/NI_Project_Acceptance_Criterion__c.object-meta.xml
<CustomObject>
    <label>Project Acceptance Criterion</label>
    <nameField>
        <displayFormat>PAC-{00000}</displayFormat>
        <label>Acceptance Criterion</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Acceptance Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_Project_Acceptance_Criterion__c/fields/Applicable_Object__c.field-meta.xml
<CustomField>
    <fullName>Applicable_Object__c</fullName>
    <label>Applicable Object</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Object_List</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NI_Project_Acceptance_Criterion__c/fields/Given__c.field-meta.xml
<CustomField>
    <fullName>Given__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>&quot;Given&quot;  statement of the acceptance criterion logic.  These are the conditions that must be met in order to initiate the acceptance criterion.  For example:  &quot;Given that I am logged in as System Admin...&quot;</inlineHelpText>
    <label>Given</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NI_Project_Acceptance_Criterion__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_Project_Acceptance_Criterion__c/fields/NI_Global_Acceptance_Criterion__c.field-meta.xml
<CustomField>
    <fullName>NI_Global_Acceptance_Criterion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Global Acceptance Criterion</label>
    <referenceTo>NI_Global_Acceptance_Criterion__c</referenceTo>
    <relationshipLabel>Project Acceptance Criteria</relationshipLabel>
    <relationshipName>Project_Acceptance_Criteria</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Project_Acceptance_Criterion__c/fields/Then__c.field-meta.xml
<CustomField>
    <fullName>Then__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>&quot;Then&quot; statement of the acceptance criterion.  This is what the outcome should be</inlineHelpText>
    <label>Then</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NI_Project_Acceptance_Criterion__c/fields/When__c.field-meta.xml
<CustomField>
    <fullName>When__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>&quot;When&quot; statement of the acceptance criterion.  This is the action that is being performed in order to achieve the desired outcome.  For example:  &quot;When I click the submit for approval button...&quot;</inlineHelpText>
    <label>When</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/globalValueSets/Object_List.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acceptance Criterion</fullName>
    </customValue>
    <customValue>
        <fullName>Accolade</fullName>
    </customValue>
    <customValue>
        <fullName>Account</fullName>
    </customValue>
    <customValue>
        <fullName>Account Association</fullName>
    </customValue>
    <customValue>
        <fullName>Account Group</fullName>
    </customValue>
    <customValue>
        <fullName>Account Group Line</fullName>
    </customValue>
    <customValue>
        <fullName>Account Order History</fullName>
    </customValue>
    <customValue>
        <fullName>Acct Plan</fullName>
    </customValue>
    <customValue>
        <fullName>Activity Line Item</fullName>
    </customValue>
    <customValue>
        <fullName>AH_Case_Solution</fullName>
    </customValue>
    <customValue>
        <fullName>AH_ Related Opportunity Line items</fullName>
    </customValue>
    <customValue>
        <fullName>AH Batch Apex Result</fullName>
    </customValue>
    <customValue>
        <fullName>AH Case Flag Preferences</fullName>
    </customValue>
    <customValue>
        <fullName>AH Case Flags History Tracking</fullName>
    </customValue>
    <customValue>
        <fullName>AH Case Flags Store Types</fullName>
    </customValue>
    <customValue>
        <fullName>AH CRS Billing Notification</fullName>
    </customValue>
    <customValue>
        <fullName>AH Error Log</fullName>
    </customValue>
    <customValue>
        <fullName>AH FFA Sales Invoice Trigger Handler</fullName>
    </customValue>
    <customValue>
        <fullName>AH IT Request CR Field Mapping</fullName>
    </customValue>
    <customValue>
        <fullName>AH IT Request CR Record Type Mapping</fullName>
    </customValue>
    <customValue>
        <fullName>AH IT Request Settings</fullName>
    </customValue>
    <customValue>
        <fullName>AH Milestone Settings</fullName>
    </customValue>
    <customValue>
        <fullName>AH Opportunity Related Account</fullName>
    </customValue>
    <customValue>
        <fullName>AH Partner Community Record Share</fullName>
    </customValue>
    <customValue>
        <fullName>AH Products Family-Unit</fullName>
    </customValue>
    <customValue>
        <fullName>AH Requisition Fields to Clone</fullName>
    </customValue>
    <customValue>
        <fullName>AH Salesforce Instance</fullName>
    </customValue>
    <customValue>
        <fullName>AH Salesforce Instance to Notification</fullName>
    </customValue>
    <customValue>
        <fullName>AH Salesforce Trust Impact/Event</fullName>
    </customValue>
    <customValue>
        <fullName>AH Salesforce Trust Notification</fullName>
    </customValue>
    <masterLabel>Object List</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/DetailUpdateButtonController.cls
/************************************************************************************************
Name            : DetailUpdateButtonController  Class
Author          : Supriya Galinde
Created Date    : 3/20/2017
Last Mod Date   : 4/6/2017
Last Mod By     : Supriya Galinde
NICC Reference  : 
Description     : Class that handles code for the UpdateGlobal onclick javascript Button.
:
*************************************************************************************************/
global class DetailUpdateButtonController 
{
    global static NI_Project_Acceptance_Criterion__c objProject {get;set;}
    global static NI_Global_Acceptance_Criterion__c objGlobal {get;set;}
    global static string Message {get;set;}
    
    webservice static String updateGAC(Id ProjectId)
    {
        
        system.debug('in updateGAC');
        List<NI_Global_Acceptance_Criterion__c> gacList = new List<NI_Global_Acceptance_Criterion__c>();
        objGlobal = new NI_Global_Acceptance_Criterion__c();
        objProject =  [SELECT id, Name__c, Given__c, When__c,Then__c, NI_Global_Acceptance_Criterion__c, Applicable_Object__c
                       FROM NI_Project_Acceptance_Criterion__c WHERE id =: ProjectId];
        
        //get NI_Global_Acceptance_Criterion__c from lookup field of PAC in GAC id.
        if(objProject.NI_Global_Acceptance_Criterion__c != null)
        {
            system.debug('in if1');
            objGlobal = [SELECT id,Name,Given__c,When__c,Then__c, Applicable_Object__c FROM NI_Global_Acceptance_Criterion__c 
                         where Id=: objProject.NI_Global_Acceptance_Criterion__c];
            system.debug('objGlobal'+objGlobal);
        }
        else
        {
            system.debug('in else');
            message = 'No GAC to update.';
        }
        
        system.debug('objGlobal');
        //message = 'GAC have same Name, Given, When, Then';
        
        if(objGlobal.id != null)
        {
            //if PAC Name__c is equal to GAC Name and when we clik on update Global button then update the GAC fields to match the fields in PAC.
            if(objProject.Name__c == objGlobal.Name)
            {
                system.debug('in if2');
                if((objProject.Name__c == objGlobal.Name) && 
                   (objProject.Given__c != objGlobal.Given__c ||
                    objProject.When__c != objGlobal.When__c ||
                    objProject.Then__c != objGlobal.Then__c || 
                   	objProject.Applicable_Object__c != objGlobal.Applicable_Object__c))
                {
                    objGlobal.Given__c = objProject.Given__c ;
                    objGlobal.When__c = objProject.When__c ;
                    objGlobal.Then__c = objProject.Then__c ;
                    objGlobal.Applicable_Object__c = objProject.Applicable_Object__c;
                    //update objGlobal;
                    gacList.add(objGlobal);
                    system.debug('objGlobal' + objGlobal);
                    message = 'GAC updated succesfully';
                }
                else
                {
                     message = 'GAC have same Name, Given, When, Then';
                }
            }
            //if PAC Name__c is not equal to GAC Name and we try to update the name__c field on PAC then display an error message
            else
            {
                message = 'You cannot update the Name on an existing Global Acceptance Criterion record';
            }
            
        }
        if(!gacList.isEmpty()){
            update gacList;
            system.debug('gacList'+gacList);
        }

            return message;
        
        //PageReference orderPage = new PageReference('/force_OrderDetail?id=' + NI_Global_Acceptance_Criterion__c.id);
        //orderPage.setRedirect(true);
        //return orderPage;
    }
}