force-app/main/default/objects/NI_Global_Acceptance_Criterion__c/NI_Global_Acceptance_Criterion__c.object-meta.xml
<CustomObject>
    <description>Salesforce.com Change Request: NICC-018290

Used to capture acceptance criteria for NI Project Backlog records</description>
    <label>Global Acceptance Criterion</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Acceptance Criterion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Global Acceptance Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_Global_Acceptance_Criterion__c/fields/Then__c.field-meta.xml
<CustomField>
    <fullName>Then__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>&quot;Then&quot; statement of the acceptance criterion.  This is what the outcome should be</inlineHelpText>
    <label>Then</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NI_Project_Acceptance_Criterion__c/NI_Project_Acceptance_Criterion__c.object-meta.xml
<CustomObject>
    <label>Project Acceptance Criterion</label>
    <nameField>
        <displayFormat>PAC-{00000}</displayFormat>
        <label>Acceptance Criterion</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Acceptance Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_Project_Acceptance_Criterion__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_Project_Acceptance_Criterion__c/fields/NI_Global_Acceptance_Criterion__c.field-meta.xml
<CustomField>
    <fullName>NI_Global_Acceptance_Criterion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Global Acceptance Criterion</label>
    <referenceTo>NI_Global_Acceptance_Criterion__c</referenceTo>
    <relationshipLabel>Project Acceptance Criteria</relationshipLabel>
    <relationshipName>Project_Acceptance_Criteria</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Project_Acceptance_Criterion__c/fields/NI_Project_Backlog__c.field-meta.xml
<CustomField>
    <fullName>NI_Project_Backlog__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>NI_Project_Backlog__c</referenceTo>
    <relationshipName>Project_Acceptance_Criteria</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Project_Acceptance_Criterion__c/fields/Then__c.field-meta.xml
<CustomField>
    <fullName>Then__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>&quot;Then&quot; statement of the acceptance criterion.  This is what the outcome should be</inlineHelpText>
    <label>Then</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NI_Project_Backlog__c/NI_Project_Backlog__c.object-meta.xml
<CustomObject>
    <description>Updated 12/19/2020 per NICC-047197:  Changed Object Label to &quot;AH Project Backlog&quot;
Corporate Systems related projects that are submitted to IT, and executed by the IT Business Systems Team.</description>
    <label>AH Project Backlog</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Project Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AH Project Backlog</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/NI_PacEditPageCntrlTest.cls
/****************************************************************************************
Name            : NI_PacEditPageCntrlTest Class
Author          : Supriya Galinde
Created Date    : 3/20/2017
Last Mod Date   : 4/11/2017
Last Mod By     : Supriya Galinde
NICC Reference  : 
Description     : test Class for NI_PACEditPageController Class
:  
******************************************************************************************/
@isTest
public class NI_PacEditPageCntrlTest 
{
    static testMethod void testMethod1()
    {
        NI_Project_Backlog__c objProjectBacklog = NI_TestClassData.createTestProjectBacklog(1);
		insert objProjectBacklog;
        
         NI_Global_Acceptance_Criterion__c objGAC1 = NI_TestClassData.createTestGAC(1, 'Account');
         objGAC1.Name = 'Test PAC 1';
         insert objGAC1;
        
        NI_Project_Acceptance_Criterion__c objPAC1 = NI_TestClassData.createTestPAC(1, objProjectBacklog.Id, 'Acceptance Criterion');
         objPac1.NI_Global_Acceptance_Criterion__c = objGac1.Id;
         insert objPAC1;
        
        ApexPages.StandardController stdLead = new ApexPages.StandardController(objPAC1);
		NI_PACEditPageController pacCntrl = new NI_PACEditPageController(stdLead);
        objPAC1.Then__c = 'Test Then123';
        update objPAC1;       
        
        pacCntrl.DoSave();
        pacCntrl.DoSaveNew();
        pacCntrl.DoCancel();
        System.assertEquals(objPAC1.Then__c, 'Test Then123');
    }
    
    static testMethod void testMethod2()
    {
        NI_Project_Backlog__c objProjectBacklog = NI_TestClassData.createTestProjectBacklog(1);
		insert objProjectBacklog;
        
         NI_Global_Acceptance_Criterion__c objGAC2 = NI_TestClassData.createTestGAC(1, 'Acceptance Criterion');
         insert objGAC2;
        
        NI_Project_Acceptance_Criterion__c objPAC2 = NI_TestClassData.createTestPAC(1, objProjectBacklog.Id, 'Acceptance Criterion');
         objPAC2.NI_Global_Acceptance_Criterion__c = objGac2.Id;
         insert objPAC2;
        
        objPAC2.Name__c = 'Test Name123';
        update objPAC2;   
        
        ApexPages.StandardController stdCntrl = new ApexPages.StandardController(objPAC2);
		NI_PACEditPageController pacCntrl = new NI_PACEditPageController(stdCntrl);
        objPAC2.Then__c = 'Test Then123';
        update objPAC2;     
        
        pacCntrl.DoSave();
        pacCntrl.DoSaveNew();
        pacCntrl.DoCancel();
        
        System.assertEquals(objPAC2.Name__c, 'Test Name123');
    }
}