force-app/main/default/objects/NI_Org_Details__c/NI_Org_Details__c.object-meta.xml
<CustomObject>
    <description>Holds Org/Account specific details such as subscription connection credentials.</description>
    <label>NI Org Details</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Org Details ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Org Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_Org_Details__c/fields/AdminLoginName__c.field-meta.xml
<CustomField>
    <fullName>AdminLoginName__c</fullName>
    <description>This field has been replaced by the Admin Login Name (Encrypted) (Admin_Login_Name_Encrypted__c) field</description>
    <encryptionScheme>None</encryptionScheme>
    <label>DO NOT USE Admin Login Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_Org_Details__c/fields/AdminPassword__c.field-meta.xml
<CustomField>
    <fullName>AdminPassword__c</fullName>
    <description>This field has been replaced by the &quot;Admin Password (Encrypted)&quot; field</description>
    <encryptionScheme>None</encryptionScheme>
    <label>DO NOT USE Admin Password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_Org_Details__c/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Salesforce.com Change Request: NICC-006294

Indicates if an org detail is inactive</description>
    <inlineHelpText>Indicates if an org detail is inactive</inlineHelpText>
    <label>Inactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NI_Org_Details__c/fields/License_Type__c.field-meta.xml
<CustomField>
    <fullName>License_Type__c</fullName>
    <description>Salesforce.com Change Request: NICC-006916</description>
    <inlineHelpText>Type of License</inlineHelpText>
    <label>License Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Embedded</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Mixed</fullName>
            </value>
            <value>
                <fullName>Sales Cloud</fullName>
            </value>
            <value>
                <fullName>Embedded Plus</fullName>
            </value>
            <value>
                <fullName>EDA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NI_Org_Details__c/fields/Org_ID__c.field-meta.xml
<CustomField>
    <fullName>Org_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Org ID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/NI_Org_Details__c/fields/Org_Name__c.field-meta.xml
<CustomField>
    <fullName>Org_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Org Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_Org_Details__c/fields/Org_Status__c.field-meta.xml
<CustomField>
    <fullName>Org_Status__c</fullName>
    <complianceGroup>Normal</complianceGroup>
    <description>Salesforce.com Change Request: NICC-006967

Requested on Behalf of Suzanne LeDuc: 

I need a way to indicate if an org is in trial. I&apos;m thinking instead of another check box, having a picklist called Org Status with the values: created, provisioned, In process, Trial, Demo</description>
    <inlineHelpText>Status of the Org</inlineHelpText>
    <label>Org Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Demo</fullName>
            </value>
            <value>
                <fullName>In process</fullName>
            </value>
            <value>
                <fullName>Not Active</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>Trial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NI_Org_Details_to_Accounts__c/NI_Org_Details_to_Accounts__c.object-meta.xml
<CustomObject>
    <description>Junction Object between NI Org Details and Account</description>
    <label>NI Org Details to Accounts</label>
    <nameField>
        <displayFormat>OD-{000000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NI Org Details to Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/NI_Location_TriggerHandler_Test.cls
/************************************************************************************************
Name            : NI_Location_TriggerHandler_Test Class
Author          : Suzanne LeDuc
Created Date    : 09/10/2015
Last Mod Date   : 09/10/2015
Last Mod By     : Sean Harris
NICC Reference  : NICC-014223
Description     : Class that tests NI_Location_TriggerHandler Class
                :
                :
*************************************************************************************************/
@isTest
public class NI_Location_TriggerHandler_Test  
{
 
    
    // ======================================================================================================================================= 
    // CREATE TEST DATA
    // ======================================================================================================================================= 
    @testSetup static void createTestData() 
    {
        
		system.debug(' *** START NI_Location_TriggerHandler_Test.createTestData() - QUERIES ISSUED = ' + Limits.getQueries());	
        
        Test.startTest();
        
		// CREATE TEST ACCOUNT RECORD 
        List<Account> lstAccountInserts = new List<Account>();
        
        Account a1 = NI_TestClassData.createTestAccount(1);
        a1.Name = 'NI_Location_TriggerHandler_Test ACCOUNT';
        lstAccountInserts.add(a1);  
        
        Account a2 = NI_TestClassData.CreateTestAccount(2);
        lstAccountInserts.add(a2);  
        
        database.insert(lstAccountInserts);
                                       
        // CREATE TEST ORG DETAIL RECORD
        Id rtInit = Schema.SObjectType.NI_Org_Details__c.getRecordTypeInfosByName().get('LOD Support Admin').getRecordTypeId();
        NI_Org_Details__c od = NI_TestClassData.createTestNiOrgDetails(rtInit, 1, 'Salesforce Production');
        
        od.Org_Name__c = a1.Name;
        od.Org_Id__c = 'XXXXXXXXXX00001';
        od.AdminLoginName__c = 'test@test.com';
        od.AdminPassword__c = '123456789';
        od.License_Type__c =  'Enterprise';
        od.Org_Status__c = 'In Process';
        od.Inactive__c = false;
		insert od;

        // CREATE NI_Org_Details_to_Accounts__c RECORD
        NI_Org_Details_to_Accounts__c O2A = NI_TestClassData.createTestNIOrgDetails2Accounts(od.Id, a1.Id); 
        insert O2A;
        
        // CREATE newmarketsvcs__IServer__c RECORD
        newmarketsvcs__IServer__c nwsSys = NI_TestClassData.CreateTestNWS_IServer(1, 'Org.XXXXXXXXXX00001@Delphi.fdc');
        nwsSys.newmarketsvcs__NewmarketUser__c = 'Org.XXXXXXXXXX00001@Delphi.fdc';
        insert nwsSys;

        // CREATE newmarketsvcs__Location__c RECORD
        newmarketsvcs__Location__c nwsLoc = NI_TestClassData.createTestNWS_Location(1, nwsSys.Id, a1.Id);
        nwsLoc.newmarketsvcs__Master_Location__c = a1.Id;
        nwsLoc.newmarketsvcs__IServerID__c = nwsSys.Id;
        nwsLoc.newmarketsvcs__Name__c = 'Test';
        nwsLoc.newmarketsvcs__Source_System_Type__c = 'Delphifdc'; 
        insert nwsLoc;    
        
        nwsLoc.newmarketsvcs__City__c = 'Portsmith';
        update nwsLoc;

        // Update the Location
        nwsLoc.newmarketsvcs__Master_Location__c = a2.Id;
        update nwsLoc;

		system.debug(' *** END NI_Location_TriggerHandler_Test.createTestData() - QUERIES ISSUED = ' + Limits.getQueries());	
        
    }
       
    // ======================================================================================================================================= 
    // = TEST METHOD 1: 
    // ======================================================================================================================================= 
    @isTest static void test1() 
    {
        
        system.debug(' *** START NI_Location_TriggerHandler_Test.test1() - QUERIES ISSUED = ' + Limits.getQueries());	
        
        Account a1 = [SELECT Id, Name FROM Account WHERE Name = 'NI_Location_TriggerHandler_Test ACCOUNT'];
        
        Test.startTest();
        

        // CREATE TEST ORG DETAILS RECORD
        Id rtInit = Schema.SObjectType.NI_Org_Details__c.getRecordTypeInfosByName().get('HRM Support Admin').getRecordTypeId();
        
        NI_Org_Details__c o = NI_TestClassData.createTestNiOrgDetails(rtInit, 1, 'Salesforce Production');
        o.Org_Name__c = a1.Name;
        o.AdminLoginName__c = 'test@test.com';
        o.AdminPassword__c = '123456789';
        o.License_Type__c = 'Enterprise';
        o.Org_Status__c = 'In Process';
        o.Inactive__c = false;        
        insert o;
        
        // CREATE TEST ORG DETAILS TO ACCOUNT RECORD
        NI_Org_Details_to_Accounts__c o2a = NI_TestClassData.createTestNIOrgDetails2Accounts(o.Id, a1.Id); 
        insert o2a;
        
        // CREATE TEST ISERVER "SYSTEM" RECORD
        newmarketsvcs__IServer__c nwsSystem = new newmarketsvcs__IServer__c();
        nwsSystem.newmarketsvcs__IServer_ID__c = 'IS-99999';
        nwsSystem.newmarketsvcs__NewmarketUser__c = 'Org.' + String.valueOf(o.Id) + '@Delphi.fdc';
        insert nwsSystem;
        
        // CREATE TEST LOCATION RECORD
        newmarketsvcs__Location__c loc1 = new newmarketsvcs__Location__c();
        loc1.newmarketsvcs__Master_Location__c = a1.Id;
        loc1.newmarketsvcs__IServerID__c = nwsSystem.Id;
        loc1.newmarketsvcs__Name__c = 'Test';
        loc1.newmarketsvcs__Source_System_Type__c = 'Delphifdc';
        insert loc1;
        
        Test.stopTest();
        
        system.debug(' ***  END  NI_Location_TriggerHandler_Test.test1() - QUERIES ISSUED = ' + Limits.getQueries());	
        
    }        
   
}