force-app/main/default/objects/NI_Org_Details__c/NI_Org_Details__c.object-meta.xml
<CustomObject>
    <description>Holds Org/Account specific details such as subscription connection credentials.</description>
    <label>NI Org Details</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Org Details ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Org Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_Org_Details__c/fields/AdminLoginName__c.field-meta.xml
<CustomField>
    <fullName>AdminLoginName__c</fullName>
    <description>This field has been replaced by the Admin Login Name (Encrypted) (Admin_Login_Name_Encrypted__c) field</description>
    <encryptionScheme>None</encryptionScheme>
    <label>DO NOT USE Admin Login Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_Org_Details__c/fields/AdminPassword__c.field-meta.xml
<CustomField>
    <fullName>AdminPassword__c</fullName>
    <description>This field has been replaced by the &quot;Admin Password (Encrypted)&quot; field</description>
    <encryptionScheme>None</encryptionScheme>
    <label>DO NOT USE Admin Password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_Org_Details__c/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Salesforce.com Change Request: NICC-006294

Indicates if an org detail is inactive</description>
    <inlineHelpText>Indicates if an org detail is inactive</inlineHelpText>
    <label>Inactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NI_Org_Details__c/fields/License_Type__c.field-meta.xml
<CustomField>
    <fullName>License_Type__c</fullName>
    <description>Salesforce.com Change Request: NICC-006916</description>
    <inlineHelpText>Type of License</inlineHelpText>
    <label>License Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Embedded</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Mixed</fullName>
            </value>
            <value>
                <fullName>Sales Cloud</fullName>
            </value>
            <value>
                <fullName>Embedded Plus</fullName>
            </value>
            <value>
                <fullName>EDA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NI_Org_Details__c/fields/Org_ID__c.field-meta.xml
<CustomField>
    <fullName>Org_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Org ID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/NI_Org_Details__c/fields/Org_Name__c.field-meta.xml
<CustomField>
    <fullName>Org_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Org Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_Org_Details__c/fields/Org_Status__c.field-meta.xml
<CustomField>
    <fullName>Org_Status__c</fullName>
    <complianceGroup>Normal</complianceGroup>
    <description>Salesforce.com Change Request: NICC-006967

Requested on Behalf of Suzanne LeDuc: 

I need a way to indicate if an org is in trial. I&apos;m thinking instead of another check box, having a picklist called Org Status with the values: created, provisioned, In process, Trial, Demo</description>
    <inlineHelpText>Status of the Org</inlineHelpText>
    <label>Org Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Demo</fullName>
            </value>
            <value>
                <fullName>In process</fullName>
            </value>
            <value>
                <fullName>Not Active</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>Trial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NI_TriggerBypassSwitches__c/NI_TriggerBypassSwitches__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>NICC-010252: Global Custom Setting for Trigger Bypassing

Used to turn off code execution on triggers globally or per specific object(s).</description>
    <label>NI Trigger Bypass Switches</label>
</CustomObject>

force-app/main/default/objects/NI_TriggerBypassSwitches__c/fields/BypassNWSIServer_ON__c.field-meta.xml
<CustomField>
    <fullName>BypassNWSIServer_ON__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass NWS IServer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/NI_IServer_TriggerHandler_Test.cls
/************************************************************************************************
Name            : NI_IServer_TriggerHandler_Test Class
Author          : Suzanne LeDuc
Created Date    : 09/10/2015
Last Mod Date   : 08/02/2019
Last Mod By     : Bhuleshwar Deshpande
NICC Reference  : NICC-014223
Description     : Class that tests NI_IServer_TriggerHandler_Test Class
                :
                :
*************************************************************************************************/
@isTest
public class NI_IServer_TriggerHandler_Test 
{
    
    
    public static testMethod void NI_IServerInsertHandlerTest() 
    {
        ///Create Org Details Record
        Account a = NI_TestClassData.CreateTestAccount(1);
        
        NI_Org_Details__c orgDetails = NI_TestClassData.createTestNiOrgDetails( '01260000000DnbPAAS',1,'Salesforce Production');
        insert orgDetails;
        
        //Create System Record
        newmarketsvcs__IServer__c nwsSystem = new newmarketsvcs__IServer__c();
        nwsSystem.newmarketsvcs__IServer_ID__c = 'IS-99999';
        nwsSystem.newmarketsvcs__NewmarketUser__c = 'Org.00D00000000abce@Delphi.fdc';
        insert nwsSystem;
        
       

    }
    
    
    
    // ======================================================================================================================================= //
    // = BULK INSERT TEST
    // ======================================================================================================================================= //
    public static testMethod void NWS_Newmarketsvcs_IServer_BulkTest() 
    {    
        
        List<NI_Org_Details__c> lstOrgDetailsInsert = new List<NI_Org_Details__c>();
        List<newmarketsvcs__IServer__c> lstNWS_IServerInsert = new List<newmarketsvcs__IServer__c>();
        
        Id rtInit = NI_TestClassData.getRecordTypeId('NI_Org_Details__c', 'LOD Support Admin');   
        
        String s = '00000';
        
        /**********
        NI_TriggerBypassSwitches__c niNWSCustomSetting = new NI_TriggerBypassSwitches__c();         
        niNWSCustomSetting.Name = 'BypassNWSIServer_ON__c';        
        niNWSCustomSetting.BypassNWSIServer_ON__c = true;        
        insert niNWSCustomSetting;
        
        List<NI_TriggerBypassSwitches__c> custLst = [Select id,BypassNWSIServer_ON__c from NI_TriggerBypassSwitches__c];
        system.debug('custLst' + custLst);
        //update niNWSCustomSetting;
        ***********/
        // CREATE TEST ACCOUNT RECORD
        Account a = NI_TestClassData.CreateTestAccount(1);
        insert a;        
        
		test.startTest();        
        // CREATE 200+ ORG DETAILS & NWS I-SERVER RECORDS 
        for (integer i = 2; (i < 202); i++)
        {
            NI_Org_Details__c od = NI_TestClassData.createTestNiOrgDetails(rtInit, 1, 'Salesforce Production');
            
            od.Org_Name__c = a.Name;
            string strOrgId = 'XXXXXXXXXX' + s.Substring(0, (s.Length() - String.valueOf(i).Length())) + String.valueOf(i);
            od.Org_ID__c = strOrgId;
            od.AdminLoginName__c = 'test@test.com';
            od.AdminPassword__c = '123456789';
            od.License_Type__c =  'Enterprise';
            od.Org_Status__c = 'In Process';
            od.Inactive__c = false;
            
            lstOrgDetailsInsert.add(od);   
            
           
            newmarketsvcs__IServer__c nwsSys = NI_TestClassData.CreateTestNWS_IServer(i, 'Org.' + strOrgId + '@Delphi.fdc');
            lstNWS_IServerInsert.add(nwsSys);
            
        }
        
        Database.insert(lstOrgDetailsInsert);
        
        Database.insert(lstNWS_IServerInsert);
        
        test.stopTest();
        
    }   
    
    public static testMethod void NI_IServerInsertHandlerNegativeTest() 
    {
        ///Create Org Details Record
        Account a = NI_TestClassData.CreateTestAccount(1);
        
        NI_Org_Details__c orgDetails = NI_TestClassData.createTestNiOrgDetails( '01260000000DnbPAAS',1,'Salesforce Production');
        insert orgDetails;
        
        //Create System Record
        newmarketsvcs__IServer__c nwsSystem = new newmarketsvcs__IServer__c();
        nwsSystem.newmarketsvcs__IServer_ID__c = 'IS-99999';
        //nwsSystem.newmarketsvcs__NewmarketUser__c = 'Org.00D00000000abce@Delphi.fdc';
        insert nwsSystem;
        
    }

}