force-app/main/default/objects/NI_Org_Details__c/NI_Org_Details__c.object-meta.xml
<CustomObject>
    <description>Holds Org/Account specific details such as subscription connection credentials.</description>
    <label>NI Org Details</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Org Details ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Org Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_Org_Details__c/fields/Data_Storage__c.field-meta.xml
<CustomField>
    <fullName>Data_Storage__c</fullName>
    <complianceGroup>Normal</complianceGroup>
    <label>Current Data Storage (GB)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NI_Org_Details__c/fields/Data_Storage_Limit__c.field-meta.xml
<CustomField>
    <fullName>Data_Storage_Limit__c</fullName>
    <label>Purchased Data Storage (GB)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NI_Org_Details__c/fields/File_Storage_Percent_Used__c.field-meta.xml
<CustomField>
    <fullName>File_Storage_Percent_Used__c</fullName>
    <complianceGroup>Normal</complianceGroup>
    <encryptionScheme>None</encryptionScheme>
    <label>File Storage Percent Used</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_Org_Details__c/fields/Org_ID__c.field-meta.xml
<CustomField>
    <fullName>Org_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Org ID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/NI_Org_Details__c/fields/ParentAccountId__c.field-meta.xml
<CustomField>
    <fullName>ParentAccountId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Parent Account Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_Org_Details__c/fields/Purchased_Limited_Users__c.field-meta.xml
<CustomField>
    <fullName>Purchased_Limited_Users__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Purchased Limited Users</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NI_Org_Details__c/fields/Shared_Org__c.field-meta.xml
<CustomField>
    <fullName>Shared_Org__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Salesforce.com Change Request: NICC-006916</description>
    <inlineHelpText>Salesforce org that is CRM that has had the HRM application installed in it. Newmarket cannot sell licenses to these orgs, we can only service the application</inlineHelpText>
    <label>Shared Org</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/NI_Org_Details_TriggerHandler_Test.cls
/****************************************************************************************
Name            : NI_Org_Details_TriggerHandler Class_Test Test Class
Author          : Stuart Emery
Created Date    : 7/16/2013
Last Mod Date   : 8/8/2014 - NICC-011439
Last Mod By     : Stuart Emery
NICC Reference  : 
Description     : test Class for NI_Org_Details_TriggerHandler Class
: 
: 
******************************************************************************************/
@isTest (SeeAllData=true)
private class NI_Org_Details_TriggerHandler_Test 
{
    
    static testMethod void myUnitTest() 
    {    
        
        NI_Org_Details_TriggerHandler handler = new NI_Org_Details_TriggerHandler(true);
        boolean IsTriggerContext = handler.IsTriggerContext;        
        
        Id rtInit = NI_TestClassData.getRecordTypeId('NI_Org_Details__c', 'LOD Support Admin');
        
        Account a = NI_TestClassData.createTestAccount(1);
        insert a;
        
        //GET THE ORGANIZATION ID OF THE CURRENT USER  
        String orgId = UserInfo.getOrganizationId();
        orgId = orgId.substring(0, 15); //SET THE ORGID TO THE 15 CHARACTER ORGID
        
        NI_Org_Details__c od = NI_TestClassData.createTestNiOrgDetails(rtInit, 1, 'Salesforce Production');
        od.ParentAccountId__c = a.Id;
        //od.Org_ID__c = '00DA0000000abcd';
        od.Org_ID__c = orgId;
        insert od;
        
    } 
    
    static testMethod void testUpdate() 
    {    
        
        NI_Org_Details_TriggerHandler handler = new NI_Org_Details_TriggerHandler(true);
        boolean IsTriggerContext = handler.IsTriggerContext;        
        
        Id rtInit = NI_TestClassData.getRecordTypeId('NI_Org_Details__c', 'LOD Support Admin');
        
        Account a = NI_TestClassData.createTestAccount(1);
        insert a;
        
        //GET THE ORGANIZATION ID OF THE CURRENT USER  
        String orgId = UserInfo.getOrganizationId();
        orgId = orgId.substring(0, 15); //SET THE ORGID TO THE 15 CHARACTER ORGID
        
        NI_Org_Details__c od = NI_TestClassData.createTestNiOrgDetails(rtInit, 1, 'Salesforce Production');
        od.ParentAccountId__c = a.Id;
        od.File_Storage_Percent_Used__c = '10000';
        od.Data_Storage_Limit__c = 100;
        od.Data_Storage__c = 110;
        //od.Org_ID__c = '00DA0000000abcd';
        od.Org_ID__c = orgId;
        od.Purchased_Limited_Users__c = 2;
        od.Shared_Org__c = false ; 
        insert od;
        
        od.File_Storage_Percent_Used__c = '100';
        od.Data_Storage_Limit__c = 120;
        od.Purchased_Limited_Users__c = -2;
        od.Shared_Org__c = true;
        update od;
        
    }   
    
    static testMethod void testUpdate1()
    {
         NI_Org_Details_TriggerHandler handler = new NI_Org_Details_TriggerHandler(true);
        boolean IsTriggerContext = handler.IsTriggerContext;        
        
        Id rtInit = NI_TestClassData.getRecordTypeId('NI_Org_Details__c', 'LOD Support Admin');
        
        Account a = NI_TestClassData.createTestAccount(1);
        insert a;
        
        //GET THE ORGANIZATION ID OF THE CURRENT USER  
        String orgId = UserInfo.getOrganizationId();
        orgId = orgId.substring(0, 15); //SET THE ORGID TO THE 15 CHARACTER ORGID
        
        NI_Org_Details__c od = NI_TestClassData.createTestNiOrgDetails(rtInit, 1, 'Salesforce Production');
        od.ParentAccountId__c = a.Id;
        od.File_Storage_Percent_Used__c = '100';
        od.Data_Storage_Limit__c = 120;
        od.Data_Storage__c = 110;
        //od.Org_ID__c = '00DA0000000abcd';
        od.Org_ID__c = orgId;
        od.Purchased_Limited_Users__c = -2;
        od.Shared_Org__c = true;
        insert od;
        
        od.File_Storage_Percent_Used__c = '1000';
        od.Data_Storage_Limit__c = 100;
        od.Purchased_Limited_Users__c = 2;
        od.Shared_Org__c = false;
        update od;
    }
    
    static testMethod void testUpdate2() 
    {    
        
        NI_Org_Details_TriggerHandler handler = new NI_Org_Details_TriggerHandler(true);
        boolean IsTriggerContext = handler.IsTriggerContext;        
        
        Id rtInit = NI_TestClassData.getRecordTypeId('NI_Org_Details__c', 'LOD Support Admin');
        
        Account a = NI_TestClassData.createTestAccount(1);
        insert a;
        
        //GET THE ORGANIZATION ID OF THE CURRENT USER  
        String orgId = UserInfo.getOrganizationId();
        orgId = orgId.substring(0, 15); //SET THE ORGID TO THE 15 CHARACTER ORGID
        
        NI_Org_Details__c od = NI_TestClassData.createTestNiOrgDetails(rtInit, 1, 'Salesforce Production');
        od.ParentAccountId__c = a.Id;
        //od.File_Storage_Percent_Used__c = '10000';
        //od.Data_Storage_Limit__c = 23;
        //od.Org_ID__c = '00DA0000000abcd';
        od.Org_ID__c = orgId;
        insert od;
        
        od.File_Storage_Percent_Used__c = '100';
        od.Data_Storage_Limit__c = 23;
        update od;
        
    }      
    
}