force-app/main/default/objects/NI_Org_Details__c/NI_Org_Details__c.object-meta.xml
<CustomObject>
    <description>Holds Org/Account specific details such as subscription connection credentials.</description>
    <label>NI Org Details</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Org Details ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Org Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_Org_Details__c/fields/Admin_Login_Name_Encrypted__c.field-meta.xml
<CustomField>
    <fullName>Admin_Login_Name_Encrypted__c</fullName>
    <description>Salesforce.com Change Request: NICC-015316

Encrypted field</description>
    <inlineHelpText>The admin user login name for the org.  This is an encrypted field</inlineHelpText>
    <label>Admin Login Name (Encrypted)</label>
    <length>100</length>
    <maskChar>X</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/NI_Org_Details__c/fields/Admin_Password_Encrypted__c.field-meta.xml
<CustomField>
    <fullName>Admin_Password_Encrypted__c</fullName>
    <complianceGroup>Normal</complianceGroup>
    <description>Salesforce.com Change Request: NICC-015316

Encrypted field</description>
    <inlineHelpText>The admin user password.  This is an encrypted field</inlineHelpText>
    <label>Admin Password (Encrypted)</label>
    <length>100</length>
    <maskChar>X</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/NI_Org_Details__c/fields/Org_Name__c.field-meta.xml
<CustomField>
    <fullName>Org_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Org Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_Org_Details__c/fields/Org_Type__c.field-meta.xml
<CustomField>
    <fullName>Org_Type__c</fullName>
    <description>Salesforce.com Change Request: NICC-007567

Used to identify the type of environment that the org detail record represents. There can be a Production Org and various Sandbox Orgs.</description>
    <inlineHelpText>Type of environment</inlineHelpText>
    <label>Org Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce Production</fullName>
            </value>
            <value>
                <fullName>Salesforce Sandbox - Configuration Only</fullName>
            </value>
            <value>
                <fullName>Salesforce Sandbox - Developer</fullName>
            </value>
            <value>
                <fullName>Salesforce Sandbox - Full</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NI_Org_Details__c/fields/Primary_Account__c.field-meta.xml
<CustomField>
    <fullName>Primary_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Management Company or main Account in the Org.</inlineHelpText>
    <label>Primary Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Org Details (Main Account)</relationshipLabel>
    <relationshipName>Org_Details1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Org_Details__c/fields/Security_Token_Encrypted__c.field-meta.xml
<CustomField>
    <fullName>Security_Token_Encrypted__c</fullName>
    <description>Salesforce.com Change Request: NICC-015316

Encrypted field</description>
    <inlineHelpText>The security token for the admin user.  This is an encrypted field.</inlineHelpText>
    <label>Security Token (Encrypted)</label>
    <length>100</length>
    <maskChar>X</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/NI_Org_Details_Installed_Packages__c/NI_Org_Details_Installed_Packages__c.object-meta.xml
<CustomObject>
    <label>NI Org Details Installed Packages</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NI Org Details Installed Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_Org_Details_Installed_Packages__c/fields/Allowed_Licenses__c.field-meta.xml
<CustomField>
    <fullName>Allowed_Licenses__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Allowed Licenses</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_Org_Details_Installed_Packages__c/fields/Apps__c.field-meta.xml
<CustomField>
    <fullName>Apps__c</fullName>
    <label>Apps</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NI_Org_Details_Installed_Packages__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <complianceGroup>Normal</complianceGroup>
    <encryptionScheme>None</encryptionScheme>
    <label>Expiration Date</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_Org_Details_Installed_Packages__c/fields/Install_Date__c.field-meta.xml
<CustomField>
    <fullName>Install_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Install Date</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_Org_Details_Installed_Packages__c/fields/Limits__c.field-meta.xml
<CustomField>
    <fullName>Limits__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Limits</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NI_Org_Details_Installed_Packages__c/fields/Managed__c.field-meta.xml
<CustomField>
    <fullName>Managed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Managed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NI_Org_Details_Installed_Packages__c/fields/Namespace_Prefix__c.field-meta.xml
<CustomField>
    <fullName>Namespace_Prefix__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Namespace Prefix</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_Org_Details_Installed_Packages__c/fields/NI_Org_Details__c.field-meta.xml
<CustomField>
    <fullName>NI_Org_Details__c</fullName>
    <label>NI Org Details</label>
    <referenceTo>NI_Org_Details__c</referenceTo>
    <relationshipLabel>NI Org Details Installed Packages</relationshipLabel>
    <relationshipName>NI_Org_Details_Installed_Packages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NI_Org_Details_Installed_Packages__c/fields/Objects__c.field-meta.xml
<CustomField>
    <fullName>Objects__c</fullName>
    <complianceGroup>Normal</complianceGroup>
    <label>Objects</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NI_Org_Details_Installed_Packages__c/fields/Publisher__c.field-meta.xml
<CustomField>
    <fullName>Publisher__c</fullName>
    <complianceGroup>Normal</complianceGroup>
    <encryptionScheme>None</encryptionScheme>
    <label>Publisher</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_Org_Details_Installed_Packages__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <complianceGroup>Normal</complianceGroup>
    <encryptionScheme>None</encryptionScheme>
    <label>Status</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_Org_Details_Installed_Packages__c/fields/Tabs__c.field-meta.xml
<CustomField>
    <fullName>Tabs__c</fullName>
    <label>Tabs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NI_Org_Details_Installed_Packages__c/fields/Used_Licenses__c.field-meta.xml
<CustomField>
    <fullName>Used_Licenses__c</fullName>
    <complianceGroup>Normal</complianceGroup>
    <encryptionScheme>None</encryptionScheme>
    <label>Used Licenses</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_Org_Details_Installed_Packages__c/fields/Version_Number__c.field-meta.xml
<CustomField>
    <fullName>Version_Number__c</fullName>
    <complianceGroup>Normal</complianceGroup>
    <encryptionScheme>None</encryptionScheme>
    <label>Version Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PollingResult__c/PollingResult__c.object-meta.xml
<CustomObject>
    <description>Salesforce.com Change Request: NICC-006221

Used for the HRM Monitoring Tools. Monitor how our customers are using the HRM application and whether there are any issues in their deployments, such as storage overage, etc.</description>
    <label>Polling Result</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Polling Result Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Polling Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PollingResult__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <complianceGroup>Normal</complianceGroup>
    <label>NI Org</label>
    <referenceTo>NI_Org_Details__c</referenceTo>
    <relationshipLabel>Polling Results</relationshipLabel>
    <relationshipName>Polling_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PollingResult__c/fields/ApiAllocation__c.field-meta.xml
<CustomField>
    <fullName>ApiAllocation__c</fullName>
    <complianceGroup>Normal</complianceGroup>
    <label>Api Allocation</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PollingResult__c/fields/DataStorageAllocation__c.field-meta.xml
<CustomField>
    <fullName>DataStorageAllocation__c</fullName>
    <label>Data Storage Allocation</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PollingResult__c/fields/DataStorageUsage__c.field-meta.xml
<CustomField>
    <fullName>DataStorageUsage__c</fullName>
    <label>Data Storage Usage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PollingResult__c/fields/DateTime__c.field-meta.xml
<CustomField>
    <fullName>DateTime__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/PollingResult__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <complianceGroup>Normal</complianceGroup>
    <encryptionScheme>None</encryptionScheme>
    <label>Error</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PollingResult__c/fields/ErrorOccured__c.field-meta.xml
<CustomField>
    <fullName>ErrorOccured__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Error Occured</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PollingResult__c/fields/ErrorType__c.field-meta.xml
<CustomField>
    <fullName>ErrorType__c</fullName>
    <complianceGroup>Normal</complianceGroup>
    <encryptionScheme>None</encryptionScheme>
    <label>Error Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PollingResult__c/fields/HRMPackageVersion__c.field-meta.xml
<CustomField>
    <fullName>HRMPackageVersion__c</fullName>
    <complianceGroup>Normal</complianceGroup>
    <encryptionScheme>None</encryptionScheme>
    <label>HRM Package Version</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PollingResult__c/fields/PackageExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>PackageExpirationDate__c</fullName>
    <complianceGroup>Normal</complianceGroup>
    <encryptionScheme>None</encryptionScheme>
    <label>Package Expiration Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PollingResult__c/fields/PackageStatus__c.field-meta.xml
<CustomField>
    <fullName>PackageStatus__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Package Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PollingResult__c/fields/PackageUsedLicenses__c.field-meta.xml
<CustomField>
    <fullName>PackageUsedLicenses__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Package Used Licenses</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PollingResult__c/fields/TotalActiveSalesforcePlatformUsers__c.field-meta.xml
<CustomField>
    <fullName>TotalActiveSalesforcePlatformUsers__c</fullName>
    <label>Total Active Salesforce Platform Users</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PollingResult__c/fields/TotalEmailCampaigns__c.field-meta.xml
<CustomField>
    <fullName>TotalEmailCampaigns__c</fullName>
    <label>Total Email Campaigns</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PollingResult__c/fields/TotalLicensedSalesforcePlatformUsers__c.field-meta.xml
<CustomField>
    <fullName>TotalLicensedSalesforcePlatformUsers__c</fullName>
    <complianceGroup>Normal</complianceGroup>
    <label>TotalLicensed Salesforce Platform Users</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PollingResult__c/fields/TotalLicensedSalesforceUsers__c.field-meta.xml
<CustomField>
    <fullName>TotalLicensedSalesforceUsers__c</fullName>
    <complianceGroup>Normal</complianceGroup>
    <label>Total Licensed Salesforce Users</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PollingResult__c/fields/TotalMemberAccounts__c.field-meta.xml
<CustomField>
    <fullName>TotalMemberAccounts__c</fullName>
    <label>Total Member Accounts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PollingResult__c/fields/TotalReservations__c.field-meta.xml
<CustomField>
    <fullName>TotalReservations__c</fullName>
    <complianceGroup>Normal</complianceGroup>
    <label>Total Reservations</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PollingResult__c/fields/UnmanagedCustomApps__c.field-meta.xml
<CustomField>
    <fullName>UnmanagedCustomApps__c</fullName>
    <complianceGroup>Normal</complianceGroup>
    <label>Unmanaged Custom Apps</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/FillAccount_Test.cls
/****************************************************************************************
Name            : FillAccount_Test Class
Author          : Sean Harris
Created Date    : 11/21/2016
Last Mod Date   : 04/25/2019
Last Mod By     : Shashikant Nikam
NICC Reference  : 
Description     : Test Class for the FillAccount_Test Class 
                : 
                : 
******************************************************************************************/
@isTest
public class FillAccount_Test 
{

    // ======================================================================================================================================= //
    // = CREATE TEST DATA
    // ======================================================================================================================================= 
    @testSetup static void createTestData() 
    {    

        // CREATE 2 ORG DETAILS RECORDS WITH DIFFERENT ORG TYPES AND ASSERT THEY WERE CREATED ================================================
        Id rtInit = NI_TestClassData.getRecordTypeId('NI_Org_Details__c', 'LOD Support Admin');       

        NI_Org_Details__c odProd = NI_TestClassData.createTestNiOrgDetails(rtInit, 1, 'Salesforce Production');  
        odProd.Org_Type__c = 'Salesforce Production';
        NI_Org_Details__c odSand = NI_TestClassData.createTestNiOrgDetails(rtInit, 2, 'Salesforce Sandbox'); 
        odSand.Org_Type__c = 'Salesforce Sandbox - Full';
        
        List<NI_Org_Details__c> lstOrgDetailInsert = new List<NI_Org_Details__c>();
        lstOrgDetailInsert.Add(odProd);
        lstOrgDetailInsert.Add(odSand);
        
        system.debug('odProd=='+odProd);
        system.debug('odSand=='+odSand);
        
        Database.Insert(lstOrgDetailInsert);
        
        List<NI_Org_Details__c> lstOrgDetailAsserts1 = new List<NI_Org_Details__c>([SELECT Id FROM NI_Org_Details__c WHERE Org_Name__c = 'TEST1' AND Org_Type__c = 'Salesforce Production']);
        system.debug('lstOrgDetailAsserts1=='+lstOrgDetailAsserts1);
        system.assertEquals(1, lstOrgDetailAsserts1.Size());
        
        List<NI_Org_Details__c> lstOrgDetailAsserts2 = new List<NI_Org_Details__c>([SELECT Id FROM NI_Org_Details__c WHERE Org_Name__c = 'TEST2' AND Org_Type__c = 'Salesforce Sandbox - Full']);
        system.debug('lstOrgDetailAsserts2=='+lstOrgDetailAsserts2);
        system.assertEquals(1, lstOrgDetailAsserts2.Size());
        
        /*NI_Org_Details_Installed_Packages__c:{Id=aJgq000000000ObCAI, 
        Name=Salesforce1 and Chatter Apps, Namespace_Prefix__c=sf_chttr_apps, 
        Publisher__c=Salesforce.com, NI_Org_Details__c=a4Oq00000004wjnEAA, 
        Managed__c=true, Install_Date__c=11/16/2015 4:58 PM, 
        Version_Number__c=1.11, Status__c=Free,
        Allowed_Licenses__c=N/A, Used_Licenses__c=N/A, 
        Expiration_Date__c=N/A, Limits__c=false, Apps__c=0, Tabs__c=0, Objects__c=0})*/
        
        NI_Org_Details_Installed_Packages__c insPkg = new NI_Org_Details_Installed_Packages__c();
        insPkg.Name='Salesforce1 and Chatter Apps';
        insPkg.Namespace_Prefix__c='sf_chttr_apps_test';
        insPkg.Publisher__c='Salesforce.com';
        insPkg.NI_Org_Details__c=lstOrgDetailAsserts2[0].Id;
        insert insPkg;
        
        
        
        /*Package_Namespace_Preefix__mdt pckPrefix = new Package_Namespace_Preefix__mdt();
        pckPrefix.DeveloperName = 'HRM';
        insert pckPrefix;*/
        
    }

    // ======================================================================================================================================= //
    // = TEST METHOD 1: 
    // ======================================================================================================================================= //
    
    @isTest static void fillAccountTestError()
    {

        FillAccount fillAccount = new FillAccount();

        fillAccount.isTest = true;
        RecordType rt = [SELECT Name, Id FROM RecordType WHERE sObjectType = 'NI_Org_Details__c' AND Name  = 'LOD Support Admin' AND isActive = true];
        Id rtInit =  rt.Id;
        String orgId = UserInfo.getOrganizationId();
        
        orgId = orgId.substring(0, 15); //SET THE ORGID TO THE 15 CHARACTER ORGID
        account primacc = NI_TestClassData.createTestAccount(1);
        primacc.c2g__CODABankAccountName__c = 'FFA Bank';
        primacc.c2g__CODABankAccountNumber__c = '007';
		primacc.c2g__CODABankCity__c = 'Pune';
        primacc.c2g__CODABankCountry__c = 'India';
        primacc.c2g__CODABankName__c = 'ABC Corp.';
        primacc.c2g__CODABankStateProvince__c = 'Maharashtra';
        primacc.c2g__CODABankSWIFTNumber__c = '00112233';
        primacc.c2g__CODABankStreet__c = 'Koregaon Park';
        insert primacc;
        
        NI_Org_Details__c orgdets = [SELECT Id, Name, Org_Name__c, Admin_Login_Name_Encrypted__c, Admin_Password_Encrypted__c, 
                                Security_Token_Encrypted__c, Org_Type__c, RecordTypeId  
                                FROM NI_Org_Details__c 
                                WHERE Org_Name__c = 'TEST2' AND Org_Type__c = 'Salesforce Sandbox - Full'];
        
        orgdets.Primary_Account__c = primacc.id;
        orgdets.Security_Token_Encrypted__c = '123456789';
        
        update orgdets;
        system.debug('orgdets====' + orgdets);
        
        Test.startTest();
        
        system.debug('test1');
        fillAccount.account = new NI_Org_Details__c();
        fillAccount.account = [SELECT  Id,Name, Primary_Account__c, Org_Name__c, Org_Type__c, Security_Token_Encrypted__c, Admin_Login_Name_Encrypted__c, Admin_Password_Encrypted__c FROM NI_Org_Details__c WHERE Id =: orgdets.Id];
        fillAccount.previous = new PollingResult__c();
        fillAccount.previous.DateTime__c = Datetime.newInstance(0);
        fillAccount.sessionId = '00DP0000003oo7k!ARIAQMHvusZ12Pyo1fZmrAeEv5NJG5rV0tFMx5lay.PM.QqAwLRG9zGmLyqpHYYd8MpoL9pIKOpr6TJNPEhnx63s92pfcqVV';
        
        Test.setMock(WebServiceMock.class, new WebServiceMockImpl());
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockImpl('endPoint'));        
        fillAccount.fill();  
        StaticResource sr = [SELECT Id, body FROM StaticResource WHERE Name = 'Mock_Data_For_getPackageDataElement'];
        Blob bContents = sr.body;

        String contents = bContents.toString();

        system.debug('contents'+contents);
        fillAccount testparam  = new fillAccount();
        string str = testparam.getPackageDataElement(contents,1);
        
        Test.stopTest();
    }       


    @isTest static void fillAccountTest()
    {

        FillAccount fillAccount = new FillAccount();

        fillAccount.isTest = true;
        RecordType rt = [SELECT Name, Id FROM RecordType WHERE sObjectType = 'NI_Org_Details__c' AND Name  = 'LOD Support Admin' AND isActive = true];
        Id rtInit =  rt.Id;
        String orgId = UserInfo.getOrganizationId();
        
        orgId = orgId.substring(0, 15); //SET THE ORGID TO THE 15 CHARACTER ORGID
        account primacc = NI_TestClassData.createTestAccount(1);
        primacc.c2g__CODABankAccountName__c = 'FFA Bank';
        primacc.c2g__CODABankAccountNumber__c = '007';
		primacc.c2g__CODABankCity__c = 'Pune';
        primacc.c2g__CODABankCountry__c = 'India';
        primacc.c2g__CODABankName__c = 'ABC Corp.';
        primacc.c2g__CODABankStateProvince__c = 'Maharashtra';
        primacc.c2g__CODABankSWIFTNumber__c = '00112233';
        primacc.c2g__CODABankStreet__c = 'Koregaon Park';
        insert primacc;
        
        //createTestNiOrgDetails ( Id idRt,  Integer iRecordNumber,       String orgType ) 
//        NI_Org_Details__c orgdets = NI_TestClassData.createTestNiOrgDetails (rtInit, 1, 'Salesforce Sandbox - Developer' );
        NI_Org_Details__c orgdets = [SELECT Id, Name, Org_Name__c, Admin_Login_Name_Encrypted__c, Admin_Password_Encrypted__c, 
                                Security_Token_Encrypted__c, Org_Type__c, RecordTypeId  
                                FROM NI_Org_Details__c 
                                WHERE Org_Name__c = 'TEST2' AND Org_Type__c = 'Salesforce Sandbox - Full'];
        
        orgdets.Primary_Account__c = primacc.id;
        orgdets.Security_Token_Encrypted__c = '123456789';
        
//        insert orgdets;
        update orgdets;
        system.debug('orgdets====' + orgdets);
        
        test.starttest();
        system.debug('test1');
        fillAccount.account = new NI_Org_Details__c();
        fillAccount.account = [SELECT  Id,Name, Primary_Account__c, Org_Name__c, Org_Type__c, Security_Token_Encrypted__c, Admin_Login_Name_Encrypted__c, Admin_Password_Encrypted__c FROM NI_Org_Details__c WHERE Id =: orgdets.Id];
        fillAccount.previous = new PollingResult__c();
        fillAccount.previous.DateTime__c = Datetime.newInstance(0);
        fillAccount.sessionId = '00DP0000003oo7k!ARIAQMHvusZ12Pyo1fZmrAeEv5NJG5rV0tFMx5lay.PM.QqAwLRG9zGmLyqpHYYd8MpoL9pIKOpr6TJNPEhnx63s92pfcqVV';
        
        Test.setMock(WebServiceMock.class, new WebServiceMockImpl());
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockImpl());        
        fillAccount.fill();  
        system.debug('test2');
        StaticResource sr = [SELECT Id, body FROM StaticResource WHERE Name = 'Mock_Data_For_getPackageDataElement'];
        system.debug('test3');
        Blob bContents = sr.body;
        system.debug('test4');
        String contents = bContents.toString();
        system.debug('contents'+contents);
         fillAccount testparam  = new fillAccount();
        string str = testparam.getPackageDataElement(contents,1);
        
        test.stoptest();
        
            List<NI_Org_Details_Installed_Packages__c> lstODInstPacks = new List<NI_Org_Details_Installed_Packages__c>(
                [SELECT Id, Name, Namespace_Prefix__c, Publisher__c, NI_Org_Details__c, Managed__c, Install_Date__c, 
                 Version_Number__c, Status__c, Allowed_Licenses__c, Used_Licenses__c, Expiration_Date__c, Limits__c, 
                 Apps__c, Tabs__c, Objects__c 
                 FROM NI_Org_Details_Installed_Packages__c]
            );
        system.debug('lstODInstPacksExisting'+lstODInstPacks);
        
/*        
        FillAccount fillAccount = new FillAccount();
        
        Test.setMock(WebServiceMock.class, new WebServiceMockImpl());
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockImpl());
        
//        HttpResponse res = HttpCalloutMockImpl.respond();
        
        fillAccount.isTest = true;
        NI_Org_Details__c od = [SELECT Id, Name, Org_Name__c, Admin_Login_Name_Encrypted__c, Admin_Password_Encrypted__c, 
                                Security_Token_Encrypted__c, Org_Type__c, RecordTypeId  
                                FROM NI_Org_Details__c 
                                WHERE Org_Name__c = 'TEST1' AND Org_Type__c = 'Salesforce Production'];
        fillAccount.account = od;
        fillAccount.previous = new PollingResult__c();
        fillAccount.previous.DateTime__c = Datetime.newInstance(0);
        fillAccount.fill();     
        //System.assertEquals('PollingResult__c:{Error__c=, ErrorOccured__c=false, TotalReservations__c=0, TotalActiveSalesforcePlatformUsers__c=null, TotalLicensedSalesforceUsers__c=null, UnmanagedCustomApps__c=12, DateTime__c=1970-01-01 00:00:00, PackageStatus__c=Активно, HRMPackageVersion__c=1.373, DataStorageAllocation__c=0.244140625, TotalEmailCampaigns__c=0, ErrorType__c=, ApiAllocation__c=10000, DataStorageUsage__c=0.1412109375, TotalLicensedSalesforcePlatformUsers__c=null, PackageExpirationDate__c=Без срока действия, AccountId__c=null, PackageUsedLicenses__c=0, TotalMemberAccounts__c=0, ApiUsage__c=0, Name=1969-12-31 19:00:00, UnmanagedCustomTabs__c=0, TotalBookings__c=0, TotalActiveSalesforceUsers__c=null, ReportingPeriod__c=0, PackageAllowedLicenses__c=Не ограничено, UnmanagedCustomObjects__c=0}', string.valueOf(fillAccount.result));
*/        
    }              
    
    // ======================================================================================================================================= //
    // = TEST METHOD 2: 
    // ======================================================================================================================================= //
    @isTest static void testError() 
    {
        FillAccount fillAccount = new FillAccount();        
        fillAccount.fill();
        System.assert(fillAccount.result.ErrorOccured__c);
    }
    
    // ======================================================================================================================================= //
    // = TEST METHOD 3: 
    // ======================================================================================================================================= //

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
 /* @isTest static void fillAccountTest3()
    {

        FillAccount fillAccount = new FillAccount();

        fillAccount.isTest = true;
        RecordType rt = [SELECT Name, Id FROM RecordType WHERE sObjectType = 'NI_Org_Details__c' AND Name  = 'LOD Support Admin' AND isActive = true];
        Id rtInit =  rt.Id;
        String orgId = UserInfo.getOrganizationId();
        
        orgId = orgId.substring(0, 15); //SET THE ORGID TO THE 15 CHARACTER ORGID
        account primacc = NI_TestClassData.createTestAccount(1);
        insert primacc;
        
        //createTestNiOrgDetails ( Id idRt,  Integer iRecordNumber,       String orgType ) 
//        NI_Org_Details__c orgdets = NI_TestClassData.createTestNiOrgDetails (rtInit, 1, 'Salesforce Sandbox - Developer' );
        NI_Org_Details__c orgdets = [SELECT Id, Name, Org_Name__c, Admin_Login_Name_Encrypted__c, Admin_Password_Encrypted__c, 
                                Security_Token_Encrypted__c, Org_Type__c, RecordTypeId  
                                FROM NI_Org_Details__c 
                                WHERE Org_Name__c = 'TEST2' AND Org_Type__c = 'Salesforce Sandbox - Full'];
        
        orgdets.Primary_Account__c = primacc.id;
        orgdets.Security_Token_Encrypted__c = '123456789';
        
//        insert orgdets;
        update orgdets;
        system.debug('orgdets====' + orgdets);
        
        test.starttest();
        system.debug('test1');
        fillAccount.account = new NI_Org_Details__c();
        fillAccount.account = [SELECT  Id,Name, Primary_Account__c, Org_Name__c, Org_Type__c, Security_Token_Encrypted__c, Admin_Login_Name_Encrypted__c, Admin_Password_Encrypted__c FROM NI_Org_Details__c WHERE Id =: orgdets.Id];
        fillAccount.previous = new PollingResult__c();
        fillAccount.previous.DateTime__c = Datetime.newInstance(0);
        fillAccount.sessionId = '00DP0000003oo7k!ARIAQMHvusZ12Pyo1fZmrAeEv5NJG5rV0tFMx5lay.PM.QqAwLRG9zGmLyqpHYYd8MpoL9pIKOpr6TJNPEhnx63s92pfcqVV';
        
        Test.setMock(WebServiceMock.class, new WebServiceMockImpl2());
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMockImpl());        
        fillAccount.parsePackages();  

        test.stoptest();
         
    }              
*/ 
    
    
    
    
/*
  private class WebServiceMockImpl2 implements WebServiceMock 
  {
    public void doInvoke(
      Object stub, Object request, Map<String, Object> response,
      String endpoint, String soapAction, String requestName,
      String responseNS, String responseName, String responseType) 
    {
            if(request instanceof MetadataService.readMetadata_element){
                //MetadataService.readInstalledPackageResponse_element mr = new MetadataService.readInstalledPackageResponse_element();
        response.put('response_x', new MetadataService.readInstalledPackageResponse_element());
              return;
            }
            
            
            PartnerRemote.loginResponse_element  respElement =  new PartnerRemote.loginResponse_element();
         
         respElement.result = new PartnerRemote.LoginResult();
         respElement.result.serverUrl = 'd/services/d';
         respElement.result.sessionId = '';
         respElement.result.userInfo = new PartnerRemote.GetUserInfoResult();
         respElement.result.userInfo.organizationId = '';
         respElement.result.userInfo.organizationName = '';
         response.put('response_x', respElement); 
    }
  }
*/
    
    
    
    
    
}