force-app/main/default/objects/AH_UDC_Response__c/AH_UDC_Response__c.object-meta.xml
<CustomObject>
    <description>This object contains details of Responses to Workbook steps</description>
    <label>UDC Response</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UDC Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_UDC_Response__c/fields/Responded__c.field-meta.xml
<CustomField>
    <fullName>Responded__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>This is the Date/Time at which the response was recorded</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This is the Date/Time at which the response was recorded</inlineHelpText>
    <label>Responded</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AH_UDC_Workbook__c/AH_UDC_Workbook__c.object-meta.xml
<CustomObject>
    <description>This object contains details of workbooks and sent workbooks</description>
    <label>UDC Workbook</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Workbook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UDC Workbooks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_UDC_WorkbookStep__c/AH_UDC_WorkbookStep__c.object-meta.xml
<CustomObject>
    <description>This object contains details of Workbook steps and sent Workbook steps.</description>
    <label>UDC Workbook Step</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Workbook Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UDC Workbook Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_UDC_WorkbookStep__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>The External URL that will be shown for the step.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The External URL that will be shown for the step.</inlineHelpText>
    <label>External URL</label>
    <length>2048</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/AH_UDC_ResponseTriggerHelper_TEST.cls
@isTest 
private class AH_UDC_ResponseTriggerHelper_TEST {

   private static AH_UDC_Workbook__c wb = null;
   private static AH_UDC_WorkbookStep__c wbs = null;

	@TestSetup private static void setup() {
      AH_UDC_InitializationHelper.Initialize('ConfigurationSettings');
   }

   private static void testData1()
   {
      //Insert Workbook Sent
      Id wbRTId = Schema.SObjectType.AH_UDC_Workbook__c.getRecordTypeInfosByDeveloperName().get(AH_UDC_Constants.RECORD_TYPE_WORKBOOK_SENT).getRecordTypeId();

      String product = AH_UDC_TestData.GetProductPicklist() [0].getLabel();
      wb = AH_UDC_TestData.GetWorkbookObject(null, 'Test1', 'Test Workbook 1 Description', product);
      wb.RecordTypeId = wbRTId;
      insert wb;

      //Insert Workbook Step Sent with Security Code
      Id wbsRTId = Schema.SObjectType.AH_UDC_WorkbookStep__c.getRecordTypeInfosByDeveloperName().get(AH_UDC_Constants.RECORD_TYPE_WORKBOOK_STEP_SENT).getRecordTypeId();

      wbs = AH_UDC_TestData.GetWorkbookStepObject(wb.Id, 'Test1');
      wbs.URL__c = 'https://www.amadeus.com/';
      wbs.RecordTypeId = wbsRTId;
      insert wbs;

   }
   //TODO This test class needs asserts... also coverage is not as expected... need to determine why.

   @istest
   private static void TestMostRecentResponse() {
      testData1();

      Test.startTest();

      Id responseRTId = Schema.SObjectType.AH_UDC_Response__c.getRecordTypeInfosByDeveloperName().get(AH_UDC_Constants.RECORD_TYPE_RESPONSE_FORM_ASSEMBLY).getRecordTypeId();

      //Insert Reponse
      AH_UDC_Response__c response1 = AH_UDC_TestData.GetStepResponseObject(wbs.Id);
      response1.RecordTypeId = responseRTId;
      insert response1;

      //Insert Reponse
      AH_UDC_Response__c response2 = AH_UDC_TestData.GetStepResponseObject(wbs.Id);
      response2.RecordTypeId = responseRTId;
      insert response2;

      //Update Reponse
      response2.Responded__c = Datetime.now();
      update response2;

      delete response2;

      Test.stopTest();
   }

   @istest
   private static void TestException() {
      testData1();

      Test.startTest();

      Id responseRTId = Schema.SObjectType.AH_UDC_Response__c.getRecordTypeInfosByDeveloperName().get(AH_UDC_Constants.RECORD_TYPE_RESPONSE_FORM_ASSEMBLY).getRecordTypeId();

      try
      {
         //Insert Reponse
         AH_UDC_Response__c response1 = AH_UDC_TestData.GetStepResponseObject(wbs.Id);
         response1.RecordTypeId = responseRTId;
         response1.Responded__c =  date.parse('1/1/2000');
         insert response1;
      }
      catch(exception exc)
      {
      }

      Test.stopTest();
   }

}