force-app/main/default/objects/INTGR_Case__c/INTGR_Case__c.object-meta.xml
<CustomObject>
    <description>!!! INTEGRATION OBJECT- DO NOT ALTER !!!
NICC-032393</description>
    <label>Integration Case</label>
    <nameField>
        <displayFormat>INTGR-{0000000}</displayFormat>
        <label>Integration Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/INTGR_Case__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>NICC-030216 - Lookup to case created by integration. This field is set by a Process Builder after Standard case is created via the Integration.</description>
    <inlineHelpText>Lookup to case created by integration. This field is set by a Process Builder after Standard case is created via the Integration.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Integration Cases</relationshipLabel>
    <relationshipName>Integration_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/INTGR_Case__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>NICC-030216 - Explanation that describes the issue in more detail.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Explanation that describes the issue in more detail.</inlineHelpText>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/INTGR_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>NICC-030216 - Value set by integration user and integration code for two-way (inbound/outbound) updating of Case status. Special rules apply (see documentation)</description>
    <inlineHelpText>Value set by integration user and integration code for two-way (inbound/outbound) updating of Case status. Special rules apply (see documentation)</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Acknowledged</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recovered</fullName>
            </value>
            <value>
                <fullName>Verified as Recovered</fullName>
            </value>
            <value>
                <fullName>Pending Master Recovery</fullName>
            </value>
            <value>
                <fullName>Pending Problem Resolution</fullName>
            </value>
            <value>
                <fullName>Pending Vendor</fullName>
            </value>
            <value>
                <fullName>Closed as recovered</fullName>
            </value>
            <value>
                <fullName>Closed as rejected</fullName>
            </value>
            <value>
                <fullName>Closed as withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/INTGR_Case__c/fields/System_Affected__c.field-meta.xml
<CustomField>
    <fullName>System_Affected__c</fullName>
    <description>NICC-030216 - Restricted picklist value of Type of environment impacted by issue.</description>
    <inlineHelpText>Type of environment impacted by issue.</inlineHelpText>
    <label>System Affected</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Production</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Internal Test System</fullName>
                <isActive>false</isActive>
                <label>Internal Test System</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NI_Integration_Log__c/NI_Integration_Log__c.object-meta.xml
<CustomObject>
    <label>NI Integration Log</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>NI Integration Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NI Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_Integration_Log__c/fields/Attachment_Id__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Id__c</fullName>
    <description>NICC-023347
The 18 character Salesforce Id of the attachment record related to this integration message. This field is updated when attachments are sent as part of the integration.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The 18 character Salesforce Id of the attachment record related to this integration message. This field is updated when attachments are sent as part of the integration.</inlineHelpText>
    <label>Attachment Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_Integration_Log__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to Case object from NI Integration Logs</description>
    <inlineHelpText>Lookup to Case object from NI Integration Logs</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>NI Integration Logs</relationshipLabel>
    <relationshipName>NI_Integration_Logs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Integration_Log__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Captures the details of the response from the web services call.

NICC-030216 - Relabeled from XML Response to Response
NICC-032393</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Detailed response from the web services call.</inlineHelpText>
    <label>Response</label>
    <length>60000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NI_Integration_Log__c/fields/Do_Retries__c.field-meta.xml
<CustomField>
    <fullName>Do_Retries__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is used to determine to resend the failed messages to server.</description>
    <inlineHelpText>This is used to determine to resend the failed messages to server.</inlineHelpText>
    <label>Do Retries</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NI_Integration_Log__c/fields/File_Id__c.field-meta.xml
<CustomField>
    <fullName>File_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>File Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_Integration_Log__c/fields/Integration_Case__c.field-meta.xml
<CustomField>
    <fullName>Integration_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>NICC-030216 - Lookup to Integration case for retry attempts and logging purpose
NICC-032393</description>
    <inlineHelpText>Lookup to Integration case for retry attempts and logging purpose</inlineHelpText>
    <label>Integration Case</label>
    <referenceTo>INTGR_Case__c</referenceTo>
    <relationshipLabel>NI Integration Logs</relationshipLabel>
    <relationshipName>NI_Integration_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Integration_Log__c/fields/Integration_Name__c.field-meta.xml
<CustomField>
    <fullName>Integration_Name__c</fullName>
    <description>Integration log records populated with integration name.</description>
    <label>Integration Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Win@proach</fullName>
            </value>
            <value>
                <fullName>ServiceNow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NI_Integration_Log__c/fields/Log_Date__c.field-meta.xml
<CustomField>
    <fullName>Log_Date__c</fullName>
    <description>DateTime field that captures the date and time of the transaction</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Log Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/NI_Integration_Log__c/fields/Retries_Performed__c.field-meta.xml
<CustomField>
    <fullName>Retries_Performed__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total number of retries performed for re sending failed message.</description>
    <inlineHelpText>Total number of retries performed for re sending failed message.</inlineHelpText>
    <label>Retries Performed</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NI_Integration_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Values will be set based on the response from the web services call</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NI_Integration_Log__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <description>It will be set accordingly based on whether the web services call was an insert or update.</description>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Insert</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NI_Integration_Log__c/fields/UpdateFor__c.field-meta.xml
<CustomField>
    <fullName>UpdateFor__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>UpdateFor</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_Integration_Log__c/fields/Web_Service_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Web_Service_Endpoint__c</fullName>
    <description>Web Service URL Endpoint for the particular log record.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Web Service Endpoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/NI_Integration_Log__c/fields/XMLRequest__c.field-meta.xml
<CustomField>
    <fullName>XMLRequest__c</fullName>
    <description>Win@proach/Service Now request for log purpose, it may contain xml or json request for create/update fields, attachments etc.
NICC-030216 - Relabeled from XMLRequest to Request
NICC-032393</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Win@proach/Service Now request for log purpose, it may contain xml or json request for create/update fields, attachments etc.</inlineHelpText>
    <label>Request</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/ServiceNowIncidentSettings__c/ServiceNowIncidentSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This setting is used to manage integration between Salesforce and ServiceNow. Create record name as &quot;Default&quot; and enter the required values for it.</description>
    <label>ServiceNow Incident Settings</label>
</CustomObject>

force-app/main/default/objects/ServiceNowIncidentSettings__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Default Account Id for legacy CRS integration cases with IHG</inlineHelpText>
    <label>Account Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceNowIncidentSettings__c/fields/Integration_UserId__c.field-meta.xml
<CustomField>
    <fullName>Integration_UserId__c</fullName>
    <description>Integration user record Id e.g. 00517000001YWXyAAO</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Integration user record Id e.g. 00517000001YWXyAAO</inlineHelpText>
    <label>Integration UserId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceNowIncidentSettings__c/fields/Integration_Username__c.field-meta.xml
<CustomField>
    <fullName>Integration_Username__c</fullName>
    <description>Salesforce username of the ServiceNow integration user, we do not need to send the information back to ServiceNow because the insert or update came from ServiceNow</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Integration username in Salesforce Org e.g. ihg_servicenow@newmarketinc.com.winaproach</inlineHelpText>
    <label>Integration Username</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WinaproachIncidentSettings__c/WinaproachIncidentSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This settings used to manage end points and credentials for Win@proach integration. Create record name as &quot;Default&quot; and enter the required values for it.</description>
    <label>Win@proach Incident Settings</label>
</CustomObject>

force-app/main/default/objects/WinaproachIncidentSettings__c/fields/Integration_Username__c.field-meta.xml
<CustomField>
    <fullName>Integration_Username__c</fullName>
    <description>Salesforce username of the winaproach integration user, we do not need to send the information back to Win@proach because the insert or update came from Win@proach</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Salesforce username of the integration user i.e. winaproach user.  We do not need to send the information back to Win@proach because the insert or update came from Win@proach</inlineHelpText>
    <label>Integration Username</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NI_Integration_Log_TriggerHandlerTest.cls
/************************************************************************************************
				!!! INTEGRATION CLASS - DO NOT ALTER !!!                          
*************************************************************************************************
Name            : NI_Integration_Log_TriggerHandlerTest 
Author          : Sean Harris
Created Date    : 05/03/2018
Last Mod Date   : 01/17/2019
Last Mod By     : Sean Harris
NICC Reference  : 
Description     : Test class for NI_Integration_Log_TriggerHandler
				: 
				: 
*************************************************************************************************/
@isTest
private class NI_Integration_Log_TriggerHandlerTest 
{

    // ======================================================================================================================================= 
    // = TEST METHOD 1: LEGACY WIN@PROACH INTEGRATION LOG (INSERT)
    // =======================================================================================================================================     
    static testMethod void test1() 
    {    
        
        // CREATE TEST INTEGRATION USERS
        // WIN@PRCH 
        User waUser = NI_TestClassData.createTestUser(1, 'Winaproach Integration Only - Standard'); 
        waUser.FirstName = 'Winaproach';
        waUser.LastName = 'Useraccount';
        waUser.CommunityNickname = 'apex0001';
        waUser.UserName = 'winaproachTEST@newmarketinc.com.apextestx';
        insert waUser;    
        
        // IHG CUSTOMER
        User snUser = NI_TestClassData.createTestUser(2, 'IHG Integration Only - Standard'); 
        snUser.FirstName = 'InterContinental';
        snUser.LastName = 'Useraccount'; 
        snUser.CommunityNickname = 'apex0002';
        snUser.UserName = 'ihg_servicenowTEST@newmarketinc.com.apextestx';
        insert snUser;              
        
        // CREATE TEST IHG ACCOUNT & CONTACT
        Account accIHG = NI_TestClassData.createTestAccount(1);
        accIHG.Name = 'NI_Integration_Log_TriggerHandlerTest IHG Account';
        insert accIHG; 
        
        Contact cntIHG = NI_TestClassData.createTestContact(1, accIHG.Id);		
        cntIHG.RecordTypeId = Schema.getGlobalDescribe().get('Contact').getDescribe().getRecordTypeInfosByName().get('Contact').getRecordTypeId();
        cntIHG.FirstName = 'InterContinental';
        cntIHG.LastName = 'Contact';
        insert cntIHG;    
        
        // CREATE WIN@PROACH & SERVICE NOW CUSTOM SETTINGS
        NI_TestClassData.createTestWinaproachServiceNowSettings();
        
        WinaproachIncidentSettings__c ws = WinaproachIncidentSettings__c.getInstance('Default');
        ws.Integration_Username__c = 'winaproachTEST@newmarketinc.com.apextestx';
        update ws;
        
        ServiceNowIncidentSettings__c sn = [SELECT Id, AccountId__c, Integration_UserId__c, Integration_Username__c 
                                            FROM ServiceNowIncidentSettings__c 
                                            WHERE name = 'Default' 
                                            LIMIT 1];
        
        sn.Integration_Username__c = 'ihg_servicenowTEST@newmarketinc.com.apextestx';
        sn.Integration_UserId__c = snUser.Id;
        sn.AccountId__c = accIHG.Id;
        update sn;         

        Case c = NI_TestClassData.createTestCase(1, accIHG.Id);
        c.AccountId = null;
        c.Subject = 'APEX TEST testIntegrationLogTH IHG';
        c.RecordTypeId = Schema.getGlobalDescribe().get('Case').getDescribe().getRecordTypeInfosByName().get('CRS Incident').getRecordTypeId();
        c.type = 'Inquiry';
        c.Amadeus_ExternalSystemAssigneeGroup__c = 'MHDHOT';
        c.Status = 'Recovered';
        c.Winaproach_Logger__c = 'test';
        c.Description = 'Test description';	
        c.Origin = 'Win@proach Integration';
        c.System_Affected__c = 'Disaster Recovery'; 
        
        Test.setMock(HttpCalloutMock.class, new NI_WinaproachTestMock());
        insert c;            
        
        String sCaseId = string.valueOf(c.Id);
        
        NI_Integration_Log__c il1 = new NI_Integration_Log__c();
        il1.Case__c = c.Id;
        il1.Do_Retries__c = true;
        il1.Integration_Name__c = 'Win@proach';
        il1.Log_Date__c = Datetime.now();
        il1.Retries_Performed__c = 0;
        il1.Status__c = 'Failed';
        il1.Transaction_Type__c = 'Insert';
        il1.Web_Service_Endpoint__c = 'https://aproach.amadeus.net/aproach/webserviceDEV/services/CustomersWebServices';
        il1.XMLRequest__c = '<?xml version="1.0" encoding="UTF-8"?><ticket_exchange><create><record_type>incident</record_type><external_record_id>' + sCaseId + '</external_record_id><category><system_category>P</system_category></category><severity>3</severity><urgency>N</urgency><Status>AA</Status><assignee><group>MHDHOT</group></assignee><logger><group>Intercontinental Hotels Group</group><name>loggername</name></logger><owner><group>MHDHOT</group><name>spatil</name><tel>7654321</tel></owner><dates><start_date_time>2017-02-23 05:13:00</start_date_time></dates><affected_service>AHP CRS</affected_service><title>Test subject2</title><description><entry><date_time>2017-02-23 06:37:55</date_time><group>MHDHOT</group><name>loggername</name><text><line>test desc2</line></text></entry></description></create></ticket_exchange>';
        il1.Description__c = '<?xml version="1.0" encoding="UTF-8"?><ticket_exchange><create><record_type>incident</record_type><external_record_id>' + sCaseId + '</external_record_id><category><system_category>P</system_category></category><severity>3</severity><urgency>N</urgency><Status>AA</Status><assignee><group>MHDHOT</group></assignee><logger><group>Intercontinental Hotels Group</group><name>loggername</name></logger><owner><group>MHDHOT</group><name>spatil</name><tel>7654321</tel></owner><dates><start_date_time>2017-02-23 05:13:00</start_date_time></dates><affected_service>AHP CRS</affected_service><title>Test subject2</title><description><entry><date_time>2017-02-23 06:37:55</date_time><group>MHDHOT</group><name>loggername</name><text><line>test desc2</line></text></entry></description></create></ticket_exchange>';
        insert il1;   
        
        NI_Integration_Log__c il2 = new NI_Integration_Log__c();
        il2.Case__c = c.Id;
        il2.Do_Retries__c = true;
        il2.Integration_Name__c = 'Win@proach';
        il2.Log_Date__c = Datetime.now();
        il2.Retries_Performed__c = 0;
        il2.Status__c = 'Failed';
        il2.Transaction_Type__c = 'Update';
        il2.Web_Service_Endpoint__c = 'https://aproach.amadeus.net/aproach/webserviceDEV/services/CustomersWebServices';
        il2.XMLRequest__c = '<?xml version="1.0" encoding="UTF-8"?><ticket_exchange><create><record_type>incident</record_type><external_record_id>' + sCaseId + '</external_record_id><category><system_category>P</system_category></category><severity>3</severity><urgency>N</urgency><Status>AA</Status><assignee><group>MHDHOT</group></assignee><logger><group>Intercontinental Hotels Group</group><name>loggername</name></logger><owner><group>MHDHOT</group><name>spatil</name><tel>7654321</tel></owner><dates><start_date_time>2017-02-23 05:13:00</start_date_time></dates><affected_service>AHP CRS</affected_service><title>Test subject2</title><description><entry><date_time>2017-02-23 06:37:55</date_time><group>MHDHOT</group><name>loggername</name><text><line>test desc2</line></text></entry></description></create></ticket_exchange>';
        il2.Description__c = '<?xml version="1.0" encoding="UTF-8"?><ticket_exchange><create><record_type>incident</record_type><external_record_id>' + sCaseId + '</external_record_id><category><system_category>P</system_category></category><severity>3</severity><urgency>N</urgency><Status>AA</Status><assignee><group>MHDHOT</group></assignee><logger><group>Intercontinental Hotels Group</group><name>loggername</name></logger><owner><group>MHDHOT</group><name>spatil</name><tel>7654321</tel></owner><dates><start_date_time>2017-02-23 05:13:00</start_date_time></dates><affected_service>AHP CRS</affected_service><title>Test subject2</title><description><entry><date_time>2017-02-23 06:37:55</date_time><group>MHDHOT</group><name>loggername</name><text><line>test desc2</line></text></entry></description></create></ticket_exchange>';
        insert il2;   
        
        
	    Test.startTest(); 

        // ASSERT THAT THERE ARE INTEGRATION LOG RECORDS THAT MEET CRITERIA FOR NI_BatchWinaproachResend CLASS QUERY
        List<NI_Integration_Log__c> lstILogAsserts = new List<NI_Integration_Log__c>(
            [SELECT Id, Case__c, Status__c, Transaction_Type__c, Integration_Name__c, UpdateFor__c, 
             Retries_Performed__c, Do_Retries__c, XMLRequest__c, Attachment_Id__c ,File_Id__c 
             FROM NI_Integration_Log__c 
             WHERE Status__c = 'Failed' 
             AND Integration_Name__c = 'Win@proach' 
             AND Integration_Case__c = null 
             AND Do_Retries__c = true 
             AND Retries_Performed__c < 5]); 

        system.assertEquals(2, lstILogAsserts.size());
        
        // ABORT ANY EXISTING TEST JOBS
//        for (CronTrigger ct : [SELECT Id, CronJobDetail.Name FROM CronTrigger WHERE CronJobDetail.Name IN ('ResendJob', 'Resend_Message')])
//        {
//            system.abortJob(ct.Id);
//        }        
        
        NI_BatchWinaproachResend x = new NI_BatchWinaproachResend(); 

        Id batchprocessid = Database.executeBatch(x); 
        system.debug('batchprocessid = ' + batchprocessid);
        system.assertNotEquals(null, batchprocessid);

        Test.stopTest(); 

    }

    // ======================================================================================================================================= 
    // = TEST METHOD 2: LEGACY SERVICE NOW INTEGRATION LOG (INSERT)
    // ======================================================================================================================================= 
    static testMethod void test2() 
    {    
        
        // CREATE TEST INTEGRATION USERS
        // WIN@PRCH 
        User waUser = NI_TestClassData.createTestUser(1, 'Winaproach Integration Only - Standard'); 
        waUser.FirstName = 'Winaproach';
        waUser.LastName = 'Useraccount';
        waUser.CommunityNickname = 'apex0001';
        waUser.UserName = 'winaproachTEST@newmarketinc.com.apextestx';
        insert waUser;    
        
        // IHG CUSTOMER
        User snUser = NI_TestClassData.createTestUser(2, 'IHG Integration Only - Standard'); 
        snUser.FirstName = 'InterContinental';
        snUser.LastName = 'Useraccount'; 
        snUser.CommunityNickname = 'apex0002';
        snUser.UserName = 'ihg_servicenowTEST@newmarketinc.com.apextestx';
        insert snUser;              
        
        // CREATE TEST IHG ACCOUNT & CONTACT
        Account accIHG = NI_TestClassData.createTestAccount(1);
        accIHG.Name = 'NI_Integration_Log_TriggerHandlerTest IHG Account';
        insert accIHG; 
        
        Contact cntIHG = NI_TestClassData.createTestContact(1, accIHG.Id);		
        cntIHG.RecordTypeId = Schema.getGlobalDescribe().get('Contact').getDescribe().getRecordTypeInfosByName().get('Contact').getRecordTypeId();
        cntIHG.FirstName = 'InterContinental';
        cntIHG.LastName = 'Contact';
        insert cntIHG;    
        
        // CREATE WIN@PROACH & SERVICE NOW CUSTOM SETTINGS
        NI_TestClassData.createTestWinaproachServiceNowSettings();
        
        WinaproachIncidentSettings__c ws = WinaproachIncidentSettings__c.getInstance('Default');
        ws.Integration_Username__c = 'winaproachTEST@newmarketinc.com.apextestx';
        update ws;
        
        ServiceNowIncidentSettings__c sn = [SELECT Id, AccountId__c, Integration_UserId__c, Integration_Username__c 
                                            FROM ServiceNowIncidentSettings__c 
                                            WHERE name = 'Default' 
                                            LIMIT 1];
        
        sn.Integration_Username__c = 'ihg_servicenowTEST@newmarketinc.com.apextestx';
        sn.Integration_UserId__c = snUser.Id;
        sn.AccountId__c = accIHG.Id;
        update sn;         

        Case c = NI_TestClassData.createTestCase(1, accIHG.Id);
        c.AccountId = null;
        c.Subject = 'APEX TEST testIntegrationLogTH IHG';
        c.RecordTypeId = Schema.getGlobalDescribe().get('Case').getDescribe().getRecordTypeInfosByName().get('CRS Incident').getRecordTypeId();
        c.type = 'Inquiry';
        c.Amadeus_ExternalSystemAssigneeGroup__c = 'MHDHOT';
        c.Status = 'Recovered';
        c.Winaproach_Logger__c = 'test';
        c.Description = 'Test description';	
        c.Origin = 'Win@proach Integration';
        c.System_Affected__c = 'Disaster Recovery'; 
        
        Test.setMock(HttpCalloutMock.class, new NI_WinaproachTestMock());
        insert c;            
        
        String sCaseId = string.valueOf(c.Id);
        
        NI_Integration_Log__c il1 = new NI_Integration_Log__c();
        il1.Case__c = c.Id;
        il1.Do_Retries__c = true;
        il1.Integration_Name__c = 'ServiceNow';
        il1.Log_Date__c = Datetime.now();
        il1.Retries_Performed__c = 0;
        il1.Status__c = 'Failed';
        il1.Transaction_Type__c = 'Insert';
        il1.Web_Service_Endpoint__c = 'https://aproach.amadeus.net/aproach/webserviceDEV/services/CustomersWebServices';
        il1.XMLRequest__c = '<?xml version="1.0" encoding="UTF-8"?><ticket_exchange><create><record_type>incident</record_type><external_record_id>' + sCaseId + '</external_record_id><category><system_category>P</system_category></category><severity>3</severity><urgency>N</urgency><Status>AA</Status><assignee><group>MHDHOT</group></assignee><logger><group>Intercontinental Hotels Group</group><name>loggername</name></logger><owner><group>MHDHOT</group><name>spatil</name><tel>7654321</tel></owner><dates><start_date_time>2017-02-23 05:13:00</start_date_time></dates><affected_service>AHP CRS</affected_service><title>Test subject2</title><description><entry><date_time>2017-02-23 06:37:55</date_time><group>MHDHOT</group><name>loggername</name><text><line>test desc2</line></text></entry></description></create></ticket_exchange>';
        il1.Description__c = '<?xml version="1.0" encoding="UTF-8"?><ticket_exchange><create><record_type>incident</record_type><external_record_id>' + sCaseId + '</external_record_id><category><system_category>P</system_category></category><severity>3</severity><urgency>N</urgency><Status>AA</Status><assignee><group>MHDHOT</group></assignee><logger><group>Intercontinental Hotels Group</group><name>loggername</name></logger><owner><group>MHDHOT</group><name>spatil</name><tel>7654321</tel></owner><dates><start_date_time>2017-02-23 05:13:00</start_date_time></dates><affected_service>AHP CRS</affected_service><title>Test subject2</title><description><entry><date_time>2017-02-23 06:37:55</date_time><group>MHDHOT</group><name>loggername</name><text><line>test desc2</line></text></entry></description></create></ticket_exchange>';
        insert il1;   
        
        NI_Integration_Log__c il2 = new NI_Integration_Log__c();
        il2.Case__c = c.Id;
        il2.Do_Retries__c = true;
        il2.Integration_Name__c = 'ServiceNow';
        il2.Log_Date__c = Datetime.now();
        il2.Retries_Performed__c = 0;
        il2.Status__c = 'Failed';
        il2.Transaction_Type__c = 'Update';
        il2.Web_Service_Endpoint__c = 'https://aproach.amadeus.net/aproach/webserviceDEV/services/CustomersWebServices';
        il2.XMLRequest__c = '<?xml version="1.0" encoding="UTF-8"?><ticket_exchange><create><record_type>incident</record_type><external_record_id>' + sCaseId + '</external_record_id><category><system_category>P</system_category></category><severity>3</severity><urgency>N</urgency><Status>AA</Status><assignee><group>MHDHOT</group></assignee><logger><group>Intercontinental Hotels Group</group><name>loggername</name></logger><owner><group>MHDHOT</group><name>spatil</name><tel>7654321</tel></owner><dates><start_date_time>2017-02-23 05:13:00</start_date_time></dates><affected_service>AHP CRS</affected_service><title>Test subject2</title><description><entry><date_time>2017-02-23 06:37:55</date_time><group>MHDHOT</group><name>loggername</name><text><line>test desc2</line></text></entry></description></create></ticket_exchange>';
        il2.Description__c = '<?xml version="1.0" encoding="UTF-8"?><ticket_exchange><create><record_type>incident</record_type><external_record_id>' + sCaseId + '</external_record_id><category><system_category>P</system_category></category><severity>3</severity><urgency>N</urgency><Status>AA</Status><assignee><group>MHDHOT</group></assignee><logger><group>Intercontinental Hotels Group</group><name>loggername</name></logger><owner><group>MHDHOT</group><name>spatil</name><tel>7654321</tel></owner><dates><start_date_time>2017-02-23 05:13:00</start_date_time></dates><affected_service>AHP CRS</affected_service><title>Test subject2</title><description><entry><date_time>2017-02-23 06:37:55</date_time><group>MHDHOT</group><name>loggername</name><text><line>test desc2</line></text></entry></description></create></ticket_exchange>';
        insert il2;   

        
	    Test.startTest(); 

        // ASSERT THAT THERE ARE INTEGRATION LOG RECORDS THAT MEET CRITERIA FOR NI_BatchServiceNowResend CLASS QUERY
        List<NI_Integration_Log__c> lstILogAsserts = new List<NI_Integration_Log__c>(
            [SELECT Id, Case__c, Status__c, Transaction_Type__c, Integration_Name__c, UpdateFor__c, 
             Retries_Performed__c, Do_Retries__c, XMLRequest__c, Attachment_Id__c  
             FROM NI_Integration_Log__c 
             WHERE Status__c = 'Failed' 
             AND Integration_Name__c = 'ServiceNow' 
             AND Integration_Case__c = null 
             AND Do_Retries__c = true 
             AND Retries_Performed__c < 5]); 

        system.assertEquals(2, lstILogAsserts.size());

        // ABORT ANY EXISTING TEST JOBS
//        for (CronTrigger ct : [SELECT Id, CronJobDetail.Name FROM CronTrigger WHERE CronJobDetail.Name IN ('ResendJobServiceNow', 'Resend_ServiceNowMessage')])
//        {
//            system.abortJob(ct.Id);
//        }
        
        NI_BatchServiceNowResend x = new NI_BatchServiceNowResend(); 

        Id batchprocessid = Database.executeBatch(x); 
        system.debug('batchprocessid = ' + batchprocessid);
        system.assertNotEquals(null, batchprocessid);
         
        Test.stopTest(); 

    }

    // ======================================================================================================================================= 
    // = TEST METHOD 3: NEXT WIN@PROACH INTEGRATION LOG
    // ======================================================================================================================================= 
    static testMethod void test3() 
    {    
        
        // CREATE TEST INTEGRATION USERS
        // WIN@PRCH 
        User waUser = NI_TestClassData.createTestUser(1, 'Winaproach Integration Only - Standard'); 
        waUser.FirstName = 'Winaproach';
        waUser.LastName = 'Useraccount';
        waUser.CommunityNickname = 'apex0001';
        waUser.UserName = 'winaproachTEST@newmarketinc.com.apextestx';
        insert waUser;    
        
        // NEXT CUSTOMER
        User newUser = NI_TestClassData.createTestUser(3, 'Case Integration Customers'); 
        newUser.FirstName = 'Next';
        newUser.LastName = 'Useraccount';    
        newUser.CommunityNickname = 'apex0003';
        newUser.UserName = 'servicenowTEST@newmarketinc.com.apextestx';
        insert newUser;            
        
        // CREATE TEST IHG ACCOUNT & CONTACT
        Account a = NI_TestClassData.createTestAccount(1);
        a.Name = 'NI_Integration_Log_TriggerHandlerTest NEXT Account';
        insert a; 
        
        Contact cnt = NI_TestClassData.createTestContact(1, a.Id);		
        cnt.RecordTypeId = Schema.getGlobalDescribe().get('Contact').getDescribe().getRecordTypeInfosByName().get('Contact').getRecordTypeId();
        cnt.FirstName = 'Next';
        cnt.LastName = 'User';
        insert cnt;    

        // CREATE TEST INTEGRATION ACCOUNT RECORD
        INTGR_Account__c iAcc = NI_TestClassData.createTestINTGR_Account(1, a.Id, newUser.Id);
        iAcc.Active__c = true;
        iAcc.Assignment_Group__c = 'Test Group';
        iAcc.Case_Origin__c = 'ServiceNow';
        iAcc.Logger_Desk_Agent_Name__c = 'ServiceNow';
        iAcc.Default_New_Case_Status__c = 'New';
        iAcc.Logger_Desk_Agent_Phone__c = '123456789';
        iAcc.Logger_Group__c = 'ServiceNow';
        iAcc.Resend_Failed_Message_Interval_in_Min__c = 1;
        iAcc.Max_Count_To_Resend_Failed_Message__c = 5;
        insert iAcc;
        
        // CREATE WIN@PROACH & SERVICE NOW CUSTOM SETTINGS
        NI_TestClassData.createTestWinaproachServiceNowSettings();
        
        WinaproachIncidentSettings__c ws = WinaproachIncidentSettings__c.getInstance('Default');
        ws.Integration_Username__c = 'winaproachTEST@newmarketinc.com.apextestx';
        update ws;  

        // CREATE TEST NEXT CASE
        INTGR_Case__c ics = NI_TestClassData.createTestINTGR_Case(1, iAcc.Id, null);
        ics.Customer_Ticket_System_Id__c = 'INC000001';
        ics.Customer_Ticket_Number__c = 'INC000001';
        ics.Status__c = 'Acknowledged';
        ics.Subject__c = 'APEX TEST testIntegrationLogTH NEXT';
        Test.setMock(HttpCalloutMock.class, new INTGR_REST_MockResponseGenerator());
        insert ics;             
        
        Case c = NI_TestClassData.createTestCase(1, a.Id);
        //c.AccountId = null;		// ADDED DUE TO PERMISSIONS
        c.Subject = 'APEX TEST testIntegrationLogTH IHG';
        c.RecordTypeId = Schema.getGlobalDescribe().get('Case').getDescribe().getRecordTypeInfosByName().get('CRS Incident').getRecordTypeId();
        c.type = 'Inquiry';
        c.Amadeus_ExternalSystemAssigneeGroup__c = 'MHDHOT';
        c.Status = 'Recovered';
        c.Winaproach_Logger__c = 'test';
        c.Description = 'Test description';	
        c.Origin = 'Win@proach Integration';
        c.System_Affected__c = 'Disaster Recovery'; 
        
        Test.setMock(HttpCalloutMock.class, new NI_WinaproachTestMock());
        insert c;            
        
        String sCaseId = string.valueOf(c.Id);
        
        NI_Integration_Log__c il1 = new NI_Integration_Log__c();
        il1.Case__c = c.Id;
        il1.Do_Retries__c = true;
        il1.Integration_Case__c = ics.Id;
        il1.Integration_Name__c = 'Win@proach';
        il1.Log_Date__c = Datetime.now();
        il1.Retries_Performed__c = 0;
        il1.Status__c = 'Failed';
        il1.Transaction_Type__c = 'Insert';
        il1.Web_Service_Endpoint__c = 'https://aproach.amadeus.net/aproach/webserviceDEV/services/CustomersWebServices';
        il1.XMLRequest__c = '<?xml version="1.0" encoding="UTF-8"?><ticket_exchange><create><record_type>incident</record_type><external_record_id>' + sCaseId + '</external_record_id><category><system_category>P</system_category></category><severity>3</severity><urgency>N</urgency><Status>AA</Status><assignee><group>MHDHOT</group></assignee><logger><group>Intercontinental Hotels Group</group><name>loggername</name></logger><owner><group>MHDHOT</group><name>spatil</name><tel>7654321</tel></owner><dates><start_date_time>2017-02-23 05:13:00</start_date_time></dates><affected_service>AHP CRS</affected_service><title>Test subject2</title><description><entry><date_time>2017-02-23 06:37:55</date_time><group>MHDHOT</group><name>loggername</name><text><line>test desc2</line></text></entry></description></create></ticket_exchange>';
        il1.Description__c = '<?xml version="1.0" encoding="UTF-8"?><ticket_exchange><create><record_type>incident</record_type><external_record_id>' + sCaseId + '</external_record_id><category><system_category>P</system_category></category><severity>3</severity><urgency>N</urgency><Status>AA</Status><assignee><group>MHDHOT</group></assignee><logger><group>Intercontinental Hotels Group</group><name>loggername</name></logger><owner><group>MHDHOT</group><name>spatil</name><tel>7654321</tel></owner><dates><start_date_time>2017-02-23 05:13:00</start_date_time></dates><affected_service>AHP CRS</affected_service><title>Test subject2</title><description><entry><date_time>2017-02-23 06:37:55</date_time><group>MHDHOT</group><name>loggername</name><text><line>test desc2</line></text></entry></description></create></ticket_exchange>';
        insert il1;           

        
        NI_Integration_Log__c il2 = new NI_Integration_Log__c();
        il2.Case__c = c.Id;
        il2.Do_Retries__c = true;
        il2.Integration_Case__c = ics.Id;
        il2.Integration_Name__c = 'Win@proach';
        il2.Log_Date__c = Datetime.now();
        il2.Retries_Performed__c = 0;
        il2.Status__c = 'Failed';
        il2.Transaction_Type__c = 'Update';
        il2.Web_Service_Endpoint__c = 'https://aproach.amadeus.net/aproach/webserviceDEV/services/CustomersWebServices';
        il2.XMLRequest__c = '<?xml version="1.0" encoding="UTF-8"?><ticket_exchange><create><record_type>incident</record_type><external_record_id>' + sCaseId + '</external_record_id><category><system_category>P</system_category></category><severity>3</severity><urgency>N</urgency><Status>AA</Status><assignee><group>MHDHOT</group></assignee><logger><group>Intercontinental Hotels Group</group><name>loggername</name></logger><owner><group>MHDHOT</group><name>spatil</name><tel>7654321</tel></owner><dates><start_date_time>2017-02-23 05:13:00</start_date_time></dates><affected_service>AHP CRS</affected_service><title>Test subject2</title><description><entry><date_time>2017-02-23 06:37:55</date_time><group>MHDHOT</group><name>loggername</name><text><line>test desc2</line></text></entry></description></create></ticket_exchange>';
        il2.Description__c = '<?xml version="1.0" encoding="UTF-8"?><ticket_exchange><create><record_type>incident</record_type><external_record_id>' + sCaseId + '</external_record_id><category><system_category>P</system_category></category><severity>3</severity><urgency>N</urgency><Status>AA</Status><assignee><group>MHDHOT</group></assignee><logger><group>Intercontinental Hotels Group</group><name>loggername</name></logger><owner><group>MHDHOT</group><name>spatil</name><tel>7654321</tel></owner><dates><start_date_time>2017-02-23 05:13:00</start_date_time></dates><affected_service>AHP CRS</affected_service><title>Test subject2</title><description><entry><date_time>2017-02-23 06:37:55</date_time><group>MHDHOT</group><name>loggername</name><text><line>test desc2</line></text></entry></description></create></ticket_exchange>';
        insert il2;           
        
	    Test.startTest(); 

        // ASSERT THAT THERE ARE INTEGRATION LOG RECORDS THAT MEET CRITERIA FOR INTGR_ResendWinaproach CLASS QUERY
        List<NI_Integration_Log__c> lstILogAsserts = new List<NI_Integration_Log__c>(
            [SELECT Id, Case__c, Status__c, Transaction_Type__c, Integration_Name__c, UpdateFor__c, 
             Retries_Performed__c, Do_Retries__c, XMLRequest__c, Attachment_Id__c  
             FROM NI_Integration_Log__c 
             WHERE Status__c = 'Failed' 
             AND Integration_Name__c = 'Win@proach' 
             AND Integration_Case__r.INTGR_Account__c =: iAcc.Id 
             AND Do_Retries__c = true 
             AND Retries_Performed__c < 5]); 

        system.assertEquals(2, lstILogAsserts.size());
        
        // ABORT ANY EXISTING TEST JOBS
//        for (CronTrigger ct : [SELECT Id, CronJobDetail.Name FROM CronTrigger WHERE CronJobDetail.Name LIKE 'INTGR_%'])
//        {
//            system.abortJob(ct.Id);
//        }
        
        Integer iResendInterval = Integer.valueOf(iAcc.Resend_Failed_Message_Interval_in_Min__c);
        
        INTGR_ResendWinaproach x = new INTGR_ResendWinaproach('INTGR_Resend_WINAPRCH_', iAcc.Id, iResendInterval); 

        Id batchprocessid = Database.executeBatch(x); 
        system.debug('batchprocessid = ' + batchprocessid);
        system.assertNotEquals(null, batchprocessid);
        
        Test.stopTest(); 

    }

    // ======================================================================================================================================= 
    // = TEST METHOD 4: NEXT SERVICE NOW INTEGRATION LOG
    // ======================================================================================================================================= 
    static testmethod void test4() 
    {
        
        // CREATE TEST INTEGRATION USERS
        // WIN@PRCH 
        User waUser = NI_TestClassData.createTestUser(1, 'Winaproach Integration Only - Standard'); 
        waUser.FirstName = 'Winaproach';
        waUser.LastName = 'Useraccount';
        waUser.CommunityNickname = 'apex0001';
        waUser.UserName = 'winaproachTEST@newmarketinc.com.apextestx';
        insert waUser;    
        
        // NEXT CUSTOMER
        User newUser = NI_TestClassData.createTestUser(3, 'Case Integration Customers'); 
        newUser.FirstName = 'Next';
        newUser.LastName = 'Useraccount';    
        newUser.CommunityNickname = 'apex0003';
        newUser.UserName = 'servicenowTEST@newmarketinc.com.apextestx';
        insert newUser;            
        
        // CREATE TEST IHG ACCOUNT & CONTACT
        Account a = NI_TestClassData.createTestAccount(1);
        a.Name = 'NI_Integration_Log_TriggerHandlerTest NEXT Account';
        insert a; 
        
        Contact cnt = NI_TestClassData.createTestContact(1, a.Id);		
        cnt.RecordTypeId = Schema.getGlobalDescribe().get('Contact').getDescribe().getRecordTypeInfosByName().get('Contact').getRecordTypeId();
        cnt.FirstName = 'Next';
        cnt.LastName = 'User';
        insert cnt;    

        // CREATE TEST INTEGRATION ACCOUNT RECORD
        INTGR_Account__c iAcc = NI_TestClassData.createTestINTGR_Account(1, a.Id, newUser.Id);
        iAcc.Active__c = true;
        iAcc.Assignment_Group__c = 'Test Group';
        iAcc.Case_Origin__c = 'ServiceNow';
        iAcc.Logger_Desk_Agent_Name__c = 'ServiceNow';
        iAcc.Default_New_Case_Status__c = 'New';
        iAcc.Logger_Desk_Agent_Phone__c = '123456789';
        iAcc.Logger_Group__c = 'ServiceNow';
        iAcc.Resend_Failed_Message_Interval_in_Min__c = 1;
        iAcc.Max_Count_To_Resend_Failed_Message__c = 5;
        insert iAcc;
        
        // CREATE WIN@PROACH & SERVICE NOW CUSTOM SETTINGS
        NI_TestClassData.createTestWinaproachServiceNowSettings();
        
        WinaproachIncidentSettings__c ws = WinaproachIncidentSettings__c.getInstance('Default');
        ws.Integration_Username__c = 'winaproachTEST@newmarketinc.com.apextestx';
        update ws;  

        // CREATE TEST NEXT CASE
        INTGR_Case__c ics = NI_TestClassData.createTestINTGR_Case(1, iAcc.Id, null);
        ics.Customer_Ticket_System_Id__c = 'INC000001';
        ics.Customer_Ticket_Number__c = 'INC000001';
        ics.Status__c = 'Acknowledged';
        ics.Subject__c = 'APEX TEST testIntegrationLogTH NEXT';
        Test.setMock(HttpCalloutMock.class, new INTGR_REST_MockResponseGenerator());
        insert ics;             
        
        Case c = NI_TestClassData.createTestCase(1, a.Id);
        //c.AccountId = null;		// ADDED DUE TO PERMISSIONS
        c.Subject = 'APEX TEST testIntegrationLogTH IHG';
        c.RecordTypeId = Schema.getGlobalDescribe().get('Case').getDescribe().getRecordTypeInfosByName().get('CRS Incident').getRecordTypeId();
        c.type = 'Inquiry';
        c.Amadeus_ExternalSystemAssigneeGroup__c = 'MHDHOT';
        c.Status = 'Recovered';
        c.Winaproach_Logger__c = 'test';
        c.Description = 'Test description';	
        c.Origin = 'Win@proach Integration';
        c.System_Affected__c = 'Disaster Recovery'; 
        
        Test.setMock(HttpCalloutMock.class, new NI_WinaproachTestMock());
        insert c;            
        
        String sCaseId = string.valueOf(c.Id);
        
        NI_Integration_Log__c il1 = new NI_Integration_Log__c();
        il1.Case__c = c.Id;
        il1.Do_Retries__c = true;
        il1.Integration_Case__c = ics.Id;
        il1.Integration_Name__c = 'ServiceNow';
        il1.Log_Date__c = Datetime.now();
        il1.Retries_Performed__c = 0;
        il1.Status__c = 'Failed';
        il1.Transaction_Type__c = 'Insert';
        il1.Web_Service_Endpoint__c = 'https://aproach.amadeus.net/aproach/webserviceDEV/services/CustomersWebServices';
        il1.XMLRequest__c = '<?xml version="1.0" encoding="UTF-8"?><ticket_exchange><create><record_type>incident</record_type><external_record_id>' + sCaseId + '</external_record_id><category><system_category>P</system_category></category><severity>3</severity><urgency>N</urgency><Status>AA</Status><assignee><group>MHDHOT</group></assignee><logger><group>Intercontinental Hotels Group</group><name>loggername</name></logger><owner><group>MHDHOT</group><name>spatil</name><tel>7654321</tel></owner><dates><start_date_time>2017-02-23 05:13:00</start_date_time></dates><affected_service>AHP CRS</affected_service><title>Test subject2</title><description><entry><date_time>2017-02-23 06:37:55</date_time><group>MHDHOT</group><name>loggername</name><text><line>test desc2</line></text></entry></description></create></ticket_exchange>';
        il1.Description__c = '<?xml version="1.0" encoding="UTF-8"?><ticket_exchange><create><record_type>incident</record_type><external_record_id>' + sCaseId + '</external_record_id><category><system_category>P</system_category></category><severity>3</severity><urgency>N</urgency><Status>AA</Status><assignee><group>MHDHOT</group></assignee><logger><group>Intercontinental Hotels Group</group><name>loggername</name></logger><owner><group>MHDHOT</group><name>spatil</name><tel>7654321</tel></owner><dates><start_date_time>2017-02-23 05:13:00</start_date_time></dates><affected_service>AHP CRS</affected_service><title>Test subject2</title><description><entry><date_time>2017-02-23 06:37:55</date_time><group>MHDHOT</group><name>loggername</name><text><line>test desc2</line></text></entry></description></create></ticket_exchange>';
        insert il1;           
        
        NI_Integration_Log__c il2 = new NI_Integration_Log__c();
        il2.Case__c = c.Id;
        il2.Do_Retries__c = true;
        il2.Integration_Case__c = ics.Id;
        il2.Integration_Name__c = 'ServiceNow';
        il2.Log_Date__c = Datetime.now();
        il2.Retries_Performed__c = 0;
        il2.Status__c = 'Failed';
        il2.Transaction_Type__c = 'Update';
        il2.Web_Service_Endpoint__c = 'https://aproach.amadeus.net/aproach/webserviceDEV/services/CustomersWebServices';
        il2.XMLRequest__c = '<?xml version="1.0" encoding="UTF-8"?><ticket_exchange><create><record_type>incident</record_type><external_record_id>' + sCaseId + '</external_record_id><category><system_category>P</system_category></category><severity>3</severity><urgency>N</urgency><Status>AA</Status><assignee><group>MHDHOT</group></assignee><logger><group>Intercontinental Hotels Group</group><name>loggername</name></logger><owner><group>MHDHOT</group><name>spatil</name><tel>7654321</tel></owner><dates><start_date_time>2017-02-23 05:13:00</start_date_time></dates><affected_service>AHP CRS</affected_service><title>Test subject2</title><description><entry><date_time>2017-02-23 06:37:55</date_time><group>MHDHOT</group><name>loggername</name><text><line>test desc2</line></text></entry></description></create></ticket_exchange>';
        il2.Description__c = '<?xml version="1.0" encoding="UTF-8"?><ticket_exchange><create><record_type>incident</record_type><external_record_id>' + sCaseId + '</external_record_id><category><system_category>P</system_category></category><severity>3</severity><urgency>N</urgency><Status>AA</Status><assignee><group>MHDHOT</group></assignee><logger><group>Intercontinental Hotels Group</group><name>loggername</name></logger><owner><group>MHDHOT</group><name>spatil</name><tel>7654321</tel></owner><dates><start_date_time>2017-02-23 05:13:00</start_date_time></dates><affected_service>AHP CRS</affected_service><title>Test subject2</title><description><entry><date_time>2017-02-23 06:37:55</date_time><group>MHDHOT</group><name>loggername</name><text><line>test desc2</line></text></entry></description></create></ticket_exchange>';
        insert il2;              
        
	    Test.startTest(); 

        // ASSERT THAT THERE ARE INTEGRATION LOG RECORDS THAT MEET CRITERIA FOR INTGR_ResendServiceNow CLASS QUERY
        List<NI_Integration_Log__c> lstILogAsserts = new List<NI_Integration_Log__c>(
            [SELECT Id, Case__c, Status__c, Transaction_Type__c, Integration_Name__c, UpdateFor__c, 
             Retries_Performed__c, Do_Retries__c, XMLRequest__c, Attachment_Id__c  
             FROM NI_Integration_Log__c 
             WHERE Status__c = 'Failed' 
             AND Integration_Name__c = 'ServiceNow' 
             AND Integration_Case__r.INTGR_Account__c =: iAcc.Id 
             AND Do_Retries__c = true 
             AND Retries_Performed__c < 5]); 

        system.assertEquals(2, lstILogAsserts.size());
        
        // ABORT ANY EXISTING TEST JOBS
//        for (CronTrigger ct : [SELECT Id, CronJobDetail.Name FROM CronTrigger WHERE CronJobDetail.Name LIKE 'INTGR_%'])
//        {
//            system.abortJob(ct.Id);
//        }
        
        Integer iMaxResendTimes = Integer.valueOf(iAcc.Resend_Failed_Message_Interval_in_Min__c);
        Integer iResendInterval = Integer.valueOf(iAcc.Resend_Failed_Message_Interval_in_Min__c);
        
        INTGR_ResendServiceNow x = new INTGR_ResendServiceNow('INTGR_Resend_SVCNOW_', iAcc.Id, iMaxResendTimes, iResendInterval); 

        Id batchprocessid = Database.executeBatch(x); 
        system.debug('batchprocessid = ' + batchprocessid);
        system.assertNotEquals(null, batchprocessid);

        Test.stopTest();       
            
    }
    
}