force-app/main/default/objects/Medallia_Selection_Criteria__c/Medallia_Selection_Criteria__c.object-meta.xml
<CustomObject>
    <description>NICC-060033</description>
    <label>Medallia Selection Criteria</label>
    <nameField>
        <displayFormat>MSC-{0000}</displayFormat>
        <label>Selection Criteria Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medallia Selection Criteria</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Medallia_Selection_Criteria__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Criteria Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Medallia_Selection_Criteria__c/fields/Days_between_Surveys__c.field-meta.xml
<CustomField>
    <fullName>Days_between_Surveys__c</fullName>
    <label>Days between Surveys</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Medallia_Selection_Criteria__c/fields/Last_Execution_time__c.field-meta.xml
<CustomField>
    <fullName>Last_Execution_time__c</fullName>
    <description>The last time the process related to this criteria was executed</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The last time the process related to this criteria was executed</inlineHelpText>
    <label>Last Execution time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Medallia_Selection_Criteria__c/fields/Next_Execution_time__c.field-meta.xml
<CustomField>
    <fullName>Next_Execution_time__c</fullName>
    <formula>Last_Execution_time__c  +  Interval__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Next Execution time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Medallia_Selection_Criteria__c/fields/SurveySubType__c.field-meta.xml
<CustomField>
    <fullName>SurveySubType__c</fullName>
    <label>SurveySubType</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Project</fullName>
            </value>
            <value>
                <fullName>W/Training</fullName>
            </value>
            <value>
                <fullName>No/Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Medallia_Selection_Criteria__c/fields/SurveyType__c.field-meta.xml
<CustomField>
    <fullName>SurveyType__c</fullName>
    <label>SurveyType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Services - Installer Survey</fullName>
            </value>
            <value>
                <fullName>Services - Consulting Survey</fullName>
            </value>
            <value>
                <fullName>Services - Training Survey</fullName>
            </value>
            <value>
                <fullName>Services - Project Manager</fullName>
            </value>
            <value>
                <fullName>Customer Support</fullName>
            </value>
            <value>
                <fullName>Solution Adoption</fullName>
            </value>
            <value>
                <fullName>Project Managers - 1</fullName>
                <isActive>false</isActive>
                <label>Project Managers No Training</label>
            </value>
            <value>
                <fullName>Project Managers - 2</fullName>
                <isActive>false</isActive>
                <label>Project Managers With Training</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AH_MedalliaSurvey_Schedule.cls
/***********************************************************************************************
Name            : AH_MedalliaSurvey_Schedule
Author          : Bhagwat Garkal
Created Date    : 04/28/2022
Last Mod Date   : 04/28/2022
Last Mod By     : Bhagwat Garkal
NICC Reference  : 
Description     : Schedulable class for AH_MedalliaSurvey_Batch Class.   
                :
                :
************************************************************************************************/
global class AH_MedalliaSurvey_Schedule implements Schedulable 
{
    global void execute(SchedulableContext sc) 
    {
        try
        {
            List<Medallia_Selection_Criteria__c> updateCriteria = new List<Medallia_Selection_Criteria__c>();
            for (Medallia_Selection_Criteria__c serviceCriteria : [SELECT Id, Days_between_Surveys__c, Active__c, Last_Execution_time__c, Next_Execution_time__c, SurveySubType__c,
                                                                   RecordType.Name, RecordType.DeveloperName, SurveyType__c 
                                                                   FROM Medallia_Selection_Criteria__c 
                                                                   WHERE Active__c = true])
            {
                if (serviceCriteria.Next_Execution_time__c != null)
                {
                    Date executionDate = serviceCriteria.Next_Execution_time__c.date();
                    if (executionDate.isSameDay(System.today()))
                    {
                        serviceCriteria.Last_Execution_time__c = System.now();
                        AH_MedalliaSurvey_Batch batch = new AH_MedalliaSurvey_Batch(serviceCriteria.RecordType.DeveloperName, serviceCriteria.SurveyType__c, serviceCriteria.SurveySubType__c);
                        Id batchId = Database.executeBatch(batch);
                        
                        //Update Last_Execution_time
                        updateCriteria.add(serviceCriteria);
                    }    
                } 
            }
            
            //Updating Last_Execution_time, So Next_Execution_time will get setup
            if (!updateCriteria.isEmpty())
            {
                update updateCriteria;
            }
            
        }
        catch (Exception e)
        {
            AH_DTS_Integration_Logger.writeToDTSLog(system.now(), 'Medallia', 'Active', 'Error', 'Error Scheduling Apex Job', e.getMessage(), '4 - Minor', UserInfo.getUserName(), 'AH_MedalliaSurvey_Schedule', 'Apex Job Scheduler', 'Salesforce', true, false); 
        }
    }
    
}