force-app/main/default/objects/AH_UDC_Contact__c/AH_UDC_Contact__c.object-meta.xml
<CustomObject>
    <description>This is a junction object for assigning contacts to the NI Documentation record for Unified Data Collection</description>
    <label>UDC Contact</label>
    <nameField>
        <displayFormat>DCC-{0000}</displayFormat>
        <label>Data Collection Contact</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UDC Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_UDC_Form__c/AH_UDC_Form__c.object-meta.xml
<CustomObject>
    <description>This object contains details of Forms that are available as Workbook Steps.</description>
    <label>UDC Form</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UDC Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_UDC_Log__c/AH_UDC_Log__c.object-meta.xml
<CustomObject>
    <description>This log is for use by Amadeus Hospitality Solutions Delivery custom code.</description>
    <label>UDC Log</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UDC Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_UDC_Log__c/fields/LogText__c.field-meta.xml
<CustomField>
    <fullName>LogText__c</fullName>
    <description>The detailed text content of the log entry.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Log Text</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AH_UDC_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>This is the title message for the log.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This is the title message for the log.</inlineHelpText>
    <label>Message</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AH_UDC_PropertyAccount__c/AH_UDC_PropertyAccount__c.object-meta.xml
<CustomObject>
    <description>Captures central data for UDC.</description>
    <label>UDC Property Account</label>
    <nameField>
        <displayFormat>UDCProperty-{0000}</displayFormat>
        <label>UDCPropertyAccount Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UDC Property Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_UDC_Response__c/AH_UDC_Response__c.object-meta.xml
<CustomObject>
    <description>This object contains details of Responses to Workbook steps</description>
    <label>UDC Response</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UDC Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_UDC_ResponseQA__c/AH_UDC_ResponseQA__c.object-meta.xml
<CustomObject>
    <description>This object contains the Name/Value response details.</description>
    <label>UDC Response QA</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>UDC Response QA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UDC Response QAs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_UDC_Workbook__c/AH_UDC_Workbook__c.object-meta.xml
<CustomObject>
    <description>This object contains details of workbooks and sent workbooks</description>
    <label>UDC Workbook</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Workbook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UDC Workbooks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_UDC_Workbook__c/fields/RelatedTo__c.field-meta.xml
<CustomField>
    <fullName>RelatedTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the NI Documentation record to which the sent Workbook was attached</description>
    <inlineHelpText>This is the NI Documentation record to which the sent Workbook was attached</inlineHelpText>
    <label>Related To</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only &apos;Unified Data Collection - Workbook&apos; record type is accepted.</errorMessage>
        <filterItems>
            <field>NI_Documentation__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Unified Data Collection - Workbook</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>NI_Documentation__c</referenceTo>
    <relationshipLabel>UDC Workbook Sent</relationshipLabel>
    <relationshipName>Workbooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AH_UDC_WorkbookStep__c/AH_UDC_WorkbookStep__c.object-meta.xml
<CustomObject>
    <description>This object contains details of Workbook steps and sent Workbook steps.</description>
    <label>UDC Workbook Step</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Workbook Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UDC Workbook Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_UDC_WorkbookStep__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The form which this step uses</description>
    <inlineHelpText>The form which this step uses</inlineHelpText>
    <label>Form</label>
    <referenceTo>AH_UDC_Form__c</referenceTo>
    <relationshipLabel>UDC Workbook Steps</relationshipLabel>
    <relationshipName>Workbook_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AH_UDC_WorkbookStep__c/fields/Workbook__c.field-meta.xml
<CustomField>
    <fullName>Workbook__c</fullName>
    <description>This is the Workbook record to which the step is attached</description>
    <inlineHelpText>This is the Workbook record to which the step is attached</inlineHelpText>
    <label>Workbook</label>
    <referenceTo>AH_UDC_Workbook__c</referenceTo>
    <relationshipLabel>UDC Workbook Steps</relationshipLabel>
    <relationshipName>Workbook_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AH_UDC_WorkbookStepResponse__c/AH_UDC_WorkbookStepResponse__c.object-meta.xml
<CustomObject>
    <description>This is a junction object used to associate a Workbook Sent Step with Responses</description>
    <label>UDC Workbook Step Response</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Workbook Step Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UDC Workbook Step Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_Documentation__c/NI_Documentation__c.object-meta.xml
<CustomObject>
    <label>NI Documentation</label>
    <nameField>
        <displayFormat>DOC-{00000}</displayFormat>
        <label>Doc #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NI Documentation</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_Documentation__c/fields/AH_UDC_PropertyAccount__c.field-meta.xml
<CustomField>
    <fullName>AH_UDC_PropertyAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Property Account record that will be updated by the form inputs.</description>
    <inlineHelpText>This is the Property Account record that will be updated by the form inputs.</inlineHelpText>
    <label>UDC Property Account</label>
    <referenceTo>AH_UDC_PropertyAccount__c</referenceTo>
    <relationshipLabel>NI Documentation</relationshipLabel>
    <relationshipName>NI_Documentation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AH_UDC_REST_WorkbookSentInfo_TEST.cls
/**
 * Name          : AH_UDC_REST_WorkbookSentInfo_TEST
 * Created By    : Amadeus Hospitality Services (Rob.Stevens@Amadeus.com)
 * Created Date  : 2021-07-25
 * Description   : This is a test class for AH_UDC_REST_WorkbookSentInfo
 * Dependencies  : AH_UDC_REST_WorkbookSentInfo
 **/

@isTest
private class AH_UDC_REST_WorkbookSentInfo_TEST {
   private static AH_UDC_Workbook__c wb = null;
   private static AH_UDC_WorkbookStep__c wbs = null;
   private static AH_UDC_WorkbookStep__c wbswithNoResponse = null;
   private static AH_UDC_WorkbookStep__c wbswithAF = null;
   private static AH_UDC_Form__c m_oForm = null;
   private static AH_UDC_Form__c m_oFormAF = null;
   private static AH_UDC_WorkbookStepResponse__c wbsResponse1 = null;
   private static AH_UDC_WorkbookStepResponse__c wbsResponseAF = null;
   private static AH_UDC_Response__c response1 = null;
   private static AH_UDC_Response__c responseAF = null;
   private static AH_UDC_ResponseQA__c responseQA1 = null;

   @TestSetup private static void setup() {
      AH_UDC_InitializationHelper.Initialize('ConfigurationSettings');
      List<User> listUsers = new List<User> ();
      //Build UDC Workbook User
      listUsers.add(AH_UDC_TestData.BuildUser(AH_UDC_Constants.PROFILE_DEFAULT_NAME_PSA_SF_LIGHTNING,
                                              AH_UDC_Constants.PERMISSIONSET_DEFAULT_NAME_UDC_WORKBOOK_USER,
                                              'WBSI_WBUser1', null, false));

      User oCurrentUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
      oCurrentUser.ContactId = null;

      System.runAs(oCurrentUser) {
         AH_UDC_TestData.InsertWithRetries(listUsers);
         //WB User
         AH_UDC_TestData.AddPermissionSetToUser(AH_UDC_Constants.PERMISSIONSET_DEFAULT_NAME_UDC_WORKBOOK_USER, listUsers[0].Id);
      }
   }

   private static void testData1(boolean withSteps)
   { 
      // Create Account record
      Account oAccount = AH_UDC_TestData.GetAccountObject('GUID');
      insert oAccount;

      // Create Contact record
      Contact oContact = AH_UDC_TestData.GetContactObject(oAccount.Id, 'Test', 'Contact', 'US', 'Portsmouth', '03801', 'NH', '75 New Hampshire Ave');
      insert oContact;

      // Create Property Account object with blank property name to get more code coverage
      AH_UDC_PropertyAccount__c oPropertyAccount = AH_UDC_TestData.GetPropertyObject('WBSITest1', 'Portsmouth', 'US', '03801', 'NH', '75 New Hampshire Ave', '3410 Via Mercato, St 105');
      insert oPropertyAccount;

      // Create NI Doc record
      NI_Documentation__c oNiDoc = AH_UDC_TestData.GetNIDocObject('WBSITest1', Date.newInstance(2021, 3, 31));
      oNiDoc.AH_UDC_PropertyAccount__c = oPropertyAccount.Id;
      insert oNiDoc;

      // Create Contact NI Doc mapping record
      AH_UDC_Contact__c oUdcContact = AH_UDC_TestData.GetUDCContactObject(oNiDoc.Id, oContact.Id, UserInfo.getDefaultCurrency());
      insert oUdcContact;

      //Insert Workbook Sent
      Id wbRTId = Schema.SObjectType.AH_UDC_Workbook__c.getRecordTypeInfosByDeveloperName().get(AH_UDC_Constants.RECORD_TYPE_WORKBOOK_SENT).getRecordTypeId();

      String product = AH_UDC_TestData.GetProductPicklist() [0].getLabel();
      wb = AH_UDC_TestData.GetWorkbookObject(oNiDoc.Id, 'WBSITest1', 'Test Workbook 1 Description', product);
      wb.RecordTypeId = wbRTId;
      wb.RelatedTo__c = oNiDoc.Id;
      insert wb;

      if (withSteps)
         {
         //Insert Workbook Step Sent with Security Code
         Id wbsRTId = Schema.SObjectType.AH_UDC_WorkbookStep__c.getRecordTypeInfosByDeveloperName().get(AH_UDC_Constants.RECORD_TYPE_WORKBOOK_STEP_SENT).getRecordTypeId();
         Id rtFormAssemblyForm = Schema.SObjectType.AH_UDC_Form__c.getRecordTypeInfosByDeveloperName().get(AH_UDC_Constants.RECORD_TYPE_FORM_FORM_ASSEMBLY).getRecordTypeId();
         String definitionFA = '{"title":"UDCSB - Unit Test - Picklist - Source","FormAssemblyId":"4853245","CustomUrlId":"58c874ca-f1e4-4504-9878-b4b97af509ec","fields":[{"Name":"Security Code","APIName":"tfa_6","Repeat":"","Picklist":"false"},{"Name":"Token","APIName":"tfa_7","Repeat":"","Picklist":"false"},{"Name":"Parent Security Code","APIName":"tfa_9","Repeat":"","Picklist":"false"},{"Name":"Room Types","APIName":"tfa_1","Repeat":"tfa_1-D[0]","Picklist":"false"},{"Name":"Yes","APIName":"tfa_13","Repeat":""},{"Name":"No","APIName":"tfa_11","Repeat":""},{"Name":"Do you have Rooms","APIName":"tfa_10","Repeat":""}]}';
         m_oForm = AH_UDC_TestData.GetForm(definitionFA, '4853111', 'TestFormFA', '58c874ca-f1e4-4504-9878-b4b97af509ec');
         m_oForm.RecordTypeId = rtFormAssemblyForm;
         insert m_oForm;

         wbs = AH_UDC_TestData.GetWorkbookStepObject(wb.Id, 'WBSITest1');
         wbs.Form__c = m_oForm.Id;
         wbs.RecordTypeId = wbsRTId;
         wbs.Workbook__c = wb.id;
         insert wbs;

         //Insert Response
         Id responseRTId = Schema.SObjectType.AH_UDC_Response__c.getRecordTypeInfosByDeveloperName().get(AH_UDC_Constants.RECORD_TYPE_RESPONSE_FORM_ASSEMBLY).getRecordTypeId();
         Id responseRTIdAF = Schema.SObjectType.AH_UDC_Response__c.getRecordTypeInfosByDeveloperName().get(AH_UDC_Constants.RECORD_TYPE_RESPONSE_AMADEUS_FORM).getRecordTypeId();
         response1 = AH_UDC_TestData.GetStepResponseObject();
         response1.RecordTypeId = responseRTId;
         insert response1;

         //Insert Workbook Step Response
         wbsResponse1 = AH_UDC_TestData.GetWorkbookStepResponseObject(wbs.id, response1.id);
         insert wbsResponse1;

         //Insert ReponseQA
         Id responseQARTId = Schema.SObjectType.AH_UDC_ResponseQA__c.getRecordTypeInfosByDeveloperName().get(AH_UDC_Constants.RECORD_TYPE_RESPONSE_QA_FORM_ASSEMBLY).getRecordTypeId();
         responseQA1 = AH_UDC_TestData.GetStepResponseQAObject(response1.id, 'Test Question 1', 'tfa_10', 'Test Answer 1', 'tfa_13');
         responseQA1.RecordTypeId = responseQARTId;
         insert responseQA1;
      }
   }

   @isTest
   private static void TestGet() {
      testData1(true);
      User UDCWBUser1 = [SELECT Id FROM user WHERE LastName = 'WBSI_WBUser1'];
      System.runAs(UDCWBUser1)
      {
         Test.startTest();

         RestRequest reqG = new RestRequest();
         RestResponse resG = new RestResponse();
         reqG.requestURI = '/services/apexrest/AH_UDC_WorkbookSentInfo'; //Request URL
         reqG.params.put('workbookSentId', wb.Id);
         reqG.httpMethod = 'GET'; //HTTP Request Type
         RestContext.request = reqG;
         RestContext.response = resG;

         AH_UDC_REST_WorkbookSentInfo.get();

         AH_UDC_REST_WorkbookSentInfo.WorkbookSentInfoResponse resp = null;
         resp = (AH_UDC_REST_WorkbookSentInfo.WorkbookSentInfoResponse) JSON.deserialize(RestContext.response.responseBody.toString(), AH_UDC_REST_WorkbookSentInfo.WorkbookSentInfoResponse.class);

         Test.stopTest();

         System.assertEquals('200', resp.statusCode, 'Expected 200 Response');
         System.assertEquals(1, resp.WorkbookSteps.size(), 'Workbook Step count different than expected');
         
         //There will be 1 log message from initializing the Config Settings
         List<AH_UDC_Log__c> logMessages = [select id, Message__c, LogText__c from AH_UDC_Log__c];
         System.assertEquals(1, logMessages.size(), 'More Log Messages exist than were expected');
         System.assert(logMessages[0].LogText__c.contains('Initialize AH_UDC_ConfigurationSettings Completed'), 'Did not have the log message that was expected');
      }
   }

   @isTest
   private static void TestException() {
      testData1(false);
      User UDCWBUser1 = [SELECT Id FROM user WHERE LastName = 'WBSI_WBUser1'];
      System.runAs(UDCWBUser1)
      {
         Test.startTest();

         RestRequest reqG = new RestRequest();
         RestResponse resG = new RestResponse();
         reqG.requestURI = '/services/apexrest/AH_UDC_WorkbookSentInfo'; //Request URL
         reqG.params.put('workbookSentId', 'exception1');
         reqG.httpMethod = 'GET'; //HTTP Request Type
         RestContext.request = reqG;
         RestContext.response = resG;

         AH_UDC_REST_WorkbookSentInfo.get();

         AH_UDC_REST_WorkbookSentInfo.WorkbookSentInfoResponse resp = null;
         resp = (AH_UDC_REST_WorkbookSentInfo.WorkbookSentInfoResponse) JSON.deserialize(RestContext.response.responseBody.toString(), AH_UDC_REST_WorkbookSentInfo.WorkbookSentInfoResponse.class);

         Test.stopTest();

         System.assertEquals('500', resp.statusCode, 'Expected 200 Response');
      }
   }

   @isTest
   private static void Test400() {
      testData1(false);
      User UDCWBUser1 = [SELECT Id FROM user WHERE LastName = 'WBSI_WBUser1'];
      System.runAs(UDCWBUser1)
      {
         Test.startTest();

         RestRequest reqG = new RestRequest();
         RestResponse resG = new RestResponse();
         reqG.requestURI = '/services/apexrest/AH_UDC_WorkbookSentInfo'; //Request URL
         reqG.params.put('workbookSentId', '');
         reqG.httpMethod = 'GET'; //HTTP Request Type
         RestContext.request = reqG;
         RestContext.response = resG;

         AH_UDC_REST_WorkbookSentInfo.get();

         AH_UDC_REST_WorkbookSentInfo.WorkbookSentInfoResponse resp = null;
         resp = (AH_UDC_REST_WorkbookSentInfo.WorkbookSentInfoResponse) JSON.deserialize(RestContext.response.responseBody.toString(), AH_UDC_REST_WorkbookSentInfo.WorkbookSentInfoResponse.class);

         Test.stopTest();

         System.assertEquals('400', resp.statusCode, 'Expected 200 Response');
      }
   }

   @isTest
   private static void Test404() {
      testData1(false);
      User UDCWBUser1 = [SELECT Id FROM user WHERE LastName = 'WBSI_WBUser1'];
      System.runAs(UDCWBUser1)
      {
         Test.startTest();

         RestRequest reqG = new RestRequest();
         RestResponse resG = new RestResponse();
         reqG.requestURI = '/services/apexrest/AH_UDC_WorkbookSentInfo'; //Request URL
         reqG.params.put('workbookSentId',  wb.Id);
         reqG.httpMethod = 'GET'; //HTTP Request Type
         RestContext.request = reqG;
         RestContext.response = resG;

         AH_UDC_REST_WorkbookSentInfo.get();

         AH_UDC_REST_WorkbookSentInfo.WorkbookSentInfoResponse resp = null;
         resp = (AH_UDC_REST_WorkbookSentInfo.WorkbookSentInfoResponse) JSON.deserialize(RestContext.response.responseBody.toString(), AH_UDC_REST_WorkbookSentInfo.WorkbookSentInfoResponse.class);

         Test.stopTest();

         System.assertEquals('404', resp.statusCode, 'Expected 200 Response');
      }
   }
}