force-app/main/default/objects/AH_UDC_Contact__c/AH_UDC_Contact__c.object-meta.xml
<CustomObject>
    <description>This is a junction object for assigning contacts to the NI Documentation record for Unified Data Collection</description>
    <label>UDC Contact</label>
    <nameField>
        <displayFormat>DCC-{0000}</displayFormat>
        <label>Data Collection Contact</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UDC Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_UDC_Log__c/AH_UDC_Log__c.object-meta.xml
<CustomObject>
    <description>This log is for use by Amadeus Hospitality Solutions Delivery custom code.</description>
    <label>UDC Log</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UDC Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_UDC_Log__c/fields/LogText__c.field-meta.xml
<CustomField>
    <fullName>LogText__c</fullName>
    <description>The detailed text content of the log entry.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Log Text</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AH_UDC_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>This is the title message for the log.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This is the title message for the log.</inlineHelpText>
    <label>Message</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AH_UDC_PropertyAccount__c/AH_UDC_PropertyAccount__c.object-meta.xml
<CustomObject>
    <description>Captures central data for UDC.</description>
    <label>UDC Property Account</label>
    <nameField>
        <displayFormat>UDCProperty-{0000}</displayFormat>
        <label>UDCPropertyAccount Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UDC Property Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_UDC_Response__c/AH_UDC_Response__c.object-meta.xml
<CustomObject>
    <description>This object contains details of Responses to Workbook steps</description>
    <label>UDC Response</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UDC Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_UDC_ResponseQA__c/AH_UDC_ResponseQA__c.object-meta.xml
<CustomObject>
    <description>This object contains the Name/Value response details.</description>
    <label>UDC Response QA</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>UDC Response QA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UDC Response QAs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_UDC_Workbook__c/AH_UDC_Workbook__c.object-meta.xml
<CustomObject>
    <description>This object contains details of workbooks and sent workbooks</description>
    <label>UDC Workbook</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Workbook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UDC Workbooks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_UDC_WorkbookStep__c/AH_UDC_WorkbookStep__c.object-meta.xml
<CustomObject>
    <description>This object contains details of Workbook steps and sent Workbook steps.</description>
    <label>UDC Workbook Step</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Workbook Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UDC Workbook Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_UDC_WorkbookStep__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>The External URL that will be shown for the step.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The External URL that will be shown for the step.</inlineHelpText>
    <label>External URL</label>
    <length>2048</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AH_UDC_WorkbookStep__c/fields/Workbook__c.field-meta.xml
<CustomField>
    <fullName>Workbook__c</fullName>
    <description>This is the Workbook record to which the step is attached</description>
    <inlineHelpText>This is the Workbook record to which the step is attached</inlineHelpText>
    <label>Workbook</label>
    <referenceTo>AH_UDC_Workbook__c</referenceTo>
    <relationshipLabel>UDC Workbook Steps</relationshipLabel>
    <relationshipName>Workbook_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NI_Documentation__c/NI_Documentation__c.object-meta.xml
<CustomObject>
    <label>NI Documentation</label>
    <nameField>
        <displayFormat>DOC-{00000}</displayFormat>
        <label>Doc #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NI Documentation</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_Documentation__c/fields/AH_UDC_PropertyAccount__c.field-meta.xml
<CustomField>
    <fullName>AH_UDC_PropertyAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Property Account record that will be updated by the form inputs.</description>
    <inlineHelpText>This is the Property Account record that will be updated by the form inputs.</inlineHelpText>
    <label>UDC Property Account</label>
    <referenceTo>AH_UDC_PropertyAccount__c</referenceTo>
    <relationshipLabel>NI Documentation</relationshipLabel>
    <relationshipName>NI_Documentation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AH_UDC_REST_WorkbookSentExportTest.cls
/**
 * Name          : AH_UDC_REST_WorkbookSentExportTest
 * Created By    : Amadeus Hospitality Services (Rob.Stevens@Amadeus.com)
 * Created Date  : 2020-11-23
 * Description   : This is a test class for AH_UDC_REST_WorkbookSentExport
 * Dependencies  : AH_UDC_REST_WorkbookSentExport
 **/

@isTest
private class AH_UDC_REST_WorkbookSentExportTest {

   private static AH_UDC_Workbook__c wb = null;
   private static AH_UDC_WorkbookStep__c wbs = null;
   private static AH_UDC_Response__c response1 = null;
   private static AH_UDC_ResponseQA__c responseQA1 = null;

   @TestSetup private static void setup() {
      AH_UDC_InitializationHelper.Initialize('ConfigurationSettings');
   }

   private static void testData1()
   {
      // Create Account record
      Account oAccount = AH_UDC_TestData.GetAccountObject('UDC Test Account for Test class', 'Hospitality Companies', 'Portsmouth', 'US', '03801', 'NH', '75 New Hampshire Ave');
      insert oAccount;

      // Create Contact record
      Contact oContact = AH_UDC_TestData.GetContactObject(oAccount.Id, 'Test', 'Contact', 'US', 'Portsmouth', '03801', 'NH', '75 New Hampshire Ave');
      insert oContact;

      // Create Contact record
      Contact oContact2 = AH_UDC_TestData.GetContactObject(oAccount.Id, 'Test2', 'Contact2', 'US', 'Portsmouth', '03801', 'NH', '75 New Hampshire Ave');
      insert oContact2;

      // Create Property Account object with blank property name to get more code coverage
      AH_UDC_PropertyAccount__c oPropertyAccount = AH_UDC_TestData.GetPropertyObject('', 'Portsmouth', 'US', '03801', 'NH', '75 New Hampshire Ave', '3410 Via Mercato, St 105', 'St 104', '1 Portsmouth Ave.');
      insert oPropertyAccount;

      // Create NI Doc record
      NI_Documentation__c oNiDoc = AH_UDC_TestData.GetNIDocObject('TestDocName', Date.newInstance(2021, 3, 31));
      oNiDoc.AH_UDC_PropertyAccount__c = oPropertyAccount.Id;
      insert oNiDoc;

      // Create Contact NI Doc mapping record
      AH_UDC_Contact__c oUdcContact = AH_UDC_TestData.GetUDCContactObject(oNiDoc.Id, oContact.Id, UserInfo.getDefaultCurrency());
      insert oUdcContact;
      oUdcContact = AH_UDC_TestData.GetUDCContactObject(oNiDoc.Id, oContact2.Id, UserInfo.getDefaultCurrency());
      insert oUdcContact;

      //Insert Workbook Sent
      Id wbRTId = Schema.SObjectType.AH_UDC_Workbook__c.getRecordTypeInfosByDeveloperName().get(AH_UDC_Constants.RECORD_TYPE_WORKBOOK_SENT).getRecordTypeId();

      String product = AH_UDC_TestData.GetProductPicklist() [0].getLabel();
      wb = AH_UDC_TestData.GetWorkbookObject(oNiDoc.Id, 'Test 1', 'Test Workbook 1 Description', product);
      wb.RecordTypeId = wbRTId;
      insert wb;

      //Insert Workbook Step Sent with Security Code
      Id wbsRTId = Schema.SObjectType.AH_UDC_WorkbookStep__c.getRecordTypeInfosByDeveloperName().get(AH_UDC_Constants.RECORD_TYPE_WORKBOOK_STEP_SENT).getRecordTypeId();

      wbs = AH_UDC_TestData.GetWorkbookStepObject(wb.Id, 'Test1');
      wbs.URL__c = 'https://www.lipsum.com/';
      wbs.RecordTypeId = wbsRTId;
      wbs.Workbook__c = wb.id;
      insert wbs;

      //Insert Reponse
      Id responseRTId = Schema.SObjectType.AH_UDC_Response__c.getRecordTypeInfosByDeveloperName().get(AH_UDC_Constants.RECORD_TYPE_RESPONSE_FORM_ASSEMBLY).getRecordTypeId();

      response1 = AH_UDC_TestData.GetStepResponseObject(wbs.id);
      response1.RecordTypeId = responseRTId;
      insert response1;

      //Insert ReponseQA
      Id responseQARTId = Schema.SObjectType.AH_UDC_ResponseQA__c.getRecordTypeInfosByDeveloperName().get(AH_UDC_Constants.RECORD_TYPE_RESPONSE_QA_FORM_ASSEMBLY).getRecordTypeId();

      responseQA1 = AH_UDC_TestData.GetStepResponseQAObject(response1.id, 'Test Question 1', 'tfa_2', 'Test Answer 1', 'tfa_3');
      responseQA1.RecordTypeId = responseQARTId;
      insert responseQA1;
   }

   @isTest
   private static void TestGet() {
      testData1();

      Test.startTest();

      RestRequest reqG = new RestRequest();
      RestResponse resG = new RestResponse();
      reqG.requestURI = '/services/apexrest/AH_UDC_WorkbookSentExport'; //Request URL
      reqG.params.put('wbId', wb.Id);
      reqG.httpMethod = 'GET'; //HTTP Request Type
      RestContext.request = reqG;
      RestContext.response = resG;

      AH_UDC_REST_WorkbookSentExport.get();

      AH_UDC_REST_WorkbookSentExport.WorkbookSentExportResponse resp = null;
      resp = (AH_UDC_REST_WorkbookSentExport.WorkbookSentExportResponse) JSON.deserialize(RestContext.response.responseBody.toString(), AH_UDC_REST_WorkbookSentExport.WorkbookSentExportResponse.class);

      Test.stopTest();

      System.assertEquals('200', resp.statusCode, 'Expected 200 Response');

      List<AH_UDC_Log__c> logMessages = [select id, Message__c, LogText__c from AH_UDC_Log__c];
      // There will 1 log message from initializing the Config Settings
      System.assertEquals(1, logMessages.size(), 'More Log Messages exist than were expected');
      System.assert(logMessages[0].LogText__c.contains('Initialize AH_UDC_ConfigurationSettings Completed'), 'Did not have the log message that was expected');
   }

   @isTest
   private static void TestGet400Error() {
      testData1();

      Test.startTest();

      RestRequest reqG = new RestRequest();
      RestResponse resG = new RestResponse();
      reqG.requestURI = '/services/apexrest/AH_UDC_WorkbookSentExport'; //Request URL
      reqG.params.put('wbBADId', wb.id);
      reqG.httpMethod = 'GET'; //HTTP Request Type
      RestContext.request = reqG;
      RestContext.response = resG;

      AH_UDC_REST_WorkbookSentExport.get();

      AH_UDC_REST_WorkbookSentExport.WorkbookSentExportResponse resp = null;
      resp = (AH_UDC_REST_WorkbookSentExport.WorkbookSentExportResponse) JSON.deserialize(RestContext.response.responseBody.toString(),
                                                                                          AH_UDC_REST_WorkbookSentExport.WorkbookSentExportResponse.class);

      Test.stopTest();

      System.assertEquals('400', resp.statusCode, 'Expected 400 Response');

      List<AH_UDC_Log__c> logMessages = [select id, Message__c, LogText__c from AH_UDC_Log__c];
      // There will 1 log message from initializing the Config Settings
      System.assertEquals(1, logMessages.size(), 'More Log Messages exist than were expected');
      System.assert(logMessages[0].LogText__c.contains('Initialize AH_UDC_ConfigurationSettings Completed'), 'Did not have the log message that was expected');
   }

   @isTest
   private static void TestGet401Error() {
      testData1();

      Test.startTest();

      RestRequest reqG = new RestRequest();
      RestResponse resG = new RestResponse();
      reqG.requestURI = '/services/apexrest/AH_UDC_WorkbookSentExport'; //Request URL
      reqG.params.put('wbId', wbs.Id);
      reqG.httpMethod = 'GET'; //HTTP Request Type
      RestContext.request = reqG;
      RestContext.response = resG;

      AH_UDC_REST_WorkbookSentExport.get();

      AH_UDC_REST_WorkbookSentExport.WorkbookSentExportResponse resp = null;
      resp = (AH_UDC_REST_WorkbookSentExport.WorkbookSentExportResponse) JSON.deserialize(RestContext.response.responseBody.toString(),
                                                                                          AH_UDC_REST_WorkbookSentExport.WorkbookSentExportResponse.class);

      Test.stopTest();

      System.assertEquals('401', resp.statusCode, 'Expected 401 Response');

      List<AH_UDC_Log__c> logMessages = [select id, Message__c, LogText__c from AH_UDC_Log__c];
      // There will 1 log message from initializing the Config Settings
      System.assertEquals(1, logMessages.size(), 'More Log Messages exist than were expected');
      System.assert(logMessages[0].LogText__c.contains('Initialize AH_UDC_ConfigurationSettings Completed'), 'Did not have the log message that was expected');
   }

   @isTest
   private static void TestGet500Error() {
      testData1();

      Test.startTest();
      String badId = '123';
      RestRequest reqG = new RestRequest();
      RestResponse resG = new RestResponse();
      reqG.requestURI = '/services/apexrest/AH_UDC_WorkbookSentExport'; //Request URL
      reqG.params.put('wbId', badId);
      reqG.httpMethod = 'GET'; //HTTP Request Type
      RestContext.request = reqG;
      RestContext.response = resG;

      AH_UDC_REST_WorkbookSentExport.get();

      AH_UDC_REST_WorkbookSentExport.WorkbookSentExportResponse resp = null;
      resp = (AH_UDC_REST_WorkbookSentExport.WorkbookSentExportResponse) JSON.deserialize(RestContext.response.responseBody.toString(),
                                                                                          AH_UDC_REST_WorkbookSentExport.WorkbookSentExportResponse.class);

      Test.stopTest();

      System.assertEquals('500', resp.statusCode, 'Expected 500 Response');

      List<AH_UDC_Log__c> logMessages = [SELECT Id, Message__c, LogText__c FROM AH_UDC_Log__c];

      // There will one log message from initializing the Config Settings, and one for Invalid Id
      System.assertEquals(2, logMessages.size(), 'More Log Messages exist than were expected');
      System.assert(logMessages[0].LogText__c.contains('Initialize AH_UDC_ConfigurationSettings Completed'), 'Did not have the log message that was expected for initializing the ConfigSettings');
      System.assert(logMessages[1].LogText__c.contains('Invalid id: ' + badId), 'Did not have the log message that was expected for the badId that was sent');
   }
}