force-app/main/default/objects/AH_Trust_to_Incident__c/AH_Trust_to_Incident__c.object-meta.xml
<CustomObject>
    <label>AH Trust to Incident</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>AH Trust to Incident Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AH Trusts to Incidents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_Trust_to_Incident__c/fields/AH_Trust__c.field-meta.xml
<CustomField>
    <fullName>AH_Trust__c</fullName>
    <label>AH Trust</label>
    <referenceTo>NI_Trust__c</referenceTo>
    <relationshipLabel>AH Trust Incidents</relationshipLabel>
    <relationshipName>AH_Trusts_to_Incidents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AH_Trust_to_Incident__c/fields/AH_Trust_Incident__c.field-meta.xml
<CustomField>
    <fullName>AH_Trust_Incident__c</fullName>
    <label>AH Trust Incident</label>
    <referenceTo>NI_Trust_Outage__c</referenceTo>
    <relationshipLabel>AH Trusts to Incidents</relationshipLabel>
    <relationshipName>AH_Trusts_to_Incidents</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NI_Trust__c/NI_Trust__c.object-meta.xml
<CustomObject>
    <description>Parent object used in the AHTrust website that contains the platforms displayed to customers visiting the site.</description>
    <label>AH Trust</label>
    <nameField>
        <displayFormat>T-{00000}</displayFormat>
        <label>NI Trust Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AH Trust</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_Trust__c/fields/Platform_Name_External__c.field-meta.xml
<CustomField>
    <fullName>Platform_Name_External__c</fullName>
    <description>NICC-007128: External platform name that displays in public NI Trust site.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>External platform name that displays in public NI Trust site.</inlineHelpText>
    <label>External Platform Name</label>
    <length>225</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_Trust_Outage__c/NI_Trust_Outage__c.object-meta.xml
<CustomObject>
    <description>Outages for the NI Trust Object</description>
    <label>AH Trust Incident</label>
    <nameField>
        <displayFormat>I-{000000}</displayFormat>
        <label>AH Trust Outage Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AH Trust Incidents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_Trust_Outage__c/fields/Amadeus_Investigative_Action__c.field-meta.xml
<CustomField>
    <fullName>Amadeus_Investigative_Action__c</fullName>
    <defaultValue>&quot;Amadeus teams are responding to a critical issue impacting the above identified service. Our first priority is to restore the service as soon as possible. We will provide you with additional details and keep you updated as more information becomes available.&quot;</defaultValue>
    <description>NICC-028950 - Added for the Trust Incident Notifications project.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Replace this text and provide information regarding the investigation and/or recovery actions.</inlineHelpText>
    <label>Amadeus Investigative Action</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NI_Trust_Outage__c/fields/Case_Number__c.field-meta.xml
<CustomField>
    <fullName>Case_Number__c</fullName>
    <description>NICC-028950 - Added for the Trust Incident Notifications project.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The support case associated with this incident.</inlineHelpText>
    <label>Case Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_Trust_Outage__c/fields/Customer_Impact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Impact__c</fullName>
    <defaultValue>&quot;Customers may be experiencing &lt;insert symptoms here&gt;. This prevents customers from &lt;insert text here&gt;; or &lt;insert text here&gt; functionality is currently not available for certain customers. This prevents customers from &lt;insert text here&gt;.&quot;</defaultValue>
    <description>NICC-028950 - Added for the Trust Incident Notifications project.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Replace this text by inserting the impact of this issue as understood from the IR.</inlineHelpText>
    <label>Customer Impact</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NI_Trust_Outage__c/fields/Editable_Duration__c.field-meta.xml
<CustomField>
    <fullName>Editable_Duration__c</fullName>
    <description>NICC-019102</description>
    <inlineHelpText>Incident End Time - Incident Start Time (in minutes). This field is populated by a workflow rule only if it is blank, the End Date and End Time GMT fields have been populated, and the status is not Resolved.</inlineHelpText>
    <label>Total Duration (Editable)</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NI_Trust_Outage__c/fields/Estimated_Duration__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Duration__c</fullName>
    <description>NICC-028950 - Added for the Trust Incident Notifications project.</description>
    <inlineHelpText>The estimated duration of the incident - this only applies to Planned outages/incidents.</inlineHelpText>
    <label>Estimated Duration in Minutes</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NI_Trust_Outage__c/fields/HotSOS_Application__c.field-meta.xml
<CustomField>
    <fullName>HotSOS_Application__c</fullName>
    <description>NICC-028950 - Added for the Trust Incident Notifications project.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Used to indicate the HotSOS application when the instance/data center is used as the Trust Platform Name. This field can be left blank for other products/platforms.</inlineHelpText>
    <label>HotSOS Application</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_Trust_Outage__c/fields/Incident_Description__c.field-meta.xml
<CustomField>
    <fullName>Incident_Description__c</fullName>
    <defaultValue>&quot;Some customers have reported &lt;insert issue here&gt;; or  Some customers may be experiencing &lt;insert issue here&gt;.&quot;</defaultValue>
    <description>NICC-028950 - Added for the Trust Incident Notifications project.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Replace this text by inserting a description of the issue as reported by the customer(s).</inlineHelpText>
    <label>Incident Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NI_Trust_Outage__c/fields/Incident_End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Incident_End_Date_Time__c</fullName>
    <description>NICC-028950 - Added for the Trust Incident Notifications project.</description>
    <formula>IF(ISBLANK(End_Date__c),
&apos;&apos;,
Text(MONTH(End_Date__c)) &amp;&quot;/&quot;&amp; Text(DAY(End_Date__c)) &amp;&quot;/&quot;&amp; Text(YEAR(End_Date__c)) &amp;&quot; &quot;&amp; if (ISBLANK(End_Time_GMT__c), &apos;00:00&apos;, IF(CONTAINS(End_Time_GMT__c, &apos;:&apos;), End_Time_GMT__c, End_Time_GMT__c &amp;&quot;:00&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Formula field that combines the End Date and End Time GMT fields for display in email notifications and the Trust website.</inlineHelpText>
    <label>Incident End Date/Time</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_Trust_Outage__c/fields/Incident_Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Incident_Start_Date_Time__c</fullName>
    <description>NICC-028950 - Added for the Trust Incident Notifications project.</description>
    <formula>IF(ISBLANK(Start_Date__c),
&apos;&apos;,
Text(MONTH(Start_Date__c)) &amp;&quot;/&quot;&amp; Text(DAY(Start_Date__c)) &amp;&quot;/&quot;&amp; Text(YEAR(Start_Date__c)) &amp;&quot; &quot;&amp; if (ISBLANK(Start_Time_GMT__c), &apos;00:00&apos;, IF(CONTAINS(Start_Time_GMT__c, &apos;:&apos;), Start_Time_GMT__c, Start_Time_GMT__c &amp;&quot;:00&quot;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Formula field that combines the Start Date and Start Time GMT fields for display in email notifications and the Trust website.</inlineHelpText>
    <label>Incident Start Date/Time</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_Trust_Outage__c/fields/Make_Public__c.field-meta.xml
<CustomField>
    <fullName>Make_Public__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NICC-007128: Toggle record to be displayed on the customer facing NI Trust page.</description>
    <inlineHelpText>When checked will display exception on customer facing NI Trust page.</inlineHelpText>
    <label>Make Public</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NI_Trust_Outage__c/fields/NI_Trust__c.field-meta.xml
<CustomField>
    <fullName>NI_Trust__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>NICC-041989 - Changed from Master-detail to regular lookup field</description>
    <label>AH Trust</label>
    <referenceTo>NI_Trust__c</referenceTo>
    <relationshipLabel>AH Trust Incidents</relationshipLabel>
    <relationshipName>NI_Trust_Outages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Trust_Outage__c/fields/Notification_Heading__c.field-meta.xml
<CustomField>
    <fullName>Notification_Heading__c</fullName>
    <defaultValue>&quot;Please be informed about the following Amadeus Hospitality incident.&quot;</defaultValue>
    <description>NICC-028950 - Added for the Trust Incident Notifications project.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Text that displays a the top of an incident notification email.</inlineHelpText>
    <label>Notification Heading</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NI_Trust_Outage__c/fields/Outage_End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Outage_End_Date_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>End Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/NI_Trust_Outage__c/fields/Outage_Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Outage_Start_Date_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Start Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/NI_Trust_Outage__c/fields/Root_Cause_Analysis__c.field-meta.xml
<CustomField>
    <fullName>Root_Cause_Analysis__c</fullName>
    <description>NICC-028950 - Added for the Trust Incident Notifications project.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The root cause of the incident - this field will not be shown on notifications if blank.</inlineHelpText>
    <label>Root Cause Analysis</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NI_Trust_Outage__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <description>NICC-028950 - Added for the Trust Incident Notifications project.</description>
    <inlineHelpText>The severity of the incident - automated incident notifications can only be sent for Severity 1 and 2 incidents.</inlineHelpText>
    <label>Severity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 - Critical</fullName>
            </value>
            <value>
                <fullName>2 - Urgent</fullName>
            </value>
            <value>
                <fullName>3 - Medium</fullName>
            </value>
            <value>
                <fullName>4 - Minor</fullName>
            </value>
            <value>
                <fullName>2 - Serious</fullName>
                <isActive>false</isActive>
                <label>2 - Serious</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NI_Trust_Outage__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>NICC-028950 - Added for the Trust Incident Notifications project.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Incident start time in MM/DD/YYYY format.</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NI_Trust_Outage__c/fields/Total_Duration__c.field-meta.xml
<CustomField>
    <fullName>Total_Duration__c</fullName>
    <description>Formula was updated for NICC-028950.</description>
    <formula>VALUE(IF(OR(ISBLANK(End_Date__c), ISBLANK(End_Time_GMT__c), End_Time_GMT__c = &quot;HH:MM&quot;), &quot;&quot;, TEXT(( DATETIMEVALUE(TEXT(YEAR(End_Date__c))+&quot;-&quot; +TEXT(MONTH(End_Date__c))+&quot;-&quot;+TEXT(DAY(End_Date__c))+&quot; &quot;+End_Time_GMT__c+&quot;:00&quot;) - DATETIMEVALUE(TEXT(YEAR(Start_Date__c))+&quot;-&quot; +TEXT(MONTH(Start_Date__c))+&quot;-&quot;+TEXT(DAY(Start_Date__c))+&quot; &quot;+Start_Time_GMT__c+&quot;:00&quot;) ) * 24 * 60)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Incident End Time - Incident Start Time (in minutes)</inlineHelpText>
    <label>Total Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NI_Trust_Outage__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Service Disruption</fullName>
            </value>
            <value>
                <fullName>Degraded Service</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>Upgrade</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NI_Trust_Outage__c/fields/Workaround_Information__c.field-meta.xml
<CustomField>
    <fullName>Workaround_Information__c</fullName>
    <description>NICC-028950 - Added for the Trust Incident Notifications project.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Workaround for the incident if available - this field will not be shown on notifications if blank.</inlineHelpText>
    <label>Workaround Information</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/NI_TrustStatusHistory.cls
/**************************************************************************************** 
Name            : NI_TrustStatusHistory Class 
Author          : 
Created Date    : 
Last Mod Date   : 05/25/2020
Last Mod By     : Shashikant Nikam
NICC Reference  : 
Description     : Extension controller for NI_StatusHistory Visualforce Page Component
                : 
                :  
******************************************************************************************/

public class NI_TrustStatusHistory 
{
    
    public String query{ get; set; } 						// dynamic query to be formed based on the history filters
    public String selectedPlatform{ get; set; } 			// Selected platform to filter history data
    public String selectedDate{ get; set; } 				// Selected date range to filter history data
    public List<SelectOption> platformSOList{ get; set; } 	// SelectOption list to show all platforms in filter criteria
    //public List<IncidenceHistory> incidenceHistoryList{ get; set; }
 
    public String ipPlatformName {get; set;}				// HOLDS PLATFROM ID SENT FROM VF PAGE
    public static Boolean isMadeNull = false;				// BOOLEAN VARIABLE
    
    // DEFAULT CONSTRUCTOR
    public NI_TrustStatusHistory()
    {
        system.debug('in VF Component Constructor ...ipPlatformName : '+ipPlatformName);
        
        // INITIALISE LIST AND SET DETAULT VALUES FOR FILTERS
        platformSOList = new List<SelectOption>();
        selectedPlatform = 'all';
        //selectedDate = '7';
        selectedDate = '90';
        platformSOList.add(new SelectOption('all', 'All'));
        
        // GET ALL PLATFORM RECORDS
        for(NI_Trust__c platform: [Select Id, Platform_Name_External__c from NI_Trust__c])
        {
            platformSOList.add(new SelectOption(platform.Id, platform.Platform_Name_External__c ));
        }

        // CALL REFRESH HISTORY METHOD TO SHOW HISTORY WITH DEFAULT VALUES
        refreshHistory();
    }
    
    // STANDARDSET CONSTRUCTOR   =    THIS WILL BEUSED FOR PAGINATION
    public ApexPages.StandardSetController con {
        get {
            if(con == null) {
                con = new ApexPages.StandardSetController(Database.getQueryLocator(query));
                // SETS THE NUMBER OF RECORDS IN EACH PAGE SET
                con.setPageSize(10); 
            }
            return con;
        }
        set;
    }
    
    // METHOD TO RETURN THE DATE REANGE FOR FILTERS ON HISTPRY PAGE
    public List<SelectOption> getDateRangeOptions()
    {
        List<SelectOption> dateList = new List<SelectOption>();
        dateList.add(new SelectOption('7', 'Most Recent'));
        dateList.add(new SelectOption('2', 'Last 48 Hours'));
        dateList.add(new SelectOption('LAST_WEEK', 'Last Week'));
        dateList.add(new SelectOption('LAST_MONTH', 'Last Month'));
        dateList.add(new SelectOption('90', 'Last 90 Days'));
        //dateList.add(new SelectOption('THIS_YEAR', 'This Year'));
        return dateList;
    }
    
    // @author Prashant Wayal
    // @description - METHOD TO FETCH THE HISTORY DATA BASED ON THE FILTER CRITERIA
    public PageReference refreshHistory()
    {
        //incidenceHistoryList.clear();
        
        // SET con VARIABLE TO NULL TO GET NEW DATA BASED ON FILTERS
        con = null;
		
        ipPlatformName= NULL;
        isMadeNull = true;
        
        // CHANGED BY SHASHIKANT ON 01/15/2020 
        String query1 = 'select Id, Name, Outage_End_Date_Time__c,  Description__c, Root_Cause_Analysis__c, RecordType.Name, '+                                          
                        ' Notification_Heading__c, Severity__c, HotSOS_Application__c, Case_Number__c, Estimated_Duration__c, '+
                        ' Incident_Description__c, Customer_Impact__c, Workaround_Information__c, Editable_Duration__c, '+
                        ' Incident_Start_Date_Time__c, Incident_End_Date_Time__c, Start_Date__c, '+
                        ' ( SELECT id, AH_Trust__c, AH_Trust__r.Platform_Name_External__c FROM AH_Trusts_to_Incidents__r ';

        if(!selectedPlatform.equals('all'))
        {
            query1 += ' WHERE AH_Trust__c = \''+selectedPlatform+'\'), '; 
        }
        else{
            query1 += ' ), ';
        }
        query1 += 	' Outage_Start_Date_Time__c, Total_Duration__c, Type__c, Amadeus_Investigative_Action__c '+
            		' from NI_Trust_Outage__c where Make_Public__c = TRUE '+
        			' ORDER BY Start_Date__c DESC';
        
        /*
        if(selectedDate.equals('LAST_WEEK') || selectedDate.equals('LAST_MONTH')){// || selectedDate.equals('THIS_YEAR')){
            query1 += ' AND Start_Date__c  = '+selectedDate;
        }
        else{
            query1 += ' AND Start_Date__c = LAST_N_DAYS:'+selectedDate;
        }
        */
        
        // INITIALISE CLASS QUERY VARIABLE WITH NEW QUERY
        this.query = query1;
        
        system.debug('query1 : '+query1);
        
        // CALL incidenceHistoryList METHOD TO FETCH NEW HISTORY DATA
        getIncidenceHistoryList();
        
        // START PAGINATION FROM PAGE NO 1
        con.setPageNumber(1);
        
        return null;
    }
    
    // @author Prashant Wayal
    // @description - METHOD TO GET THE INCIDENCE HISTORY DATA
    public List<IncidenceHistory> getIncidenceHistoryList()
    {
        system.debug('============================in getIncidenceHistoryList.....selectedPlatform : '+selectedPlatform+'...ipPlatformName : '+ipPlatformName);
        
        // GET HISTORY DATA
        Map<String, List<DaysIncidence>> historyMap = showHistory();
        List<IncidenceHistory> incList = new List<IncidenceHistory>();
        
        // LOOP THROUGH HISTORY DATA TO FORMAT DATA IN PROPER FORMAT
        for(String s: historyMap.keySet())
        {
            // CREATE NEW IncidenceHistory OBJECT AND ASSIGN VALUES TO MEMBER VARIABLES
            IncidenceHistory hist = new IncidenceHistory();
            hist.monthName = s;
            hist.incidenceList = historyMap.get(s);
            
            // ADD IncidenceHistory OBJECT TO LIST
            incList.add(hist);
        }
        system.debug('incList size : '+incList.size());
        
        // RETURN IncidenceHistory LIST
        return incList;
    }
    
    // @author Prashant Wayal
    // @description - METHOD TO GET THE HISTORY DATA BASED ON NEW FILTERS & QUERY
    public Map<String, List<DaysIncidence>> showHistory()
    {
        
        Map<String, List<DaysIncidence>> historyMap = new Map<String, List<DaysIncidence>>();
        
        system.debug('in showHistory.....selectedPlatform : '+selectedPlatform+'...ipPlatformName : '+ipPlatformName + '...isMadeNull : '+isMadeNull);
        
        Boolean isPlatformChanged = false;
        
        // GET ALL INCIDENVE RECORDS BASED ON THE NEWLY FORMATTED QUERY FROM STANDARD SET CONTROLLER
        if(ipPlatformName != NULL && ipPlatformName != '' && isMadeNull == false)
        {            
            // CALL METHOD TO REFRESH THE QUERY RESULT ACCORDIN TO SELECTED PLATFORM
        	updateRefreshHistory();
            
            isPlatformChanged = true;
        }
        
        system.debug('con.getRecords() size : '+con.getRecords().size());
        
        List<NI_Trust_Outage__c> newOutList = new List<NI_Trust_Outage__c>();
        for(NI_Trust_Outage__c outage: (List<NI_Trust_Outage__c>) con.getRecords())
        {
            //system.debug('outage.id : '+outage.Name);
            
            // GET MONTH OF THE YEAR 
            //String monthYear = outage.Outage_Start_Date_Time__c.format('MMMM yyyy');
            Datetime stDtTime = getDatetime(outage.Incident_Start_Date_Time__c);
            
            if(selectedDate.equals('LAST_WEEK'))
            {
                Date myDate = Date.today().addDays(-7);
                Date weekStart = myDate.toStartofWeek();
                Date weekEnd = weekStart.addDays(+7);
                
                Datetime LastweekstartTime = Datetime.newInstanceGMT(weekStart.year(),weekStart.month(),weekStart.day(),00,00,00);
                Datetime LastweekendTime = Datetime.newInstanceGMT(weekEnd.year(),weekEnd.month(),weekEnd.day(),00,00,00);

                if (stDtTime >=LastweekstartTime && stDtTime <= LastweekendTime){
                    newOutList.add(outage);
                }
            }
            else if(selectedDate.equals('LAST_MONTH'))
            {
                Date myDate = Date.today().addMonths(-1);
                Date mnthStart = myDate.toStartOfMonth();
                Integer noOfDays = date.daysInMonth(mnthStart.year(), mnthStart.month());
                Date mnthEnd = mnthStart.addDays(+noOfDays);
                
                Datetime LastmnthstartTime = Datetime.newInstanceGMT(mnthStart.year(),mnthStart.month(),mnthStart.day(),00,00,00);
                Datetime LastmnthsendTime = Datetime.newInstanceGMT(mnthEnd.year(),mnthEnd.month(),mnthEnd.day(),00,00,00);

                if (stDtTime >=LastmnthstartTime && stDtTime <= LastmnthsendTime){
                    newOutList.add(outage);
                }
            } 
            else 
            {
                Datetime stDtTm = System.now().addDays(-Integer.valueOf(selectedDate));

                if (stDtTime >=stDtTm){
                    newOutList.add(outage);
                }
            }
        }    
        system.debug('newOutList size : '+newOutList.size());
        
        for(NI_Trust_Outage__c outage: newOutList)
        {
            
            Datetime stDtTime = getDatetime(outage.Incident_Start_Date_Time__c);
            String monthYear = stDtTime.format('MMMM yyyy');

            // CHECK IF historyMap CONTAINS RECORDS FOE PARTICULAR MONTH
            // IF KEY IS PRESENT, ADD INCIDENCE RECORD IN THE SAME APP
            if(historyMap.get(monthYear) != null)
            {
                List<DaysIncidence> dList = createHistoryRecord(outage);
                for(DaysIncidence d : dList)
                {
                    if(d.incId != NULL)
                    {
                        String key = d.incId +'_'+  d.trustId  +'_'+  monthYear;
                        historyMap.get(monthYear).add(d);
                    }
                }
            }
            else
            {
                // ADD NEW MONTH RECORD FOR SHOWING HISTORY
                List<DaysIncidence> dList = createHistoryRecord(outage);
                for(DaysIncidence d : dList)
                {
                    if(d.incId != NULL)
                    {
                        if( historyMap.containsKey(monthYear) )
                        {
                            historyMap.get(monthYear).add(d);
                        }
                        else 
                        {
                            historyMap.put(monthYear, new List<DaysIncidence>{d});
						}
                        
                        String key = d.incId +'_'+  d.trustId  +'_'+  monthYear;
                    }
                }
            }
        }
        system.debug('historyMap size : '+historyMap.size());

        // ADDED BY SHASHIKANT ON 05/13/2020
        if(isPlatformChanged)
        {
            List<IncidenceHistory> incList = new List<IncidenceHistory>();
            
            // LOOP THROUGH HISTORY DATA TO FORMAT DATA IN PROPER FORMAT
            for(String s: historyMap.keySet())
            {
                // CREATE NEW IncidenceHistory OBJECT AND ASSIGN VALUES TO MEMBER VARIABLES
                IncidenceHistory hist = new IncidenceHistory();
                hist.monthName = s;
                hist.incidenceList = historyMap.get(s);
                
                // ADD IncidenceHistory TO LIST 
                incList.add(hist);
            }
        }
        
        // RETURN history map
        return historyMap;
    }
    
    
    // ADDED BY SHASHIKANT ON 05/13/2020
    // METHOD TO FETCH THE DATA OF PARTICULAR PATFORM AND SET THE con VARIABLE
    public void updateRefreshHistory()
    {
        
        con = null;
        
        system.debug('in updateRefreshHistory....selectedPlatform : '+selectedPlatform+'.....ipPlatformName : '+ipPlatformName);
        
        String query1 = 'select Id, Name, Outage_End_Date_Time__c,  Description__c, Root_Cause_Analysis__c, RecordType.Name, '+                                          
            ' Notification_Heading__c, Severity__c, HotSOS_Application__c, Case_Number__c, Estimated_Duration__c, '+
            ' Incident_Description__c, Customer_Impact__c, Workaround_Information__c, Editable_Duration__c, '+
            ' Incident_Start_Date_Time__c, Incident_End_Date_Time__c, Start_Date__c, '+
            ' ( SELECT id, AH_Trust__c, AH_Trust__r.Platform_Name_External__c FROM AH_Trusts_to_Incidents__r ';
        
        if( (ipPlatformName != NULL || ipPlatformName != '') )
        {
            query1 += ' WHERE AH_Trust__c = \''+ipPlatformName+'\'), '; 
        }
        else{
            query1 += ' ), ';
        }
        query1 += 	' Outage_Start_Date_Time__c, Total_Duration__c, Type__c, Amadeus_Investigative_Action__c '+
            ' from NI_Trust_Outage__c where Make_Public__c = TRUE '+
            ' ORDER BY Start_Date__c DESC';
        
        // INITIALISE CLASS QUERY VARIABLE WITH NEW QUERY
        this.query = query1;
        
        system.debug('query1 : '+query1);
        
        selectedPlatform = ipPlatformName;
        ipPlatformName = NULL;
        
        // START PAGINATION FROM PAGE NO 1
        con.setPageNumber(1); 
    }
  
    
    // @author Prashant Wayal
    // @description - METHOD TO CREATE DaysIncidence RECORD BASED ON THE INCIDENCE DETAILS
    public List<DaysIncidence> createHistoryRecord(NI_Trust_Outage__c outage)
    {
        
        system.debug('In createHistoryRecord method...'+outage.id);

		List<DaysIncidence> incList = new List<DaysIncidence>();
        for(AH_Trust_to_Incident__c juncObj: outage.AH_Trusts_to_Incidents__r)
        {
            // CREATE DaysIncidence OBJECT FOR INCIDENCE RECORD AND INITIALISE MEMBER VARIABLES
        	DaysIncidence inc = new DaysIncidence();
            
			system.debug('juncObj.AH_Trust__c : '+juncObj.AH_Trust__c +' => '+juncObj.AH_Trust__r.Platform_Name_External__c);
            inc.trustId = juncObj.AH_Trust__c;
            inc.incId = outage.Id;
            inc.incidenceName = (outage.Description__c != null)?(' - '+outage.Description__c):'';
            //inc.incidenceDetails = outage.Public_Details__c;
            
            Datetime stDtTime = getDatetimeWtGMT(outage.Incident_Start_Date_Time__c);
            Datetime endDtTime = NULL;
            if (outage.Incident_End_Date_Time__c!= NULL){
                endDtTime = getDatetimeWtGMT(outage.Incident_End_Date_Time__c);
            }
            
            //ADDED BY SHASHIKANT ON 05/30/2018
            inc.NotificationHeading = outage.Notification_Heading__c;
            inc.Severity = outage.Severity__c;
            inc.HotSOSApplication = outage.HotSOS_Application__c;
            inc.CaseNumber = outage.Case_Number__c;
            inc.startDtTime = NULL;
            if (stDtTime != NULL){
                inc.startDtTime = String.valueOf(stDtTime) + ' GMT';
            }
            inc.endDtTime = NULL;
            if (endDtTime != NULL){
                inc.endDtTime = String.valueOf(endDtTime);
            }
            inc.EstimatedDuration = String.valueOf(outage.Estimated_Duration__c);
            inc.IncidentDescription = outage.Incident_Description__c;
            inc.CustomerImpact = outage.Customer_Impact__c;
            inc.WorkaroundInformation = outage.Workaround_Information__c;
            inc.EditableDuration = String.valueOf(outage.Editable_Duration__c);
            inc.AmadeusInvestigativeAction = outage.Amadeus_Investigative_Action__c;
            
            // FORMAT START TIME
            inc.dayName = stDtTime.format('M/d');
            
            //COMENTED External_Platform_Name__c FIELD on 01/15/2020
            //inc.platformName = outage.External_Platform_Name__c;   
            inc.platformName = juncObj.AH_Trust__r.Platform_Name_External__c;   
            inc.type = ' - '+outage.Type__c;
            inc.rootCause = outage.Root_Cause_Analysis__c;
            inc.RecordTypeName = outage.RecordType.Name;
            
            incList.add(inc);
        }
        
        // RETURN DaysIncidence OBJECT
        return incList;
    }
    

    private Datetime getDatetime(String str){
        
        Datetime newDate;
            
        if (str != NULL) {
            List<String> dtTme = str.split(' ');
            List<String> dtValues = dtTme[0].split('/');
            Date dt = Date.newInstance(Integer.valueof(dtValues[2]), Integer.valueof(dtValues[0]), Integer.valueof(dtValues[1]));
            
            List<String> timeValues = dtTme[1].split(':');
            Time tm = Time.newInstance(Integer.valueof(timeValues[0]), Integer.valueof(timeValues[1]), 0, 0);
            newDate = Datetime.newInstanceGMT(dt, tm);
        }
        return newDate;
    }
    
    private Datetime getDatetimeWtGMT(String str){
        
        Datetime newDate;
            
        if (str != NULL) {
            List<String> dtTme = str.split(' ');
            List<String> dtValues = dtTme[0].split('/');
            Date dt = Date.newInstance(Integer.valueof(dtValues[2]), Integer.valueof(dtValues[0]), Integer.valueof(dtValues[1]));
            
            List<String> timeValues = dtTme[1].split(':');
            Time tm = Time.newInstance(Integer.valueof(timeValues[0]), Integer.valueof(timeValues[1]), 0, 0);
            newDate = Datetime.newInstance(dt, tm);
        }
        return newDate;
    }
    
    // =========================================================================================================================================
    //			PAGINATION METHODS 
    // =========================================================================================================================================
    
    // INDICATES WHETHER THERE ARE MORE RECORDS AFTER THE CURRENT PAGE SET
    public Boolean hasNext {
        get {
            return con.getHasNext();
        }
        set;
    }

    // INDICATES WHETHER THERE ARE MORE RECORDS BEFORE THE CURRENT PAGE SET 
    public Boolean hasPrevious {
        get {
            return con.getHasPrevious();
        }
        set;
    }

    // RETURNS THE PAGE NUMBER OF THE CURRENT PAGE SET 
    public Integer pageNumber {
        get {
            return con.getPageNumber();
        }
        set;
    }

    // RETURNS FIRST PAGE OF RECORDS
     public void first() {
         con.first();
     }

     // RETURNS LAST PAGE OF RECORDS
     public void last() {
         con.last();
     }

     // RETURNS PREVIOUS PAGE OF RECORDS
     public void previous() {
         con.previous();
     }

     // RETURNS NEXT PAGE OF RECORDS
     public void next() {
         con.next();
     }

     // RETUNS THE PageReference OF THE ORIGINAL PAGE, IF KNOWN, OF THE HOME PAGE
     public void cancel() {
         con.cancel();
     }
      
    
    // =========================================================================================================================================
    //			WRAPPER CLASSES 
    // =========================================================================================================================================

    // WRAPPER CLASS TO HOLD VALUES FOR INCIDENCES REPORTED IN SPECIFIC MONTH
    public class IncidenceHistory
    {
        public String monthName{ get; set; } 					//month name
        public List<DaysIncidence> incidenceList{ get; set; } 	//List of all incidences reported in month
    }
    
    // WRAPPER CLASS TO HOLD VALUES OF INCIDENCE REPORTED
    public class DaysIncidence
    {
        public Id trustId { get; set; } 						//Trust Id
        public Id incId { get; set; } 							//Incidence Id
        public String incidenceName{ get; set; } 				//Incidence name
        //public String startTime{ get; set; } 					//Incidence start time
        //public String endTime{ get; set; } 					//Incidence end time
        public String platformName{ get; set; } 				//Platform on which incidence is reported
        public String type{ get; set; } 						//Type of incidence 
        public String rootCause{ get; set; } 					//Root cause of incidence
        public String dayName{ get; set; } 						//Day name on which incidence is reported

        // ADDED BY SHASHIKANT - 05/30/2018
        public String startDtTime{ get; set; } 					//Incidence start time
        public String endDtTime{ get; set; } 					//Incidence end time
        public String NotificationHeading{ get; set; } 			//Incidence Notification Heading        
        public String Severity{ get; set; } 					//Severity of the incidence
        public String HotSOSApplication{ get; set; } 			//Hot SOS Application of the incidence
        public String CaseNumber{ get; set; } 					//Case Number of the incidence
        public String EstimatedDuration{ get; set; } 			//Estimated Duration of the incidence
        public String IncidentDescription{ get; set; } 			//Incident Description of the incidence
        public String CustomerImpact{ get; set; } 				//Customer Impact of the incidence
        public String WorkaroundInformation{ get; set; } 		//Workaround Information of the incidence
        public String AmadeusInvestigativeAction{ get; set; } 	//Amadeus Investigative Action of the incidence
        public String EditableDuration{ get; set; } 			//Total Duration (Editable) of the incidence
        public String RecordTypeName { get; set; } 				//Record Type of the incidence
    }
}