force-app/main/default/objects/NI_Documentation__c/NI_Documentation__c.object-meta.xml
<CustomObject>
    <label>NI Documentation</label>
    <nameField>
        <displayFormat>DOC-{00000}</displayFormat>
        <label>Doc #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NI Documentation</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_Documentation__c/fields/AH_PLCM_Portal_Completion_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>AH_PLCM_Portal_Completion_Due_Date__c</fullName>
    <businessOwnerGroup>DEPT_Platform_Life_Cycle_Management</businessOwnerGroup>
    <description>NICC-036103</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Date the customer is required to complete all of the Customer Portal input requirements.</inlineHelpText>
    <label>Portal Completion Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NI_Documentation__c/fields/AH_PLCM_Portal_Progress__c.field-meta.xml
<CustomField>
    <fullName>AH_PLCM_Portal_Progress__c</fullName>
    <businessOwnerGroup>DEPT_Platform_Life_Cycle_Management</businessOwnerGroup>
    <description>NICC-036103</description>
    <inlineHelpText>Status of Migration Portal customer steps</inlineHelpText>
    <label>Portal Progress</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Portal Invitation Sent</fullName>
                <default>true</default>
                <label>Portal Invitation Sent</label>
            </value>
            <value>
                <fullName>Property Information Confirmed</fullName>
            </value>
            <value>
                <fullName>Property Details Complete</fullName>
            </value>
            <value>
                <fullName>Migration Users Complete</fullName>
            </value>
            <value>
                <fullName>Cross-Reference Complete</fullName>
            </value>
            <value>
                <fullName>Function Room Information Provided</fullName>
            </value>
            <value>
                <fullName>Room Capacity Information Provided</fullName>
            </value>
            <value>
                <fullName>Inventory Information Provided</fullName>
            </value>
            <value>
                <fullName>Customer Inputs Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NI_Documentation__c/fields/Document_Name__c.field-meta.xml
<CustomField>
    <fullName>Document_Name__c</fullName>
    <defaultValue>IF($RecordType.DeveloperName = &quot;HRM_Configuration&quot;, &quot;HRM Configuration&quot;, &quot;&quot;)</defaultValue>
    <description>Name of the Document</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Name of the Document</inlineHelpText>
    <label>Document Name</label>
    <length>120</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_Documentation__c/fields/DRC_Call_Date__c.field-meta.xml
<CustomField>
    <fullName>DRC_Call_Date__c</fullName>
    <description>DRC Call Date for Project Coordinator</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>DRC Call Date for Project Coordinator</inlineHelpText>
    <label>DRC Call Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/AH_PLCM_MM_Welcome.cls
/***********************************************************************************************
Name            : AH_PLCM_MM_Welcome
Author          : Tushar Gupta
Created Date    : 06-June-2020
Last Mod Date   : 06-June-2020
Last Mod By     : Tushar Gupta
NICC Reference  : 
Description     : Apex class for Welcome page
************************************************************************************************/
public class AH_PLCM_MM_Welcome extends AH_PLCM_MM_Common_Class {
    //Properties declaration
    public List<NI_Documentation__c> lstProjects { get; set; }
    public List<SelectOption> ddlProjects { get; set; }
    public NI_Documentation__c objProject { get; set; } 

    public AH_PLCM_MM_Welcome() {
        try {           
            //Get all projects from salesforce object
            lstProjects = GetProjectsByUser(false);            
            //Prepare list for project drop down
            FillListForProjectDropDown();
        }
        catch(Exception ex) {   
            //set error variable to redirect at error page
            IsErrorOccurred = true;            
        }
    }

    //Fill values in project drop down
    private void FillListForProjectDropDown() { 
        Map<Id, string> lstCompletedProjects = null;
        try {           
            //Fill list for project drop down
            ddlProjects = new List<SelectOption>();
            ddlProjects.add(new SelectOption('', '-- None --'));
            
            if(lstProjects.size() == 1) {
                //If only one project assigned then select it as default
                ProjectId = lstProjects.get(0).Id;
            }

            //List of completed projects (Need to add these project after not completed projects)
            lstCompletedProjects = new Map<Id, string>();

            for (NI_Documentation__c obj : lstProjects) {
                if(objProject == null) {
                    //Set project object value in the case when customer have only one project assigned
                    objProject = obj;
                }

                if(obj.AH_PLCM_Portal_Progress__c == ProjectPortalStatus.InventoryInformationProvided || obj.AH_PLCM_Portal_Progress__c == ProjectPortalStatus.CustomerInputCompleted) {
                    //Add project in completed list
                    lstCompletedProjects.put(obj.Id, obj.Document_Name__c + ' (Mapping Completed)');
                }
                else {
                    //Add project in not completed list
                    ddlProjects.add(new SelectOption(obj.Id, obj.Document_Name__c));
                }
            }
            
            if(lstCompletedProjects.size() > 0) {
                //Add completed projects in list after mapping pending projects
                for (Id id : lstCompletedProjects.keySet()) {
                    ddlProjects.add(new SelectOption(id, lstCompletedProjects.get(id)));
                }
            }
        }
        catch(Exception ex) {
            throw ex;
        }
        finally {
            //Release memory of objects
            lstCompletedProjects = null;
        }
    }   

    //Redirect to property page on click of next button
    public PageReference RedirectToFunctionRoomPage() { 
        List<NI_Documentation__c> lstProj = null;
        Map<string, string> lstParameters = null;
        try {
            if(!String.IsBlank(ProjectId)) {
                //Get project details based on id
                lstProj = new List<NI_Documentation__c>([SELECT Id, Name, AH_PLCM_Portal_Completion_Due_Date__c, DRC_Call_Date__c, AH_PLCM_Portal_Progress__c FROM NI_Documentation__c WHERE Id =: ProjectId]);

                if(lstProj != null && lstProj.size() > 0) {
                    //Update Migration Dates in Project Object
                    NI_Documentation__c obj = lstProj.get(0);
                
                   	obj.DRC_Call_Date__c = objProject.DRC_Call_Date__c;
                    if(String.isBlank(lstProj.get(0).AH_PLCM_Portal_Progress__c) || lstProj.get(0).AH_PLCM_Portal_Progress__c == 'Portal Invitation Sent'){
                        obj.AH_PLCM_Portal_Progress__c = ProjectPortalStatus.PropertyInformationConfirmed;
                    }
                    update obj;
                }

                //Redirect to function room page
                lstParameters = new Map<string, string>();
                lstParameters.put('ProjectId', ProjectId);
                System.debug('lstParameters'+lstParameters);
                return RedirectToPage(PageNames.FunctionRoomPage, lstParameters);
            }
            return null;
        }
        catch(Exception ex) {
            //Redirect to error page
            return RedirectToErrorPage('RedirectToFunctionRoomPage',ex);
        }
        finally {
            //Release memory of objects
            lstParameters = null;
            lstProj= null;
        }        
    }
}