force-app/main/default/objects/AH_Rally_Setup__c/AH_Rally_Setup__c.object-meta.xml
<CustomObject>
    <description>setup to configure Rally Support Manager</description>
    <label>Rally Setup</label>
    <nameField>
        <displayFormat>RS{0000}</displayFormat>
        <label>Rally Setup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rally Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_Rally_Setup__c/fields/API_Version__c.field-meta.xml
<CustomField>
    <fullName>API_Version__c</fullName>
    <description>This contains the API version number</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>V2.0</inlineHelpText>
    <label>API Version</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AH_Rally_Setup__c/fields/Exception_Notification_Email__c.field-meta.xml
<CustomField>
    <fullName>Exception_Notification_Email__c</fullName>
    <description>This contains email address to which an email is sent when the scheduler fails.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>enter a email address which is used to notify when scheduler fails</inlineHelpText>
    <label>Exception Notification Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/AH_Rally_Setup__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <description>Password associated with the Rally username.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>password associated with the Rally username.</inlineHelpText>
    <label>Password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AH_Rally_Setup__c/fields/RallyURL__c.field-meta.xml
<CustomField>
    <fullName>RallyURL__c</fullName>
    <description>URL for the Rally subscription in which defects and requirements will be created.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>URL for the Rally subscription in which defects and requirements will be created.</inlineHelpText>
    <label>RallyURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AH_Rally_Setup__c/fields/Schedular_Last_Run__c.field-meta.xml
<CustomField>
    <fullName>Schedular_Last_Run__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>This contains the time of the scehedular last run</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Schedular Last Run</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AH_Rally_Setup__c/fields/Story_Field_Map__c.field-meta.xml
<CustomField>
    <fullName>Story_Field_Map__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Story Field Map</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AH_Rally_Setup__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <description>Rally username used to create Rally artifacts from Salesforce.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Rally username used to create Rally artifacts from Salesforce.</inlineHelpText>
    <label>Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AH_Rally_Setup__c/fields/workspace__c.field-meta.xml
<CustomField>
    <fullName>workspace__c</fullName>
    <defaultValue>&quot;Workspace 1&quot;</defaultValue>
    <description>Rally workspace where defects and requirements will be created .</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Rally workspace where defects and requirements will be created .</inlineHelpText>
    <label>Workspace Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Attachment_Relation__c/Case_Attachment_Relation__c.object-meta.xml
<CustomObject>
    <description>This is a kind of junction object of case and attachment which will have a details of attachments created in rally.  Prior Name: Case Attachment Relation</description>
    <label>Rally Attachments</label>
    <nameField>
        <displayFormat>CAR-{00000}</displayFormat>
        <label>Case Attachment Relation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rally Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Attachment_Relation__c/fields/Case_Id__c.field-meta.xml
<CustomField>
    <fullName>Case_Id__c</fullName>
    <description>This contains the case id</description>
    <label>Case Id</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Case_Attachment_Relations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Case_Attachment_Relation__c/fields/Sf_Attachment_Id__c.field-meta.xml
<CustomField>
    <fullName>Sf_Attachment_Id__c</fullName>
    <description>This contains the SF attachment id</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Sf Attachment Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Attachment_Relation__c/fields/To_be_Send__c.field-meta.xml
<CustomField>
    <fullName>To_be_Send__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is checked if the check box is checked.</description>
    <label>To be Send</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case_Comment_Relation__c/Case_Comment_Relation__c.object-meta.xml
<CustomObject>
    <description>This contains the details of rally discussion details with respective to sf details. Prior Name: Case Comment Relation</description>
    <label>Rally Comments</label>
    <nameField>
        <displayFormat>CCR-{00000}</displayFormat>
        <label>Case Comment Relation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rally Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Comment_Relation__c/fields/Case_Id__c.field-meta.xml
<CustomField>
    <fullName>Case_Id__c</fullName>
    <description>This contains the case id of sf</description>
    <label>Case Id</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Case_Comment_Relations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Comment_Relation__c/fields/Sf_Comment_Id__c.field-meta.xml
<CustomField>
    <fullName>Sf_Comment_Id__c</fullName>
    <description>This contains the comment id</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Sf Comment Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Comment_Relation__c/fields/To_be_Send__c.field-meta.xml
<CustomField>
    <fullName>To_be_Send__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is the checked when check box is checked</description>
    <label>To be Send</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/COLA_Settings__c/COLA_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This will have all cola related as well as other custom settings needed</description>
    <label>COLA Settings</label>
</CustomObject>

force-app/main/default/objects/COLA_Settings__c/fields/Allow_Product_Creation__c.field-meta.xml
<CustomField>
    <fullName>Allow_Product_Creation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is to enable diable product creation for COLA and Renewal</description>
    <label>Allow Product Creation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/COLA_Settings__c/fields/Project_Mapping_Row_Count__c.field-meta.xml
<CustomField>
    <fullName>Project_Mapping_Row_Count__c</fullName>
    <description>This stores the number which will be used to display rows in the Product Project Mapping Page</description>
    <label>Project Mapping Row Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NI_DeploymentInstanceIndex__c/NI_DeploymentInstanceIndex__c.object-meta.xml
<CustomObject>
    <label>Deployment Instance Index</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Deployment Instance Index Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployment Instance Indexes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Group__c/Product_Group__c.object-meta.xml
<CustomObject>
    <label>Product Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductMapping__c/ProductMapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used to map products into Rally.</description>
    <label>Product Project Mapping</label>
</CustomObject>

force-app/main/default/objects/ProductMapping__c/fields/Affected_Component__c.field-meta.xml
<CustomField>
    <fullName>Affected_Component__c</fullName>
    <description>TC (Affected Component) now &quot;Module&quot;</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Module</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductMapping__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>This contains product value</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Case Product Line</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductMapping__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <description>This contains product family value</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Solution Domain</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductMapping__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>This contains project value</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Project</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Solution_Count__c/Solution_Count__c.object-meta.xml
<CustomObject>
    <label>Solution Count</label>
    <nameField>
        <displayFormat>SC-{000000000}</displayFormat>
        <label>Solution Count Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solution Counts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Solution_Count__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Solution Counts</relationshipLabel>
    <relationshipName>Solution_Counts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Solution_Count__c/fields/Number_of_Solutions__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Solutions__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Solutions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AH_Rally_SendAttachmentSchedule_Test.cls
/****************************************************************************************
Name            : AH_Rally_SendAttachmentSchedule_Test (TC Org Name: ScheduleAttachmentToTeamTestClass)
Author          : Valerie Gallardo
Created Date    : 01/21/2014
Last Mod Date   : 11/25/2020
Last Mod By     : Sean Harris
NICC Reference  : NICC-
Description     : Test class for AH_Rally_SendAttachmentSchedule
				: 
				: 
******************************************************************************************/
@isTest
public class AH_Rally_SendAttachmentSchedule_Test 
{

    // ======================================================================================================================================= 
    // = CREATE TEST DATA
    // ======================================================================================================================================= 
    @testSetup static void createTestData() 
    {

        Folder f = [SELECT Id FROM Folder WHERE Name = 'Support Email Templates'];
        BrandTemplate bt = [SELECT Id FROM BrandTemplate WHERE Name = 'Standard Letterhead (Sample)'];
        
        List<EmailTemplate> lstEmailTemplates = new List<EmailTemplate>();
        
        EmailTemplate e1 = new EmailTemplate();
        e1.Name = 'Forwarding to Web Support (EMEA & ASPAC) Web to Case';
        e1.Subject = 'Test Email Template #1';
        e1.developerName = 'TestEmailTemplate_1'; 
        e1.FolderId = f.Id; 
        e1.TemplateType = 'html'; 
        e1.HtmlValue = '<html><head></head><body><h1>HelloWorld1</h1></body></html>';
        e1.BrandTemplateId = bt.Id;
        e1.TemplateStyle = 'formalLetter';
        e1.IsActive = true;
        lstEmailTemplates.add(e1);

        EmailTemplate e2 = new EmailTemplate();
        e2.Name = 'Forwarding to Collections for Billing Questions';
        e2.Subject = 'Test Email Template #2';
        e2.developerName = 'TestEmailTemplate_2'; 
        e2.FolderId = f.Id; 
        e2.TemplateType = 'html'; 
        e2.HtmlValue = '<html><head></head><body><h1>HelloWorld2</h1></body></html>';
        e2.BrandTemplateId = bt.Id;
        e2.TemplateStyle = 'formalLetter';
        e2.IsActive = true;
        lstEmailTemplates.add(e2);

        EmailTemplate e3 = new EmailTemplate();
        e3.Name = 'Forwarding to GDS (images)';
        e3.Subject = 'Test Email Template #3';
        e3.developerName = 'TestEmailTemplate_3'; 
        e3.FolderId = f.Id; 
        e3.TemplateType = 'html'; 
        e3.HtmlValue = '<html><head></head><body><h1>HelloWorld3</h1></body></html>';
        e3.BrandTemplateId = bt.Id;
        e3.TemplateStyle = 'formalLetter';
        e3.IsActive = true;
        lstEmailTemplates.add(e3);

        EmailTemplate e4 = new EmailTemplate();
        e4.Name = 'Forwarding to Learning Services';
        e4.Subject = 'Test Email Template #4';
        e4.developerName = 'TestEmailTemplate_4'; 
        e4.FolderId = f.Id; 
        e4.TemplateType = 'html'; 
        e4.HtmlValue = '<html><head></head><body><h1>HelloWorld4</h1></body></html>';
        e4.BrandTemplateId = bt.Id;
        e4.TemplateStyle = 'formalLetter';
        e4.IsActive = true;
        lstEmailTemplates.add(e4);        
        
        database.insert(lstEmailTemplates);        

    }

    // ======================================================================================================================================= 
    // = TEST METHOD 1: testschedule
    // ======================================================================================================================================= 
    @isTest static void test1() 
    {

        
        // CREATE WIN@PROACH CUSTOM SETTINGS
        NI_TestClassData.createTestWinaproachServiceNowSettings();
        
        // CREATE TEST PRODUCT PROJECT (CUSTOM SETTING) RECORD
        ProductMapping__c pro = new ProductMapping__c();
        pro.Name = 'Mapping0';
        pro.Product_Family__c = 'Reservation Solutions';
        pro.Affected_Component__c = '';
        pro.Product__c = 'iHotelier CRS'; //'DataBridge';
        pro.Project__c = 'L3 PMSConnect';
        insert pro;
    
        COLA_Settings__c cs =  new COLA_Settings__c();
        cs.Name = 'STOMAutomation';
        cs.Allow_Product_Creation__c = true;
        cs.Project_Mapping_Row_Count__c = 100;
        insert cs; 

        // CREATE TEST RALLY SETUP RECORD
		AH_Rally_Setup__c rsm = new AH_Rally_Setup__c(); 
		rsm.API_Version__c = '1.43';
		rsm.Exception_Notification_Email__c = 'abc@abc.com';
		rsm.password__c = '12345';
		rsm.rallyUrl__c = 'https://rally1.rallydev.com';
		rsm.username__c = 'travelclick';
		rsm.workspace__c = 'jira';
		rsm.Schedular_Last_Run__c = DATETIME.now();
		rsm.Story_Field_Map__c = '{"Description":{"fldValue":"None","literalValue":""},"KanbanState":{"custom":1,"fldValue":"None","literalValue":""},"L3KanbanStage":{"custom":1,"fldValue":"Default","literalValue":"Advance Investigation"},"Moscow":{"custom":1,"fldValue":"None","literalValue":""},"Name":{"fldValue":"Subject","literalValue":""},"Owner":{"fldValue":"None","literalValue":""},"Package":{"fldValue":"None","literalValue":""},"Rank":{"fldValue":"None","literalValue":""},"ReadyDeprecated":{"custom":1,"fldValue":"None","literalValue":""},"SalesforcePriority":{"custom":1,"fldValue":"Priority","literalValue":""},"StoryType":{"custom":1,"fldValue":"Default","literalValue":"L3/Salesforce"}}';
        insert rsm;  
        
        // CREATE TEST ACCOUNT RECORD
        Account a = NI_TestClassData.createTestAccount(1);
        a.Name = 'AH_Rally_CreateUserStory_Test Account';
        insert a;
        
        // CREATE TEST CONTACT
        Contact cnt = NI_TestClassData.createTestContact(1, a.Id);
        cnt.FirstName = 'APEXTESTUSER';
        cnt.LastName = 'APEXTESTUSER';
        insert cnt;
        
        // CREATE 2 TEST CASE RECORDS
		Case cs1 = NI_TestClassData.createTestCase(1, a.Id);
        cs1.Subject = 'AH_Rally_CreateUserStory_Test Case# 1';
        cs1.User_Story_Id__c = 'US90582';
        cs1.Priority = 'Medium';
        cs1.Status = 'Escalate to L3';
        cs1.Type = 'Approvals';
        cs1.Origin = 'Fax';
        cs1.Number_of_Requests__c = 1;
        cs1.L3_Ticket_Summary__c = 'abc';
        cs1.L3_Steps_To_Reproduce__c = 'abc';
        cs1.Product_Family__c = 'Reservation Solutions';
        cs1.Product__c = 'iHotelier CRS';
        cs1.UserStory_Rally_Status__c = 'In Progress';
        cs1.Rally_Artifact_Ref__c = 'https://rally1.rallydev.com/slm/webservice/1.43/defect/14961076175.js';
        cs1.Affected_Component__c = '';
        insert cs1;

        // CREATE 2 TEST CASE ATTACHMENT RELATION RECORD
        Case_Attachment_Relation__c attach = new Case_Attachment_Relation__c();
        attach.case_id__c = cs1.Id;
        attach.To_be_Send__c = true;
        attach.Sf_Attachment_Id__c = '123456789123456789';
        insert attach;
        
        // CREATE 2 TEST CASE COMMENT RELATION RECORD
        Case_Comment_Relation__c comment = new Case_Comment_Relation__c();
        comment.case_Id__c = cs1.Id;
        comment.To_be_Send__c = true;
        comment.Sf_Comment_Id__c = '123456789123456789';
        insert comment;

        // CREATE TEST DI INDEX RECORD  
        NI_DeploymentInstanceIndex__c diIdx = NI_TestClassData.createDI_Index(1, 'APEX TEST');
        insert diIdx;
        
        // CREATE TEST PRODUCT GROUP RECORD  
        Product_Group__c pgp = NI_TestClassData.createProductGroup(1, 'Apex Test Group');
        insert pgp;

		// CREATE TEST PRODUCT RECORD          
        Product2 prd = NI_TestClassData.createProduct2(1, pgp.Id, 'ZZZFULFILL-APEX-001', 'Subscription');
        prd.DI_Index__c = diIdx.Id;
        insert prd;

        // CREATE TEST DI RECORD  
        Asset di = NI_TestClassData.createTestAsset(1, a.Id, prd.Id); 
        di.Product_Group__c = pgp.Id; 
        insert di;

        // CREATE TEST SOLUTION RECORD  
        Solution sol = NI_TestClassData.createSolution(1); 
        sol.SolutionName = 'AH_Rally_CreateUserStory_Test Solution';
        insert sol;

        // ADD A SOLUTION TO CASE
        CaseSolution csSol = NI_TestClassData.createCaseSolution(cs1.Id, sol.Id);
        insert csSol;

        Solution_Count__c sc = new Solution_Count__c();
        sc.Case__c = cs1.Id;
        sc.Number_of_Solutions__c = 1;
        insert sc;           
        
        Test.startTest();

        AH_Rally_SendAttachmentSchedule sh1 = new AH_Rally_SendAttachmentSchedule();
        String sch = '0 15 * * * ?';
        system.schedule('Test scheduledBatchable', sch, sh1);
        
        Test.stopTest();
        
    }
    
}