force-app/main/default/objects/AH_Rally_Setup__c/AH_Rally_Setup__c.object-meta.xml
<CustomObject>
    <description>setup to configure Rally Support Manager</description>
    <label>Rally Setup</label>
    <nameField>
        <displayFormat>RS{0000}</displayFormat>
        <label>Rally Setup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rally Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_Rally_Setup__c/fields/API_Version__c.field-meta.xml
<CustomField>
    <fullName>API_Version__c</fullName>
    <description>This contains the API version number</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>V2.0</inlineHelpText>
    <label>API Version</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AH_Rally_Setup__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <description>Password associated with the Rally username.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>password associated with the Rally username.</inlineHelpText>
    <label>Password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AH_Rally_Setup__c/fields/RallyURL__c.field-meta.xml
<CustomField>
    <fullName>RallyURL__c</fullName>
    <description>URL for the Rally subscription in which defects and requirements will be created.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>URL for the Rally subscription in which defects and requirements will be created.</inlineHelpText>
    <label>RallyURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AH_Rally_Setup__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <description>Rally username used to create Rally artifacts from Salesforce.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Rally username used to create Rally artifacts from Salesforce.</inlineHelpText>
    <label>Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AH_Rally_Setup__c/fields/workspace__c.field-meta.xml
<CustomField>
    <fullName>workspace__c</fullName>
    <defaultValue>&quot;Workspace 1&quot;</defaultValue>
    <description>Rally workspace where defects and requirements will be created .</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Rally workspace where defects and requirements will be created .</inlineHelpText>
    <label>Workspace Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Attachment_Relation__c/Case_Attachment_Relation__c.object-meta.xml
<CustomObject>
    <description>This is a kind of junction object of case and attachment which will have a details of attachments created in rally.  Prior Name: Case Attachment Relation</description>
    <label>Rally Attachments</label>
    <nameField>
        <displayFormat>CAR-{00000}</displayFormat>
        <label>Case Attachment Relation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rally Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Attachment_Relation__c/fields/Case_Id__c.field-meta.xml
<CustomField>
    <fullName>Case_Id__c</fullName>
    <description>This contains the case id</description>
    <label>Case Id</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Case_Attachment_Relations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Case_Attachment_Relation__c/fields/Defect_Id__c.field-meta.xml
<CustomField>
    <fullName>Defect_Id__c</fullName>
    <description>This contains defect id</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Defect Id</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Attachment_Relation__c/fields/Rally_Attachment_Id__c.field-meta.xml
<CustomField>
    <fullName>Rally_Attachment_Id__c</fullName>
    <description>This contains the attachment id of rally</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Rally Attachment Id</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Attachment_Relation__c/fields/Sf_Attachment_Id__c.field-meta.xml
<CustomField>
    <fullName>Sf_Attachment_Id__c</fullName>
    <description>This contains the SF attachment id</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Sf Attachment Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Attachment_Relation__c/fields/SF_File_Id__c.field-meta.xml
<CustomField>
    <fullName>SF_File_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>SF File Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Attachment_Relation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This contains status value</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Attachment_Relation__c/fields/To_be_Send__c.field-meta.xml
<CustomField>
    <fullName>To_be_Send__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is checked if the check box is checked.</description>
    <label>To be Send</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case_Comment_Relation__c/Case_Comment_Relation__c.object-meta.xml
<CustomObject>
    <description>This contains the details of rally discussion details with respective to sf details. Prior Name: Case Comment Relation</description>
    <label>Rally Comments</label>
    <nameField>
        <displayFormat>CCR-{00000}</displayFormat>
        <label>Case Comment Relation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rally Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Comment_Relation__c/fields/Case_Id__c.field-meta.xml
<CustomField>
    <fullName>Case_Id__c</fullName>
    <description>This contains the case id of sf</description>
    <label>Case Id</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>Case_Comment_Relations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Comment_Relation__c/fields/Defect_Id__c.field-meta.xml
<CustomField>
    <fullName>Defect_Id__c</fullName>
    <description>This contains the defect id value</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Defect Id</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Comment_Relation__c/fields/Sf_Comment_Id__c.field-meta.xml
<CustomField>
    <fullName>Sf_Comment_Id__c</fullName>
    <description>This contains the comment id</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Sf Comment Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Comment_Relation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This contains the status of comment</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Comment_Relation__c/fields/To_be_Send__c.field-meta.xml
<CustomField>
    <fullName>To_be_Send__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is the checked when check box is checked</description>
    <label>To be Send</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AH_Rally_LEXMethods.cls
/****************************************************************************************
Name            : AH_Rally_LEXMethods
Author          : Sean Harris
Created Date    : 11/25/2020
Last Mod Date   : 11/25/2020
Last Mod By     : Sean Harris
NICC Reference  : NICC-047046
Description     : Class with @auraEnabled methods used by Lightning Components
				: 
				: 
******************************************************************************************/
public class AH_Rally_LEXMethods 
{
    
    @auraEnabled
    public static Map<String, sObject> returnCaseRecs(String caseId)
    {
        Map<String, sObject> mp = new Map<String, sObject>();
        try
        {
            Case cs = [SELECT L3_Steps_To_Reproduce__c, Rally_Artifact_Ref__c, L3_Ticket_Summary__c, Rally_Case_Type__c FROM Case WHERE Id =: caseId LIMIT 1];
            mp.put('getCase', cs);
            AH_Rally_Setup__c rallySMObj = [SELECT Username__c, Password__c, RallyURL__c, Workspace__c, API_Version__c FROM AH_Rally_Setup__c ORDER BY Name ASC];						        
            mp.put('getRallySM', rallySMObj);            
        }
        catch (Exception e)
        {
            system.debug('Error : ' + e.getStackTraceString());
        }
        return mp;
    }

    @auraEnabled
    public static List<String> returnAttachments(String caseId)
    {
        List<Case_Attachment_Relation__c> attachmentIdL = [SELECT Sf_Attachment_Id__c FROM Case_Attachment_Relation__c WHERE To_be_Send__c = true and Case_Id__c =: caseId];
        List<String> ids = new List<String>();
        for (Case_Attachment_Relation__c c : attachmentIdL)
        {
            ids.add(c.Sf_Attachment_Id__c);
        }
        return ids;        
    }

    @auraEnabled
    public static List<String> returnComments(String caseId)
    {
        List<String> ids = new List<String>();
        List<Case_Comment_Relation__c> commentIdL = [SELECT Sf_Comment_Id__c FROM Case_Comment_Relation__c WHERE To_be_Send__c = true and Case_Id__c =: caseId];
        for (Case_Comment_Relation__c c : commentIdL)
        {
            ids.add(c.Sf_Comment_Id__c);
        }
        return ids;
    }
    
    @auraEnabled
    public static String returnWorkspaceURL()
    {
        String workspaceURL = AH_Rally_Library.workspaceUrl(); 
        return workspaceURL;
    }

    @auraEnabled
    public static String resultofUserStory(String caseId)
    {
        String msg = AH_Rally_CreateUserStory.createUserStory(caseID);
        return msg;
    }

    @auraEnabled
    public static String callout(String methodType, String endPoint, String body)
    {
        String res = AH_Rally_Library.sendRequestObject(methodType, endpoint, body); 
        return res;
    }

    @auraEnabled
    public static void updateComments(String caseId, String defectId, String commentId, String SalesforceCommentId)
    {
        AH_Rally_InsertIntoDB.UpdateIntoCommentObject(caseId, defectId, commentId, SalesforceCommentId);
    }    
    
    @auraEnabled
    public static String sendAttachmentMethod(String attachId)
    {
        String myQuery = 'SELECT Name, BodyLength, Body, ContentType from Attachment WHERE Id = \'' + attachId + '\' ';  
        Attachment a = Database.query(myQuery);
        JSONGenerator gen = JSON.createGenerator(true);   
        gen.writeStartObject();
        gen.writeStringField('Name', a.Name);
        gen.writeNumberField('BodyLength', a.BodyLength);               
        gen.writeStringField('Body', EncodingUtil.base64encode(a.Body));
        if (a.ContentType != null)
        {
            gen.writeStringField('ContentType', a.ContentType);    
        }  
        gen.writeEndObject(); 
        String jstring = gen.getAsString();
        return jstring; 
    }

    @auraEnabled
    public static void callUpdateIntoCARBasedOnOperation(String defectId, String cID, String RallyattachemntId, String Salesforceattid)
    {
        String dId = String.valueOf(defectId);
        String rattachId = String.valueOf(RallyattachemntId);
        try
        {
            Case_Attachment_Relation__c carList = [SELECT Sf_Attachment_Id__c, Case_Id__c, To_be_Send__c 
                                                   FROM Case_Attachment_Relation__c 
                                                   WHERE To_be_Send__c = true 
                                                   AND Sf_Attachment_Id__c =: Salesforceattid];
            if (carList != null)
            {
                carList.Rally_Attachment_Id__c = RallyattachemntId;
                carList.Defect_Id__c = defectId;
                carList.Status__c = 'Sent';
                carList.To_be_Send__c = false; 
                update carList;
            }
        }
        catch (Exception e)
        {
            System.debug(e.getMessage());
        }
    }
    
    @auraEnabled
    public static void makeUserLREFalse()
    {
        String userId = System.UserInfo.getUserId();
        User u = [SELECT Id, Name, UserPreferencesLightningExperiencePreferred FROM User WHERE Id =: userId];
        if (u.UserPreferencesLightningExperiencePreferred)
        {
            u.UserPreferencesLightningExperiencePreferred = false;
        }
        update u;
    }
    
/*
    @auraEnabled
    public static void sendAttachment(List<String> attachId)
    {
    	//takes the Id that is returned from above "returnAttachments" method        
    }

    @auraEnabled
    public static String returnConversationBody(String caseId, String commentid)
    {
        String jsonBody = CaseCommentofSalesforce.createConversationPostContent(caseId, commentid);
        return jsonBody;
    }
*/
    
    @AuraEnabled
    public static String getContentDocs(Id recId)
    {   
        
        List<ContentDocumentLink> cdls = [SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId =: recId];
        
        // Make a List of ContentDocument IDs
        List<Id> cdIdList = new List<Id>();
        
        for (ContentDocumentLink nextCDL : cdls) 
        {
            cdIdList.add(nextCDL.ContentDocumentId); 
        }        
        
        Case caseRallyUS = [SELECT Id, User_Story_Id__c FROM Case WHERE Id =: recId];
        
        List<Case_Attachment_Relation__c> cars = [SELECT SF_File_Id__c, Status__c FROM Case_Attachment_Relation__c WHERE SF_File_Id__c != '' AND Case_Id__c =: recId];
        
        Map<Id, String> carRelationMap = new Map<Id, String>();
        
        for (Case_Attachment_Relation__c car:cars)
        {                   
            carRelationMap.put(car.SF_File_Id__c, car.Status__c);
        }
        
        List<ContentDocument> entries = [SELECT Id, Title, FileType, ContentSize, LastModifiedDate FROM ContentDocument WHERE Id IN :cdIdList order by CreatedDate desc];
        List<FileWrap> fwl = new List<FileWrap>();
        
        for (ContentDocument cd : entries)
        {
            
            FileWrap fw = new FileWrap();
            fw.Id = cd.Id;
            fw.Title = cd.Title;
            fw.FileType = cd.FileType;
            fw.ContentSize = cd.ContentSize;
            fw.LastModifiedDate = cd.LastModifiedDate;
            fw.Body = '';            
            fw.Description = '';
            
            if (caseRallyUS.User_Story_Id__c !='' && caseRallyUS.User_Story_Id__c != null)
            {
                fw.userStoryCreated = true;
            }
            
            if (carRelationMap.containsKey(cd.Id))
            {
                fw.fileStatus = carRelationMap.get(cd.Id);
            }
            
            fwl.add(fw);
            
        }
        
        return JSON.serialize(fwl);
        
    }
    
    @AuraEnabled
    public static void deleteFiles(Id recId)
    { 
        ContentDocument cd = [SELECT Id, Title, FileType, ContentSize, LastModifiedDate FROM ContentDocument WHERE Id =: recId];
        delete cd;
    }
    
    @AuraEnabled
    public static String sendAttachment(Id recId, Id caseId)
    { 
        
        String res = ''; 
        
        try
        {  
            
            String username;
            String password;
            String workspacename;
            String Rallyurl; 
            String API_Version;
            
            if (!Test.isRunningTest())
            {
                String workspaceUrl = AH_Rally_Library.workspaceUrl();
            }
            
            AH_Rally_Setup__c rrsc = [SELECT Username__c, Password__c, RallyURL__c, Workspace__c,API_Version__c FROM AH_Rally_Setup__c ORDER BY Name ASC LIMIT 1]; 
            
            if (rrsc != null)
            {
                username = rrsc.Username__c;
                password = rrsc.Password__c;
                workspacename=rrsc.Workspace__c;
                API_Version = rrsc.API_Version__c;
                Rallyurl = rrsc.RallyURL__c; 
            }
            
            String jsonStr = AH_Rally_SendFiles.valuesofAttachmentFiles(recId);   
            
            if (jsonStr == 'FileSizeException')
            {
                res = 'exception|File size is too large to send to rally.';
            }
            else
            {
                FileWrap filewrap = (FileWrap)JSON.deserialize(jsonStr, FileWrap.class);           
                String attachmentContent = filewrap.Body;            
                res = AH_Rally_SendFiles.sendAttachmentFiles(recId, caseId);
                if (res == 'object not found')
                {
                    res = 'exception|User Story is Deleted in Rally';
                }
            }
            
        }
        catch (Exception e)
        {
            res='exception|' + e.getMessage();
        }
        
        return res;
        
    }

    //Accepts the record id and sends a boolean status about the updation
    @AuraEnabled @RemoteAction
    public static Boolean updateCase(Id caseId){
        try{
            case cs = new case();
            cs.id = caseId;
            cs.recordtypeid=Schema.SObjectType.case.getRecordTypeInfosByName().get('Rally Support').getRecordTypeId();
            update cs;
            return true;
        }
        catch(Exception e){
            return false;
        }
    }
    
    public class FileWrap
    {
        Id id;
        Integer ContentSize;  
        Datetime LastModifiedDate;
        String Title;
        String Body;
        String FileType;
        String Description;
        String fileStatus;
        Boolean userStoryCreated = false;
    }
    
}