force-app/main/default/objects/AH_Rally_Setup__c/AH_Rally_Setup__c.object-meta.xml
<CustomObject>
    <description>setup to configure Rally Support Manager</description>
    <label>Rally Setup</label>
    <nameField>
        <displayFormat>RS{0000}</displayFormat>
        <label>Rally Setup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rally Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_Rally_Setup__c/fields/API_Version__c.field-meta.xml
<CustomField>
    <fullName>API_Version__c</fullName>
    <description>This contains the API version number</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>V2.0</inlineHelpText>
    <label>API Version</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AH_Rally_Setup__c/fields/Exception_Notification_Email__c.field-meta.xml
<CustomField>
    <fullName>Exception_Notification_Email__c</fullName>
    <description>This contains email address to which an email is sent when the scheduler fails.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>enter a email address which is used to notify when scheduler fails</inlineHelpText>
    <label>Exception Notification Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/AH_Rally_Setup__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <description>Password associated with the Rally username.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>password associated with the Rally username.</inlineHelpText>
    <label>Password</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AH_Rally_Setup__c/fields/RallyURL__c.field-meta.xml
<CustomField>
    <fullName>RallyURL__c</fullName>
    <description>URL for the Rally subscription in which defects and requirements will be created.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>URL for the Rally subscription in which defects and requirements will be created.</inlineHelpText>
    <label>RallyURL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AH_Rally_Setup__c/fields/Schedular_Last_Run__c.field-meta.xml
<CustomField>
    <fullName>Schedular_Last_Run__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>This contains the time of the scehedular last run</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Schedular Last Run</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AH_Rally_Setup__c/fields/Story_Field_Map__c.field-meta.xml
<CustomField>
    <fullName>Story_Field_Map__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Story Field Map</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AH_Rally_Setup__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <description>Rally username used to create Rally artifacts from Salesforce.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Rally username used to create Rally artifacts from Salesforce.</inlineHelpText>
    <label>Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AH_Rally_Setup__c/fields/workspace__c.field-meta.xml
<CustomField>
    <fullName>workspace__c</fullName>
    <defaultValue>&quot;Workspace 1&quot;</defaultValue>
    <description>Rally workspace where defects and requirements will be created .</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Rally workspace where defects and requirements will be created .</inlineHelpText>
    <label>Workspace Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AH_Rally_AttachmentJSON_Test.cls
/****************************************************************************************
Name            : AH_Rally_AttachmentJSON  (TC Org Name: LRAttachmentJSON)
Author          : Valerie Gallardo
Created Date    : 01/21/2014
Last Mod Date   : 11/25/2020
Last Mod By     : Sean Harris
NICC Reference  : NICC-047046
Description     : Test class for AH_Rally_AttachmentJSON
				: 
				: 
******************************************************************************************/
@isTest
public class AH_Rally_AttachmentJSON_Test 
{

    @isTest static void test1() 
    {
        
        // CREATE RALLY SETUP RECORD
        AH_Rally_Setup__c rsm = new AH_Rally_Setup__c();
        //rsm.API_Version__c = 1.43;
        rsm.Exception_Notification_Email__c = 'abc@abc.com';
        rsm.password__c = '12345';
        rsm.rallyUrl__c = 'https://rally1.rallydev.com';
        rsm.username__c = 'travelclick';
        rsm.workspace__c = 'jira';
        rsm.Schedular_Last_Run__c = DATETIME.now();
        rsm.Story_Field_Map__c = '{"Description":{"fldValue":"None","literalValue":""},"KanbanState":{"custom":1,"fldValue":"None","literalValue":""},"L3KanbanStage":{"custom":1,"fldValue":"Default","literalValue":"Advance Investigation"},"Moscow":{"custom":1,"fldValue":"None","literalValue":""},"Name":{"fldValue":"Subject","literalValue":""},"Owner":{"fldValue":"None","literalValue":""},"Package":{"fldValue":"None","literalValue":""},"Rank":{"fldValue":"None","literalValue":""},"ReadyDeprecated":{"custom":1,"fldValue":"None","literalValue":""},"SalesforcePriority":{"custom":1,"fldValue":"Priority","literalValue":""},"StoryType":{"custom":1,"fldValue":"Default","literalValue":"L3/Salesforce"}}';
        insert rsm;         
        
        Test.startTest();
        
        String res = '{"AH_Rally_AttachmentJSON":[{"Content":"Hello"}]}';
        AH_Rally_AttachmentJSON attcls = (AH_Rally_AttachmentJSON) json.deserialize(res, AH_Rally_AttachmentJSON.class);  
        
        Test.stopTest();
        
        system.assert(true);

    }

}