force-app/main/default/objects/OrgInfo__c/OrgInfo__c.object-meta.xml
<CustomObject>
    <description>Base organization information retrieved during polling for the org search functionality</description>
    <label>OrgInfo</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrgInfos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/OrgPropDocTemplateCount__c/OrgPropDocTemplateCount__c.object-meta.xml
<CustomObject>
    <description>Org Property Document Template Count information retrieved during polling for the org search functionality</description>
    <label>OrgPropDocTemplateCount</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrgPropDocTemplateCounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrgPropDocTemplateCount__c/fields/OrgInfo__c.field-meta.xml
<CustomField>
    <fullName>OrgInfo__c</fullName>
    <complianceGroup>Normal</complianceGroup>
    <description>Key to tie this table to the ID field on the OrgInfo table</description>
    <label>OrgInfo</label>
    <referenceTo>OrgInfo__c</referenceTo>
    <relationshipLabel>OrgPropDocTemplateCount</relationshipLabel>
    <relationshipName>OrgPropDocTemplateCount</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OrgProperty__c/OrgProperty__c.object-meta.xml
<CustomObject>
    <description>Organization Property information retrieved during polling for the org search functionality</description>
    <label>OrgProperty</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrgProperties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrgProperty__c/fields/OrgInfo__c.field-meta.xml
<CustomField>
    <fullName>OrgInfo__c</fullName>
    <complianceGroup>Normal</complianceGroup>
    <description>Key to tie this table to the ID field on the OrgInfo table</description>
    <label>OrgInfo</label>
    <referenceTo>OrgInfo__c</referenceTo>
    <relationshipLabel>OrgProperties</relationshipLabel>
    <relationshipName>OrgProperties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OrgPropertyIntegrationSetting__c/OrgPropertyIntegrationSetting__c.object-meta.xml
<CustomObject>
    <description>Organization Property Integration Setting information retrieved during polling for the org search functionality</description>
    <label>OrgPropertyIntegrationSetting</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrgPropertyIntegrationSettings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrgPropertyIntegrationSetting__c/fields/OrgInfo__c.field-meta.xml
<CustomField>
    <fullName>OrgInfo__c</fullName>
    <complianceGroup>Normal</complianceGroup>
    <description>Key to tie this table to the ID field on the OrgInfo table</description>
    <label>OrgInfo</label>
    <referenceTo>OrgInfo__c</referenceTo>
    <relationshipLabel>OrgPropertyIntegrationSettings</relationshipLabel>
    <relationshipName>OrgPropertyIntegrationSettings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OrgPropMenuItemCount__c/OrgPropMenuItemCount__c.object-meta.xml
<CustomObject>
    <description>Org Property Menu Item Count information retrieved during polling for the org search functionality</description>
    <label>OrgPropMenuItemCount</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrgPropMenuItemCounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrgPropMenuItemCount__c/fields/OrgInfo__c.field-meta.xml
<CustomField>
    <fullName>OrgInfo__c</fullName>
    <complianceGroup>Normal</complianceGroup>
    <description>Key to tie this table to the ID field on the OrgInfo table</description>
    <label>OrgInfo</label>
    <referenceTo>OrgInfo__c</referenceTo>
    <relationshipLabel>OrgPropMenuItemCount</relationshipLabel>
    <relationshipName>OrgPropMenuItemCount</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OrgSetupValue__c/OrgSetupValue__c.object-meta.xml
<CustomObject>
    <description>Setup Value information retrieved from polling for search functionality</description>
    <label>OrgSetupValue</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrgSetupValues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrgSetupValue__c/fields/OrgInfo__c.field-meta.xml
<CustomField>
    <fullName>OrgInfo__c</fullName>
    <complianceGroup>Normal</complianceGroup>
    <description>Key to tie this table to the ID field on the OrgInfo table</description>
    <label>OrgInfo</label>
    <referenceTo>OrgInfo__c</referenceTo>
    <relationshipLabel>OrgSetupValue</relationshipLabel>
    <relationshipName>OrgSetupValue</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/OrgPropertyBatch.cls
/************************************************************************************************
Name            : OrgPropertyBatch - Batch Class
Author          : Michael Pedro
Last Mod Date   : 05/05/2022
Last Mod By     : Michael Pedro
Description     : Property related object batch class for org search
*************************************************************************************************/
@IsTest
public class OrgPropertyBatch
{   
    // need re-work to handle batchable data limits

    // global List<OrgInfoBatch.OrgPropertyQueryInfo> allOrgPropertyQueryInfo;
    
    // global OrgPropertyBatch(List<OrgInfoBatch.OrgPropertyQueryInfo> queryInfo) 
    // {
    //     this.allOrgPropertyQueryInfo = queryInfo;
    // }
    
    // global Iterable<OrgInfoBatch.OrgPropertyQueryInfo> start(Database.BatchableContext bc) 
    // {       
    //     return this.allOrgPropertyQueryInfo;
    // }

    // global void execute(Database.BatchableContext bc, List<OrgInfoBatch.OrgPropertyQueryInfo> orgPropertiesInfo) 
    // {
    //     for (OrgInfoBatch.OrgPropertyQueryInfo propInfo: orgPropertiesInfo) {
    //        // if (propInfo.OrgInfoResult != null) {
    //             // upsert properties
    //             if (propInfo.OrgPropertyResult != null) {
    //                 List<OrgProperty__c> propsForUpsert = new List<OrgProperty__c>();
    //                 for (OrgProperty__c p :propInfo.OrgPropertyResult) {
    //                     p.OrgInfo__c = propInfo.OrgInfoId;
    //                     propsForUpsert.add(p);
    //                 }
    //                 OrgNi.insertWithRetry(propsForUpsert,3);
    //             }
    //             // upsert property integrations
    //             if (propInfo.orgPropertyIntegrationSettingResult != null) {
    //                 List<OrgPropertyIntegrationSetting__c> propertyIntForUpsert = new List<OrgPropertyIntegrationSetting__c>();
    //                 for (OrgPropertyIntegrationSetting__c pi :propInfo.orgPropertyIntegrationSettingResult) {
    //                     pi.OrgInfo__c = propInfo.OrgInfoId;
    //                     propertyIntForUpsert.add(pi);
    //                 }
    //                 OrgNi.insertWithRetry(propertyIntForUpsert,3);
    //             }

    //             if (propInfo.OrgPropertyMenuItemCountsResult != null) {
    //                 List<OrgPropMenuItemCount__c> propMenuCounts = new List<OrgPropMenuItemCount__c>();
    //                 for (OrgPropMenuItemCount__c pmc :propInfo.OrgPropertyMenuItemCountsResult) {
    //                     pmc.OrgInfo__c = propInfo.OrgInfoId;
    //                     propMenuCounts.add(pmc);
    //                 }
    //                 OrgNi.insertWithRetry(propMenuCounts,3);
    //             }

    //             if (propInfo.OrgPropDocumentTemplateResult != null) {
    //                 List<OrgPropDocTemplateCount__c> docTemps = new List<OrgPropDocTemplateCount__c>();
    //                 for (OrgPropDocTemplateCount__c dt :propInfo.OrgPropDocumentTemplateResult) {
    //                     dt.OrgInfo__c = propInfo.OrgInfoId;
    //                     docTemps.add(dt);
    //                 }
    //                 OrgNi.insertWithRetry(docTemps,3);
    //             }

    //             if (propInfo.OrgSetupValueResult != null) {
    //                 List<OrgSetupValue__c> svs = new List<OrgSetupValue__c>();
    //                 for (OrgSetupValue__c sv :propInfo.OrgSetupValueResult) {
    //                     sv.OrgInfo__c = propInfo.OrgInfoId;
    //                     svs.add(sv);
    //                 }
    //                 OrgNi.insertWithRetry(svs,3);
    //             }
    //      //   }
    //     }
    // }
    
    // global void finish(Database.BatchableContext bc)
    // {
    // }
    
}