force-app/main/default/objects/Billing_Contract_Line_Item__c/Billing_Contract_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Billing Contract Line Item</label>
    <nameField>
        <displayFormat>BL-{00000}</displayFormat>
        <label>Billing Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Contract Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Credit_Processed__c.field-meta.xml
<CustomField>
    <fullName>Credit_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Will be marked true if a credit has been processed for this line item</inlineHelpText>
    <label>Credit Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Invoiced__c.field-meta.xml
<CustomField>
    <fullName>Invoiced__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Invoiced</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Line_Item_Description__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Provide information on line items</inlineHelpText>
    <label>Line Item Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Terms</label>
    <referenceTo>Payment_Terms__c</referenceTo>
    <relationshipLabel>Billing Contract Line Items</relationshipLabel>
    <relationshipName>Billing_Contract_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>0</defaultValue>
    <description>NICC-035500 - Changed Decimal Places</description>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Billing_Contract_Line_Item__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Terms__c/Payment_Terms__c.object-meta.xml
<CustomObject>
    <description>Payment Terms Object that holds information on how billing a client should proceed based on specific invoicing requirements.</description>
    <label>Invoice Terms</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Payment Terms Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Terms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/billingContractCreditHandler.cls
/****************************************************************************************
Name            : billingContractCreditHandler
Author          : CLD
Created Date    : April 19, 2016
Description     : Contains various methods for interacting with Billing Contracts
Open Items:
******************************************************************************************/

public class billingContractCreditHandler {
	
	/****************************************************************************************
	Method to Process Renewals for Activity Lines
	****************************************************************************************/
	public static void processBCCredits (List<billingContractCreditController.bliWrapper> wrapperList)
	{
		List<Billing_Contract_Line_Item__c> bliInsertList = new List<Billing_Contract_Line_Item__c>();
		List<Billing_Contract_Line_Item__c> bliUpdateList = new List<Billing_Contract_Line_Item__c>();

		
		//======STEP 1: CLONE THE BILLING LINES SELECTED.
		for(billingContractCreditController.bliWrapper wrapper : wrapperList)
		{
			Billing_Contract_Line_Item__c newBLI = wrapper.bliObject.clone(false,true,false,false);
			newBLI.Quantity__c = wrapper.dummy_bliObject.Quantity__c;
			newBLI.Unit_Price__c = wrapper.dummy_bliObject.Unit_Price__c;
			newBLI.Total_Amount__c = (newBLI.Quantity__c * newBLI.Unit_Price__c).setScale(2);
			newBLI.Payment_Terms__c = wrapper.dummy_bliObject.Payment_Terms__c;
			newBLI.Line_Item_Description__c = 'CREDIT - ' + newBLI.Line_Item_Description__c;
			newBLI.Invoiced__c = false;

			bliInsertList.add(newBLI);
			bliUpdateList.add(wrapper.bliObject);
		}
		insert bliInsertList;

		
		//======STEP 3: UPDATE ANY BILLING LINES THAT HAVE BEEN CREDITED SO THE CAN BE 
		for(Billing_Contract_Line_Item__c bli : bliUpdateList){
			bli.Credit_Processed__c = true;
		}
		update bliUpdateList;
	}
}