force-app/main/default/objects/AH_PLCM_MM_Inventory__c/AH_PLCM_MM_Inventory__c.object-meta.xml
<CustomObject>
    <description>Meeting Matrix inventory of physical items (tables, chairs, etc).  Used for MM to AHD conversions.</description>
    <label>MM Inventory</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>AHD Conversion Property</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MM Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_PLCM_MM_Inventory__c/fields/MM_Chair_1_Height__c.field-meta.xml
<CustomField>
    <fullName>MM_Chair_1_Height__c</fullName>
    <description>What is the chair height?</description>
    <inlineHelpText>What is the chair height?</inlineHelpText>
    <label>Chair 1 Height</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AH_PLCM_MM_Room_Details__c/AH_PLCM_MM_Room_Details__c.object-meta.xml
<CustomObject>
    <description>This object contains the Meeting Matrix room details.</description>
    <label>MM Room Details</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Function Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MM Room Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_PLCM_MM_Room_Details__c/fields/MM_Source_Type__c.field-meta.xml
<CustomField>
    <fullName>MM_Source_Type__c</fullName>
    <description>Type of source data.</description>
    <inlineHelpText>What is the source of your diagramming data?</inlineHelpText>
    <label>Source Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MM</fullName>
                <default>true</default>
                <label>MM</label>
            </value>
            <value>
                <fullName>CAD</fullName>
            </value>
            <value>
                <fullName>PDF</fullName>
            </value>
            <value>
                <fullName>Onsite (Total Station)</fullName>
            </value>
            <value>
                <fullName>DD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NI_Documentation__c/NI_Documentation__c.object-meta.xml
<CustomObject>
    <label>NI Documentation</label>
    <nameField>
        <displayFormat>DOC-{00000}</displayFormat>
        <label>Doc #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NI Documentation</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_Documentation__c/fields/Document_Name__c.field-meta.xml
<CustomField>
    <fullName>Document_Name__c</fullName>
    <defaultValue>IF($RecordType.DeveloperName = &quot;HRM_Configuration&quot;, &quot;HRM Configuration&quot;, &quot;&quot;)</defaultValue>
    <description>Name of the Document</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Name of the Document</inlineHelpText>
    <label>Document Name</label>
    <length>120</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AH_PLCM_MM_Inventory_Test.cls
/***********************************************************************************************
Name            : AH_PLCM_MM_Inventory_Test
Author          : Tushar Gupta
Created Date    : 17-Aug-2020
Last Mod Date   : 17-Aug-2020
Last Mod By     : Tushar Gupta
NICC Reference  : 
Description     : Apex class for Inventory Page Test
************************************************************************************************/
@isTest
public class AH_PLCM_MM_Inventory_Test {
    static String ProjectId = ''; // set the project id

    static testMethod void AH_PLCM_MM_Inventory_Test_Method() {         
        //insert new record into NI Documentatin object for testing
        NI_Documentation__c niDoc = NI_TestClassData.createTestNI_DocumentationForMM('Hotel Wonderful MM Conversion', date.today().format(), date.today().format(), 'Function Room Information Provided', false, false, false, 'Project Plan', true, date.today().format());
        insert niDoc;
        ProjectId = niDoc.Id;

        // insert new record into Inventory Object
        AH_PLCM_MM_Inventory__c inventoryObj = NI_TestClassData.createTest_Inventory(true, 'Chair1', 12, 15, 6, ProjectId);
        insert inventoryObj;

        //Initialize the page AH_PLCM_MM_Inventory
        PageReference pRef = Page.AH_PLCM_MM_Inventory;
        
        String pageUrl = '';

        //Add parameters to page URL
        pRef.getParameters().put('ProjectId', ProjectId);
        Test.setCurrentPage(pRef); //set the current page

        Test.startTest();
        //Intialize the Room capacities controller
        AH_PLCM_MM_Inventory inventory= new AH_PLCM_MM_Inventory();
        
        // check the save action
        inventory.inventoryObj = new AH_PLCM_MM_Inventory__c();
        inventory.SaveData();

        // check the update action
        inventory.inventoryObj.MM_Chair_1_Height__c = 11;
        inventory.SaveData();
        System.assertEquals(11, inventory.inventoryObj.MM_Chair_1_Height__c);

        // check the navigation url
        string invetoryPage = inventory.ConfirmAndNext().getUrl();

        System.assertEquals('/apex/AH_PLCM_MM_Thank_You?ProjectId='+ ProjectId, invetoryPage);

        string RoomCapacitiesPage = inventory.BackToRoomCapacitiesPage().getUrl();
        System.assertEquals('/apex/AH_PLCM_MM_Room_Capacities?ProjectId='+ ProjectId, RoomCapacitiesPage);

        // check the exceptions
        inventory.inventoryObj = null;
        inventory.SaveData();

        //Start - Test common class methods
        try {
            integer a = 0, b = 1, c = b/a;
        }
        catch(Exception ex){
            pageUrl = inventory.RedirectToErrorPage('AH_PLCM_MM_Inventory_Test_Method    ', ex).getUrl();
            System.assertEquals('/apex/AH_PLCM_MM_Error_Page', pageUrl);
        }
        // test the terms and condtions status
        inventory.CheckTermsAndConditionStatus();
    
        // initialize the invetory values
        inventory.SetDefaultInventoryValue();
        
        // get querystring Value
        string queryString = inventory.getAllQueryString();
       
        // initialize  the test class method
        boolean IsTestClass = inventory.setIsTestClassAsTrue();
        inventory.CommunityUrl = 'community';

        // get property name which is assigned to ni doc
        string propertyName = inventory.GetMMPropertyName();
        System.assertEquals(niDoc.Document_Name__c, propertyName);

        // initalize the picklist values
        inventory.GetPickListValueFromObject('AH_PLCM_MM_Room_Details__c','MM_Source_Type__c');

        // call the default room capacities page
        inventory.GetDefaultRoomCapacityValues();
        //End - Test common class methods

        Test.stopTest();
    }
}