force-app/main/default/objects/AH_UDC_Form__c/AH_UDC_Form__c.object-meta.xml
<CustomObject>
    <description>This object contains details of Forms that are available as Workbook Steps.</description>
    <label>UDC Form</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UDC Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_UDC_Log__c/AH_UDC_Log__c.object-meta.xml
<CustomObject>
    <description>This log is for use by Amadeus Hospitality Solutions Delivery custom code.</description>
    <label>UDC Log</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UDC Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_UDC_Response__c/AH_UDC_Response__c.object-meta.xml
<CustomObject>
    <description>This object contains details of Responses to Workbook steps</description>
    <label>UDC Response</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UDC Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_UDC_Response__c/fields/WorkbookStep__c.field-meta.xml
<CustomField>
    <fullName>WorkbookStep__c</fullName>
    <description>This is the Sent Workbook Step to which the response is tied</description>
    <inlineHelpText>This is the Sent Workbook Step to which the response is tied</inlineHelpText>
    <label>Workbook Step</label>
    <referenceTo>AH_UDC_WorkbookStep__c</referenceTo>
    <relationshipLabel>Responses</relationshipLabel>
    <relationshipName>UDC_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AH_UDC_Workbook__c/AH_UDC_Workbook__c.object-meta.xml
<CustomObject>
    <description>This object contains details of workbooks and sent workbooks</description>
    <label>UDC Workbook</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Workbook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UDC Workbooks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_UDC_Workbook__c/fields/CompletedDate__c.field-meta.xml
<CustomField>
    <fullName>CompletedDate__c</fullName>
    <description>The date the sent Workbook was completed</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date the sent Workbook was completed</inlineHelpText>
    <label>Completed Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AH_UDC_Workbook__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This determines if the Workbook is available to be sent</description>
    <inlineHelpText>This determines if the Workbook is available to be sent</inlineHelpText>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AH_UDC_Workbook__c/fields/RelatedTo__c.field-meta.xml
<CustomField>
    <fullName>RelatedTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the NI Documentation record to which the sent Workbook was attached</description>
    <inlineHelpText>This is the NI Documentation record to which the sent Workbook was attached</inlineHelpText>
    <label>Related To</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only &apos;Unified Data Collection - Workbook&apos; record type is accepted.</errorMessage>
        <filterItems>
            <field>NI_Documentation__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Unified Data Collection - Workbook</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>NI_Documentation__c</referenceTo>
    <relationshipLabel>UDC Workbook Sent</relationshipLabel>
    <relationshipName>Workbooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AH_UDC_Workbook__c/fields/RelatedToDocName__c.field-meta.xml
<CustomField>
    <fullName>RelatedToDocName__c</fullName>
    <description>Document Name</description>
    <formula>HYPERLINK(&quot;/&quot; &amp; RelatedTo__c, RelatedTo__r.Document_Name__c,&quot;_self&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Document Name</inlineHelpText>
    <label>Related To Document Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AH_UDC_Workbook__c/fields/SecurityCode__c.field-meta.xml
<CustomField>
    <fullName>SecurityCode__c</fullName>
    <description>This is the security code specific and unique to this Workbook Sent. This will allow the form to retrieve data from Salesforce.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>This is the security code specific and unique to this Workbook Sent. This will allow the form to retrieve data from Salesforce.</inlineHelpText>
    <label>Security Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AH_UDC_Workbook__c/fields/SentDate__c.field-meta.xml
<CustomField>
    <fullName>SentDate__c</fullName>
    <description>The date the Workbook was sent</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date the Workbook was sent</inlineHelpText>
    <label>Sent Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AH_UDC_Workbook__c/fields/SentStatus__c.field-meta.xml
<CustomField>
    <fullName>SentStatus__c</fullName>
    <description>Displays the status of the Worksheet Sent</description>
    <inlineHelpText>Displays the status of the Worksheet Sent</inlineHelpText>
    <label>Sent Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed/Locked</fullName>
            </value>
            <value>
                <fullName>Failed To Send</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AH_UDC_WorkbookStep__c/AH_UDC_WorkbookStep__c.object-meta.xml
<CustomObject>
    <description>This object contains details of Workbook steps and sent Workbook steps.</description>
    <label>UDC Workbook Step</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Workbook Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UDC Workbook Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_UDC_WorkbookStep__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This determines if this step is enabled</description>
    <inlineHelpText>This determines if this step is enabled</inlineHelpText>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AH_UDC_WorkbookStep__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The form which this step uses</description>
    <inlineHelpText>The form which this step uses</inlineHelpText>
    <label>Form</label>
    <referenceTo>AH_UDC_Form__c</referenceTo>
    <relationshipLabel>UDC Workbook Steps</relationshipLabel>
    <relationshipName>Workbook_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AH_UDC_WorkbookStep__c/fields/SortOrder__c.field-meta.xml
<CustomField>
    <fullName>SortOrder__c</fullName>
    <description>The order of the steps</description>
    <inlineHelpText>The order of the steps</inlineHelpText>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AH_UDC_WorkbookStep__c/fields/StepCompleted__c.field-meta.xml
<CustomField>
    <fullName>StepCompleted__c</fullName>
    <description>This designates when the step has been completed by the community user</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This designates when the step has been completed by the community user</inlineHelpText>
    <label>Step Completed</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AH_UDC_WorkbookStep__c/fields/StepStatus__c.field-meta.xml
<CustomField>
    <fullName>StepStatus__c</fullName>
    <description>This shows the status of the step sent</description>
    <inlineHelpText>This shows the status of the step sent</inlineHelpText>
    <label>Step Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <color>#BBBBBB</color>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <color>#F3D904</color>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <color>#419249</color>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Locked</fullName>
                <color>#FF6666</color>
                <label>Locked</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AH_UDC_WorkbookStep__c/fields/Workbook__c.field-meta.xml
<CustomField>
    <fullName>Workbook__c</fullName>
    <description>This is the Workbook record to which the step is attached</description>
    <inlineHelpText>This is the Workbook record to which the step is attached</inlineHelpText>
    <label>Workbook</label>
    <referenceTo>AH_UDC_Workbook__c</referenceTo>
    <relationshipLabel>UDC Workbook Steps</relationshipLabel>
    <relationshipName>Workbook_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AH_UDC_WorkbookStepResponse__c/AH_UDC_WorkbookStepResponse__c.object-meta.xml
<CustomObject>
    <description>This is a junction object used to associate a Workbook Sent Step with Responses</description>
    <label>UDC Workbook Step Response</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Workbook Step Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UDC Workbook Step Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_UDC_WorkbookStepResponse__c/fields/IsMostRecentResponse__c.field-meta.xml
<CustomField>
    <fullName>IsMostRecentResponse__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is true if the response is the most recent; this helps with reports and formulas that are showing responses.</description>
    <inlineHelpText>This field is true if the response is the most recent; this helps with reports and formulas that are showing responses.</inlineHelpText>
    <label>Is Most Recent Response</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AH_UDC_WorkbookStepResponse__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <referenceTo>AH_UDC_Response__c</referenceTo>
    <relationshipName>Workbook_Step_Responses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AH_UDC_WorkbookStepResponse__c/fields/WorkbookStep__c.field-meta.xml
<CustomField>
    <fullName>WorkbookStep__c</fullName>
    <label>Workbook Step</label>
    <referenceTo>AH_UDC_WorkbookStep__c</referenceTo>
    <relationshipName>Workbook_Step_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NI_Documentation__c/NI_Documentation__c.object-meta.xml
<CustomObject>
    <label>NI Documentation</label>
    <nameField>
        <displayFormat>DOC-{00000}</displayFormat>
        <label>Doc #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NI Documentation</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/AH_UDC_WorkbookResponsesExt.cls
/**
 * Name          : AH_UDC_WorkbookResponsesExt
 * Created By    : Amadeus Hospitality Services (Rob.Stevens@Amadeus.com)
 * Created Date  : 2020-01-20
 * Description   : This is an extension class for the page AH_UDC_WorkbookResponses.
 * Dependencies  : 
 **/
public with sharing class AH_UDC_WorkbookResponsesExt {
   public Boolean IsErrorOccurred { get; set; }
   @TestVisible
   private ID selectedWorkbookId { get; set; }

   public Workbook displayWorkbook { get; set; }
   public string mode { get; set; }
   public string filename { get; set; }

   public static String getNewLine() {
      return '\n';
   }

   public static String getNewCell() {
      return ',';
   }

   @TestVisible private string LogFunctionalArea = 'AH_UDC_WorkbookResponsesExt'; //This is used for AH_UDC_Log Entries being written on this page
   //This is used to store AH_UDC_Log records that can't be written on the load of the controller
   public List<AH_UDC_log__c> PageLoadLogMessages { get; set; } { PageLoadLogMessages = new List<AH_UDC_Log__c> (); }
   //This is used client side to determine if AH_UDC_Log Messages need to be written from the Page Load
   public Boolean HasPageLoadLogMessages {
      get {
         AH_UDC_LogHelper.Debug('PageLoadLogMessages: ' + PageLoadLogMessages);
         return PageLoadLogMessages.size() > 0;
      }
   }

   public AH_UDC_WorkbookResponsesExt(ApexPages.StandardController controller) {
      try {
         AH_UDC_LogHelper.QueueLogs = true;
         mode = '';

         if (String.isBlank(ApexPages.currentPage().getParameters().get('wbid'))) {
            IsErrorOccurred = true;
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.FATAL, 'No Workbook was specified.'));
            return;
         }

         if (Test.isRunningTest() && (ApexPages.currentPage().getParameters().get('wbid') == 'TestException')) {
            Integer a = 1 / 0;
         }

         selectedWorkbookId = String.escapeSingleQuotes(ApexPages.currentPage().getParameters().get('wbid'));

         if (ApexPages.currentPage().getParameters().get('mode') == 'CSV') {
            mode = 'CSV';
            filename = 'Responses.csv';
         }
         getResponses(selectedWorkbookId);
      }
      catch(Exception exc) {
         IsErrorOccurred = true;
         ApexPages.addMessage(new ApexPages.message(ApexPages.severity.FATAL, Label.AH_UDC_Common_Error_Message_Backend));
         AH_UDC_LogHelper.Log(AH_UDC_LogHelper.LogLevel_EXC,
                              'AH_UDC_WorkbookResponsesExt', 'Constructor',
                              'An exception occurred in the constructor',
                              exc, null, null);
         return;
      }
      finally {
         //Write any Queued Log Messages to controller property
         PageLoadLogMessages = AH_UDC_LogHelper.GetQueuedLogs();
         AH_UDC_LogHelper.clearQueuedLogs();
         AH_UDC_LogHelper.QueueLogs = false;
      }
   }

   @TestVisible
   // Returns back whether the responses were successfully retrieved or not
   private Boolean getResponses(String workbookId) {
      try {
         List<AH_UDC_Workbook__c> wbRecords = [select id, name, SentDate__c, SentStatus__c, RelatedToDocName__c, CompletedDate__c,
                                               RelatedTo__r.name
                                               from AH_UDC_Workbook__c
                                               where Id = :workbookId];

         if (wbRecords == null || wbRecords.size() != 1) {
            IsErrorOccurred = true;
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.FATAL, 'The requested Workbook ID could not be found.'));
            return false;
         }

         displayWorkbook = new Workbook();
         displayWorkbook.Record = wbRecords[0];

         List<AH_UDC_WorkbookStep__c> stepRecords = [SELECT id, name, StepStatus__c, StepCompleted__c,
                                                     Workbook__r.SecurityCode__c,
                                                     Form__r.id, Form__r.RecordTypeId
                                                     FROM AH_UDC_WorkbookStep__c
                                                     WHERE Workbook__c = :workbookId
                                                     AND Enabled__c = true
                                                     ORDER BY SortOrder__c asc];
         if (stepRecords == null || stepRecords.size() == 0) {
            IsErrorOccurred = true;
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.FATAL, 'The requested Workbook does not have any steps.'));
            return false;
         }

         displayWorkbook.WorkbookSteps = new List<WorkbookStep> ();
         string StepToken = AH_UDC_Shared.CreateStepToken(stepRecords[0].Workbook__r.SecurityCode__c, stepRecords[0].Form__r.id, stepRecords[0].id );
         string ExportUrl = AH_UDC_ConfigHelper.GetString('AH_UDC_ExportUrl', '');
         displayWorkbook.ExportCsvUrl = ExportUrl.replace('{TOKEN}', StepToken).replace('{MODE}', 'CSV').replace('{STEP}', '*');
         displayWorkbook.ExportJsonUrl = ExportUrl.replace('{TOKEN}', StepToken).replace('{MODE}', 'JSON').replace('{STEP}', '*');

         List<Id> WorkbookStepIds = new List<Id> ();
         for (AH_UDC_WorkbookStep__c stepRecord : stepRecords)
         {
            WorkbookStepIds.add(stepRecord.id);
         }
         List<AH_UDC_WorkbookStepResponse__c> ResponseRecords = [SELECT WorkbookStep__c, Response__r.CreatedDate
                                                                 FROM AH_UDC_WorkbookStepResponse__c
                                                                 WHERE IsMostRecentResponse__c = true
                                                                 AND WorkbookStep__c in :WorkbookStepIds];

         Id FileUploadFormRecordTypeId = Schema.SObjectType.AH_UDC_Form__c.getRecordTypeInfosByDeveloperName().get(AH_UDC_Constants.RECORD_TYPE_FORM_AMADEUS_FILE_UPLOAD).getRecordTypeId();
         if (String.isBlank(FileUploadFormRecordTypeId)) {
            IsErrorOccurred = true;
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.FATAL, 'File upload form record type id not found with developer name ' + AH_UDC_Constants.RECORD_TYPE_FORM_AMADEUS_FILE_UPLOAD));
            return false;
         }

         displayWorkbook.WorkbookHasResponses = ResponseRecords.size() >0;

         for (AH_UDC_WorkbookStep__c stepRecord : stepRecords) {
            WorkbookStep wbs = new WorkbookStep();
            wbs.Record = stepRecord;
            wbs.ExportCsvUrl = ExportUrl.replace('{TOKEN}', StepToken).replace('{MODE}', 'CSV').replace('{STEP}', stepRecord.id);
            wbs.ExportJsonUrl = ExportUrl.replace('{TOKEN}', StepToken).replace('{MODE}', 'JSON').replace('{STEP}', stepRecord.id);
            wbs.IsFileUploadStep = stepRecord.Form__r.RecordTypeId == FileUploadFormRecordTypeId;
            wbs.IsUrl = stepRecord.Form__c ==null;

            for (AH_UDC_WorkbookStepResponse__c ResponseRecord : ResponseRecords) {
               if (ResponseRecord.WorkbookStep__c == stepRecord.Id) {
                  wbs.ResponseRecord = ResponseRecord;
                  break;
               }
            }
            displayWorkbook.WorkbookSteps.add(wbs);
         }

         return true;
      }
      catch(Exception exc) {
         IsErrorOccurred = true;
         AH_UDC_LogHelper.Log(AH_UDC_LogHelper.LogLevel_ERROR, 'AH_UDC_WorkbookResponsesExt.getResponses', 'Unhandled Exception',
                              exc.getMessage(), exc, workbookId, 'AH_UDC_Workbook__c');
         ApexPages.addMessage(new ApexPages.message(ApexPages.severity.FATAL, Label.AH_UDC_Common_Error_Message_Backend));
         return false;
      }
   }

   //This method is used by a client side actionfunction to log AH_UDC_Log entries that couldn't be created by the page load due to SOQL DML retrictions
   public void ServerLogMessages() {
      AH_UDC_LogHelper.Debug(LogFunctionalArea + '.ServerLogMessages');
      try {
         if (PageLoadLogMessages != null && PageLoadLogMessages.size() > 0) {
            insert(PageLoadLogMessages);
         }
         PageLoadLogMessages = new List<AH_UDC_Log__c> ();
         if (Test.isRunningTest() && LogFunctionalArea == 'TestException') Integer a = 1 / 0;
      }
      catch(Exception exc) {
         AH_UDC_LogHelper.Debug(LogFunctionalArea + '.ServerLogMessages - Exception: ' + exc);
         AH_UDC_LogHelper.Log(AH_UDC_LogHelper.LogLevel_EXC,
                              LogFunctionalArea,
                              'ServerLogMessages',
                              'An exception occurred logging Page Load AH_UDC_Log entries',
                              exc, null, null);
      }
   }

   class Workbook {
      public AH_UDC_Workbook__c Record { get; set; }
      public List<WorkbookStep> WorkbookSteps { get; set; }
      public string ExportCsvUrl { get; set; }
      public string ExportJsonUrl { get; set; }
      public boolean WorkbookHasResponses { get; set; }
   }

   class WorkbookStep {
      public AH_UDC_WorkbookStep__c Record { get; set; }
      public AH_UDC_WorkbookStepResponse__c ResponseRecord { get; set; }
      public boolean IsFileUploadStep { get; set; }
      public boolean IsUrl { get; set; }
      public string ExportCsvUrl { get; set; }
      public string ExportJsonUrl { get; set; }
   }
}