force-app/main/default/objects/AH_UDC_Form__c/AH_UDC_Form__c.object-meta.xml
<CustomObject>
    <description>This object contains details of Forms that are available as Workbook Steps.</description>
    <label>UDC Form</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UDC Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_UDC_Workbook__c/AH_UDC_Workbook__c.object-meta.xml
<CustomObject>
    <description>This object contains details of workbooks and sent workbooks</description>
    <label>UDC Workbook</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Workbook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UDC Workbooks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_UDC_Workbook__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This determines if the Workbook is available to be sent</description>
    <inlineHelpText>This determines if the Workbook is available to be sent</inlineHelpText>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AH_UDC_Workbook__c/fields/RelatedTo__c.field-meta.xml
<CustomField>
    <fullName>RelatedTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the NI Documentation record to which the sent Workbook was attached</description>
    <inlineHelpText>This is the NI Documentation record to which the sent Workbook was attached</inlineHelpText>
    <label>Related To</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only &apos;Unified Data Collection - Workbook&apos; record type is accepted.</errorMessage>
        <filterItems>
            <field>NI_Documentation__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Unified Data Collection - Workbook</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>NI_Documentation__c</referenceTo>
    <relationshipLabel>UDC Workbook Sent</relationshipLabel>
    <relationshipName>Workbooks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AH_UDC_Workbook__c/fields/RelatedToDocName__c.field-meta.xml
<CustomField>
    <fullName>RelatedToDocName__c</fullName>
    <description>Document Name</description>
    <formula>HYPERLINK(&quot;/&quot; &amp; RelatedTo__c, RelatedTo__r.Document_Name__c,&quot;_self&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Document Name</inlineHelpText>
    <label>Related To Document Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AH_UDC_Workbook__c/fields/SecurityCode__c.field-meta.xml
<CustomField>
    <fullName>SecurityCode__c</fullName>
    <description>This is the security code specific and unique to this Workbook Sent. This will allow the form to retrieve data from Salesforce.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>This is the security code specific and unique to this Workbook Sent. This will allow the form to retrieve data from Salesforce.</inlineHelpText>
    <label>Security Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AH_UDC_Workbook__c/fields/SentDate__c.field-meta.xml
<CustomField>
    <fullName>SentDate__c</fullName>
    <description>The date the Workbook was sent</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The date the Workbook was sent</inlineHelpText>
    <label>Sent Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AH_UDC_Workbook__c/fields/SentStatus__c.field-meta.xml
<CustomField>
    <fullName>SentStatus__c</fullName>
    <description>Displays the status of the Worksheet Sent</description>
    <inlineHelpText>Displays the status of the Worksheet Sent</inlineHelpText>
    <label>Sent Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed/Locked</fullName>
            </value>
            <value>
                <fullName>Failed To Send</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AH_UDC_WorkbookStep__c/AH_UDC_WorkbookStep__c.object-meta.xml
<CustomObject>
    <description>This object contains details of Workbook steps and sent Workbook steps.</description>
    <label>UDC Workbook Step</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Workbook Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UDC Workbook Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_UDC_WorkbookStep__c/fields/Enabled__c.field-meta.xml
<CustomField>
    <fullName>Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This determines if this step is enabled</description>
    <inlineHelpText>This determines if this step is enabled</inlineHelpText>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AH_UDC_WorkbookStep__c/fields/Form__c.field-meta.xml
<CustomField>
    <fullName>Form__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The form which this step uses</description>
    <inlineHelpText>The form which this step uses</inlineHelpText>
    <label>Form</label>
    <referenceTo>AH_UDC_Form__c</referenceTo>
    <relationshipLabel>UDC Workbook Steps</relationshipLabel>
    <relationshipName>Workbook_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AH_UDC_WorkbookStep__c/fields/SortOrder__c.field-meta.xml
<CustomField>
    <fullName>SortOrder__c</fullName>
    <description>The order of the steps</description>
    <inlineHelpText>The order of the steps</inlineHelpText>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AH_UDC_WorkbookStep__c/fields/StepCompleted__c.field-meta.xml
<CustomField>
    <fullName>StepCompleted__c</fullName>
    <description>This designates when the step has been completed by the community user</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This designates when the step has been completed by the community user</inlineHelpText>
    <label>Step Completed</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AH_UDC_WorkbookStep__c/fields/StepStatus__c.field-meta.xml
<CustomField>
    <fullName>StepStatus__c</fullName>
    <description>This shows the status of the step sent</description>
    <inlineHelpText>This shows the status of the step sent</inlineHelpText>
    <label>Step Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <color>#BBBBBB</color>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <color>#F3D904</color>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <color>#419249</color>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Locked</fullName>
                <color>#FF6666</color>
                <label>Locked</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AH_UDC_WorkbookStep__c/fields/Workbook__c.field-meta.xml
<CustomField>
    <fullName>Workbook__c</fullName>
    <description>This is the Workbook record to which the step is attached</description>
    <inlineHelpText>This is the Workbook record to which the step is attached</inlineHelpText>
    <label>Workbook</label>
    <referenceTo>AH_UDC_Workbook__c</referenceTo>
    <relationshipLabel>UDC Workbook Steps</relationshipLabel>
    <relationshipName>Workbook_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NI_Documentation__c/NI_Documentation__c.object-meta.xml
<CustomObject>
    <label>NI Documentation</label>
    <nameField>
        <displayFormat>DOC-{00000}</displayFormat>
        <label>Doc #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NI Documentation</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/AH_UDC_REST_WorkbookSentInfo.cls
/**
 * Name          : AH_UDC_REST_WorkbookSentInfo
 * Created By    : Amadeus Hospitality Services (Rob.Stevens@Amadeus.com)
 * Created Date  : 2021-01-12
 * Description   : This class accepts a WorkBookSent Id and returns data about the workbook.  This is used by integrating applications.
 * Dependencies  : 
 **/

@RestResource(urlMapping = '/AH_UDC_WorkbookSentInfo')
global with sharing class AH_UDC_REST_WorkbookSentInfo {
   public static final Integer QAJsonMaxPerRequest = 20;

   @HttpGet
   global static void get() {
      AH_UDC_LogHelper.QueueLogs = true;

      AH_UDC_LogHelper.Debug('AH_UDC_REST_WorkbookSentInfo');
      WorkbookSentInfoResponse resp = new WorkbookSentInfoResponse();
      RestRequest req = RestContext.request;
      try {
         String workbookSentId = RestContext.request.params.get('workbookSentId');
         if (Test.isRunningTest() && workbookSentId=='exception1') integer e = 1/0;

         if (String.isBlank(workbookSentId)) {
            resp.statusCode = '400';
            resp.message = 'Bad Request';
            RestContext.response.responseBody = Blob.valueOf(resp.compileResponse());
            return;
         }

         //Check that Workbook Sent ID is valid and that the user has access to it
         List<AH_UDC_WorkbookStep__c> workbooksteps = [SELECT id, name, StepStatus__c, StepCompleted__c,
                                                       Workbook__r.SecurityCode__c, Workbook__r.RelatedToDocName__c, Workbook__r.SentDate__c, Workbook__r.SentStatus__c,
                                                       Workbook__r.RelatedTo__r.Name, Workbook__r.RelatedTo__r.Document_Name__c,
                                                       Form__r.id
                                                       FROM AH_UDC_WorkbookStep__c
                                                       WHERE Workbook__c = :workbookSentId
                                                       AND Enabled__c = true
                                                       ORDER BY SortOrder__c asc];

         if (workbooksteps == null || workbooksteps.size() == 0) {
            resp.statusCode = '404';
            resp.message = 'Not Found';
            RestContext.response.responseBody = Blob.valueOf(resp.compileResponse());
            return;
         }

         resp.workbookSentId = workbookSentId;
         resp.documentName = workbooksteps[0].Workbook__r.RelatedTo__r.Document_Name__c;
         resp.documentId = workbooksteps[0].Workbook__r.RelatedTo__r.Name;
         resp.sentDate = workbooksteps[0].Workbook__r.SentDate__c;
         resp.sentStatus = workbooksteps[0].Workbook__r.SentStatus__c;

         string StepToken = AH_UDC_Shared.CreateStepToken(workbooksteps[0].Workbook__r.SecurityCode__c, workbooksteps[0].Form__r.id);
         string ExportUrl = AH_UDC_ConfigHelper.GetString('AH_UDC_ExportUrl', '');
         resp.ExportCsvUrl = ExportUrl.replace('{TOKEN}', StepToken).replace('{MODE}', 'CSV').replace('{STEP}', '*');
         resp.ExportJsonUrl = ExportUrl.replace('{TOKEN}', StepToken).replace('{MODE}', 'JSON').replace('{STEP}', '*');

         for (AH_UDC_WorkbookStep__c WorkbookStep : WorkbookSteps) {
            WorkbookStep wbs = new WorkbookStep();
            wbs.id = WorkbookStep.Id;
            wbs.name = WorkbookStep.name;
            wbs.stepStatus = WorkbookStep.StepStatus__c;
            wbs.ExportCsvUrl = ExportUrl.replace('{TOKEN}', StepToken).replace('{MODE}', 'CSV').replace('{STEP}', WorkbookStep.id);
            wbs.ExportJsonUrl = ExportUrl.replace('{TOKEN}', StepToken).replace('{MODE}', 'JSON').replace('{STEP}', WorkbookStep.id);
            resp.WorkbookSteps.add(wbs);
         }

         resp.statusCode = '200';
         resp.message = 'Ok';
         RestContext.response.responseBody = Blob.valueOf(resp.compileResponse());
      }
      catch(Exception e) {
         AH_UDC_LogHelper.Log(AH_UDC_LogHelper.LogLevel_EXC,
                              'AH_UDC_REST_WorkbookSentInfo', 'get',
                              'An exception occurred processing a response: ' + e.getMessage(),
                              e, null, null);

         //Set the Return code
         resp.statusCode = '500';
         resp.message = 'Exception Occurred';
         RestContext.response.responseBody = Blob.valueOf(resp.compileResponse());
      }
      finally {
         try {
            AH_UDC_LogHelper.writeQueuedLogs();
         }
         catch(Exception exc) {
            //If logs can't be written at least show an error in debug
            AH_UDC_LogHelper.Debug('AH_UDC_REST_WorkbookSentInfo.Get - Failed to write QueuedLogs');
         }
      }
   }

   @TestVisible
   private class WorkbookSentInfoResponse {
      public String statusCode { get; set; }
      public String message { get; set; }
      public String workbookSentId { get; set; }
      public string documentName { get; set; }
      public string documentId { get; set; }
      public DateTime sentDate { get; set; }
      public string sentStatus { get; set; }

      public string exportCsvUrl { get; set; }
      public string exportJsonUrl { get; set; }

      public List<WorkbookStep> WorkbookSteps { get; set; }

      public WorkbookSentInfoResponse() {
         this.WorkbookSteps = new List<WorkbookStep> ();
      }

      //Convert response to the JSON format
      public String compileResponse() {
         return JSON.serialize(this, true);
      }
   }

   class WorkbookStep {
      public string id { get; set; }
      public string name { get; set; }
      public string stepStatus { get; set; }

      public string exportCsvUrl { get; set; }
      public string exportJsonUrl { get; set; }
   }


}