force-app/main/default/objects/INTGR_Account__c/INTGR_Account__c.object-meta.xml
<CustomObject>
    <description>!!! INTEGRATION OBJECT- DO NOT ALTER !!!
NICC-032393</description>
    <label>Integration Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Integration Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/INTGR_Account__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NICC-030216 - Provides the means to Enable/Disable a customer&apos;s integration</description>
    <inlineHelpText>When this checkbox is checked the integration is live for this specific customer. Uncheck to disable the integration.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/INTGR_Account__c/fields/RequestFormat__c.field-meta.xml
<CustomField>
    <fullName>RequestFormat__c</fullName>
    <description>NICC-030216 - The method/language used to generate the out bound call to customer ITSM.</description>
    <inlineHelpText>The method/language used to generate the out bound call to customer ITSM.</inlineHelpText>
    <label>Request Format</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>XML</fullName>
            </value>
            <value>
                <fullName>JSON</fullName>
            </value>
            <value>
                <fullName>SOAP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/INTGR_Case__c/INTGR_Case__c.object-meta.xml
<CustomObject>
    <description>!!! INTEGRATION OBJECT- DO NOT ALTER !!!
NICC-032393</description>
    <label>Integration Case</label>
    <nameField>
        <displayFormat>INTGR-{0000000}</displayFormat>
        <label>Integration Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/INTGR_Case__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>NICC-030216 - Lookup to case created by integration. This field is set by a Process Builder after Standard case is created via the Integration.</description>
    <inlineHelpText>Lookup to case created by integration. This field is set by a Process Builder after Standard case is created via the Integration.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Integration Cases</relationshipLabel>
    <relationshipName>Integration_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/INTGR_Case__c/fields/Customer_Ticket_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Ticket_Number__c</fullName>
    <description>NICC-030216 - User-friendly case/incident number of record in customer ITSM.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>User-friendly case/incident number of record in customer ITSM.</inlineHelpText>
    <label>Customer Ticket Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/INTGR_Case__c/fields/Customer_Ticket_System_Id__c.field-meta.xml
<CustomField>
    <fullName>Customer_Ticket_System_Id__c</fullName>
    <description>NICC-030216 - Primary key (system id) of case/incident record in customer ITSM.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Primary key (system id) of case/incident record in customer ITSM.</inlineHelpText>
    <label>Customer Ticket System Id</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/INTGR_Case__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>NICC-030216 - Explanation that describes the issue in more detail.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Explanation that describes the issue in more detail.</inlineHelpText>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/INTGR_Case__c/fields/INTGR_Account__c.field-meta.xml
<CustomField>
    <fullName>INTGR_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>NICC-030216 - Lookup populated by integration code for ease in referencing field values and to create a relationship for a related list on the INTGR_Account__c Object</description>
    <inlineHelpText>Lookup to integration account record details</inlineHelpText>
    <label>Integration Account</label>
    <referenceTo>INTGR_Account__c</referenceTo>
    <relationshipLabel>Integration Cases</relationshipLabel>
    <relationshipName>Integration_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/INTGR_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>NICC-030216 - Value set by integration user and integration code for two-way (inbound/outbound) updating of Case status. Special rules apply (see documentation)</description>
    <inlineHelpText>Value set by integration user and integration code for two-way (inbound/outbound) updating of Case status. Special rules apply (see documentation)</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Acknowledged</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recovered</fullName>
            </value>
            <value>
                <fullName>Verified as Recovered</fullName>
            </value>
            <value>
                <fullName>Pending Master Recovery</fullName>
            </value>
            <value>
                <fullName>Pending Problem Resolution</fullName>
            </value>
            <value>
                <fullName>Pending Vendor</fullName>
            </value>
            <value>
                <fullName>Closed as recovered</fullName>
            </value>
            <value>
                <fullName>Closed as rejected</fullName>
            </value>
            <value>
                <fullName>Closed as withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/INTGR_Case_Comment__c/INTGR_Case_Comment__c.object-meta.xml
<CustomObject>
    <description>!!! INTEGRATION OBJECT- DO NOT ALTER !!!
NICC-032393</description>
    <label>Integration Case Comment</label>
    <nameField>
        <displayFormat>INTGRC-{0000000}</displayFormat>
        <label>Integration Case Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Case Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/INTGR_Case_Comment__c/fields/Customer_Ticket_System_Id__c.field-meta.xml
<CustomField>
    <fullName>Customer_Ticket_System_Id__c</fullName>
    <description>NICC-030216 - Formula reference to primary key (system id) set on the related integration case/incident record in customer ITSM.</description>
    <formula>INTGR_Case__r.Customer_Ticket_System_Id__c</formula>
    <inlineHelpText>Formula reference to primary key (system id) set on the related integration case/incident record in customer ITSM.</inlineHelpText>
    <label>Customer Ticket System Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/INTGR_Case_Comment__c/fields/INTGR_Case__c.field-meta.xml
<CustomField>
    <fullName>INTGR_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>NICC-030216 - Lookup to parent integration case</description>
    <inlineHelpText>Lookup to parent integration case</inlineHelpText>
    <label>Case</label>
    <referenceTo>INTGR_Case__c</referenceTo>
    <relationshipLabel>Integration Case Comments</relationshipLabel>
    <relationshipName>Integration_Case_Comments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/INTGR_Field_Mapping__c/INTGR_Field_Mapping__c.object-meta.xml
<CustomObject>
    <description>!!! INTEGRATION OBJECT- DO NOT ALTER !!!
NICC-032393</description>
    <label>Integration Field Mapping</label>
    <nameField>
        <displayFormat>IFM-{00000}</displayFormat>
        <label>Integration Field Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Field Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/INTGR_Field_Mapping__c/fields/Integration_Account__c.field-meta.xml
<CustomField>
    <fullName>Integration_Account__c</fullName>
    <description>NICC-030216 - Lookup to parent integration account the mapping is for.</description>
    <inlineHelpText>Lookup to parent integration account the mapping is for.</inlineHelpText>
    <label>Integration Account</label>
    <referenceTo>INTGR_Account__c</referenceTo>
    <relationshipLabel>Integration Field Mappings</relationshipLabel>
    <relationshipName>Integration_Field_Mappings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NI_Integration_Log__c/NI_Integration_Log__c.object-meta.xml
<CustomObject>
    <label>NI Integration Log</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>NI Integration Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NI Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_Integration_Log__c/fields/Attachment_Id__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Id__c</fullName>
    <description>NICC-023347
The 18 character Salesforce Id of the attachment record related to this integration message. This field is updated when attachments are sent as part of the integration.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The 18 character Salesforce Id of the attachment record related to this integration message. This field is updated when attachments are sent as part of the integration.</inlineHelpText>
    <label>Attachment Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_Integration_Log__c/fields/Attachment_Name__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Name__c</fullName>
    <description>NICC-023347
The name of the attachment record related to this integration message. This field is updated when attachments are sent as part of the integration.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The name of the attachment record related to this integration message. This field is updated when attachments are sent as part of the integration.</inlineHelpText>
    <label>Attachment Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_Integration_Log__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to Case object from NI Integration Logs</description>
    <inlineHelpText>Lookup to Case object from NI Integration Logs</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>NI Integration Logs</relationshipLabel>
    <relationshipName>NI_Integration_Logs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Integration_Log__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Captures the details of the response from the web services call.

NICC-030216 - Relabeled from XML Response to Response
NICC-032393</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Detailed response from the web services call.</inlineHelpText>
    <label>Response</label>
    <length>60000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NI_Integration_Log__c/fields/Integration_Account__c.field-meta.xml
<CustomField>
    <fullName>Integration_Account__c</fullName>
    <description>NICC-032393</description>
    <formula>Case__r.Integration_Account__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Integration Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WinaproachIncidentSettings__c/WinaproachIncidentSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This settings used to manage end points and credentials for Win@proach integration. Create record name as &quot;Default&quot; and enter the required values for it.</description>
    <label>Win@proach Incident Settings</label>
</CustomObject>

force-app/main/default/objects/WinaproachIncidentSettings__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <description>Username to access Win@proach services through API</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Username to access Win@proach services through API</inlineHelpText>
    <label>Username</label>
    <length>35</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/INTGR_IntegrationHelper_Test.cls
/************************************************************************************************
				!!! INTEGRATION CLASS - DO NOT ALTER !!!                          
*************************************************************************************************
Name            : INTGR_IntegrationHelper_Test Class
Author          : Princy Jain
Created Date    : 04/20/2018
Last Mod Date   : 01/14/2019
Last Mod By     : Sean Harris
NICC Reference  : 
Description     : Test Class for INTGR_IntegrationHelper_Test Class
                : 
                : 
******************************************************************************************/
@isTest
public class INTGR_IntegrationHelper_Test
{
    
    public static Map<Id, NI_Integration_Log__c> mapNiIntegrationLog = new Map<Id, NI_Integration_Log__c>();
    public static Map<Id, Id> mapIntCaseCreate = new Map<Id, Id>();
    public static Map<Id, Id> mapIntCaseUpdate = new Map<Id, Id>();
    public static Map<Id, Id> mapIntCaseCommCreate = new Map<Id, Id>();
    public static Map<Id, Id> mapIntFilesCreate = new Map<Id, Id>();
    
    // ======================================================================================================================================= 
    // = CREATE TEST DATA
    // =======================================================================================================================================      
    @testSetup static void setup() 
    {
        
        ServiceNowIncidentSettings__c setting = NI_TestClassData.createServiceNowIncidentSettings();
        insert setting;
        
        WinaproachIncidentSettings__c winSettings = NI_TestClassData.createWinaproachIncidentSettings();
        winSettings.Username__c = UserInfo.getUserName();
        insert winSettings;
        
        Winaproach_Incident_Case_Record_Type__c winCaseRC = NI_TestClassData.createIncidentCaseRecordType();
        insert winCaseRC;
        
        WinaproachIncidentStatusMapping__c winIncSetting = NI_TestClassData.createIncidentStatusMapping();
        insert winIncSetting;
        
        User cUser = NI_TestClassData.createTestUser(111, 'System Administrator');
        cUser.Email = 'testuserZzzzzz' + 111 + '@salesforce.com';
        cUser.Alias = '111user';
        insert cUser; 
        
        Account a1 = NI_TestClassData.createTestAccount(1);
        insert a1;
        
        INTGR_Account__c acc = NI_TestClassData.createTestINTGR_Account(1, a1.Id, cUser.Id);
        acc.Active__c = true;
        insert acc;
        
        List<INTGR_Field_Mapping__c> fMapping = NI_TestClassData.createTestINTGR_AccountMapping(1, acc.Id);
        insert fMapping;
        
        Map<String, String> srcTargetFieldMap1 = new Map<String, String>();
        srcTargetFieldMap1.put('Description__c', 'Description');
        
        Case cs = NI_TestClassData.createTestCaseIntegration(1, a1.Id);
        cs.Integration_Account__c = acc.Id;
        insert cs;
        
        CaseComment comm = NI_TestClassData.createTestCaseComment (1, cs.Id);
        insert comm;
        
        INTGR_Case__c caseObj = NI_TestClassData.createTestINTGR_Case(1, acc.Id, cs.Id);
        insert caseObj ;
        
        caseObj.Customer_Ticket_System_Id__c = '11223344355';
        caseObj.Customer_Ticket_Number__c = 'INC001';
        update caseObj;
        
        INTGR_Case_Comment__c caseComm = NI_TestClassData.createTestINTGR_CaseComm(caseObj.Id);
        insert caseComm;
        
        ContentVersion cv1 = NI_TestClassData.createContentVersion();
        cv1.CaseId__c = cs.Id;
        insert cv1;
        
        List<NI_Integration_Log__c> logList = new List<NI_Integration_Log__c>();
        NI_Integration_Log__c log1 = INTGR_IntegrationHelper.createNIIntegraionLog(cs.Id, caseObj.Id, null, 'error Occured','Failed','insert', 'INTGR_Case__c', 'test.salesforce.com', 'ServiceNow', 'testbody');
        logList.add(log1);
        NI_Integration_Log__c log2 = INTGR_IntegrationHelper.createNIIntegraionLog(cs.Id, caseObj.Id, null, 'error Occured','Failed','update', 'INTGR_Case__c', 'test.salesforce.com', 'ServiceNow', 'testbody');
        logList.add(log2);
        NI_Integration_Log__c log3 = INTGR_IntegrationHelper.createNIIntegraionLog(cs.Id, caseObj.Id, caseComm.Id, 'error Occured','Failed','insert', 'INTGR_Case_Comment__c', 'test.salesforce.com', 'ServiceNow', 'testbody');
        logList.add(log3);
        NI_Integration_Log__c log4 = INTGR_IntegrationHelper.createNIIntegraionLog(cs.Id, caseObj.Id, null, 'error Occured','Failed','insert', 'ContentVersion', 'test.salesforce.com', 'ServiceNow', 'testbody');
        log4.Attachment_Id__c = cv1.Id;
        log4.Attachment_Name__c = cv1.Title;
        logList.add(log4);
        
        insert loglist;
        
    }
    
    // ======================================================================================================================================= 
    // = TEST METHOD 1:
    // =======================================================================================================================================     
    static testMethod void caseInsertCallout()
    {
        
        Test.setMock(HttpCalloutMock.class, new INTGR_REST_MockResponseGenerator());
        
        Test.startTest();
        
        Account a1 = [SELECT Id FROM Account LIMIT 1][0];
        
        Case cs1 = NI_TestClassData.createTestCaseIntegration(1, a1.Id);
        insert cs1;
        
        Map<Id, Case> idVsCaseObjMap = INTGR_Case_SOQLDataProvider.getSCdetailsToInsertIC(cs1.Id);
        INTGR_IntegrationHelper.upsertIntegrationCase(idVsCaseObjMap, true, false, null);
        
        Test.stopTest();
        
    }
    
    // ======================================================================================================================================= 
    // = TEST METHOD 2:
    // =======================================================================================================================================     
    static testmethod void caseUpdateCallout() 
    {
        
        Test.startTest();
        
        Case caseObj = [SELECT Id, Description FROM Case LIMIT 1][0];
        caseObj.Description = 'update Description';
        update caseObj ;
        
        INTGR_Account__c acc = [SELECT Id, RequestFormat__c FROM INTGR_Account__c LIMIT 1][0];
        acc.RequestFormat__c = 'SOAP';
        update acc;
        
        Case caseObj1 = [SELECT Id, Description FROM Case LIMIT 1][0];
        caseObj1.Description  = 'update Description SOAP';
        update caseObj1 ;        
        
        Test.setMock(HttpCalloutMock.class, new INTGR_REST_MockResponseGenerator());
        
        Test.stopTest();
        
    }
    
    // ======================================================================================================================================= 
    // = TEST METHOD 3:
    // =======================================================================================================================================     
    static testmethod void caseCommentUpdateCallout() 
    {
        
        Test.startTest(); 
        
        CaseComment comm = [SELECT Id, CommentBody FROM CaseComment LIMIT 1][0];
        comm.CommentBody = 'Updating case comment.';
        update comm;
        
        INTGR_Account__c acc = [SELECT Id, RequestFormat__c FROM INTGR_Account__c LIMIT 1][0];
        acc.RequestFormat__c = 'SOAP';
        update acc;
        
        Test.setMock(HttpCalloutMock.class, new INTGR_REST_MockResponseGenerator());
        
        Test.stopTest();
        
    }
    
    // ======================================================================================================================================= 
    // = TEST METHOD 4:
    // =======================================================================================================================================     
    static testmethod void retryCallout() 
    {
        
        Test.startTest();
        
        for (NI_Integration_Log__c nlog : [SELECT Id, Case__c, Status__c, Transaction_Type__c, Integration_Name__c,
                                           Integration_Case__c, createdDate, Integration_Case_Comment__c, UpdateFor__c, 
                                           Retries_Performed__c, Do_Retries__c, XMLRequest__c, Web_Service_Endpoint__c, Attachment_Id__c 
                                           FROM NI_Integration_Log__c 
                                           WHERE status__c = 'Failed' 
                                           AND Integration_Name__c = 'ServiceNow' 
                                           AND Do_Retries__c = true LIMIT 6])
        {
            
            mapNiIntegrationLog.put(nlog.id, nlog);
            
            if (nlog.Transaction_Type__c.equalsIgnoreCase('Insert') && nlog.UpdateFor__c.equalsIgnoreCase('INTGR_Case__c')) 
            {
                mapIntCaseCreate.put(nlog.Integration_Case__c, nlog.id);
            }
            
            if (nlog.Transaction_Type__c.equalsIgnoreCase('Update') && nlog.UpdateFor__c.equalsIgnoreCase('INTGR_Case__c'))
            {
                mapIntCaseUpdate.put(nlog.Integration_Case__c, nlog.id);
            }
            
            if (nlog.UpdateFor__c.equalsIgnoreCase('INTGR_Case_Comment__c'))
            {
                mapIntCaseCommCreate.put(nlog.Integration_Case_Comment__c, nlog.id);
            }
            
            if (nlog.UpdateFor__c.equalsIgnoreCase('ContentVersion'))
            {
                mapIntFilesCreate.put(nlog.Attachment_Id__c, nlog.id);
            }
            
        }
        
        INTGR_IntegrationHelper.initiateResendFailedRecordsToSN(mapNiIntegrationLog, mapIntCaseCreate, mapIntCaseUpdate, mapIntCaseCommCreate, mapIntFilesCreate);
        Test.setMock(HttpCalloutMock.class, new INTGR_REST_MockResponseGenerator());
        
        Test.stopTest();
        
    }
    
}