force-app/main/default/objects/INTGR_Account__c/INTGR_Account__c.object-meta.xml
<CustomObject>
    <description>!!! INTEGRATION OBJECT- DO NOT ALTER !!!
NICC-032393</description>
    <label>Integration Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Integration Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/INTGR_Account__c/fields/Assignment_Group__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Group__c</fullName>
    <description>NICC-030216 - Default value to be assigned to any case inbound or outbound from service now</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Default value to be assigned to any case inbound or outbound from service now</inlineHelpText>
    <label>Assignment Group</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/INTGR_Case__c/INTGR_Case__c.object-meta.xml
<CustomObject>
    <description>!!! INTEGRATION OBJECT- DO NOT ALTER !!!
NICC-032393</description>
    <label>Integration Case</label>
    <nameField>
        <displayFormat>INTGR-{0000000}</displayFormat>
        <label>Integration Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/INTGR_Case__c/fields/Affected_Service__c.field-meta.xml
<CustomField>
    <fullName>Affected_Service__c</fullName>
    <description>NICC-030216 - Picklist value for customer to set that denotes what service has an issue.</description>
    <inlineHelpText>Picklist value for customer to set that denotes what service has an issue.</inlineHelpText>
    <label>Affected Service</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin Portal</fullName>
            </value>
            <value>
                <fullName>CRS Solution</fullName>
            </value>
            <value>
                <fullName>CRS Administration Portal</fullName>
            </value>
            <value>
                <fullName>Payment Platform</fullName>
            </value>
            <value>
                <fullName>Call Center</fullName>
            </value>
            <value>
                <fullName>Channel Manager</fullName>
            </value>
            <value>
                <fullName>Content Manager or ACPMS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/INTGR_Case__c/fields/Assignment_Group__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Group__c</fullName>
    <description>NICC-030216 - The group to be set by winaproach</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The group to be set by winaproach</inlineHelpText>
    <label>Assignment Group</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/INTGR_Case__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>NICC-030216 - Lookup to case created by integration. This field is set by a Process Builder after Standard case is created via the Integration.</description>
    <inlineHelpText>Lookup to case created by integration. This field is set by a Process Builder after Standard case is created via the Integration.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Integration Cases</relationshipLabel>
    <relationshipName>Integration_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/INTGR_Case__c/fields/Customer_Ticket_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Ticket_Number__c</fullName>
    <description>NICC-030216 - User-friendly case/incident number of record in customer ITSM.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>User-friendly case/incident number of record in customer ITSM.</inlineHelpText>
    <label>Customer Ticket Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/INTGR_Case__c/fields/Customer_Ticket_System_Id__c.field-meta.xml
<CustomField>
    <fullName>Customer_Ticket_System_Id__c</fullName>
    <description>NICC-030216 - Primary key (system id) of case/incident record in customer ITSM.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Primary key (system id) of case/incident record in customer ITSM.</inlineHelpText>
    <label>Customer Ticket System Id</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/INTGR_Case__c/fields/Hotel_Code__c.field-meta.xml
<CustomField>
    <fullName>Hotel_Code__c</fullName>
    <description>NICC-030216 - Set by the integration user to denote the affected property&apos;s code.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Set by the integration user to denote the affected property&apos;s code.</inlineHelpText>
    <label>Hotel Code/Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/INTGR_Case__c/fields/INTGR_Account__c.field-meta.xml
<CustomField>
    <fullName>INTGR_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>NICC-030216 - Lookup populated by integration code for ease in referencing field values and to create a relationship for a related list on the INTGR_Account__c Object</description>
    <inlineHelpText>Lookup to integration account record details</inlineHelpText>
    <label>Integration Account</label>
    <referenceTo>INTGR_Account__c</referenceTo>
    <relationshipLabel>Integration Cases</relationshipLabel>
    <relationshipName>Integration_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/INTGR_Case__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <description>NICC-030216 - Value set by integration user and integration code for two-way (inbound/outbound) updating of Case severity.</description>
    <inlineHelpText>Value set by integration user and integration code for two-way (inbound/outbound) updating of Case severity.</inlineHelpText>
    <label>Severity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/INTGR_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>NICC-030216 - Value set by integration user and integration code for two-way (inbound/outbound) updating of Case status. Special rules apply (see documentation)</description>
    <inlineHelpText>Value set by integration user and integration code for two-way (inbound/outbound) updating of Case status. Special rules apply (see documentation)</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Acknowledged</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recovered</fullName>
            </value>
            <value>
                <fullName>Verified as Recovered</fullName>
            </value>
            <value>
                <fullName>Pending Master Recovery</fullName>
            </value>
            <value>
                <fullName>Pending Problem Resolution</fullName>
            </value>
            <value>
                <fullName>Pending Vendor</fullName>
            </value>
            <value>
                <fullName>Closed as recovered</fullName>
            </value>
            <value>
                <fullName>Closed as rejected</fullName>
            </value>
            <value>
                <fullName>Closed as withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/INTGR_Case__c/fields/System_Affected__c.field-meta.xml
<CustomField>
    <fullName>System_Affected__c</fullName>
    <description>NICC-030216 - Restricted picklist value of Type of environment impacted by issue.</description>
    <inlineHelpText>Type of environment impacted by issue.</inlineHelpText>
    <label>System Affected</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Production</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Internal Test System</fullName>
                <isActive>false</isActive>
                <label>Internal Test System</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/INTGR_Case_Comment__c/INTGR_Case_Comment__c.object-meta.xml
<CustomObject>
    <description>!!! INTEGRATION OBJECT- DO NOT ALTER !!!
NICC-032393</description>
    <label>Integration Case Comment</label>
    <nameField>
        <displayFormat>INTGRC-{0000000}</displayFormat>
        <label>Integration Case Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Case Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/INTGR_Case_Comment__c/fields/Customer_Ticket_System_Id__c.field-meta.xml
<CustomField>
    <fullName>Customer_Ticket_System_Id__c</fullName>
    <description>NICC-030216 - Formula reference to primary key (system id) set on the related integration case/incident record in customer ITSM.</description>
    <formula>INTGR_Case__r.Customer_Ticket_System_Id__c</formula>
    <inlineHelpText>Formula reference to primary key (system id) set on the related integration case/incident record in customer ITSM.</inlineHelpText>
    <label>Customer Ticket System Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/INTGR_Case_Comment__c/fields/INTGR_Case__c.field-meta.xml
<CustomField>
    <fullName>INTGR_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>NICC-030216 - Lookup to parent integration case</description>
    <inlineHelpText>Lookup to parent integration case</inlineHelpText>
    <label>Case</label>
    <referenceTo>INTGR_Case__c</referenceTo>
    <relationshipLabel>Integration Case Comments</relationshipLabel>
    <relationshipName>Integration_Case_Comments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/INTGR_Status_Mapping__c/INTGR_Status_Mapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>NICC-032393 - Status mapping between Sales force and Service Now.</description>
    <label>INTGR Status Mapping</label>
</CustomObject>

force-app/main/default/objects/INTGR_Status_Mapping__c/fields/INTGR_Current_Status__c.field-meta.xml
<CustomField>
    <fullName>INTGR_Current_Status__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>INTGR Current Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/INTGR_Status_Mapping__c/fields/INTGR_Inbound_Status__c.field-meta.xml
<CustomField>
    <fullName>INTGR_Inbound_Status__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>INTGR Inbound Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/INTGR_Status_Mapping__c/fields/INTGR_Status_Updated__c.field-meta.xml
<CustomField>
    <fullName>INTGR_Status_Updated__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>INTGR Status Updated</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceNowIncidentSettings__c/ServiceNowIncidentSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This setting is used to manage integration between Salesforce and ServiceNow. Create record name as &quot;Default&quot; and enter the required values for it.</description>
    <label>ServiceNow Incident Settings</label>
</CustomObject>

force-app/main/default/objects/ServiceNowIncidentSettings__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Default Account Id for legacy CRS integration cases with IHG</inlineHelpText>
    <label>Account Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceNowIncidentSettings__c/fields/Integration_UserId__c.field-meta.xml
<CustomField>
    <fullName>Integration_UserId__c</fullName>
    <description>Integration user record Id e.g. 00517000001YWXyAAO</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Integration user record Id e.g. 00517000001YWXyAAO</inlineHelpText>
    <label>Integration UserId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceNowIncidentSettings__c/fields/Integration_Username__c.field-meta.xml
<CustomField>
    <fullName>Integration_Username__c</fullName>
    <description>Salesforce username of the ServiceNow integration user, we do not need to send the information back to ServiceNow because the insert or update came from ServiceNow</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Integration username in Salesforce Org e.g. ihg_servicenow@newmarketinc.com.winaproach</inlineHelpText>
    <label>Integration Username</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/INTGR_WinSN_CaseComment_Handler_Test.cls
/************************************************************************************************
                 !!! INTEGRATION CLASS - DO NOT ALTER !!!
*************************************************************************************************
Name            : INTGR_WinSN_CaseComment_Handler_Test
Integration     : Win@pproach / Service Now
Author          : Sean Harris
Created Date    : 02/08/2019
Last Mod Date   : 02/08/2019
Last Mod By     : Sean Harris
NICC Reference  : 
Description     : Test class for INTGR_WinSN_CaseComment_Handler
                : 
*************************************************************************************************/
@isTest
public class INTGR_WinSN_CaseComment_Handler_Test 
{

    // ======================================================================================================================================= 
    // = CREATE TEST DATA : Create Accounts, Contacts, Integration Accounts & Users, Legacy Win@aproach Custom Settings
    // =======================================================================================================================================      
    @testSetup static void createTestData()  
    {
        
        // CREATE TEST ACCOUNTS
        Account acc = NI_TestClassData.createTestAccount(1);
        acc.Name = 'INTGR_WinSN_CaseComment_Handler_Test LEGACY Account';
        insert acc;
        
        Account acc2 = NI_TestClassData.createTestAccount(2);
        acc2.Name = 'INTGR_WinSN_CaseComment_Handler_Test NEXT Account';
        insert acc2;

        Contact con = NI_TestClassData.createTestContact(1, acc.id);		
        con.RecordTypeID = Schema.getGlobalDescribe().get('Contact').getDescribe().getRecordTypeInfosByName().get('Contact').getRecordTypeId();		
        insert con;
        
        // CREATE TEST INTERGRATION USERS
        User waUser = NI_TestClassData.createTestUser(121, 'Winaproach Integration Only - Standard'); 
        waUser.UserName = 'winaproachTEST@newmarketinc.com.nextdev3';
        insert waUser;         
        
        User snUser = NI_TestClassData.createTestUser(122, 'IHG Integration Only - Standard'); 
        snUser.UserName = 'ihg_servicenowTEST@newmarketinc.com.nextdev3';
        insert snUser;         
        
        User newUser = NI_TestClassData.createTestUser(123, 'Case Integration Customers'); 
        newUser.UserName = 'servicenowTEST@newmarketinc.com.nextdev3';
        insert newUser; 
 
        // CREATE TEST INTEGRATION ACCOUNT
        INTGR_Account__c iAcc = NI_TestClassData.createTestINTGR_Account(1, acc2.Id, newUser.Id);
        iAcc.Name = 'INTGR_WinSN_CaseComment_Handler_Test INTGR Account';
        insert iAcc;
        
        // CREATE TEST INTEGRATION ACCOUNT FIELD MAPPINGS
        List<INTGR_Field_Mapping__c> lstFMs = NI_TestClassData.createTestINTGR_AccountMapping(1, iAcc.Id);
        insert lstFMs;
        
        // SET THE NEW ACCOUNT ID CUSTOM SETTING FIELD TO TEST ACCOUNT ID
        NI_TestClassData.createTestWinaproachServiceNowSettings();
        
        ServiceNowIncidentSettings__c sn = [SELECT Id, AccountId__c, Integration_UserId__c, Integration_Username__c 
                                            FROM ServiceNowIncidentSettings__c 
                                            WHERE name = 'Default' 
                                            LIMIT 1];
        
        sn.Integration_Username__c = 'ihg_servicenowTEST@newmarketinc.com.nextdev3';
        sn.Integration_UserId__c = snUser.id;
        sn.AccountId__c = acc.Id;
        update sn;  

        // POPULATE INTEGRATION CUSTOM SETTING FOR STATUS
        Set<String> statusSet = new Set<String> {'Acknowledged-Open~Open',
            'Acknowledged-Recovered~Rejected',
            'New-New~New',
            'Open-Acknowledged~Acknowledged',
            'Open-Closed~Closed as Withdrawn',
            'Open-Closed as withdrawn~Closed as Withdrawn',
            'Recovered-Acknowledged~Acknowledged',
            'Recovered-Closed~Closed as Recovered',
            'Rejected-Acknowledged~Acknowledged',
            'Rejected-Closed~Closed as Rejected'};
        
        List<INTGR_Status_Mapping__c> isMappingList = new List<INTGR_Status_Mapping__c> ();
        
        for (String status : statusSet)
        {
            INTGR_Status_Mapping__c obj = new INTGR_Status_Mapping__c();
            obj.Name = status.split('~')[0];
            obj.INTGR_Inbound_Status__c = status.split('-')[1].split('~')[0];
            obj.INTGR_Status_Updated__c = status.split('~')[1];
            obj.INTGR_Current_Status__c = status.split('-')[0];
            
            isMappingList.add(obj);
        }
        
        insert isMappingList;

        Test.startTest();        
        
        // CREATE STANDARD CASE
        Case c = NI_TestClassData.createTestCase(1, acc2.Id);
        c.Subject = 'INTGR_WinSN_CaseComment_Handler_Test NEXT Standard Case 1';
        insert c;
        
        // CREATE NEXT INTEGRATION CASE
        INTGR_Case__c ic = NI_TestClassData.createTestINTGR_Case(1, iAcc.Id, null);
        ic.Case__c = c.Id;
        ic.Customer_Ticket_System_Id__c = '6df05258-9796-481a-8eae-eb3b9c230bd3';
        ic.Customer_Ticket_Number__c = 'INC000001';
        ic.Status__c = 'Open';
        ic.Severity__c = '3';
        ic.Assignment_Group__c = 'MHDHOT';
        ic.Hotel_Code__c = 'APEXTEST';
        ic.System_Affected__c = 'Production';
        ic.Affected_Service__c = 'CRS Administration Portal';
        ic.Subject__c = 'INTGR_WinSN_CaseComment_Handler_Test NEXT Case 1';
        insert ic;        

        Test.stopTest(); 
        
        // ASSERT STANDARD CASE WAS CREATED
        INTGR_Case__c iCs = [SELECT Id, Case__c, Subject__c,  
                             Customer_Ticket_System_Id__c, Customer_Ticket_Number__c, Status__c, 
                             Severity__c, Assignment_Group__c, Hotel_Code__c, System_Affected__c, Affected_Service__c 
                             FROM INTGR_Case__c WHERE Subject__c = 'INTGR_WinSN_CaseComment_Handler_Test NEXT Case 1'];
        
        system.assertNotEquals(null, iCs.Case__c);        

        
    }
    
    // ======================================================================================================================================= 
    // = TEST METHOD 1: LEGACY
    // =======================================================================================================================================       
    static testMethod void testWinaproachCaseComment()
    {

        Account acc = [SELECT Id FROM Account WHERE Name = 'INTGR_WinSN_CaseComment_Handler_Test LEGACY Account'];

        Test.startTest(); 
        
        //Test.setMock(HttpCalloutMock.class, new NI_WinaproachTestMock());
        
        List<Id> lstIds = new List<Id>();
        Case cs = new Case();
        cs.AccountId = acc.Id;
        cs.Subject = 'TestBK- ttest10';
        cs.RecordTypeID = Schema.getGlobalDescribe().get('Case').getDescribe().getRecordTypeInfosByName().get('CRS Incident').getRecordTypeId();
        cs.Priority = '3';
        cs.Customer_Severity__c = '1';
        cs.Amadeus_ExternalSystemAssigneeGroup__c = 'MHDHOT';
        cs.Amadeus_ExternalSystemLoggerGroup__c = 'MHDAIT';
        cs.Status = 'Open';
        cs.Winaproach_Logger__c = 'test';
        cs.Description = 'Test description';
        cs.Cause_Id_Code__c = 'Application';
        cs.Resolution_Code__c = 'Environment';
        cs.Winaproach_Logger_Phone_Number__c = '123456';
        cs.Winaproach_Owner_Group__c = 'MHDHOT';
        cs.Incident_Start_Date_Time__c = Datetime.now().addHours(-5); 
        cs.Resolved_Date_and_Time__c = Datetime.now().addHours(-1);
        cs.Assignment_Group__c = 'VN-GLBL-GRS Amadeus Level 3';
        cs.Hotel_Code__c = '123';
        cs.Origin = 'Win@proach Integration';
        cs.System_Affected__c = 'Disaster Recovery';       	
        insert cs;
        
        Attachment attach = new Attachment();   	
        attach.Name = 'Unit Test Attachment';
        Blob bodyBlob = Blob.valueOf('Unit Test Attachment Body');
        attach.body = bodyBlob;
        attach.parentId = cs.id;
        insert attach;
        
        Task t = new Task();
        t.OwnerId = UserInfo.getUserId();		
        t.RecordTypeID = Schema.getGlobalDescribe().get('Task').getDescribe().getRecordTypeInfosByName().get('Amadeus Parallel Investigation').getRecordTypeId();    
        t.Subject = 'Donni';
        t.Status = 'New';
        t.Priority = 'Normal';
        t.WhatId = cs.id;
        t.Parallel_Investigation_Group__c = 'MHDHOT';
        t.Parallel_Investigation_Reason_Code__c = 'SMC Investigation Completed';
        t.Added_By_Group__c = 'MHDHOT'; 
        t.Description = 'Comments';
        t.PI_Group_Long_Names__c = 'Service Reliability Engineers - OCHOOO'; 
        t.Sub_Status__c = 'External Info';
        insert t;
        
        CaseComment csComment = NI_TestClassData.createTestCaseComment(1, cs.Id); 
        csComment.CommentBody = 'comments';
        insert csComment;                        
        
        csComment.CommentBody = 'comments update';
        update csComment; 
        
        Test.stopTest();

    }
    
    // ======================================================================================================================================= 
    // = TEST METHOD 2: LEGACY
    // =======================================================================================================================================     
    static testMethod void testServiceNowCaseComment()
    {
        
    }
    
    // ======================================================================================================================================= 
    // = TEST METHOD 3: TEST AN "OUTGOING" NEXT CASE COMMENT FROM Winaproach Integration Only - Standard USER
    // =======================================================================================================================================       
    static testMethod void testWinaproachCaseCommentNEXT()
    {

        User u = [SELECT Id FROM User WHERE UserName = 'winaproachTEST@newmarketinc.com.nextdev3'];         
        Case c = [SELECT Id FROM Case WHERE Subject = 'INTGR_WinSN_CaseComment_Handler_Test NEXT Standard Case 1'];
		INTGR_Case__c iCs = [SELECT Id FROM INTGR_Case__c WHERE Subject__c = 'INTGR_WinSN_CaseComment_Handler_Test NEXT Case 1'];
        
        system.runAs(u)
        {                
            CaseComment cc = NI_TestClassData.createTestCaseComment(1, c.Id);
            cc.CommentBody = 'INTGR_WinSN_CaseComment_Handler_Test NEXT CaseComment 1';
            insert cc;
            
        }        
        
    }
    
    // ======================================================================================================================================= 
    // = TEST METHOD 4: TEST AN "INCOMING" NEXT CASE COMMENT FROM Case Integration Customers USER
    // =======================================================================================================================================     
    static testMethod void testServiceNowCaseCommentNEXT()
    {
        
        User u = [SELECT Id FROM User WHERE UserName = 'servicenowTEST@newmarketinc.com.nextdev3'];
        Account acc = [SELECT Id FROM Account WHERE Name = 'INTGR_WinSN_CaseComment_Handler_Test NEXT Account'];
        INTGR_Account__c iAcc = [SELECT Id FROM INTGR_Account__c WHERE Name = 'INTGR_WinSN_CaseComment_Handler_Test INTGR Account'];
        
        system.runAs(u)
        {
            // CREATE INBOUND INTEGRATION CASE
            INTGR_Case__c c = NI_TestClassData.createTestINTGR_Case(1, iAcc.Id, null);
            c.Customer_Ticket_System_Id__c = '2b45c340-3473-4d57-98b9-5647b2de5a62';
            c.Customer_Ticket_Number__c = 'INC000002';
            c.Status__c = 'Open';
            c.Severity__c = '3';
            c.Assignment_Group__c = 'MHDHOT';
            c.Hotel_Code__c = 'APEXTEST';
            c.System_Affected__c = 'Production';
            c.Affected_Service__c = 'CRS Administration Portal';
            c.Subject__c = 'INTGR_WinSN_CaseComment_Handler_Test NEXT Case 2';
            insert c;
Test.startTest();            
            INTGR_Case__c iCs = [SELECT Id, Case__c, Error_Message__c FROM INTGR_Case__c WHERE Subject__c = 'INTGR_WinSN_CaseComment_Handler_Test NEXT Case 2'];
            system.assertEquals('Operation Successful.', iCs.Error_Message__c);
            
            INTGR_Case_Comment__c cc = NI_TestClassData.createTestINTGR_CaseComm(c.Id);
            insert cc;
Test.stopTest();            
        }
        
        List<Case> lstCaseAsserts = new List<Case>([SELECT Id, Subject, AccountId FROM Case WHERE Subject = 'INTGR_WinSN_CaseComment_Handler_Test NEXT Case 2']);
        system.debug(' **** lstCaseAsserts = ' + lstCaseAsserts);
        // ASSERT CORRECT ACCOUNT ID ON NEW CASE
        system.assertEquals(lstCaseAsserts.size(), 1);        
        // ASSERT CORRECT ACCOUNT ID ON NEW CASE
        system.assertEquals(lstCaseAsserts[0].AccountId, acc.Id); 
        
        Id csId = lstCaseAsserts[0].Id;
        
        List<CaseComment> lstCaseCommentAsserts = new List<CaseComment>([SELECT Id, ParentId, CommentBody FROM CaseComment]);
        system.debug(' **** lstCaseCommentAsserts = ' + lstCaseCommentAsserts);
        // ASSERT CORRECT ACCOUNT ID ON NEW CASE
        //system.assertEquals(lstCaseCommentAsserts.size(), 1);        
        // ASSERT CORRECT ACCOUNT ID ON NEW CASE
        //system.assertEquals(lstCaseCommentAsserts[0].ParentId, csId);         
        
        CaseComment newCC = NI_TestClassData.createTestCaseComment(1, csId);
        insert newCC;
        
        
    }
    
}