force-app/main/default/objects/INTGR_Account__c/INTGR_Account__c.object-meta.xml
<CustomObject>
    <description>!!! INTEGRATION OBJECT- DO NOT ALTER !!!
NICC-032393</description>
    <label>Integration Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Integration Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/INTGR_Account__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NICC-030216 - Provides the means to Enable/Disable a customer&apos;s integration</description>
    <inlineHelpText>When this checkbox is checked the integration is live for this specific customer. Uncheck to disable the integration.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/INTGR_Account__c/fields/Assignment_Group__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Group__c</fullName>
    <description>NICC-030216 - Default value to be assigned to any case inbound or outbound from service now</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Default value to be assigned to any case inbound or outbound from service now</inlineHelpText>
    <label>Assignment Group</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/INTGR_Account__c/fields/Case_Origin__c.field-meta.xml
<CustomField>
    <fullName>Case_Origin__c</fullName>
    <description>NICC-030216 - Value used by integration to set default case origin on standard Case it creates.</description>
    <inlineHelpText>Value used by integration to set default case origin on standard Case it creates.</inlineHelpText>
    <label>Case Origin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ServiceNow Integration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/INTGR_Account__c/fields/Default_New_Case_Status__c.field-meta.xml
<CustomField>
    <fullName>Default_New_Case_Status__c</fullName>
    <description>NICC-030216 - Value used by integration to set default status on standard Case it creates.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Value used by integration to set default status on standard Case it creates.</inlineHelpText>
    <label>Default New Case Status</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/INTGR_Account__c/fields/Logger_Desk_Agent_Name__c.field-meta.xml
<CustomField>
    <fullName>Logger_Desk_Agent_Name__c</fullName>
    <description>NICC-030216 - Value used by integration to set default logger agent name on standard Case it creates.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Value used by integration to set default logger agent name on standard Case it creates.</inlineHelpText>
    <label>Logger/Desk Agent Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/INTGR_Account__c/fields/Logger_Desk_Agent_Phone__c.field-meta.xml
<CustomField>
    <fullName>Logger_Desk_Agent_Phone__c</fullName>
    <description>NICC-030216 - Value used by integration to set default logger desk agent phone on standard Case it creates.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Value used by integration to set default logger desk agent phone on standard Case it creates.</inlineHelpText>
    <label>Logger /Desk Agent Phone</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/INTGR_Account__c/fields/Logger_Group__c.field-meta.xml
<CustomField>
    <fullName>Logger_Group__c</fullName>
    <description>NICC-030216 - Value used by integration to set default logger group on standard Case it creates.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Value used by integration to set default logger group on standard Case it creates.</inlineHelpText>
    <label>Logger / Group</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/INTGR_Account__c/fields/RequestFormat__c.field-meta.xml
<CustomField>
    <fullName>RequestFormat__c</fullName>
    <description>NICC-030216 - The method/language used to generate the out bound call to customer ITSM.</description>
    <inlineHelpText>The method/language used to generate the out bound call to customer ITSM.</inlineHelpText>
    <label>Request Format</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>XML</fullName>
            </value>
            <value>
                <fullName>JSON</fullName>
            </value>
            <value>
                <fullName>SOAP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/INTGR_Case__c/INTGR_Case__c.object-meta.xml
<CustomObject>
    <description>!!! INTEGRATION OBJECT- DO NOT ALTER !!!
NICC-032393</description>
    <label>Integration Case</label>
    <nameField>
        <displayFormat>INTGR-{0000000}</displayFormat>
        <label>Integration Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/INTGR_Case__c/fields/Assignment_Group__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Group__c</fullName>
    <description>NICC-030216 - The group to be set by winaproach</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The group to be set by winaproach</inlineHelpText>
    <label>Assignment Group</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/INTGR_Case__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>NICC-030216 - Lookup to case created by integration. This field is set by a Process Builder after Standard case is created via the Integration.</description>
    <inlineHelpText>Lookup to case created by integration. This field is set by a Process Builder after Standard case is created via the Integration.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Integration Cases</relationshipLabel>
    <relationshipName>Integration_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/INTGR_Case__c/fields/Customer_Ticket_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Ticket_Number__c</fullName>
    <description>NICC-030216 - User-friendly case/incident number of record in customer ITSM.</description>
    <encryptionScheme>None</encryptionScheme>
    <externalId>true</externalId>
    <inlineHelpText>User-friendly case/incident number of record in customer ITSM.</inlineHelpText>
    <label>Customer Ticket Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/INTGR_Case__c/fields/Customer_Ticket_System_Id__c.field-meta.xml
<CustomField>
    <fullName>Customer_Ticket_System_Id__c</fullName>
    <description>NICC-030216 - Primary key (system id) of case/incident record in customer ITSM.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Primary key (system id) of case/incident record in customer ITSM.</inlineHelpText>
    <label>Customer Ticket System Id</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/INTGR_Case__c/fields/INTGR_Account__c.field-meta.xml
<CustomField>
    <fullName>INTGR_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>NICC-030216 - Lookup populated by integration code for ease in referencing field values and to create a relationship for a related list on the INTGR_Account__c Object</description>
    <inlineHelpText>Lookup to integration account record details</inlineHelpText>
    <label>Integration Account</label>
    <referenceTo>INTGR_Account__c</referenceTo>
    <relationshipLabel>Integration Cases</relationshipLabel>
    <relationshipName>Integration_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/INTGR_Case__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>NICC-030216 - Value set by integration user and integration code for two-way (inbound/outbound) updating of Case subject.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Value set by integration user and integration code for two-way (inbound/outbound) updating of Case subject.</inlineHelpText>
    <label>Subject</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/INTGR_Case_Comment__c/INTGR_Case_Comment__c.object-meta.xml
<CustomObject>
    <description>!!! INTEGRATION OBJECT- DO NOT ALTER !!!
NICC-032393</description>
    <label>Integration Case Comment</label>
    <nameField>
        <displayFormat>INTGRC-{0000000}</displayFormat>
        <label>Integration Case Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Case Comments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/INTGR_Case_Comment__c/fields/Customer_Ticket_System_Id__c.field-meta.xml
<CustomField>
    <fullName>Customer_Ticket_System_Id__c</fullName>
    <description>NICC-030216 - Formula reference to primary key (system id) set on the related integration case/incident record in customer ITSM.</description>
    <formula>INTGR_Case__r.Customer_Ticket_System_Id__c</formula>
    <inlineHelpText>Formula reference to primary key (system id) set on the related integration case/incident record in customer ITSM.</inlineHelpText>
    <label>Customer Ticket System Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/INTGR_Case_Comment__c/fields/INTGR_Case__c.field-meta.xml
<CustomField>
    <fullName>INTGR_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>NICC-030216 - Lookup to parent integration case</description>
    <inlineHelpText>Lookup to parent integration case</inlineHelpText>
    <label>Case</label>
    <referenceTo>INTGR_Case__c</referenceTo>
    <relationshipLabel>Integration Case Comments</relationshipLabel>
    <relationshipName>Integration_Case_Comments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WinaproachIncidentSettings__c/WinaproachIncidentSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This settings used to manage end points and credentials for Win@proach integration. Create record name as &quot;Default&quot; and enter the required values for it.</description>
    <label>Win@proach Incident Settings</label>
</CustomObject>

force-app/main/default/objects/WinaproachIncidentSettings__c/fields/Integration_Username__c.field-meta.xml
<CustomField>
    <fullName>Integration_Username__c</fullName>
    <description>Salesforce username of the winaproach integration user, we do not need to send the information back to Win@proach because the insert or update came from Win@proach</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Salesforce username of the integration user i.e. winaproach user.  We do not need to send the information back to Win@proach because the insert or update came from Win@proach</inlineHelpText>
    <label>Integration Username</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/INTGR_ContentVersion_TriggerHandler_Test.cls
/************************************************************************************************
				!!! INTEGRATION CLASS - DO NOT ALTER !!!                          
*************************************************************************************************
Name            : INTGR_ContentVersion_TriggerHandler_Test
Author          : Princy Jain
Created Date    : 06/06/2018
Last Mod Date   : 01/14/2019
Last Mod By     : Sean Harris
NICC Reference  : 
Description     : Test class for INTGR_ContentVersion_TriggerHandler
				:
****************************************************************************************/
@isTest
public class INTGR_ContentVersion_TriggerHandler_Test
{
    
    // ======================================================================================================================================= 
    // = CREATE TEST DATA
    // =======================================================================================================================================  	
    @testSetup static void setupObjects() 
    {
        
        // CREATE WIN@PROACH & SERVICE NOW CUSTOM SETTINGS
        NI_TestClassData.createTestWinaproachServiceNowSettings();
        
        WinaproachIncidentSettings__c ws = WinaproachIncidentSettings__c.getInstance('Default');
        ws.Integration_Username__c = UserInfo.getUserName();
        update ws;
        
        // CREATE TEST CUSTOMER USER ACCOUNT
        User u = NI_TestClassData.createTestUser(111, 'Case Integration Customers');
        u.Email = 'apexTester111@amadeuscustomer.com';
        u.Alias = 'apiUser';
        insert u; 
        
        Account a1 = NI_TestClassData.createTestAccount(1);
        insert a1;
        
        // CREATE TEST INTEGRATION ACCOUNT RECORD
        INTGR_Account__c acc = NI_TestClassData.createTestINTGR_Account(1, a1.Id, u.Id);
        acc.Active__c = true;
        acc.Assignment_Group__c = 'Test Group' ;
        acc.Case_Origin__c = 'ServiceNow';
        acc.Logger_Desk_Agent_Name__c = 'ServiceNow';
        acc.Default_New_Case_Status__c = 'New';
        acc.Logger_Desk_Agent_Phone__c = '123456789';
        acc.Logger_Group__c = 'ServiceNow';
        acc.RequestFormat__c = 'XML';
        insert acc;
        
        // CREATE INBOUND DATA FOR Internal Cases
        system.runAs(u)
        {
            
            // CREATE INBOUND INTEGRATION CASE
            INTGR_Case__c caseObj2 = NI_TestClassData.createTestINTGR_Case(1, acc.id, null);
            caseObj2.Customer_Ticket_System_Id__c = 'INC000001';
            caseObj2.Customer_Ticket_Number__c = 'INC000001';
            caseObj2.Subject__c = 'PROSPECT - ' + caseObj2.Subject__c;
            insert caseObj2;
            
            INTGR_Case_Comment__c caseComm = NI_TestClassData.createTestINTGR_CaseComm(caseObj2.Id);
            
        }
        
        // CREATE OUTBOUND CASE
        Case cs = NI_TestClassData.createTestCaseIntegration(1, a1.Id);
        cs.Integration_Account__c = acc.Id;
        cs.Acknowledged__c = system.now();
        cs.Rejected_Case__c = true;
        cs.INTGR_Customer_Ticket_System_Id__c = 'INC001';
        cs.Customer_Ticket_Number__c = 'INC001';
        cs.Update_External_System__c = true;
        insert cs;
        
    }
    
    // ======================================================================================================================================= 
    // = TEST METHOD 1:
    // =======================================================================================================================================      
    static testmethod void coverContentInsertAPIUser() 
    {
        
        User u = [SELECT Id FROM User WHERE Alias = 'apiUser'];
        
        Test.startTest(); 
        
        system.runAs(u)
        {
            
            INTGR_Case__c intCase = [SELECT Id, Case__c FROM INTGR_Case__c WHERE createdbyId =: u.Id][0];
            
            ContentVersion cv = NI_TestClassData.createContentVersion();
            cv.INTGR_Case__c = intCase.Id;
            
            try 
            {
                insert cv;
            }
            catch (Exception ex)
            {
                system.debug ('Error during insert: ' + ex.getMessage());
            }
            
            List<ContentDocumentLink> cdl = [SELECT Id, ContentDocumentId FROM ContentDocumentLink WHERE ShareType = 'V' AND LinkedEntityId =: intCase.Id];
            
        }
        
        Test.setMock(HttpCalloutMock.class, new INTGR_REST_MockResponseGenerator());
        Test.stopTest();
        
    }
    
    // ======================================================================================================================================= 
    // = TEST METHOD 2:
    // =======================================================================================================================================      
    static testmethod void coverContentInsertSysAdmin() 
    {
        
        User u = [SELECT Id FROM User WHERE Alias = 'apiUser'];
        
        Test.startTest();
        
        Test.setMock(HttpCalloutMock.class, new INTGR_REST_MockResponseGenerator());
        
        Id caseId = [SELECT Id FROM Case WHERE CreatedById !=: u.Id LIMIT 1][0].Id;
        
        Map<Id, Case> idVsCaseObjMap = INTGR_Case_SOQLDataProvider.getSCdetailsToInsertIC(caseId);
        
        INTGR_IntegrationHelper.upsertIntegrationCase(idVsCaseObjMap, true, false, null);
        
        ContentVersion cv = NI_TestClassData.createContentVersion();
        insert cv;
        
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        
        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.ContentDocumentId = documents[0].Id;
        cdl.LinkedEntityId = caseId;
        cdl.ShareType = 'V';
        insert cdl;
        
        ContentVersion cv1 = [SELECT Id, INTGR_Case__c, CaseId__c FROM ContentVersion WHERE createdById !=:u.Id][0];
        
        // Fix for test failure
        if (cv1.CaseId__c != null)
        {
            system.assertNotEquals(null, cv1.CaseId__c);
        }
        
        Test.stopTest();
        
    }
    
    // ======================================================================================================================================= 
    // = TEST METHOD 3:
    // =======================================================================================================================================      
    static testmethod void coverContentInsertSysAdminSOAP() 
    {
        
        User u = [SELECT Id FROM User WHERE Alias = 'apiUser'];
        
        INTGR_Account__c acc = [SELECT Id,RequestFormat__c FROM INTGR_Account__c WHERE RequestFormat__c = 'XML'][0];
        acc.RequestFormat__c = 'SOAP';
        update acc;
        
        Test.startTest();
        
        Test.setMock(WebServiceMock.class, new INTGR_SOAP_MockResponseGenerator('abcd1234', 'INC001'));
        
        Id caseId = [SELECT Id FROM Case WHERE CreatedById !=: u.Id LIMIT 1][0].Id;
        
        Map<id,Case> idVsCaseObjMap = INTGR_Case_SOQLDataProvider.getSCdetailsToInsertIC(caseId);
        
        INTGR_IntegrationHelper.upsertIntegrationCase(idVsCaseObjMap, true, false, null);
        
        ContentVersion cv = NI_TestClassData.createContentVersion();
        insert cv;
        
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        
        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.ContentDocumentId = documents[0].Id;
        cdl.LinkedEntityId = caseId;
        cdl.ShareType = 'V';
        insert cdl;
        
        ContentVersion cv1 = [SELECT Id, INTGR_Case__c, CaseId__c FROM ContentVersion WHERE createdById !=: u.Id][0];
        //fix for test failure
        if (cv1.CaseId__c != null)
        {
            system.assertNotEquals (null, cv1.CaseId__c);
        }
        
        Test.stopTest();
        
    }
    
}