force-app/main/default/objects/INTGR_Account__c/INTGR_Account__c.object-meta.xml
<CustomObject>
    <description>!!! INTEGRATION OBJECT- DO NOT ALTER !!!
NICC-032393</description>
    <label>Integration Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Integration Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/INTGR_Account__c/fields/Max_Count_To_Resend_Failed_Message__c.field-meta.xml
<CustomField>
    <fullName>Max_Count_To_Resend_Failed_Message__c</fullName>
    <description>NICC-030216 - Maximum number of retries for re-sending failed messages to the external system</description>
    <inlineHelpText>Maximum number of retries for re-sending failed messages to the external system</inlineHelpText>
    <label>Max Count To Resend Failed Message</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/INTGR_Case__c/INTGR_Case__c.object-meta.xml
<CustomObject>
    <description>!!! INTEGRATION OBJECT- DO NOT ALTER !!!
NICC-032393</description>
    <label>Integration Case</label>
    <nameField>
        <displayFormat>INTGR-{0000000}</displayFormat>
        <label>Integration Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/INTGR_Case__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>NICC-030216 - Lookup to case created by integration. This field is set by a Process Builder after Standard case is created via the Integration.</description>
    <inlineHelpText>Lookup to case created by integration. This field is set by a Process Builder after Standard case is created via the Integration.</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Integration Cases</relationshipLabel>
    <relationshipName>Integration_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/INTGR_Case__c/fields/INTGR_Account__c.field-meta.xml
<CustomField>
    <fullName>INTGR_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>NICC-030216 - Lookup populated by integration code for ease in referencing field values and to create a relationship for a related list on the INTGR_Account__c Object</description>
    <inlineHelpText>Lookup to integration account record details</inlineHelpText>
    <label>Integration Account</label>
    <referenceTo>INTGR_Account__c</referenceTo>
    <relationshipLabel>Integration Cases</relationshipLabel>
    <relationshipName>Integration_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/INTGR_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>NICC-030216 - Value set by integration user and integration code for two-way (inbound/outbound) updating of Case status. Special rules apply (see documentation)</description>
    <inlineHelpText>Value set by integration user and integration code for two-way (inbound/outbound) updating of Case status. Special rules apply (see documentation)</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Acknowledged</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recovered</fullName>
            </value>
            <value>
                <fullName>Verified as Recovered</fullName>
            </value>
            <value>
                <fullName>Pending Master Recovery</fullName>
            </value>
            <value>
                <fullName>Pending Problem Resolution</fullName>
            </value>
            <value>
                <fullName>Pending Vendor</fullName>
            </value>
            <value>
                <fullName>Closed as recovered</fullName>
            </value>
            <value>
                <fullName>Closed as rejected</fullName>
            </value>
            <value>
                <fullName>Closed as withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NI_Integration_Log__c/NI_Integration_Log__c.object-meta.xml
<CustomObject>
    <label>NI Integration Log</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>NI Integration Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NI Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_Integration_Log__c/fields/Attachment_Id__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Id__c</fullName>
    <description>NICC-023347
The 18 character Salesforce Id of the attachment record related to this integration message. This field is updated when attachments are sent as part of the integration.</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>The 18 character Salesforce Id of the attachment record related to this integration message. This field is updated when attachments are sent as part of the integration.</inlineHelpText>
    <label>Attachment Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_Integration_Log__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to Case object from NI Integration Logs</description>
    <inlineHelpText>Lookup to Case object from NI Integration Logs</inlineHelpText>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>NI Integration Logs</relationshipLabel>
    <relationshipName>NI_Integration_Logs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Integration_Log__c/fields/Do_Retries__c.field-meta.xml
<CustomField>
    <fullName>Do_Retries__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is used to determine to resend the failed messages to server.</description>
    <inlineHelpText>This is used to determine to resend the failed messages to server.</inlineHelpText>
    <label>Do Retries</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NI_Integration_Log__c/fields/File_Id__c.field-meta.xml
<CustomField>
    <fullName>File_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>File Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_Integration_Log__c/fields/Integration_Case__c.field-meta.xml
<CustomField>
    <fullName>Integration_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>NICC-030216 - Lookup to Integration case for retry attempts and logging purpose
NICC-032393</description>
    <inlineHelpText>Lookup to Integration case for retry attempts and logging purpose</inlineHelpText>
    <label>Integration Case</label>
    <referenceTo>INTGR_Case__c</referenceTo>
    <relationshipLabel>NI Integration Logs</relationshipLabel>
    <relationshipName>NI_Integration_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Integration_Log__c/fields/Integration_Name__c.field-meta.xml
<CustomField>
    <fullName>Integration_Name__c</fullName>
    <description>Integration log records populated with integration name.</description>
    <label>Integration Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Win@proach</fullName>
            </value>
            <value>
                <fullName>ServiceNow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NI_Integration_Log__c/fields/Retries_Performed__c.field-meta.xml
<CustomField>
    <fullName>Retries_Performed__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total number of retries performed for re sending failed message.</description>
    <inlineHelpText>Total number of retries performed for re sending failed message.</inlineHelpText>
    <label>Retries Performed</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NI_Integration_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Values will be set based on the response from the web services call</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NI_Integration_Log__c/fields/Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Type__c</fullName>
    <description>It will be set accordingly based on whether the web services call was an insert or update.</description>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Insert</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NI_Integration_Log__c/fields/UpdateFor__c.field-meta.xml
<CustomField>
    <fullName>UpdateFor__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>UpdateFor</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_Integration_Log__c/fields/XMLRequest__c.field-meta.xml
<CustomField>
    <fullName>XMLRequest__c</fullName>
    <description>Win@proach/Service Now request for log purpose, it may contain xml or json request for create/update fields, attachments etc.
NICC-030216 - Relabeled from XMLRequest to Request
NICC-032393</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>Win@proach/Service Now request for log purpose, it may contain xml or json request for create/update fields, attachments etc.</inlineHelpText>
    <label>Request</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/WinaproachIncidentSettings__c/WinaproachIncidentSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This settings used to manage end points and credentials for Win@proach integration. Create record name as &quot;Default&quot; and enter the required values for it.</description>
    <label>Win@proach Incident Settings</label>
</CustomObject>

force-app/main/default/objects/WinaproachIncidentSettings__c/fields/Max_Count_To_Resend_Failed_Message__c.field-meta.xml
<CustomField>
    <fullName>Max_Count_To_Resend_Failed_Message__c</fullName>
    <defaultValue>10</defaultValue>
    <description>Maximum number of retries for re-sending failed messages.</description>
    <inlineHelpText>Maximum number of retries for re-sending failed messages.</inlineHelpText>
    <label>Max Count To Resend Failed Message</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/INTGR_ResendWinaproach.cls
/************************************************************************************************
                  INTEGRATION CLASS - DO NOT ALTER!!!
*************************************************************************************************
Name            : INTGR_ResendWinaproach Class
Author          : Sean Harris
Created Date    : 01/15/2019
Last Mod Date   : 01/15/2019 
Last Mod By     : Sean Harris
NICC Reference  : 
Description     : 
                : 
*************************************************************************************************/
global class INTGR_ResendWinaproach implements Database.Batchable<sObject>, Database.AllowsCallouts 
{

    global final String strJobName;
    global final Id intgrAcctId;
    global final Integer iResendInterval;

    global INTGR_ResendWinaproach(String sJobName, Id iAcctId, Integer iResendInt)
    {      
        strJobName = sJobName;
        intgrAcctId = iAcctId; 
        iResendInterval = iResendInt;
    }    

    global Database.QueryLocator start(Database.BatchableContext bc)
    {
        
        system.debug(' *** ENTERING INTGR_ResendWinaproach.start() - QUERIES ISSUED = ' + Limits.getQueries());
        
        // FETCH WINAPROACH RETRIES FROM CUSTOM SETTINGS
		WinaproachIncidentSettings__c winSettings = WinaproachIncidentSettings__c.getValues('Default');
		Integer maxRetries = 10;
		
        if (Integer.valueOf(winSettings.Max_Count_To_Resend_Failed_Message__c) != null)
        {
            maxRetries = Integer.valueOf(winSettings.Max_Count_To_Resend_Failed_Message__c);
        }
        
        String query = 'SELECT Id, Case__c, Status__c, Transaction_Type__c, Integration_Name__c, UpdateFor__c, ';
        query += 'Retries_Performed__c, Do_Retries__c, XMLRequest__c, Attachment_Id__c, File_Id__c ';  
        query += 'FROM NI_Integration_Log__c ';
        query += 'WHERE status__c = \'Failed\' ';
        query += 'AND Integration_Name__c = \'Win@proach\' ';
        query += 'AND Integration_Case__r.INTGR_Account__c = \'' + intgrAcctId + '\' ';  			// ADDED THIS TO FILTER OUT LEGACY INTEGRATION LOG RECORDS
        query += 'AND Do_Retries__c = true ';
        query += 'AND Retries_Performed__c < ' + maxRetries;         
        
        system.debug(' **** query = ' + query);
                     
        system.debug(' *** EXITING INTGR_ResendWinaproach.start() - QUERIES ISSUED = ' + Limits.getQueries());
        
        return Database.getQueryLocator(query);
        
    }
    
	global void execute(Database.BatchableContext bc, List<NI_Integration_Log__c> scope)
    {
		
        system.debug(' *** ENTERING INTGR_ResendWinaproach.execute() - QUERIES ISSUED = ' + Limits.getQueries());

		Map<Id, Id> mapLogCaseIds = new Map<Id, Id>();
		Map<Id, Integer> mapRetriesID = new Map<Id, Integer>();
		Map<Id, Id> mapLogCaseIdsUpdate = new Map<Id, Id>();
		Map<Id, NI_Integration_Log__c> mapNiIntLog = new Map<Id, NI_Integration_Log__c>();

        for (NI_Integration_Log__c nlog : scope)
        {
            if (nlog.Transaction_Type__c == 'Insert')
            {
                MapLogCaseIds.put(nlog.id, nlog.Case__c);
                mapRetriesID.put(nlog.id, Integer.valueOf(nlog.Retries_Performed__c));
            } 
            else 
            {
                if (nlog.Transaction_Type__c == 'Update')
                {
                    mapLogCaseIdsUpdate.put(nlog.id, nlog.Case__c);
                    mapNiIntLog.put(nlog.id, nlog);
                }
            }
        }

		if (mapLogCaseIds.size() > 0)
        {
			system.debug(' **** mapLogCaseIds = ' + mapLogCaseIds);
            system.debug(' **** mapRetriesID = ' + mapRetriesID);            
            NI_WinaproachServiceHelper.resendRequestToWinaproach(mapLogCaseIds, mapRetriesID);
        }
        
	    if (mapLogCaseIdsUpdate.size() > 0)
        {
			system.debug(' **** mapLogCaseIdsUpdate = ' + mapLogCaseIdsUpdate);
            system.debug(' **** mapNiIntLog = ' + mapNiIntLog);
            NI_WinaproachServiceHelper.resendRequestToWinaproachUpdate(mapLogCaseIdsUpdate, mapNiIntLog);	
        }

        system.debug(' *** EXITING INTGR_ResendWinaproach.execute() - QUERIES ISSUED = ' + Limits.getQueries());

	}
    
	global void finish(Database.BatchableContext bc)
    {
		
        system.debug(' *** ENTERING INTGR_ResendWinaproach.finish() - QUERIES ISSUED = ' + Limits.getQueries());
 
        // FETCH WINAPROACH RETRIES FROM CUSTOM SETTINGS
		WinaproachIncidentSettings__c winSettings = WinaproachIncidentSettings__c.getValues('Default');
		Integer maxRetries = 10;
		
        if (Integer.valueOf(winSettings.Max_Count_To_Resend_Failed_Message__c) != null)
        {
            maxRetries = Integer.valueOf(winSettings.Max_Count_To_Resend_Failed_Message__c);
        }
        
		Integer logCount = [SELECT COUNT() 
                            FROM NI_Integration_Log__c 
                            WHERE status__c = 'Failed'  
                            AND Integration_Name__c = 'Win@proach' 
                            AND Integration_Case__r.INTGR_Account__c =: intgrAcctId  			// ADDED THIS TO FILTER OUT LEGACY INTEGRATION LOG RECORDS
                            AND Do_Retries__c = true 
                            AND Retries_Performed__c <: maxRetries];        

		List<CronTrigger> lstBatch = new List<CronTrigger>([SELECT Id, CronJobDetail.Name FROM CronTrigger WHERE CronJobDetail.Name =: strJobName]); 

        system.debug(' **** logCount = ' + logCount);
        system.debug(' **** lstBatch.size() = ' + lstBatch.size());
        
        // IF THERE ARE STILL INTEGRATION LOGS TO PROCESS AND THERE IS NOT SCHEDULED JOB 
		if (logCount > 0 && (lstBatch.size() == 0))
        {
            system.debug(' **** Scheduling job named ' + strJobName + ' using apex class INTGR_ResendWinaproach');
			// CALLING BATCH TO PROCESS FAILED LOGS
			INTGR_ResendWinaproach resend = new INTGR_ResendWinaproach(strJobName, intgrAcctId, iResendInterval);
			// SETTING NAME OF BATCH WITH CALL AFTER(MIN) AND BATCH SIZE
            system.scheduleBatch(resend, strJobName, iResendInterval, 50);
		}
		
        system.debug(' *** EXITING INTGR_ResendWinaproach.finish() - QUERIES ISSUED = ' + Limits.getQueries());
 
	}
    
}