force-app/main/default/objects/AH_Finance_Request__c/AH_Finance_Request__c.object-meta.xml
<CustomObject>
    <description>NICC-030091
This object is used to capture requests for the various teams in Finance that must go through a formal approval process.   This was initially created as proof of concept to replace the FFA Credit Memo request form which is currently done in Excel.</description>
    <label>Finance Request</label>
    <nameField>
        <displayFormat>FR-{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Finance Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_Finance_Request__c/fields/Net_Credit_Amount__c.field-meta.xml
<CustomField>
    <fullName>Net_Credit_Amount__c</fullName>
    <businessOwnerGroup>DEPT_Finance</businessOwnerGroup>
    <description>Updated per NICC-037379. Field label changed from &quot;Net Credit Amount&quot; to &quot;Net Amount&quot;</description>
    <inlineHelpText>The amount to be credited or refunded.  This would be the original amount requested minus any rebill amount</inlineHelpText>
    <label>Net Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AH_Manual_Credit_Lines__c/AH_Manual_Credit_Lines__c.object-meta.xml
<CustomObject>
    <description>NICC-030091
This object is used to link Products to Finance Requests.  Finance creates these records when manual credits need to be applied.</description>
    <label>Manual Credit Lines</label>
    <nameField>
        <displayFormat>MC-{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manual Credit Lines</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_Manual_Credit_Lines__c/fields/Requested_Credit_Amount__c.field-meta.xml
<CustomField>
    <fullName>Requested_Credit_Amount__c</fullName>
    <label>Requested Credit Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/AH_Manual_Cred_Lines_TriggerHandlerTest.cls
/****************************************************************************************
Name            : AH_Manual_Cred_Lines_TriggerHandlerTest Class 
Author          : Stuart Emery
Created Date    : 9/17/2018
Last Mod Date   : 11/1/2018 
Last Mod By     : Stuart Emery
NICC Reference  : NICC-030091
Description     : Test Class for the AH_Manual_Credit_Lines_TriggerHandler Class
                : 
				:
******************************************************************************************/  
@isTest
public class AH_Manual_Cred_Lines_TriggerHandlerTest
{
    
    // CREATE TEST DATA
    @testSetup static void createTestData()
    {
        
        //CREATE A TEST FINANCE REQUEST RECORD
        AH_Finance_Request__c fr = NI_TestClassData.createFinanceRequest();
        insert fr;
        
    }
    
    
    // TEST INSERTING A RECORD
    @isTest static void testRecordInsert()
    {
        
        Test.startTest();
        system.runAs([SELECT Id FROM User WHERE Id =: UserInfo.getUserId()][0]) 
        {
            
            AH_Finance_Request__c fr = [SELECT Id, CurrencyIsoCode FROM AH_Finance_Request__c LIMIT 1];
            
            //CREATE A TEST MANUAL CREDIT LINES RECORD
            AH_Manual_Credit_Lines__c mc = NI_TestClassData.createManualCreditLines(fr.Id);
            insert mc;
            
            //TEST THE BEFORE INSERT LOGIC FOR THE SetCurrency METHOD 
            //VERIFY THE CURRENCY ISO CODE ON THE AH_Manual_Credit_Lines__c RECORD
            //MATCHES THE CURRENCY ISO CODE ON THE FINANCE REQUEST OBJECT 
            AH_Manual_Credit_Lines__c mcli2 = [SELECT Id, CurrencyIsoCode FROM AH_Manual_Credit_Lines__c LIMIT 1];
            system.assertEquals(mcli2.CurrencyIsoCode, fr.CurrencyIsoCode);
            
            //VERIFY THE NET CREDIT AMOUNT ON THE FINANCE REQUEST HAS BEEN UPDATED APPROPRIATELY
            AH_Finance_Request__c fr1 = [SELECT Id, Net_Credit_Amount__c FROM AH_Finance_Request__c LIMIT 1];
            system.assertEquals(fr1.Net_Credit_Amount__c, 110);
        }         
        Test.stopTest();
    }
    
    
    // TEST UPDATING A RECORD
    @isTest static void testRecordUpdate()
    {
        
        Test.startTest();
        system.runAs([SELECT Id FROM User WHERE Id =: UserInfo.getUserId()][0]) 
        {
            
            AH_Finance_Request__c fr = [SELECT Id FROM AH_Finance_Request__c LIMIT 1];            
            
            //CREATE A TEST FINANCE REQUEST RECORD
            AH_Manual_Credit_Lines__c mc = NI_TestClassData.createManualCreditLines(fr.Id);
            insert mc;
            
            AH_Finance_Request__c fr1 = [SELECT Id, Net_Credit_Amount__c FROM AH_Finance_Request__c LIMIT 1];
            system.assertEquals(fr1.Net_Credit_Amount__c, 110);
            
            //GET THE INSERTED MANUAL CREDIT LINES RECORD
            AH_Manual_Credit_Lines__c mc2 = [SELECT Id, Requested_Credit_Amount__c FROM AH_Manual_Credit_Lines__c LIMIT 1];
            
            //UPDATE THE REQUESTED CREDIT AMOUNT
            mc2.Requested_Credit_Amount__c = 150;
            update mc2;
            
            //ASSERT THAT THE NET CREDIT AMOUNT ON THE FINANCE REQUEST HAS BEEN UPDATED TO REFLECT THE NEW CREDIT AMOUNT
            AH_Finance_Request__c fr2 = [SELECT Id, Net_Credit_Amount__c FROM AH_Finance_Request__c LIMIT 1];
            system.assertEquals(fr2.Net_Credit_Amount__c, 160);    
        }         
        Test.stopTest();
    }
    
    
    // TEST DELETING A RECORD
    @isTest static void testRecordDelete()
    {
        
        Test.startTest();
        system.runAs([SELECT Id FROM User WHERE Id =: UserInfo.getUserId()][0]) 
        {
            
            AH_Finance_Request__c fr = [SELECT Id FROM AH_Finance_Request__c LIMIT 1];            
            
            //CREATE A TEST FINANCE REQUEST RECORD
            AH_Manual_Credit_Lines__c mc = NI_TestClassData.createManualCreditLines(fr.Id);
            insert mc;
            
            AH_Finance_Request__c fr1 = [SELECT Id, Net_Credit_Amount__c FROM AH_Finance_Request__c LIMIT 1];
            system.assertEquals(fr1.Net_Credit_Amount__c, 110);
            
            //GET THE INSERTED MANUAL CREDIT LINES RECORD
            AH_Manual_Credit_Lines__c mc2 = [SELECT Id, Requested_Credit_Amount__c FROM AH_Manual_Credit_Lines__c LIMIT 1];
            
            //DELETE THE MANUAL CREDIT LINE RECORD
            delete mc2;
            
            //ASSERT THAT THE NET CREDIT AMOUNT ON THE FINANCE REQUEST HAS BEEN UPDATED TO REFLECT THE NEW CREDIT AMOUNT
            AH_Finance_Request__c fr2 = [SELECT Id, Net_Credit_Amount__c FROM AH_Finance_Request__c LIMIT 1];
            system.assertEquals(fr2.Net_Credit_Amount__c, 10);    
        }         
        Test.stopTest();
    }
    
}