force-app/main/default/objects/AH_Finance_Request__c/AH_Finance_Request__c.object-meta.xml
<CustomObject>
    <description>NICC-030091
This object is used to capture requests for the various teams in Finance that must go through a formal approval process.   This was initially created as proof of concept to replace the FFA Credit Memo request form which is currently done in Excel.</description>
    <label>Finance Request</label>
    <nameField>
        <displayFormat>FR-{00000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Finance Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_Finance_Request_to_SIN_Line_Item__c/AH_Finance_Request_to_SIN_Line_Item__c.object-meta.xml
<CustomObject>
    <description>NICC-030091
Used as part of the Sales Credit Note Request to link Sales Invoice Line Items to the Finance Request for a Sales Credit Note</description>
    <label>Finance Request to SIN Line Item</label>
    <nameField>
        <displayFormat>SLIFR-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Finance Request to SIN Line Item</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_Finance_Request_to_SIN_Line_Item__c/fields/Finance_Request__c.field-meta.xml
<CustomField>
    <fullName>Finance_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Finance Request</label>
    <referenceTo>AH_Finance_Request__c</referenceTo>
    <relationshipLabel>Finance Request to SIN Line Item</relationshipLabel>
    <relationshipName>Finance_Request_to_SIN_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_TriggerBypassSwitches__c/NI_TriggerBypassSwitches__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>NICC-010252: Global Custom Setting for Trigger Bypassing

Used to turn off code execution on triggers globally or per specific object(s).</description>
    <label>NI Trigger Bypass Switches</label>
</CustomObject>

force-app/main/default/objects/NI_TriggerBypassSwitches__c/fields/Bypass_AH_Finance_ReqToSIN_LineItem__c.field-meta.xml
<CustomField>
    <fullName>Bypass_AH_Finance_ReqToSIN_LineItem__c</fullName>
    <defaultValue>false</defaultValue>
    <description>NICC-030091

Bypass the triggers on the AH_Finance_Request_to_SIN_Line_Item__c object</description>
    <label>Bypass_AH_Finance_ReqToSIN_LineItem</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AH_Finance_Req_to_SIN_LI_Trigger_Handler.cls
/****************************************************************************************
Name            : AH_Finance_Req_to_SIN_LI_Trigger_Handler Class 
Author          : Stuart Emery
Created Date    : 9/12/2018
Last Mod Date   : 11/1/2018
Last Mod By     : Stuart Emery
NICC Reference  : NICC-030091
Description     : Class that handles all trigger code for the 
                : AH_Finance_Request_to_SIN_Line_Item__c Object
				:
******************************************************************************************/
public class AH_Finance_Req_to_SIN_LI_Trigger_Handler 
{
    
    //VARIABLE TO HOLD THE BYPASS SWITCH CUSTOM SETTING 
    private NI_TriggerBypassSwitches__c bpSwitch {get; set;}
    
    
    public AH_Finance_Req_to_SIN_LI_Trigger_Handler()
    {
        // GET TRIGGER HANDLER BYPASS SWITCH VALUE
        bpSwitch = NI_TriggerBypassSwitches__c.getOrgDefaults();
    }
    
    //================================================================================    
    public void OnBeforeInsert(List<AH_Finance_Request_to_SIN_Line_Item__c> newTrigger)
    {   
        //EXECUTE THE CODE IF THE BYPASS SWITCH IS NOT CHECKED
        if (!bpSwitch.Bypass_AH_Finance_ReqToSIN_LineItem__c)
        {
            
            System.debug(' *** ENTERING AH_Finance_Req_to_SIN_LI_Trigger_Handler.OnBeforeInsert()');   
            
            //CALL THE SetCurrency METHOD 
            SetCurrency(newTrigger);            
        }
    }
    
    //==============================================================================================================    
    public void OnAfterInsert(List<AH_Finance_Request_to_SIN_Line_Item__c> newTrigger)
    {   
        //EXECUTE THE CODE IF THE BYPASS SWITCH IS NOT CHECKED
        if (!bpSwitch.Bypass_AH_Finance_ReqToSIN_LineItem__c)
        {
            
            System.debug(' *** ENTERING AH_Finance_Req_to_SIN_LI_Trigger_Handler.OnAfterInsert()');
            Set<Id> setIds = new Set<Id>();
            
            List<AH_Finance_Request__c> lstFrToUpdate = new List<AH_Finance_Request__c>();
            for (AH_Finance_Request_to_SIN_Line_Item__c frToSinLI : newTrigger)
            {
                setIds.add(frToSinLI.Finance_Request__c);   
            }
            
            lstFrToUpdate = ([SELECT Id 
                              FROM AH_Finance_Request__c
                              WHERE Id IN: setIds]);
            
            //CALL THE FUNCTION TO ROLLUP THE CREDIT AMOUNT  
            AH_Finance_Request_Statics.rollupFinanceRequestNetCreditAmount(lstFrToUpdate);              
        }  
    }
    
    //===================================================================================================================================================   
    public void OnAfterUpdate(List<AH_Finance_Request_to_SIN_Line_Item__c> newTrigger, Map<Id, AH_Finance_Request_to_SIN_Line_Item__c> oldMapTrigger)
    {   
        //EXECUTE THE CODE IF THE BYPASS SWITCH IS NOT CHECKED
        if (!bpSwitch.Bypass_AH_Finance_ReqToSIN_LineItem__c)
        {
            
            System.debug(' *** ENTERING AH_Finance_Req_to_SIN_LI_Trigger_Handler.OnAfterUpdate()');
            Set<Id> setIds = new Set<Id>();
            List<AH_Finance_Request__c> lstFrToUpdate = new List<AH_Finance_Request__c>();
            
            for (AH_Finance_Request_to_SIN_Line_Item__c frToSinLI : newTrigger)
            {
                AH_Finance_Request_to_SIN_Line_Item__c oldFrToSinLI = oldMapTrigger.get(frToSinLI.Id);
                if ((frToSinLI.Requested_Credit_Amount__c != oldFrToSinLI.Requested_Credit_Amount__c) || (frToSinLI.Requested_Credit_Amount__c == null))
                {
                    setIds.add(frToSinLI.Finance_Request__c);
                }
            }         
            lstFrToUpdate = ([SELECT Id 
                              FROM AH_Finance_Request__c
                              WHERE Id IN: setIds]);
            
            //CALL THE FUNCTION TO ROLLUP THE CREDIT AMOUNT 
            AH_Finance_Request_Statics.rollupFinanceRequestNetCreditAmount(lstFrToUpdate);           
        }
    }
    
    //=============================================================================================================================================    
    public void OnAfterDelete(List<AH_Finance_Request_to_SIN_Line_Item__c> oldTrigger) 
    { 
        //EXECUTE THE CODE IF THE BYPASS SWITCH IS NOT CHECKED
        if (!bpSwitch.Bypass_AH_Finance_ReqToSIN_LineItem__c)
        {   
            
            System.debug(' *** ENTERING AH_Finance_Req_to_SIN_LI_Trigger_Handler.OnAfterDelete()');         
            Set<Id> setIds = new Set<Id>();
            
            List<AH_Finance_Request__c> lstFrToUpdate = new List<AH_Finance_Request__c>();
            for (AH_Finance_Request_to_SIN_Line_Item__c frToSinLI : oldTrigger)
            {
                setIds.add(frToSinLI.Finance_Request__c);   
            }
            
            lstFrToUpdate = ([SELECT Id 
                              FROM AH_Finance_Request__c
                              WHERE Id IN : setIds]);        
            
            //CALL THE FUNCTION TO ROLLUP THE CREDIT AMOUNT 
            AH_Finance_Request_Statics.rollupFinanceRequestNetCreditAmount(lstFrToUpdate);
        }
    }
    
    //================================================================================ 
    // UPDATE THE CURRENCY FIELD
    //================================================================================      
    public void SetCurrency(List<AH_Finance_Request_to_SIN_Line_Item__c> newTrigger)    
    { 
        
        System.debug(' *** ENTERING AH_Finance_Req_to_SIN_LI_Trigger_Handler.SetCurrency()');
        
        Set<Id> setFrIds = new Set<Id>();
        
        for (AH_Finance_Request_to_SIN_Line_Item__c fli : newTrigger)
        {
            setFrIds.add(fli.Finance_Request__c);   
        }
        
        Map<Id,AH_Finance_Request__c> mapFr = new Map<Id,AH_Finance_Request__c>([SELECT Id, Name, CurrencyIsoCode 
                                                                                 FROM AH_Finance_Request__c
                                                                                 WHERE Id IN: setFrIds]);
        
        for (AH_Finance_Request_to_SIN_Line_Item__c fli2 : newTrigger)
        {
            fli2.CurrencyIsoCode = mapFr.get(fli2.Finance_Request__c).CurrencyIsoCode;  
            System.debug('FINANCE REQUEST CURRENCY ISO CODE: ' + mapFr.get(fli2.Finance_Request__c).CurrencyIsoCode);  
        }
        
        system.debug('    >>>>    QUERIES ISSUED = ' + Limits.getQueries() + ' Class: AH_Finance_Req_to_SIN_LI_Trigger_Handler.SetCurrency');
        
    }
    
}