force-app/main/default/objects/DTS_Amadeus_Logins__c/DTS_Amadeus_Logins__c.object-meta.xml
<CustomObject>
    <description>Stores details of the Amadeus Users Login History for the cross org project. Child Object of Amadeus Users object
//NICC-046831</description>
    <label>Amadeus Logins</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Amadeus Logins</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DTS_Amadeus_Logins__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Application</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DTS_Amadeus_Logins__c/fields/CountryISO__c.field-meta.xml
<CustomField>
    <fullName>CountryISO__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Country</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DTS_Amadeus_Logins__c/fields/LoginDate__c.field-meta.xml
<CustomField>
    <fullName>LoginDate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Login Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/DTS_Amadeus_Logins__c/fields/LoginTime__c.field-meta.xml
<CustomField>
    <fullName>LoginTime__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Login Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/DTS_Amadeus_Logins__c/fields/LoginType__c.field-meta.xml
<CustomField>
    <fullName>LoginType__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Login Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DTS_Amadeus_Logins__c/fields/LoginUrl__c.field-meta.xml
<CustomField>
    <fullName>LoginUrl__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Login URL</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DTS_Amadeus_Logins__c/fields/SourceIp__c.field-meta.xml
<CustomField>
    <fullName>SourceIp__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Source IP</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DTS_Amadeus_Logins__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DTS_Amadeus_Logins__c/fields/UserID__c.field-meta.xml
<CustomField>
    <fullName>UserID__c</fullName>
    <label>User ID</label>
    <referenceTo>DTS_Amadeus_Users__c</referenceTo>
    <relationshipLabel>Amadeus Logins</relationshipLabel>
    <relationshipName>Amadeus_Logins</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DTS_Amadeus_Organizations__c/DTS_Amadeus_Organizations__c.object-meta.xml
<CustomObject>
    <description>Each connected Amadeus Salesforce Instance for the Cross Orgs Project will have only one record with its basic details for identification and are manually created. This is used as the Parent object to link other Child objects in the callouts. Do not create new records or change records without Stuart Emery`s Authorization.
//NICC-046831</description>
    <label>Amadeus Organizations</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Org Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Amadeus Organizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DTS_Amadeus_Users__c/DTS_Amadeus_Users__c.object-meta.xml
<CustomObject>
    <description>Stores Users (Active, Inactive, Frozen) with Salesforce, Salesforce Platform licenses of the integrated Amadeus systems for the cross org project. Child Object of Amadeus Organizations object
//NICC-046831</description>
    <label>Amadeus Users</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Amadeus Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DTS_Amadeus_Users__c/fields/AmadeusOrg__c.field-meta.xml
<CustomField>
    <fullName>AmadeusOrg__c</fullName>
    <label>Amadeus Org</label>
    <referenceTo>DTS_Amadeus_Organizations__c</referenceTo>
    <relationshipLabel>Amadeus Users</relationshipLabel>
    <relationshipName>Amadeus_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DTS_Amadeus_Users__c/fields/UserID__c.field-meta.xml
<CustomField>
    <fullName>UserID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>User ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_Admin_Error_Log__c/NI_Admin_Error_Log__c.object-meta.xml
<CustomObject>
    <description>Error Log Object</description>
    <label>AH Error Log</label>
    <nameField>
        <displayFormat>ERR-{000000}</displayFormat>
        <label>Error Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AH Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DTS_CrossOrgsHubLoginHistory.cls
/*********************************************************************************************************************************************
Name            : DTS_CrossOrgsHubLoginHistory Class
Author          : Arul Geetha Amalraj
Created Date    : 12/02/2020
Last Mod Date   : 
Last Mod By     : 
NICC Reference  : 
Description     : CrossOrgs Project: Callout to the connected Amadeus Orgs to pull Yesterday`s LoginHistory				
Comments 		: Schedule DTS_CrossOrgsHubLogins.cls and use this only if needed.Can bring ~10000 Yesterday`s login records on a daily basis			
TestClass    	: DTS_CrossOrgsHubData_Test.cls(95%)				 
				:
**********************************************************************************************************************************************/

global class DTS_CrossOrgsHubLoginHistory implements Schedulable{	
   
	global void execute(SchedulableContext sc) {
		getHistoryData();
	}		
		
	public static void getHistoryData(){
		
		//Get Hub_Org details from SR
		StaticResource sr = [SELECT Body FROM StaticResource WHERE Name = 'DTS_CrossOrgsHub_SR'];
		Blob bodyBlob = sr.Body;
        String query = bodyBlob.toString();
		System.debug('Static Resource :'+ query);
		DTS_Amadeus_Organizations__c hubOrg = Database.Query(query);		
		
		//Query Yesterday`s Login History 		        
		Datetime dToday = System.today();
		Datetime dYestday = System.today().addDays(-1);
		System.debug('Yesterday :'+ dYestday); 
		List<LoginHistory> hQuery = [SELECT Id,UserID,LoginTime,SourceIp,LoginType,Status,LoginUrl,Application,CountryISO From LoginHistory where LoginTime >= :dYestday and LoginTime <:dToday LIMIT 10000];	
		System.debug('Yesterday`s LoginHistory for All Licenses :'+ hQuery.size());		
		
		//Variables	
		List<DTS_Amadeus_Users__c> lhList = new List<DTS_Amadeus_Users__c>();
		List<DTS_Amadeus_Logins__c> amhList = new List<DTS_Amadeus_Logins__c> ();
		
		//Get unique logged in User IDs from Login History
		Map<Id,LoginHistory> mapLogins = new Map<Id,LoginHistory>();
		if(hQuery.size()>0){			
			for(LoginHistory h : hQuery){
				mapLogins.put(h.UserId, h);  
			}					
		}
		System.debug('Unique UserID`s from LoginHistory:'+ mapLogins.size());
		
		//Get the list of active Amadeus Users w Salesforce and Salesforce Platform License
		lhList = [Select Id,UserID__c, name from DTS_Amadeus_Users__c where amadeusorg__c = :hubOrg.Id and isActive__c = True and UserID__c in:mapLogins.keyset()];
		System.debug('Active DTS Users who are Logged in Yesterday: '+lhList.size());
		
		//Map of Amadeus Users for the iteration
		Map<Id,DTS_Amadeus_Users__c> mapUsers = new Map<Id,DTS_Amadeus_Users__c>();
		if(lhList.size()>0){			
			for(DTS_Amadeus_Users__c m : lhList){
				mapUsers.put(m.UserID__c, m);
			}			
		}
		System.debug('Uniques DTS Users who are Logged in Yesterday: '+lhList.size());
		
		//History based iteration
		if(lhList.size()>0){ 
			for(LoginHistory h:hQuery ){
				if(mapUsers.containsKey(h.UserID)){
					DTS_Amadeus_Logins__c amh = new DTS_Amadeus_Logins__c();
					amh.UserID__c = mapUsers.get(h.UserID).Id;
					amh.name = mapUsers.get(h.UserID).name;			
					amh.LoginTime__c = h.LoginTime;
					amh.LoginDate__c = amh.LoginTime__c.date();
					amh.SourceIp__c = h.SourceIp;
					amh.LoginType__c = h.LoginType;				
					amh.Status__c = h.Status;
					amh.LoginUrl__c = h.LoginUrl; 
					amh.Application__c = h.Application; 
					amh.CountryISO__c = h.CountryISO; 
					amhList.add(amh);					
				}				
			}		
		}		
		System.debug('Login History List for Insert: '+ amhList.size());	
		
		if(amhList.size()>0){
			try{
			Insert amhList; 
			System.debug ('Inserted LoginHistory Scuccessfully for Hub : ' + hubOrg.name);
			}
			catch (exception e){
			System.debug('Insert Login History Failed for Hub : ' + hubOrg.name);
			NI_Error_Logger.WriteToLog ('HubOrg Insert Login History Failed for Hub :' + hubOrg.name + ': Error Message :-'+e.getmessage(), 'NI_Admin_Error_Log__c', 'DTS_CrossOrgsHubLoginHistory', 'INSERT');			   			
			}			
		}
			
	}//End of getLoginData
}

/*
    // Cron Schedule-Added here for ref:-Scheduled from UI
    DTS_CrossOrgsHubLoginHistory b = new DTS_CrossOrgsHubLoginHistory ();
    String sch = '0 0 22 * * ?';
    system.schedule('CrossOrgsHubLoginHistory: Daily @10:00 PM', sch, b);

*/