force-app/main/default/objects/Product_Group__c/Product_Group__c.object-meta.xml
<CustomObject>
    <label>Product Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SFDC_CSP_Development_Request__c/SFDC_CSP_Development_Request__c.object-meta.xml
<CustomObject>
    <description>SFDC Customer Service Project</description>
    <label>Change Request</label>
    <nameField>
        <displayFormat>CR{0000000}</displayFormat>
        <label>Change Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SFDC_CSP_Development_Request__c/fields/Child_Solution__c.field-meta.xml
<CustomField>
    <fullName>Child_Solution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Child Solution</label>
    <referenceTo>Solution</referenceTo>
    <relationshipName>Development_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SFDC_CSP_Development_Request__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Description</label>
    <length>32000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/SFDC_CSP_Development_Request__c/fields/Part__c.field-meta.xml
<CustomField>
    <fullName>Part__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Part</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SFDC_CSP_Part__c.Version__c</field>
            <operation>equals</operation>
            <valueField>$Source.Version__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SFDC_CSP_Part__c</referenceTo>
    <relationshipLabel>Change Requests</relationshipLabel>
    <relationshipName>Development_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SFDC_CSP_Development_Request__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Group</label>
    <referenceTo>Product_Group__c</referenceTo>
    <relationshipLabel>Change Requests</relationshipLabel>
    <relationshipName>Change_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SFDC_CSP_Development_Request__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Title</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SFDC_CSP_Development_Request__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Version</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>SFDC_CSP_Version__c.Product_Group__c</field>
            <operation>equals</operation>
            <valueField>$Source.Product_Group__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>SFDC_CSP_Version__c</referenceTo>
    <relationshipLabel>Change Requests</relationshipLabel>
    <relationshipName>Development_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ChangeRequestDetailsExtension.cls
public with sharing class ChangeRequestDetailsExtension 
{

    ApexPages.StandardController GstdController;
    public SFDC_CSP_Development_Request__c c;
    public Solution s;
        
    public ChangeRequestDetailsExtension(ApexPages.StandardController controller) 
    {
        GstdController = controller;
        this.c = (SFDC_CSP_Development_Request__c)controller.getRecord(); 
        
        if (ApexPages.CurrentPage().getParameters().containsKey('sol')) 
        {    
            s = [SELECT Id, SolutionNumber, SolutionName, Description__c, Product_Group__c, Version__c, Part__c FROM Solution WHERE id = :ApexPages.CurrentPage().getParameters().get('sol')];
            
            c.Child_Solution__c = s.Id;
            c.Product_Group__c = s.Product_Group__c;
            c.Version__c = s.Version__c;
            c.Part__c = s.Part__c;    
            c.Title__c = s.SolutionNumber + ' - ' + s.SolutionName;
            c.Description__c = s.Description__c;

        }
    }

}