force-app/main/default/objects/Product_Group__c/Product_Group__c.object-meta.xml
<CustomObject>
    <label>Product Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SFDC_CSP_Development_Request__c/SFDC_CSP_Development_Request__c.object-meta.xml
<CustomObject>
    <description>SFDC Customer Service Project</description>
    <label>Change Request</label>
    <nameField>
        <displayFormat>CR{0000000}</displayFormat>
        <label>Change Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Change Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SFDC_CSP_Development_Request__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Description</label>
    <length>32000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/SFDC_CSP_Development_Request__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Product Group</label>
    <referenceTo>Product_Group__c</referenceTo>
    <relationshipLabel>Change Requests</relationshipLabel>
    <relationshipName>Change_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SFDC_CSP_Development_Request__c/fields/Public_Status__c.field-meta.xml
<CustomField>
    <fullName>Public_Status__c</fullName>
    <description>This is the public (customer facing) status of the CR</description>
    <label>Public Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Product Team Review</fullName>
            </value>
            <value>
                <fullName>Under Consideration</fullName>
            </value>
            <value>
                <fullName>On Roadmap</fullName>
            </value>
            <value>
                <fullName>Coming in the Next Release</fullName>
            </value>
            <value>
                <fullName>Partially Delivered</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
            <value>
                <fullName>Solutions Available</fullName>
            </value>
            <value>
                <fullName>Not Planned</fullName>
            </value>
            <value>
                <fullName>Existing Feature</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SFDC_CSP_Development_Request__c/fields/Public_Status_Description__c.field-meta.xml
<CustomField>
    <fullName>Public_Status_Description__c</fullName>
    <description>This is the public (customer facing) description of what the Public Status means</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Public Status Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SFDC_CSP_Development_Request__c/fields/Support_Priority__c.field-meta.xml
<CustomField>
    <fullName>Support_Priority__c</fullName>
    <label>Customer Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1 - Urgent</fullName>
            </value>
            <value>
                <fullName>2 - High</fullName>
            </value>
            <value>
                <fullName>3 - Medium</fullName>
            </value>
            <value>
                <fullName>4 - Low</fullName>
            </value>
            <value>
                <fullName>Please Specify</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SFDC_CSP_Development_Request__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Title</label>
    <length>155</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SFDC_CSP_Development_Request__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Defect</fullName>
            </value>
            <value>
                <fullName>Enhancement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AH_ChangeRequest_TriggerHandler_Test.cls
/****************************************************************************************
Name            : AH_ChangeRequest_TriggerHandler_Test Test Class
Author          : Bhuleshwar Deshpande
Created Date    : 09/11/2018
Last Mod Date   : 09/14/2018
Last Mod By     : Bhuleshwar Deshpande
NICC Reference  : 
Description     : test Class for AH_ChangeRequest_TriggerHandler Class
: 
: 
******************************************************************************************/
@isTest
public class AH_ChangeRequest_TriggerHandler_Test 
{
    
    // ======================================================================================================================================= 
    // = CREATE TEST DATA
    // ======================================================================================================================================= 
    @testSetup static void createTestData()
    {
        Test.startTest();
        
        // CREATE TEST DATA FOR PRODUCT GROUP.
        Product_Group__c proGroup = new Product_Group__c();
        proGroup.Name = 'PMS';
        Database.insert(proGroup);
        proGroup = [SELECT Id, Name FROM Product_Group__c WHERE Name = 'PMS'];
        System.assertEquals('PMS', proGroup.Name, 'Wrong Product Name');

        // CREATE TEST DATA FOR CHANGE REQUESTS
      	SFDC_CSP_Development_Request__c changeRequest = new SFDC_CSP_Development_Request__c();
        changeRequest.Type__c = 'Defect';
        changeRequest.Support_Priority__c = '2-High';
        changeRequest.Product_Group__c = proGroup.Id;
        changeRequest.Public_Status__c = 'New';
        changeRequest.Title__c = 'Test product review';
        changeRequest.Description__c = 'The product test';
        Database.insert(changeRequest);
        
        system.debug('CR RECORD:'+changeRequest);
        changeRequest = [SELECT Id, Public_Status_Description__c FROM SFDC_CSP_Development_Request__c];
        system.assertEquals('The Change Request is newly submitted and will be assigned an official Product Team status within 10 business days', changeRequest.Public_Status_Description__c, 'Error in Public_Status_Description__c');
        
        Test.stopTest();  
    }
    
    // ======================================================================================================================================= 
    // = TEST METHOD 1: 
    // ======================================================================================================================================= 
    @isTest static void testMethod1()
    {
        List<SFDC_CSP_Development_Request__c> CRlst = new List<SFDC_CSP_Development_Request__c>();
        CRlst = [SELECT Id, Public_Status__c FROM SFDC_CSP_Development_Request__c];

        Test.startTest(); 
        
        CRlst[0].Public_Status__c = 'Product Team Review';
        Database.update(CRlst);  
        
        List<SFDC_CSP_Development_Request__c> updatedLst = new List<SFDC_CSP_Development_Request__c>();
        updatedLst = [SELECT Id, Public_Status_Description__c FROM SFDC_CSP_Development_Request__c];
        system.assertEquals('The Change Request is undergoing Product Team review for roadmap consideration and feedback', updatedLst[0].Public_Status_Description__c, 'Error in Public_Status_Description__c');
        
        Test.stopTest();
    }
    
}