force-app/main/default/objects/NI_Department_to_Location__c/NI_Department_to_Location__c.object-meta.xml
<CustomObject>
    <description>Salesforce.com Change Request: NICC-012978

Junction Object between the NI Department and NI Location Objects.</description>
    <label>NI Department to Location</label>
    <nameField>
        <displayFormat>DTL-{000}</displayFormat>
        <label>DTL Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NI Department to Location</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_Department_to_Location__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>NI_Department_to_Location</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Department_to_Location__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>NI_Location__c</referenceTo>
    <relationshipLabel>NI Department to Location</relationshipLabel>
    <relationshipName>NI_Department_to_Location_Junction</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NI_Department_to_Location__c/fields/NI_Departments__c.field-meta.xml
<CustomField>
    <fullName>NI_Departments__c</fullName>
    <label>NI Departments</label>
    <referenceTo>NI_Departments__c</referenceTo>
    <relationshipLabel>NI Department to Location</relationshipLabel>
    <relationshipName>Department_to_Location_Junction</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NI_Department_to_Location__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Exec Member</fullName>
                <default>true</default>
                <label>Exec Member</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NI_Departments__c/NI_Departments__c.object-meta.xml
<CustomObject>
    <description>Salesforce.com Change Request: NICC-006705

Object to track the Departments at Newarket International.  This is based on the values in HR&apos;s ADP System</description>
    <label>NI Departments</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Department</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NI Departments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_Job_Req_RecordType_Trigger_Handler__c/NI_Job_Req_RecordType_Trigger_Handler__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Use this custom setting to control the Methods that are called in the NI_JobReq_TriggerHandler Class based on Record Type.   Enter the Record Type &quot;Name&quot; in the &quot;Name&quot; field.</description>
    <label>NI Job Req Record Type Trigger Handler</label>
</CustomObject>

force-app/main/default/objects/NI_Job_Req_RecordType_Trigger_Handler__c/fields/Exec_Approver__c.field-meta.xml
<CustomField>
    <fullName>Exec_Approver__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this check box is checked, the &quot;Update_ExecApproverField&quot; method will be called for this Record Type in the &quot;NI_JobReq_TriggerHandler&quot; Class</description>
    <inlineHelpText>If this check box is checked, the &quot;Update_ExecApproverField&quot; method will be called for this Record Type in the &quot;NI_JobReq_TriggerHandler&quot; Class</inlineHelpText>
    <label>Exec Approver</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NI_Job_Requisition__c/NI_Job_Requisition__c.object-meta.xml
<CustomObject>
    <description>Salesforce.com Change Request: NICC-013403

Job Requisition Form</description>
    <label>Job Requisition</label>
    <nameField>
        <displayFormat>JR-{00000}</displayFormat>
        <label>Job Req #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Requisitions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_Job_Requisition__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Department</label>
    <referenceTo>NI_Departments__c</referenceTo>
    <relationshipName>NI_Job_Requisitions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Job_Requisition__c/fields/Employee_Disable_Date__c.field-meta.xml
<CustomField>
    <fullName>Employee_Disable_Date__c</fullName>
    <description>This field appears on the &quot;Standard Remove User&quot; Page Layout.  This is the date and time the employee should be disabled from all Newmarket Systems and Applications.  This field is updated by members of the HR Department</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This field appears on the &quot;Standard Remove User&quot; Page Layout.  This is the date and time the employee should be disabled from all Newmarket Systems and Applications.  This field is updated by members of the HR Department</inlineHelpText>
    <label>Employee Disable Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/NI_Job_Requisition__c/fields/Employee_to_Disable__c.field-meta.xml
<CustomField>
    <fullName>Employee_to_Disable__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the employee that needs to be disabled</description>
    <inlineHelpText>Name of the employee that needs to be disabled</inlineHelpText>
    <label>Employee to Disable</label>
    <referenceTo>User</referenceTo>
    <relationshipName>NI_Job_Requisitions_Disable</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Job_Requisition__c/fields/Exec_Approver__c.field-meta.xml
<CustomField>
    <fullName>Exec_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Member of the Executive Team that this job requisition should go to for Exec Approval</description>
    <inlineHelpText>Member of the Executive Team that this job requisition should go to for Exec Approval</inlineHelpText>
    <label>Exec Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>NI_Job_Requisitions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Job_Requisition__c/fields/Has_Attachment__c.field-meta.xml
<CustomField>
    <fullName>Has_Attachment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This check box is automatically checked by the as part of the &quot;uploadAttachment&quot; method in the  &quot;NI_JobReq_Ext&quot; Apex Class</description>
    <inlineHelpText>This check box is automatically checked if there is an attachment on the Job Requisition</inlineHelpText>
    <label>Has Attachment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NI_Job_Requisition__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>NI_Job_Requisitions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Job_Requisition__c/fields/NI_Location__c.field-meta.xml
<CustomField>
    <fullName>NI_Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>CODE     DESCRIPTION
010	         United States (U.S.)
020	         Asia Pacific (Singapore)
022	         Australia
024	         China
030	         EMEA 
060	         MTech
070          Itesso</inlineHelpText>
    <label>Financial Department</label>
    <referenceTo>NI_Location__c</referenceTo>
    <relationshipLabel>Job Requisitions</relationshipLabel>
    <relationshipName>NI_Job_Requisitions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Job_Requisition__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>The Role for the Offshore Contractor</description>
    <inlineHelpText>The Role for the Offshore Contractor</inlineHelpText>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Analyst</fullName>
            </value>
            <value>
                <fullName>Dev</fullName>
            </value>
            <value>
                <fullName>Management</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Project Manager</fullName>
            </value>
            <value>
                <fullName>QA</fullName>
            </value>
            <value>
                <fullName>Release Engineer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NI_Job_Requisition__c/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <label>Standard</label>
</RecordType>

force-app/main/default/objects/NI_Location__c/NI_Location__c.object-meta.xml
<CustomObject>
    <description>Salesforce.com Change Request: NICC-006705

This object is used to track the various Newmarket Offices/Locations</description>
    <label>NI Location</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>NI Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NI Location</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/NI_JobReq_TriggerHandler.cls
/************************************************************************************************
Name            : NI_JobReq_TriggerHandler Class
Author          : Stuart Emery
Created Date    : 2/23/2015
Last Mod Date   : 2/23/2015
Last Mod By     : Stuart Emery
NICC Reference  : 
Description     : Class that handles all trigger code for the NI_JobRequisition__c Object
                :
*************************************************************************************************/
public class NI_JobReq_TriggerHandler {
    
    private boolean m_isExecuting = false;
    
    //SET TO HOLD THE JOB REQUISITION RECORD TYPE IDs  
    public Set<Id> setRTypes = new Set<Id>();
    
    public NI_JobReq_TriggerHandler(boolean isExecuting)
    {
        m_isExecuting = isExecuting;
    }
    
    public boolean IsTriggerContext
    {
        get {return m_isExecuting;}
    }
    //========================================================================================================================
    public void OnBeforeInsert(List<NI_Job_Requisition__c> newTrigger)
    {
        //LIST TO HOLD THE VALUES FROM THE NI_Job_Req_RecordType_Trigger_Handler CUSTOM SETTING  
        List<NI_Job_Req_RecordType_Trigger_Handler__c> lstCS = NI_Job_Req_RecordType_Trigger_Handler__c.getAll().values();
        
        //LIST TO HOLD THE JOB REQUISITION RECORDS THAT SHOULD BE PASSED TO THE "Update_ExecApproverField" METHOD
        List<NI_Job_Requisition__c> lstJobReqsToUpdate = new List<NI_Job_Requisition__c>();
        
        //LOOP THROUGH THE lstCS AND GET THE JOB REQUISITION RECORDTYPEIDs FOR THE RECORD TYPES THAT SHOULD EXECUTE THE "Update_ExecApproverField" METHOD 
        for (NI_Job_Req_RecordType_Trigger_Handler__c jrt : lstCS)
        {
            System.debug('JOB REQ TRIGGER HANDLER CUSTOM SETTING NAME: ' + jrt.Name);
            System.debug('JOB REQ TRIGGER HANDLER CUSTOM SETTING EXEC APPROVER: ' + jrt.Exec_Approver__c);
            if(jrt.Exec_Approver__c == true)
            {
                System.debug('JOB REQUISITION RECORD TYPE NAME: ' + jrt.Name);
                setRTypes.add(NI_TestClassData.getRecordTypeId('NI_Job_Requisition__c', jrt.Name)); 
            }
            
        }
        
        if (setRTypes.size()>0)
        {
            for(Id rTypeId : setRTypes)
            {
                for (NI_Job_Requisition__c jr : newTrigger) 
                {
                    if (jr.RecordTypeId == rTypeId)
                    {
                        lstJobReqsToUpdate.add(jr);  
                    }
                    
                }   
            }
            
        }
        
        Update_ExecApproverField(lstJobReqsToUpdate);
    }
    
    //===================================================================================================================    
    public void OnAfterInsert(List<NI_Job_Requisition__c> newTrigger)
    {
        
        //CALL THE MANAGER APEX SHARING METHOD  
        Change_Manager_Share(newTrigger);
        
        //CALL THE EXEC APPROVER APEX SHARING METHOD 
        Change_ExecApprover_Share(newTrigger);
        
        //LIST OF THE INSERTED JOB REQUISITIONS
        List<NI_Job_Requisition__c> lstInsertedJobReqs = [SELECT Id, Employee_to_Disable__c, Employee_Disable_Date__c, RecordType.Name 
                                                          FROM NI_Job_Requisition__c 
                                                          WHERE Id IN: newTrigger];
        
        //LIST OF REMOVE USERS
        List<NI_Job_Requisition__c> lstRemoveUser = new List<NI_Job_Requisition__c>();
        
        for(NI_Job_Requisition__c j : lstInsertedJobReqs)
        {
          if(j.RecordType.Name == 'Standard Remove User')
          {
            lstRemoveUser.add(j);  
              
          }  
            
        }
        System.debug('NUMBER OF REMOVE USER RECORDS: ' + lstRemoveUser.size());
        //CALL THE setUserExpirationDate METHOD 
        setUserExpirationDate(lstRemoveUser);
    }
    
    //========================================================================================================================
    public void OnBeforeUpdate (List<NI_Job_Requisition__c> newTrigger, Map<Id,NI_Job_Requisition__c> oldMapTrigger)
    {
        checkAttachments(newTrigger);
    }
    
    //===================================================================================================================    
    public void OnAfterUpdate(List<NI_Job_Requisition__c> newTrigger, Map<Id,NI_Job_Requisition__c> oldMapTrigger)
    {  
        //CREATE  LIST TO HOLD ALL RECORDS WHERE THE NEW MANAGER DOESN'T MATCH THE OLD MANAGER
        List<NI_Job_Requisition__c> lstManagerShare = new List<NI_Job_Requisition__c>();
        
        //CREATE  LIST TO HOLD ALL RECORDS WHERE THE NEW EXEC APPROVER DOESN'T MATCH THE OLD EXEC MEMBER
        List<NI_Job_Requisition__c> lstExecApproverShare = new List<NI_Job_Requisition__c>();  
        
        for (NI_Job_Requisition__c jr : newTrigger) 
        {
            NI_Job_Requisition__c oldJR = oldMapTrigger.get(jr.Id);
            
            if (jr.Manager__c != oldJR.Manager__c)
            {
                lstManagerShare.add(jr);
            }
            
            if (jr.Exec_Approver__c != oldJR.Exec_Approver__c)
            {
                lstExecApproverShare.add(jr);
            }  
        }      
        
        //CALL THE MANAGER APEX SHARING METHOD
        if (lstManagerShare.size() > 0)
        {  
            Change_Manager_Share(lstManagerShare);
        }  
        
        //CALL THE EXEC APPROVER APEX SHARING METHOD
        if (lstExecApproverShare.size() > 0)
        {  
            Change_ExecApprover_Share(lstExecApproverShare);
        }       
        
    }        
    
    //=========================================================================================================================          
    //THIS METHOD UPDATES THE EXEC APPROVER FIELD BASED ON THE NI LOCATION AND DEPARTMENT
    public void Update_ExecApproverField(List<NI_Job_Requisition__c> newTrigger)
    {
        
        //LIST OF NI JOB REQUISITION RECORDS IN newTrigger    
        List<NI_Job_Requisition__c> lstJobReq = [SELECT Id, Department__c,NI_Location__c
                                                 FROM NI_Job_Requisition__c 
                                                 WHERE Id IN: newTrigger];
        //SET TO HOLD THE DEPARTMENT IDs OF THE JOB REQUISITION RECORDS
        Set<Id> setDepartmentIds = new Set<Id>();
        
        //SET TO HOLD THE LOCATION IDs OF THE JOB REQUISITION RECORDS   
        Set<Id> setLocationIds = new Set<Id>();  
        
        for (NI_Job_Requisition__c jr : newTrigger) 
        {
            setDepartmentIds.add(jr.Department__c);                
            System.debug('DEPARTMENT ID: ' + jr.Department__c);
            setLocationIds.add(jr.NI_Location__c);
            System.debug('LOCATION ID: ' + jr.NI_Location__c);   
        }   
        
        if(setDepartmentIds.size()>0 && setLocationIds.size()>0)
        {  
            //SET TO HOLD THE DEPARTMENT TO LOCATION IDs 
            List<NI_Department_to_Location__c> lstDepToLocation = [SELECT Id,Employee__c,NI_Departments__c,Location__c,Role__c
                                                                   FROM NI_Department_to_Location__c
                                                                   WHERE NI_Departments__c IN: setDepartmentIds
                                                                   AND Location__c IN: setLocationIds
                                                                   AND Role__c = 'Exec Member'];  
            if(lstDepToLocation.size()>0)
            {
                for(NI_Job_Requisition__c jreq : newTrigger)
                {
                    for(NI_Department_to_Location__c dtl : lstDepToLocation)
                    {
                        if(jreq.Department__c == dtl.NI_Departments__c && jreq.NI_Location__c == dtl.Location__c)
                        {
                            jreq.Exec_Approver__c = dtl.Employee__c;
                        }
                    }
                }
            }    
        }
    }
    // ================================================================================================
    //  APEX SHARING METHODS
    // ================================================================================================
    
    //MANAGER SHARE
    public void Change_Manager_Share(List<NI_Job_Requisition__c> newTrigger)
    {          
        
        //LIST OF SHARES THAT NEED TO BE REMOVED
        List<NI_Job_Requisition__Share> lstSharesToRemove = new List<NI_Job_Requisition__Share>([
            SELECT id 
            FROM NI_Job_Requisition__Share 
            WHERE ParentId IN : newTrigger 
            AND RowCause = 'Manager_Share__c']); 
        
        // BULK REMOVE SHARE RECORDS
        if (lstSharesToRemove.size() > 0)
        {
            Database.DeleteResult[] drList = Database.delete(lstSharesToRemove, false);
            for (Database.DeleteResult dr : drList) 
            {
                if (dr.isSuccess()) 
                {
                    System.debug('**SUCCESSFULLY DELETED SHARE RECORD ID: ' + dr.getId());
                }
                else 
                {
                    Database.Error err = dr.getErrors()[0];
                    System.debug(err.getMessage());
                }
            }        
        }
        
        //LIST OF SHARES THAT NEED TO BE ADDED   
        List<NI_Job_Requisition__Share> lstSharesToInsert = new List<NI_Job_Requisition__Share>();
        
        for (NI_Job_Requisition__c jr : newTrigger)
        {
            if ((jr.Manager__c != jr.OwnerId) && (jr.Manager__c != null))
            {
                NI_Job_Requisition__Share jrShare = new NI_Job_Requisition__Share();
                jrShare.ParentId = jr.Id;
                jrShare.UserOrGroupId = jr.Manager__c;
                jrShare.AccessLevel = 'Edit';
                jrShare.RowCause = Schema.NI_Job_Requisition__Share.RowCause.Manager_Share__c;
                lstSharesToInsert.add(jrShare);
            } 
            
        }
        
        //USE DATABASE DML METHOD TO ADD THE SHARES
        if(lstSharesToInsert.size() > 0)
        {
            Database.SaveResult[] results = Database.insert(lstSharesToInsert,true);
            for(Database.SaveResult sr: results)
            {
                if(!sr.isSuccess())
                {
                    Database.Error err = sr.getErrors()[0];
                    System.debug(err.getMessage());
                }
            }
        } 
        
    }
    //=============================================================================================================    
    //EXEC APPROVER SHARE
    public void Change_ExecApprover_Share(List<NI_Job_Requisition__c> newTrigger)
    {          
        
        //LIST OF SHARES THAT NEED TO BE REMOVED
        List<NI_Job_Requisition__Share> lstSharesToRemove = new List<NI_Job_Requisition__Share>([
            SELECT id 
            FROM NI_Job_Requisition__Share 
            WHERE ParentId IN : newTrigger 
            AND RowCause = 'Exec_Approver_Share__c']); 
        
        // BULK REMOVE SHARE RECORDS
        if (lstSharesToRemove.size() > 0)
        {
            Database.DeleteResult[] drList = Database.delete(lstSharesToRemove, false);
            for (Database.DeleteResult dr : drList) 
            {
                if (dr.isSuccess()) 
                {
                    System.debug('**SUCCESSFULLY DELETED SHARE RECORD ID: ' + dr.getId());
                }
                else 
                {
                    Database.Error err = dr.getErrors()[0];
                    System.debug(err.getMessage());
                }
            }        
        }
        
        //LIST OF SHARES THAT NEED TO BE ADDED   
        List<NI_Job_Requisition__Share> lstSharesToInsert = new List<NI_Job_Requisition__Share>();
        
        for (NI_Job_Requisition__c jr : newTrigger)
        {
            if ((jr.Exec_Approver__c != jr.OwnerId) && (jr.Exec_Approver__c != null))
            {
                NI_Job_Requisition__Share jrShare = new NI_Job_Requisition__Share();
                jrShare.ParentId = jr.Id;
                jrShare.UserOrGroupId = jr.Exec_Approver__c;
                jrShare.AccessLevel = 'Read';
                jrShare.RowCause = Schema.NI_Job_Requisition__Share.RowCause.Exec_Approver_Share__c;
                lstSharesToInsert.add(jrShare);
            } 
            
        }
        
        //USE DATABASE DML METHOD TO ADD THE SHARES
        if(lstSharesToInsert.size() > 0)
        {
            Database.SaveResult[] results = Database.insert(lstSharesToInsert,true);
            for(Database.SaveResult sr: results)
            {
                if(!sr.isSuccess())
                {
                    Database.Error err = sr.getErrors()[0];
                    System.debug(err.getMessage());
                }
            }
        } 
        
    }
    
    //===================================================================================================================
    public void checkAttachments (List<NI_Job_Requisition__c> newTrigger)
    {
        //CREATE A SET TO HOLD ALL OF THE JOB REQUISITION IDs
        Set<Id> setJobReqId = new Set<Id>();
        
        for (NI_Job_Requisition__c j : newTrigger) 
        {
            setJobReqId.add(j.Id);                
        }
        
        List <Attachment> lstJobReqAttachments = [SELECT Id, ParentId FROM Attachment WHERE ParentId IN: setJobReqId];
        
        for(NI_Job_Requisition__c jrq : newTrigger)
        {
            jrq.Has_Attachment__c = false;
            for (Attachment jreqAttach : lstJobReqAttachments) 
            {
                if(jrq.Id == jreqAttach.ParentId)
                {
                    jrq.Has_Attachment__c = true;  
                } 
                else
                {
                    jrq.Has_Attachment__c = false; 
                }  
            }
            
        }
    }
    //===================================================================================================================
    public void setUserExpirationDate (List<NI_Job_Requisition__c> newTrigger)
    {
        //CREATE A SET TO HOLD ALL OF THE UNIQUE USER IDs
        Set<Id> setUsersToDisable = new Set<Id>();
        
        for (NI_Job_Requisition__c j : newTrigger) 
        {
            setUsersToDisable.add(j.Employee_to_Disable__c);                
        }
        
        //LIST OF ALL USERS RELATED TO THE JOB REQ
        List<User> lstUsers = [SELECT Id,Expiration_Date__c  FROM User WHERE Id IN: setUsersToDisable];
        
        //LIST TO HOLD THE USERS TO UPDATE
        List<User> lstUsersToUpdate = new List<User>();
        
        for (NI_Job_Requisition__c jr : newTrigger)
        {
            for(User u : lstUsers)
            {
                If(jr.Employee_to_Disable__c == u.Id)
                {
                    u.Expiration_Date__c = jr.Employee_Disable_Date__c;
                    lstUsersToUpdate.add(u);
                }
            }
        }  
        //USE DATABASE DML METHOD TO UPDATE THE USER RECORDS
        if(lstUsersToUpdate.size() > 0)
        {
            Database.SaveResult[] results = Database.update(lstUsersToUpdate,true);
            for(Database.SaveResult sr: results)
            {
                if(!sr.isSuccess())
                {
                    Database.Error err = sr.getErrors()[0];
                    System.debug(err.getMessage());
                }
            }
        } 
    }
    
}