force-app/main/default/objects/AH_UDC_Log__c/AH_UDC_Log__c.object-meta.xml
<CustomObject>
    <description>This log is for use by Amadeus Hospitality Solutions Delivery custom code.</description>
    <label>UDC Log</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>UDC Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_UDC_WorkbookStep__c/AH_UDC_WorkbookStep__c.object-meta.xml
<CustomObject>
    <description>This object contains details of Workbook steps and sent Workbook steps.</description>
    <label>UDC Workbook Step</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Workbook Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UDC Workbook Steps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AH_UDC_WorkbookStep__c/fields/Help__c.field-meta.xml
<CustomField>
    <fullName>Help__c</fullName>
    <description>This is the Help content that will appear in the side bar when the step is shown</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>This is the Help content that will appear in the side bar when the step is shown</inlineHelpText>
    <label>Help</label>
    <length>30000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/AH_UDC_WorkbookStep__c/fields/Workbook__c.field-meta.xml
<CustomField>
    <fullName>Workbook__c</fullName>
    <description>This is the Workbook record to which the step is attached</description>
    <inlineHelpText>This is the Workbook record to which the step is attached</inlineHelpText>
    <label>Workbook</label>
    <referenceTo>AH_UDC_Workbook__c</referenceTo>
    <relationshipLabel>UDC Workbook Steps</relationshipLabel>
    <relationshipName>Workbook_Steps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AH_UDC_ViewHelp.cls
/***********************************************************************************************
  Name            : AH_UDC_ViewHelp
  Author          : Tushar Gupta
  Created Date    : 09-Apr-2021
  Last Mod Date   : 09-Apr-2021
  User Story ID   : 599601
  Last Mod By     : Tushar Gupta
  NICC Reference  : 
  Description     : Contorller class for ViewHelp
  Dependencies    : AH_UDC_Shared
  Change History  : 2021-05-10 : Rob.Stevens : Refactor for new UI
 ************************************************************************************************/
public without sharing class AH_UDC_ViewHelp {
   public String StepName { get; set; } { StepName = ''; }
   public String HelpText { get; set; } { HelpText = ''; }
   public Boolean IsErrorOccurred { get; set; } { IsErrorOccurred = false; }
   public Boolean PopOut { get; set; } { PopOut = true; }
   public Boolean IsCommunityView { get; set; } { IsCommunityView = true; }
   public String WorkbookStepId { get; set; } { WorkbookStepId = ''; }
   @TestVisible private string LogFunctionalArea = 'AH_UDC_ViewHelp'; //This is used for AH_UDC_Log Entries being written on this page
   //This is used to store AH_UDC_Log records that can't be written on the load of the controller
   public List<AH_UDC_log__c> PageLoadLogMessages { get; set; } { PageLoadLogMessages = new List<AH_UDC_Log__c> (); }
  
   public AH_UDC_ViewHelp() {
      try {
         //Get the required Step ID from the URL
         if (String.isBlank(ApexPages.currentPage().getparameters().get('id'))) {
            ShowUserError();
            return;
         }
         WorkbookStepId = String.escapeSingleQuotes(ApexPages.currentPage().getparameters().get('id')).escapeHtml4();

         if (ApexPages.currentPage().getparameters().get('Popout') != null 
             && ApexPages.currentPage().getparameters().get('Popout').toLowerCase() == 'false') PopOut = false;

         if (ApexPages.currentPage().getparameters().get('community') != null 
             && ApexPages.currentPage().getparameters().get('community').equalsIgnoreCase('false')) IsCommunityView = false;

         //Verify the Step Exists
         List<AH_UDC_WorkbookStep__c> StepDetails = [SELECT Id, Name, Help__c, Workbook__c
                                                     FROM AH_UDC_WorkbookStep__c
                                                     WHERE Id = :WorkbookStepId];
         if (StepDetails.size() == 0) {
            ShowUserError();
            return;
         }

         //Check that the user has access to the workbook/step requested
         if (AH_UDC_SharedWithoutSharing.CheckViewWorkbookUserAccess(StepDetails[0].Workbook__c) == false)
         {
            ShowUserError();
            return;
         }

         //Set the Step Name
         StepName = StepDetails[0].Name;

         HelpText = StepDetails[0].Help__c;
        
         //Generate error for test class execution to cover catch block
         if (Test.isRunningTest()) Integer a = 1/0;
      }
      catch(Exception ex) {
         ShowUserError();         
         LogException('Constructor', 'Error occurred in AH_UDC_ViewHelp() Constructor => ' + ex.getMessage() + ' at Line Number ' + ex.getLineNumber(), ex);         
      }
   }

   //Log exception and display error message to user
   private void LogException(String strMethodName, String strErrorMessage, Exception exc) {
      IsErrorOccurred = true;
      AH_UDC_SharedWithoutSharing.LogException(LogFunctionalArea, strMethodName, strErrorMessage, System.Label.AH_UDC_Common_Error_Message, exc);
   }

   public void ShowUserError()
   {      
      if (IsErrorOccurred) return; //Only show 1 error message
      IsErrorOccurred = true;
      ApexPages.addMessage(new ApexPages.message(ApexPages.severity.Error, System.Label.AH_UDC_Common_Error_Message));
   }
}