force-app/main/default/objects/NI_Departments__c/NI_Departments__c.object-meta.xml
<CustomObject>
    <description>Salesforce.com Change Request: NICC-006705

Object to track the Departments at Newarket International.  This is based on the values in HR&apos;s ADP System</description>
    <label>NI Departments</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Department</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NI Departments</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_Employee_Performance_Evaluation__c/NI_Employee_Performance_Evaluation__c.object-meta.xml
<CustomObject>
    <description>Employee Performance Evaluation</description>
    <label>NI Employee Performance Evaluation</label>
    <nameField>
        <displayFormat>Eval-{0}-{YYYY}</displayFormat>
        <label>Eval #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NI Employee Performance Evaluation</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/NI_Employee_Performance_Evaluation__c/fields/Collaborating_Manager_2__c.field-meta.xml
<CustomField>
    <fullName>Collaborating_Manager_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collaborating Manager 2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>NI_Employee_Performance_Evaluation3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Employee_Performance_Evaluation__c/fields/Collaborating_Manager_3__c.field-meta.xml
<CustomField>
    <fullName>Collaborating_Manager_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collaborating Manager 3</label>
    <referenceTo>User</referenceTo>
    <relationshipName>NI_Employee_Performance_Evaluation4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Employee_Performance_Evaluation__c/fields/Collaborating_Manager__c.field-meta.xml
<CustomField>
    <fullName>Collaborating_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Only the manager can add a Collaborating Manager, which is used when there have been very recent staffing changes. Once added, the Collaborating Manager can edit the evaluation just like the manager.</inlineHelpText>
    <label>Collaborating Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>NI_Employee_Performance_Evaluation2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Employee_Performance_Evaluation__c/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the Employee being reviewed</description>
    <label>Employee Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>NI_Employee_Performance_Evaluation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Employee_Performance_Evaluation__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Name of the manager of the employee</description>
    <label>Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>NI_Employee_Performance_Evaluation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Employee_Performance_Evaluation__c/fields/NI_Location__c.field-meta.xml
<CustomField>
    <fullName>NI_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CODE DESCRIPTION
010 United States (U.S.)
020 Asia Pacific (Singapore)
022 Australia
024 China
030 EMEA
060 MTech</description>
    <inlineHelpText>CODE DESCRIPTION
010 United States (U.S.)
020 Asia Pacific (Singapore)
022 Australia
024 China
030 EMEA
060 MTech</inlineHelpText>
    <label>Financial Department</label>
    <referenceTo>NI_Location__c</referenceTo>
    <relationshipLabel>NI Employee Performance Evaluation (Financial Department)</relationshipLabel>
    <relationshipName>NI_Employee_Performance_Evaluation1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NI_Employee_Performance_Evaluation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Employee Completed</fullName>
            </value>
            <value>
                <fullName>Employee Draft</fullName>
                <default>true</default>
                <label>Employee Draft</label>
            </value>
            <value>
                <fullName>Manager Draft</fullName>
            </value>
            <value>
                <fullName>Manager Completed</fullName>
            </value>
            <value>
                <fullName>Manager Rejected</fullName>
            </value>
            <value>
                <fullName>Evaluation Complete</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NI_Employee_Performance_Evaluation__c/fields/Time_in_Position__c.field-meta.xml
<CustomField>
    <fullName>Time_in_Position__c</fullName>
    <description>The length of time the employee has been in this position</description>
    <encryptionScheme>None</encryptionScheme>
    <inlineHelpText>How long have you been in your current position? For example, 1 year and 3 months.</inlineHelpText>
    <label>Time in Position</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NI_Location__c/NI_Location__c.object-meta.xml
<CustomObject>
    <description>Salesforce.com Change Request: NICC-006705

This object is used to track the various Newmarket Offices/Locations</description>
    <label>NI Location</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>NI Location</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NI Location</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/NI_PerformanceReview_TriggerHandler_Test.cls
/****************************************************************************************
Name            : NI_PerformanceReview_TriggerHandler_Test Class
Author          : Sean Harris
Created Date    : 12/10/2014
Last Mod Date   : 10/31/2015
Last Mod By     : Stuart Emery
NICC Reference  : 
Description     : 
                : 
                : 
******************************************************************************************/
@isTest //(SeeAllData=true)
public class NI_PerformanceReview_TriggerHandler_Test
{
    
    public static testMethod void testPerformanceReview() 
    {
        
        NI_PerformanceReview_TriggerHandler handler = new NI_PerformanceReview_TriggerHandler(true);
        boolean IsTriggerContext = handler.IsTriggerContext;
        
        //CREATE A TEST NI DEPARTMENT RECORD  
        NI_Departments__c d = NI_TestClassData.createTestNI_Department(1);
        insert d;
        
        //CREATE A TEST NI LOCATION RECORD  
        NI_Location__c l = NI_TestClassData.createTestNI_Location(1);
        insert l;
        
        // CREATE TEST MANAGER LEVEL 4 HIERARCHY ===================================================
        User Manager4 = NI_TestClassData.createTestUser(12, 'NI Administrator'); 
        Manager4.LastName = 'Manager4';
        Manager4.Alias = 'pepMgr4';
        Manager4.Email = 'prefevalManager4@newmarketinc.com';
        Manager4.Username = 'prefevalManager4@newmarketinc.com';
        Manager4.CommunityNickname = 'pepMgr4';
        insert Manager4;
        
          // CREATE TEST MANAGER LEVEL 3 HIERARCHY ===================================================
        User Manager3 = NI_TestClassData.createTestUser(11, 'NI Administrator'); 
        Manager3.LastName = 'Manager3';
        Manager3.Alias = 'pepMgr3';
        Manager3.Email = 'prefevalManager3@newmarketinc.com';
        Manager3.Username = 'prefevalManager3@newmarketinc.com';
        Manager3.CommunityNickname = 'pepMgr3';
        Manager3.ManagerId = Manager4.Id;
        insert Manager3;
        
        // CREATE TEST MANAGER LEVEL 2 HIERARCHY ===================================================
        User Manager2 = NI_TestClassData.createTestUser(10, 'NI Administrator'); 
        Manager2.LastName = 'Manager10';
        Manager2.Alias = 'pepMgr10';
        Manager2.Email = 'prefevalManager10@newmarketinc.com';
        Manager2.Username = 'prefevalManager10@newmarketinc.com';
        Manager2.CommunityNickname = 'pepMgr10';
        Manager2.ManagerId = Manager3.Id;
        insert Manager2;

        // CREATE TEST MANAGER USER ===================================================
        User Manager = NI_TestClassData.createTestUser(1, 'NI Administrator'); 
        Manager.LastName = 'Manager';
        Manager.Alias = 'pepMgr';
        Manager.Email = 'prefevalManager@newmarketinc.com';
        Manager.Username = 'prefevalManager@newmarketinc.com';
        Manager.CommunityNickname = 'pepMgr12345'; 
        Manager.ManagerId = Manager2.Id;
        insert Manager;
        
        // CREATE TEST COLLABORATING MANAGER USER ======================================
        User CoManager = NI_TestClassData.createTestUser(2, 'NI Administrator'); 
        CoManager.LastName = 'CoManager';
        CoManager.Alias = 'pepCoMgr';
        CoManager.Email = 'prefevalCoManager@newmarketinc.com';
        CoManager.Username = 'prefevalCoManager@newmarketinc.com';
        CoManager.CommunityNickname = 'pepCoMgr12345';           
        insert CoManager;
        
        // CREATE TEST COLLABORATING MANAGER 2 USER ======================================
        User CoManager2 = NI_TestClassData.createTestUser(20, 'NI Administrator'); 
        CoManager2.LastName = 'CoManager2';
        CoManager2.Alias = 'CoMgr2';
        CoManager2.Email = 'prefevalCoManager2@newmarketinc.com';
        CoManager2.Username = 'prefevalCoManager2@newmarketinc.com';
        CoManager2.CommunityNickname = 'pepCoMgr2';           
        insert CoManager2;
        
        // CREATE TEST COLLABORATING MANAGER 3 USER ======================================
        User CoManager3 = NI_TestClassData.createTestUser(21, 'NI Administrator'); 
        CoManager3.LastName = 'CoManager3';
        CoManager3.Alias = 'CoMgr3';
        CoManager3.Email = 'prefevalCoManager3@newmarketinc.com';
        CoManager3.Username = 'prefevalCoManager3@newmarketinc.com';
        CoManager3.CommunityNickname = 'pepCoMgr3';           
        insert CoManager3;

        // CREATE TEST EMPLOYEE USER ===================================================
        User Employee = NI_TestClassData.createTestUser(3, 'NI Administrator'); 
        Employee.ManagerId = Manager.Id;
        Employee.LastName = 'Employee';
        Employee.Alias = 'pepEmp';
        Employee.Email = 'prefevalEmployee@newmarketinc.com';
        Employee.Username = 'prefevalEmployee@newmarketinc.com';
        Employee.CommunityNickname = 'pepEmp12345';
        Employee.DepartmentCode__c = d.Name;
        Employee.NI_Location__c = l.Name;
        insert Employee;
        
        User EmployeeAlt = NI_TestClassData.createTestUser(4, 'NI Administrator'); 
        EmployeeAlt.Manager = Manager;
        EmployeeAlt.LastName = 'EmployeeAlt';
        EmployeeAlt.Alias = 'pepEAlt';
        EmployeeAlt.Email = 'prefevalEmployeeAlt@newmarketinc.com';
        EmployeeAlt.Username = 'prefevalEmployeeAlt@newmarketinc.com';
        EmployeeAlt.CommunityNickname = 'pepEmpAlt12345';
        EmployeeAlt.DepartmentCode__c = d.Name;
        EmployeeAlt.NI_Location__c = l.Name;
        insert EmployeeAlt;

        NI_Employee_Performance_Evaluation__c perfEval1 = NI_TestClassData.createEmployee_Performance_Evaluation(Manager.Id, CoManager.Id);   

        perfEval1.OwnerId = Employee.Id;
        perfEval1.Employee_Name__c = Employee.Id;
        perfEval1.Status__c = 'Employee Draft'; 
        perfEval1.Time_in_Position__c = '300';
        perfEval1.Collaborating_Manager_2__c = CoManager2.Id;
        perfEval1.Collaborating_Manager_3__c = CoManager3.Id;
        insert perfEval1;
         
        // INTENTIONALLY SWAP MANAGERS TO CREATE CONDITION
        perfEval1.Manager__c = CoManager.Id;
        perfEval1.Collaborating_Manager__c = Manager.Id;
        perfEval1.Employee_Name__c = EmployeeAlt.Id;
        update perfEval1;
        
        
/*        
        NI_Employee_Performance_Evaluation__c perfEval2 = NI_TestClassData.createEmployee_Performance_Evaluation(CoManager.Id, Manager.Id);   
        perfEval2.OwnerId = Employee.Id;
        perfEval2.Employee_Name__c = Employee.Name;
        perfEval2.Status__c = 'Employee Draft'; 
        perfEval2.Time_in_Position__c = '300';
        insert perfEval2;
        
        List<NI_Employee_Performance_Evaluation__c> newTrig = new List<NI_Employee_Performance_Evaluation__c>();
        Map<Id, NI_Employee_Performance_Evaluation__c> oldTrigMap = new Map<Id, NI_Employee_Performance_Evaluation__c>();
        
        newTrig.Add(perfEval1);
        newTrig.Add(perfEval2);
        oldTrigMap.Put(perfEval1.Id, perfEval1);
        oldTrigMap.Put(perfEval2.Id, perfEval2);

        
        NI_TriggerManager.isFirstTime = true;
        handler.OnAfterUpdate(newTrig, oldTrigMap);

        NI_TriggerManager.isFirstTime = true;
        handler.OnBeforeInsert(lstWHA);
        NI_TriggerManager.isFirstTime = true;
        handler.OnBeforeUpdate(lstWHA);
        NI_TriggerManager.isFirstTime = true;
        handler.OnBeforeDelete(lstWHA);
        NI_TriggerManager.isFirstTime = true;
        handler.OnAfterInsert(lstWHA);
*/
        
    }    
    
}